In [37]:
from statistics import stdev
from stable_baselines3.common.monitor import Monitor
from stable_baselines3 import A2C
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.callbacks import EvalCallback

import mlflow
from PIL.features import features

from rl_trading_lab.environment.trading_env import TradingEnv, Action

In [38]:
import logging

# Configure logging
logging.basicConfig(
  level=logging.DEBUG,
  format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

- Create a small pandas DataFrame suitable for initializing TradingEnv.
- Columns: timestamp, open, high, low, close, volume.
- Generate 200 rows of plausible OHLCV data with a datetime index.

In [39]:
import pandas as pd
import numpy as np

np.random.seed(42)

features = [
    "ratio_sma_5_close", "ratio_sma_20_close", "ratio_range_close", "fracdiff_0.4_zscore"
]
columns = ["timestamp", "close"] + features

df = pd.read_parquet("../sample_data/btcusdt_sample_10k.parquet",
                     columns=columns
                     )
df

,timestamp,close,ratio_sma_5_close,ratio_sma_20_close,ratio_range_close,fracdiff_0.4_zscore
0,2025-10-21 11:06:35.585,108308.24,1.005122,1.030419,0.000738,0.626690
1,2025-10-21 11:07:46.515,108290.04,1.008869,1.033301,0.000335,0.883138
2,2025-10-21 11:09:18.691,108227.71,1.006301,1.025187,0.000576,0.609088
3,2025-10-21 11:10:02.700,108179.22,1.028342,1.054175,0.000535,-0.021087
4,2025-10-21 11:11:03.722,108256.24,1.059898,1.055163,0.000711,-0.194621
...,...,...,...,...,...,...
9995,2025-10-25 09:38:07.057,111698.93,0.978579,0.993264,0.000293,1.264441
9996,2025-10-25 09:38:50.760,111722.63,0.996468,0.996946,0.000493,1.526022
9997,2025-10-25 09:41:23.762,111699.89,1.020242,1.012118,0.000353,-0.750411
9998,2025-10-25 09:44:27.781,111698.70,1.029383,1.014314,0.000411,-0.594010
9999,2025-10-25 09:44:59.116,111728.85,1.001131,1.018019,0.000310,1.205172

In [40]:
df.sort_values(by="timestamp", inplace=True)
df

,timestamp,close,ratio_sma_5_close,ratio_sma_20_close,ratio_range_close,fracdiff_0.4_zscore
0,2025-10-21 11:06:35.585,108308.24,1.005122,1.030419,0.000738,0.626690
1,2025-10-21 11:07:46.515,108290.04,1.008869,1.033301,0.000335,0.883138
2,2025-10-21 11:09:18.691,108227.71,1.006301,1.025187,0.000576,0.609088
3,2025-10-21 11:10:02.700,108179.22,1.028342,1.054175,0.000535,-0.021087
4,2025-10-21 11:11:03.722,108256.24,1.059898,1.055163,0.000711,-0.194621
...,...,...,...,...,...,...
9995,2025-10-25 09:38:07.057,111698.93,0.978579,0.993264,0.000293,1.264441
9996,2025-10-25 09:38:50.760,111722.63,0.996468,0.996946,0.000493,1.526022
9997,2025-10-25 09:41:23.762,111699.89,1.020242,1.012118,0.000353,-0.750411
9998,2025-10-25 09:44:27.781,111698.70,1.029383,1.014314,0.000411,-0.594010
9999,2025-10-25 09:44:59.116,111728.85,1.001131,1.018019,0.000310,1.205172

In [41]:
df.dropna(axis=0, inplace=True)

In [42]:
def make_env():
    return TradingEnv(df,
                      lookback_window=0,
                      randomize_start=True,
                      one_trade_mode=True,
                      hold_closes_position=True,
                      reward_type="returns",
                      min_holding_period=2,
                      min_episode_length=2,
                      max_position_pct=0.2,
                      price_column="close",
                      discrete_actions=True,
                      commission_rate=0.0,
                      slippage_rate=0.0,
                      features_to_use=features,
                      )

In [43]:
env = make_env()

2025-10-30 08:20:05,369 - rl_trading_lab.environment.trading_env - INFO - TradingEnv initialized: randomize_start=True, hold_closes_position=True, one_trade_mode=True, min_episode_length=2, reward_type=returns, data_length=9954

In [44]:
obs = env.reset()
obs

2025-10-30 08:20:05,980 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 251/9953

(array([1.0447077e+00, 1.0371249e+00, 4.0128411e-04, 6.7711836e-01,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00], dtype=float32),
 {'step': np.int64(251),
  'cash': 10000,
  'portfolio_value': 10000,
  'position': 0.0,
  'total_return': 0.0,
  'num_trades': 0})

In [45]:
obs, reward, terminated, truncated, info = env.step(action=Action.BUY)

2025-10-30 08:20:07,969 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108750.88
2025-10-30 08:20:07,969 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108750.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:20:07,970 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184

In [46]:
obs

array([ 1.0437194e+00,  1.0423387e+00,  8.8721601e-04,  3.4255561e-01,
        1.8390656e-02, -8.8633766e-04,  9.9982274e-01], dtype=float32)

In [47]:
reward

np.float64(-0.00017726753107654076)

In [48]:
terminated

False

In [49]:
info

{'step': np.int64(252),
 'cash': np.float64(8000.0),
 'portfolio_value': np.float64(9998.227324689235),
 'position': np.float64(0.018390655781360114),
 'total_return': np.float64(-0.00017726753107654076),
 'num_trades': 1}

In [50]:
info['position'] * obs[3]

np.float64(0.006299822352254406)

In [51]:
env.get_trade_history()

[]

In [52]:
(9972.511419154229 / 10_000 - 1)

-0.0027488580845771438

In [53]:
obs, reward, terminated, truncated, info = env.step(action=Action.SELL)

2025-10-30 08:20:19,544 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

In [54]:
env.get_trade_history()

[]

In [55]:
obs

array([ 1.0644850e+00,  1.0342150e+00,  9.5432578e-04, -1.0701023e+00,
        1.8390656e-02, -1.0961751e-03,  9.9978077e-01], dtype=float32)

In [56]:
info

{'step': np.int64(253),
 'cash': np.float64(8000.0),
 'portfolio_value': np.float64(9997.807649924303),
 'position': np.float64(0.018390655781360114),
 'total_return': np.float64(-0.0002192350075696595),
 'num_trades': 1,
 'sharpe': np.float64(-25.720927809752755),
 'max_drawdown': np.float64(4.197491728307265e-05)}

In [57]:
from stable_baselines3.common.vec_env import VecFrameStack
vec_env = VecFrameStack(env, n_stack=4)

AttributeError: 'TradingEnv' object has no attribute 'num_envs'

In [58]:

m_vec = Monitor(env, filename='monitor.csv')

In [59]:
m_vec.reset()

2025-10-30 08:20:26,247 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3730/9953

(array([ 1.0597899e+00,  1.0524679e+00,  1.9065179e-04, -3.7684655e-01,
         0.0000000e+00,  0.0000000e+00,  1.0000000e+00], dtype=float32),
 {'step': np.int64(3730),
  'cash': 10000,
  'portfolio_value': 10000,
  'position': 0.0,
  'total_return': 0.0,
  'num_trades': 0})

In [60]:
def run_environment_random(make_env, n_steps=1000):
    _env = Monitor(make_env(), filename='monitor.csv')
    _env.reset()
    for _ in range(n_steps):
        action = _env.action_space.sample()
        obs, reward, terminated, truncated, info = _env.step(action)
        if terminated or truncated:
            _env.reset()

    return _env.get_episode_times(), _env.get_episode_rewards(), _env.get_episode_lengths()

In [ ]:
t, r, l = run_environment_random(make_env=make_env, n_steps=1000)

In [61]:
from statistics import mean, stdev
mean(r), stdev(r)

NameError: name 'r' is not defined

In [62]:
mean(l), stdev(l)

NameError: name 'l' is not defined

In [ ]:
# episodes = []
# for _ in range(100):
#     actions = []
#     rewards = []
#     action = m_vec.action_space.sample()
#     obs, reward, terminated, truncated, info = m_vec.step(action)
#
#     actions.append(action)
#     rewards.append(reward)
#
#     if terminated or truncated:
#         m_vec.reset()
#         episodes.append({'actions': actions, 'rewards': rewards})

In [ ]:

model = A2C("MlpPolicy", make_env(), verbose=1, tensorboard_log="tb_log")

In [ ]:
model.learn(total_timesteps=100_000)

In [63]:
def run_environment_model(make_env, model, n_steps=1000):
    _env = Monitor(make_env(), filename='monitor.csv')
    obs, info = _env.reset()
    for _ in range(n_steps):
        action, _ = model.predict(obs)
        obs, reward, terminated, truncated, info = _env.step(action)
        if terminated or truncated:
            obs, info = _env.reset()

    return _env.get_episode_times(), _env.get_episode_rewards(), _env.get_episode_lengths()

In [ ]:
t, r, l = run_environment_model(make_env=make_env, model=model, n_steps=1000)

In [ ]:
t, r, l

In [ ]:
mean(r), stdev(r)

In [ ]:
mean(l), stdev(l)

In [ ]:
test_env = Monitor(make_env(), filename='monitor_test.csv')
obs, info = test_env.reset()
episodes = []
actions = []
rewards = []
for _ in range(100):

    action, _ = model.predict(obs)
    obs, reward, terminated, truncated, info = test_env.step(action)

    actions.append(action)
    rewards.append(reward)

    if terminated or truncated:
        test_env.reset()
        episodes.append({'actions': actions.copy(), 'rewards': rewards.copy()})
        actions = []
        rewards = []

In [ ]:
episodes

In [ ]:
m_vec.get_total_steps()

In [ ]:
test_env.get_total_steps()

In [ ]:
test_env.get_episode_rewards()

In [ ]:
test_env.get_episode_lengths()

## Use Monitor Wrapper

In [ ]:
env = Monitor(make_env())
action = env.action_space.sample()

In [ ]:
action

In [ ]:
obs, info = env.reset()
env.step(action)

In [ ]:
model.predict(obs)

## Use VecNormalize

In [65]:
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

In [64]:
def make_monitored_env():
    return Monitor(make_env(), filename='monitor.csv')

In [16]:
env = VecNormalize(DummyVecEnv([make_monitored_env]))

2025-10-30 07:44:43,355 - rl_trading_lab.environment.trading_env - INFO - TradingEnv initialized: randomize_start=True, hold_closes_position=True, one_trade_mode=True, min_episode_length=2, reward_type=returns, data_length=9954

In [ ]:
env

In [ ]:
obs = env.reset()
for _ in range(100):
    action = env.action_space.sample()
    # obs, reward, terminated, truncated, info = env.step(action)
    obs, reward, done, info = env.step([action])
    if terminated or truncated:
        env.reset()

In [ ]:
env.get_original_reward()

In [ ]:
env.env_method('get_episode_rewards')

In [ ]:
env.env_method('get_episode_lengths')

In [66]:
import os; os.getcwd()

'/Users/mohamedali/trading_project/rl-trading-lab/notebooks'

In [67]:

mlflow.set_tracking_uri("file:../mlruns")
mlflow.set_experiment("mlflow_test")  # or reuse "rl_trading"
mlflow.autolog()

2025/10/30 08:20:59 INFO mlflow.bedrock: Enabled auto-tracing for Bedrock. Note that MLflow can only trace boto3 service clients that are created after this call. If you have already created one, please recreate the client by calling `boto3.client`.
2025/10/30 08:20:59 INFO mlflow.tracking.fluent: Autologging successfully enabled for boto3.

In [19]:
model = A2C(
    "MlpPolicy",
    env=VecNormalize(DummyVecEnv([make_monitored_env]), ),
    verbose=1,
    tensorboard_log="./tb_log/"
)
model.learn(total_timesteps=100_000)

2025-10-30 07:45:16,771 - rl_trading_lab.environment.trading_env - INFO - TradingEnv initialized: randomize_start=True, hold_closes_position=True, one_trade_mode=True, min_episode_length=2, reward_type=returns, data_length=9954

Using cpu device

2025-10-30 07:45:17,324 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3451/9953

Logging to ./tb_log/A2C_4

2025-10-30 07:45:17,328 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108006.56
2025-10-30 07:45:17,329 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108006.56 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,329 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:17,332 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,334 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:17,334 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.97, Commission=$0.00, Net=$1.97 (cash flow: -$1998.03, balance: $10001.97)
2025-10-30 07:45:17,335 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7136/9953
2025-10-30 07:45:17,353 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109411.67
2025-10-30 07:45:17,354 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109411.67 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,354 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:17,356 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,359 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:17,359 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.12, Commission=$0.00, Net=$-0.12 (cash flow: -$2000.12, balance: $9999.88)
2025-10-30 07:45:17,359 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7963/9953
2025-10-30 07:45:17,362 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109972.63
2025-10-30 07:45:17,362 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109972.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,362 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:17,366 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:17,367 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.20, Commission=$0.00, Net=$-0.20 (cash flow: -$2000.20, balance: $9999.80)
2025-10-30 07:45:17,367 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5485/9953
2025-10-30 07:45:17,369 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107831.14
2025-10-30 07:45:17,370 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107831.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,370 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:17,372 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,375 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:17,375 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.43, Commission=$0.00, Net=$-0.43 (cash flow: -$2000.43, balance: $9999.57)
2025-10-30 07:45:17,376 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 543/9953
2025-10-30 07:45:17,381 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110764.53
2025-10-30 07:45:17,381 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110764.53 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,382 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:17,383 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,388 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:17,388 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.44, Commission=$0.00, Net=$-0.44 (cash flow: +$1999.56, -$0.00, balance: $9999.56)
2025-10-30 07:45:17,389 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8292/9953
2025-10-30 07:45:17,392 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111148.83
2025-10-30 07:45:17,392 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111148.83 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,392 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:17,395 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,396 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:17,397 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.64, Commission=$0.00, Net=$0.64 (cash flow: +$2000.64, -$0.00, balance: $10000.64)
2025-10-30 07:45:17,398 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5033/9953
2025-10-30 07:45:17,400 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108888.51
2025-10-30 07:45:17,401 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108888.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,401 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:17,405 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:17,406 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.52, Commission=$0.00, Net=$1.52 (cash flow: -$1998.48, balance: $10001.52)
2025-10-30 07:45:17,407 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 378/9953
2025-10-30 07:45:17,411 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109815.27
2025-10-30 07:45:17,411 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109815.27 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,411 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:17,415 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:17,416 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.12, Commission=$0.00, Net=$0.12 (cash flow: +$2000.12, -$0.00, balance: $10000.12)
2025-10-30 07:45:17,417 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 565/9953
2025-10-30 07:45:17,421 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111029.18
2025-10-30 07:45:17,421 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111029.18 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,421 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:17,423 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:17,423 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.43, Commission=$0.00, Net=$0.43 (cash flow: -$1999.57, balance: $10000.43)
2025-10-30 07:45:17,424 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3340/9953
2025-10-30 07:45:17,427 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108456.69
2025-10-30 07:45:17,427 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108456.69 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,427 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:17,429 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,431 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:17,432 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.97, Commission=$0.00, Net=$0.97 (cash flow: -$1999.03, balance: $10000.97)
2025-10-30 07:45:17,432 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7045/9953
2025-10-30 07:45:17,437 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108809.03
2025-10-30 07:45:17,437 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108809.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,437 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:17,440 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:17,440 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.34, Commission=$0.00, Net=$-0.34 (cash flow: -$2000.34, balance: $9999.66)
2025-10-30 07:45:17,441 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2214/9953
2025-10-30 07:45:17,445 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111823.05
2025-10-30 07:45:17,445 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111823.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,445 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:17,448 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,451 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:17,452 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.64, Commission=$0.00, Net=$0.64 (cash flow: -$1999.36, balance: $10000.64)
2025-10-30 07:45:17,452 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3581/9953
2025-10-30 07:45:17,455 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108589.00
2025-10-30 07:45:17,455 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108589.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,455 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:17,457 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:17,458 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.50, Commission=$0.00, Net=$0.50 (cash flow: +$2000.50, -$0.00, balance: $10000.50)
2025-10-30 07:45:17,459 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9877/9953
2025-10-30 07:45:17,461 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111500.73
2025-10-30 07:45:17,462 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111500.73 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,462 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:17,463 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,468 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:45:17,468 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.25, Commission=$0.00, Net=$-0.25 (cash flow: -$2000.25, balance: $9999.75)
2025-10-30 07:45:17,469 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4155/9953
2025-10-30 07:45:17,473 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=106759.09
2025-10-30 07:45:17,473 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $106759.09 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,473 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 07:45:17,475 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,480 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 07:45:17,480 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-5.48, Commission=$0.00, Net=$-5.48 (cash flow: -$2005.48, balance: $9994.52)
2025-10-30 07:45:17,481 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1692/9953
2025-10-30 07:45:17,483 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112504.19
2025-10-30 07:45:17,483 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112504.19 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,483 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:17,485 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:17,486 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.52, Commission=$0.00, Net=$0.52 (cash flow: -$1999.48, balance: $10000.52)
2025-10-30 07:45:17,486 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4294/9953
2025-10-30 07:45:17,487 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107988.16
2025-10-30 07:45:17,488 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107988.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,489 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:17,494 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,495 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:17,496 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.63, Commission=$0.00, Net=$2.63 (cash flow: -$1997.37, balance: $10002.63)
2025-10-30 07:45:17,497 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 198/9953
2025-10-30 07:45:17,499 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108505.74
2025-10-30 07:45:17,500 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108505.74 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,500 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:17,502 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,504 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:17,505 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: +$1999.89, -$0.00, balance: $9999.89)
2025-10-30 07:45:17,506 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7617/9953
2025-10-30 07:45:17,510 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111205.00
2025-10-30 07:45:17,510 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111205.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,510 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:17,512 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,515 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 07:45:17,515 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.04, Commission=$0.00, Net=$0.04 (cash flow: +$2000.04, -$0.00, balance: $10000.04)
2025-10-30 07:45:17,516 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1895/9953
2025-10-30 07:45:17,521 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112333.77
2025-10-30 07:45:17,521 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112333.77 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,521 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:17,524 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,526 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:17,526 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.29, Commission=$0.00, Net=$-0.29 (cash flow: -$2000.29, balance: $9999.71)
2025-10-30 07:45:17,527 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1928/9953
2025-10-30 07:45:17,529 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112303.04
2025-10-30 07:45:17,529 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112303.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:17,529 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:17,534 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:17,534 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.59, Commission=$0.00, Net=$-0.59 (cash flow: +$1999.41, -$0.00, balance: $9999.41)
2025-10-30 07:45:17,535 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7048/9953
2025-10-30 07:45:17,539 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108890.82
2025-10-30 07:45:17,539 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108890.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,539 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:17,542 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:17,543 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.06, Commission=$0.00, Net=$-1.06 (cash flow: -$2001.06, balance: $9998.94)
2025-10-30 07:45:17,543 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1599/9953
2025-10-30 07:45:17,548 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111956.00
2025-10-30 07:45:17,548 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111956.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:17,548 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:17,550 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:17,553 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:17,553 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.96, Commission=$0.00, Net=$-0.96 (cash flow: -$2000.96, balance: $9999.04)

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 3.67      |
|    ep_rew_mean        | -8.33e-06 |
| time/                 |           |
|    fps                | 352       |
|    iterations         | 100       |
|    time_elapsed       | 1         |
|    total_timesteps    | 500       |
| train/                |           |
|    entropy_loss       | -1.05     |
|    explained_variance | -6.95     |
|    learning_rate      | 0.0007    |
|    n_updates          | 99        |
|    policy_loss        | 0.0374    |
|    value_loss         | 0.00439   |
-------------------------------------

2025-10-30 07:45:18,750 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:18,750 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.68, Commission=$0.00, Net=$-1.68 (cash flow: +$1998.32, -$0.00, balance: $9998.32)
2025-10-30 07:45:18,751 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1566/9953
2025-10-30 07:45:18,754 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111948.17
2025-10-30 07:45:18,754 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111948.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,755 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:18,756 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,758 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:18,759 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.10, Commission=$0.00, Net=$1.10 (cash flow: +$2001.10, -$0.00, balance: $10001.10)
2025-10-30 07:45:18,759 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5755/9953
2025-10-30 07:45:18,762 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107696.00
2025-10-30 07:45:18,762 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107696.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,763 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:18,764 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:18,765 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:45:18,765 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6194/9953
2025-10-30 07:45:18,770 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108277.22
2025-10-30 07:45:18,770 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108277.22 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,771 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:18,772 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,775 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:18,775 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.64, Commission=$0.00, Net=$0.64 (cash flow: +$2000.64, -$0.00, balance: $10000.64)
2025-10-30 07:45:18,776 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2076/9953
2025-10-30 07:45:18,781 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112028.52
2025-10-30 07:45:18,781 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112028.52 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,782 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:18,784 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:18,784 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.44, Commission=$0.00, Net=$-0.44 (cash flow: -$2000.44, balance: $9999.56)
2025-10-30 07:45:18,785 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 344/9953
2025-10-30 07:45:18,788 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109260.07
2025-10-30 07:45:18,789 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109260.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,789 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:18,792 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,794 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:18,794 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.45, Commission=$0.00, Net=$-0.45 (cash flow: -$2000.45, balance: $9999.55)
2025-10-30 07:45:18,795 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1195/9953
2025-10-30 07:45:18,800 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113289.59
2025-10-30 07:45:18,801 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113289.59 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,801 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:18,803 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:18,804 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: +$1999.94, -$0.00, balance: $9999.94)
2025-10-30 07:45:18,804 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 433/9953
2025-10-30 07:45:18,807 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110545.70
2025-10-30 07:45:18,807 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110545.70 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,808 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:18,810 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,814 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:18,815 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.14, Commission=$0.00, Net=$-2.14 (cash flow: +$1997.86, -$0.00, balance: $9997.86)
2025-10-30 07:45:18,815 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5641/9953
2025-10-30 07:45:18,817 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107851.59
2025-10-30 07:45:18,818 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107851.59 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,818 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:18,821 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,824 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:18,824 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.99, Commission=$0.00, Net=$0.99 (cash flow: -$1999.01, balance: $10000.99)
2025-10-30 07:45:18,825 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7746/9953
2025-10-30 07:45:18,827 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110221.64
2025-10-30 07:45:18,827 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110221.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,828 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:18,829 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:18,830 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.63, Commission=$0.00, Net=$1.63 (cash flow: -$1998.37, balance: $10001.63)
2025-10-30 07:45:18,831 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4460/9953
2025-10-30 07:45:18,833 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107949.44
2025-10-30 07:45:18,833 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107949.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,833 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:18,836 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,840 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:18,840 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: +$2000.38, -$0.00, balance: $10000.38)
2025-10-30 07:45:18,841 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7381/9953
2025-10-30 07:45:18,843 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110041.97
2025-10-30 07:45:18,844 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110041.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,844 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:18,845 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:18,845 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: +$1999.19, -$0.00, balance: $9999.19)
2025-10-30 07:45:18,847 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1584/9953
2025-10-30 07:45:18,850 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112049.81
2025-10-30 07:45:18,851 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112049.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,851 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:18,855 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:18,855 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.31, Commission=$0.00, Net=$-0.31 (cash flow: -$2000.31, balance: $9999.69)
2025-10-30 07:45:18,856 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4637/9953
2025-10-30 07:45:18,858 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108871.97
2025-10-30 07:45:18,858 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108871.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,859 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:18,861 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,862 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:18,863 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.95, Commission=$0.00, Net=$-0.95 (cash flow: +$1999.05, -$0.00, balance: $9999.05)
2025-10-30 07:45:18,864 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9262/9953
2025-10-30 07:45:18,866 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110090.75
2025-10-30 07:45:18,867 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110090.75 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,867 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:18,871 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,874 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:18,874 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.12, Commission=$0.00, Net=$0.12 (cash flow: -$1999.88, balance: $10000.12)
2025-10-30 07:45:18,875 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3000/9953
2025-10-30 07:45:18,880 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108546.71
2025-10-30 07:45:18,880 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108546.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,881 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:18,882 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,886 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:18,886 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.82, Commission=$0.00, Net=$-3.82 (cash flow: +$1996.18, -$0.00, balance: $9996.18)
2025-10-30 07:45:18,886 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3967/9953
2025-10-30 07:45:18,889 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108267.96
2025-10-30 07:45:18,889 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108267.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,890 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:18,894 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:18,894 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.54, Commission=$0.00, Net=$-0.54 (cash flow: +$1999.46, -$0.00, balance: $9999.46)
2025-10-30 07:45:18,895 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1756/9953
2025-10-30 07:45:18,896 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112330.68
2025-10-30 07:45:18,896 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112330.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,897 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:18,901 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,902 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:18,903 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.19, Commission=$0.00, Net=$0.19 (cash flow: -$1999.81, balance: $10000.19)
2025-10-30 07:45:18,904 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6190/9953
2025-10-30 07:45:18,907 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108213.97
2025-10-30 07:45:18,907 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108213.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,907 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:18,912 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,913 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:18,914 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.29, Commission=$0.00, Net=$-0.29 (cash flow: +$1999.71, -$0.00, balance: $9999.71)
2025-10-30 07:45:18,916 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5421/9953
2025-10-30 07:45:18,918 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108035.13
2025-10-30 07:45:18,918 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108035.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,919 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:18,922 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:18,922 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.28, Commission=$0.00, Net=$0.28 (cash flow: +$2000.28, -$0.00, balance: $10000.28)
2025-10-30 07:45:18,924 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7574/9953
2025-10-30 07:45:18,929 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110838.00
2025-10-30 07:45:18,929 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110838.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,929 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:18,933 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,934 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:18,934 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.62, Commission=$0.00, Net=$-1.62 (cash flow: -$2001.62, balance: $9998.38)
2025-10-30 07:45:18,937 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5197/9953
2025-10-30 07:45:18,938 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108412.85
2025-10-30 07:45:18,939 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108412.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:18,939 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:18,941 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,946 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:18,946 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.42, Commission=$0.00, Net=$3.42 (cash flow: -$1996.58, balance: $10003.42)
2025-10-30 07:45:18,947 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7007/9953
2025-10-30 07:45:18,950 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109086.28
2025-10-30 07:45:18,950 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109086.28 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:18,950 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:18,953 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:18,957 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:18,958 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.47, Commission=$0.00, Net=$0.47 (cash flow: +$2000.47, -$0.00, balance: $10000.47)
2025-10-30 07:45:18,958 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6932/9953
2025-10-30 07:45:18,961 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108888.00
2025-10-30 07:45:18,961 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108888.00 (cash flow: -$2000.00, remaining: $8000.00)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 3.65     |
|    ep_rew_mean        | 3.16e-05 |
| time/                 |          |
|    fps                | 354      |
|    iterations         | 200      |
|    time_elapsed       | 2        |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -0.989   |
|    explained_variance | -0.11    |
|    learning_rate      | 0.0007   |
|    n_updates          | 199      |
|    policy_loss        | 0.117    |
|    value_loss         | 0.0646   |
------------------------------------

2025-10-30 07:45:20,145 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:20,146 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.63, Commission=$0.00, Net=$1.63 (cash flow: +$2001.63, -$0.00, balance: $10001.63)
2025-10-30 07:45:20,146 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7821/9953
2025-10-30 07:45:20,149 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109912.00
2025-10-30 07:45:20,149 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109912.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,149 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:20,152 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,158 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:20,158 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.15, Commission=$0.00, Net=$-1.15 (cash flow: -$2001.15, balance: $9998.85)
2025-10-30 07:45:20,159 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8162/9953
2025-10-30 07:45:20,167 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110916.25
2025-10-30 07:45:20,167 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110916.25 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,167 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:20,172 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:20,172 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: +$2000.20, -$0.00, balance: $10000.20)
2025-10-30 07:45:20,173 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1296/9953
2025-10-30 07:45:20,174 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113760.00
2025-10-30 07:45:20,174 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113760.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,174 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:20,178 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,180 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:20,181 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.75, Commission=$0.00, Net=$-0.75 (cash flow: -$2000.75, balance: $9999.25)
2025-10-30 07:45:20,182 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7952/9953
2025-10-30 07:45:20,186 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110020.28
2025-10-30 07:45:20,187 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110020.28 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,187 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:20,190 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,194 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:20,194 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.90, Commission=$0.00, Net=$0.90 (cash flow: +$2000.90, -$0.00, balance: $10000.90)
2025-10-30 07:45:20,195 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 398/9953
2025-10-30 07:45:20,200 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110292.73
2025-10-30 07:45:20,200 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110292.73 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,200 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:20,202 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,205 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:20,206 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.93, Commission=$0.00, Net=$1.93 (cash flow: -$1998.07, balance: $10001.93)
2025-10-30 07:45:20,207 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7950/9953
2025-10-30 07:45:20,213 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109933.63
2025-10-30 07:45:20,213 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109933.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,213 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:20,214 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,218 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:20,218 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.67, Commission=$0.00, Net=$-1.67 (cash flow: -$2001.67, balance: $9998.33)
2025-10-30 07:45:20,220 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5642/9953
2025-10-30 07:45:20,226 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107794.90
2025-10-30 07:45:20,226 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107794.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,226 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:20,229 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:20,230 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.67, Commission=$0.00, Net=$0.67 (cash flow: +$2000.67, -$0.00, balance: $10000.67)
2025-10-30 07:45:20,231 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2339/9953
2025-10-30 07:45:20,234 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111800.26
2025-10-30 07:45:20,234 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111800.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,234 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:20,236 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:20,237 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.12, Commission=$0.00, Net=$0.12 (cash flow: -$1999.88, balance: $10000.12)
2025-10-30 07:45:20,239 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1416/9953
2025-10-30 07:45:20,246 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112800.00
2025-10-30 07:45:20,246 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112800.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,246 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:20,250 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,252 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:20,252 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 07:45:20,253 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5737/9953
2025-10-30 07:45:20,255 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107652.00
2025-10-30 07:45:20,255 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107652.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,256 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:20,258 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:20,259 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.41, Commission=$0.00, Net=$-0.41 (cash flow: +$1999.59, -$0.00, balance: $9999.59)
2025-10-30 07:45:20,259 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6160/9953
2025-10-30 07:45:20,261 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108411.63
2025-10-30 07:45:20,262 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108411.63 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,262 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:20,267 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,270 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:20,270 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.57, Commission=$0.00, Net=$-0.57 (cash flow: +$1999.43, -$0.00, balance: $9999.43)
2025-10-30 07:45:20,271 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8595/9953
2025-10-30 07:45:20,275 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111152.99
2025-10-30 07:45:20,275 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111152.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,275 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:20,278 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:20,278 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.92, Commission=$0.00, Net=$0.92 (cash flow: +$2000.92, -$0.00, balance: $10000.92)
2025-10-30 07:45:20,279 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3229/9953
2025-10-30 07:45:20,282 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108438.40
2025-10-30 07:45:20,282 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108438.40 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,283 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:20,285 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,289 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:20,289 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.65, Commission=$0.00, Net=$0.65 (cash flow: -$1999.35, balance: $10000.65)
2025-10-30 07:45:20,290 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2909/9953
2025-10-30 07:45:20,293 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108994.99
2025-10-30 07:45:20,294 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $108994.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,294 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:20,295 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,301 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:20,302 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.86, Commission=$0.00, Net=$-0.86 (cash flow: +$1999.14, -$0.00, balance: $9999.14)
2025-10-30 07:45:20,302 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7689/9953
2025-10-30 07:45:20,304 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110800.00
2025-10-30 07:45:20,304 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110800.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,305 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:20,308 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,313 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:20,313 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.56, Commission=$0.00, Net=$-0.56 (cash flow: -$2000.56, balance: $9999.44)
2025-10-30 07:45:20,313 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5987/9953
2025-10-30 07:45:20,316 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107226.68
2025-10-30 07:45:20,316 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107226.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,317 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 07:45:20,319 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,324 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0187, signal=1.0
2025-10-30 07:45:20,324 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.19, Commission=$0.00, Net=$4.19 (cash flow: -$1995.81, balance: $10004.19)
2025-10-30 07:45:20,325 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6102/9953
2025-10-30 07:45:20,328 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107906.30
2025-10-30 07:45:20,329 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107906.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,329 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:20,332 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,336 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:20,336 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.41, Commission=$0.00, Net=$1.41 (cash flow: -$1998.59, balance: $10001.41)
2025-10-30 07:45:20,337 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2859/9953
2025-10-30 07:45:20,339 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109258.81
2025-10-30 07:45:20,340 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109258.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,340 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:20,343 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,344 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:20,344 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.17, Commission=$0.00, Net=$-0.17 (cash flow: -$2000.17, balance: $9999.83)
2025-10-30 07:45:20,345 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6516/9953
2025-10-30 07:45:20,349 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110167.99
2025-10-30 07:45:20,350 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110167.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,350 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:20,352 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,355 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:20,355 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.28, Commission=$0.00, Net=$2.28 (cash flow: -$1997.72, balance: $10002.28)
2025-10-30 07:45:20,355 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1880/9953
2025-10-30 07:45:20,361 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112370.73
2025-10-30 07:45:20,361 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112370.73 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,361 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:20,363 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,365 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 07:45:20,365 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.10, Commission=$0.00, Net=$0.10 (cash flow: -$1999.90, balance: $10000.10)
2025-10-30 07:45:20,366 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1660/9953
2025-10-30 07:45:20,371 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112212.05
2025-10-30 07:45:20,372 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112212.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:20,372 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:20,374 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,376 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 07:45:20,376 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: -$2000.35, balance: $9999.65)
2025-10-30 07:45:20,377 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9597/9953
2025-10-30 07:45:20,379 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111030.00
2025-10-30 07:45:20,379 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111030.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:20,380 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:20,383 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:20,386 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:20,387 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: +$2000.16, -$0.00, balance: $10000.16)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.01     |
|    ep_rew_mean        | 1.64e-05 |
| time/                 |          |
|    fps                | 364      |
|    iterations         | 300      |
|    time_elapsed       | 4        |
|    total_timesteps    | 1500     |
| train/                |          |
|    entropy_loss       | -0.972   |
|    explained_variance | -0.86    |
|    learning_rate      | 0.0007   |
|    n_updates          | 299      |
|    policy_loss        | -0.128   |
|    value_loss         | 0.0732   |
------------------------------------

2025-10-30 07:45:21,448 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,451 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:21,451 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.16, Commission=$0.00, Net=$1.16 (cash flow: -$1998.84, balance: $10001.16)
2025-10-30 07:45:21,453 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7269/9953
2025-10-30 07:45:21,457 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109555.64
2025-10-30 07:45:21,460 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109555.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,465 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:21,470 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,484 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:21,485 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.02, Commission=$0.00, Net=$-3.02 (cash flow: -$2003.02, balance: $9996.98)
2025-10-30 07:45:21,486 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2586/9953
2025-10-30 07:45:21,491 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110559.39
2025-10-30 07:45:21,492 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110559.39 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,492 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:21,505 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,507 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:21,507 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.07, Commission=$0.00, Net=$2.07 (cash flow: -$1997.93, balance: $10002.07)
2025-10-30 07:45:21,509 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3326/9953
2025-10-30 07:45:21,511 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108442.07
2025-10-30 07:45:21,511 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108442.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,511 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:21,513 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,518 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:21,519 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.70, Commission=$0.00, Net=$1.70 (cash flow: -$1998.30, balance: $10001.70)
2025-10-30 07:45:21,519 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1453/9953
2025-10-30 07:45:21,523 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112692.75
2025-10-30 07:45:21,523 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112692.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,524 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:21,527 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:21,527 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.70, Commission=$0.00, Net=$0.70 (cash flow: +$2000.70, -$0.00, balance: $10000.70)
2025-10-30 07:45:21,528 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 957/9953
2025-10-30 07:45:21,531 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113140.00
2025-10-30 07:45:21,531 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113140.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,531 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:21,535 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:21,535 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.28, Commission=$0.00, Net=$0.28 (cash flow: -$1999.72, balance: $10000.28)
2025-10-30 07:45:21,536 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5224/9953
2025-10-30 07:45:21,541 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108624.10
2025-10-30 07:45:21,541 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108624.10 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,541 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:21,544 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,547 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:21,547 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.31, Commission=$0.00, Net=$-1.31 (cash flow: +$1998.69, -$0.00, balance: $9998.69)
2025-10-30 07:45:21,548 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4416/9953
2025-10-30 07:45:21,551 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108056.81
2025-10-30 07:45:21,552 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108056.81 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,552 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:21,557 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:21,557 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.11, Commission=$0.00, Net=$1.11 (cash flow: +$2001.11, -$0.00, balance: $10001.11)
2025-10-30 07:45:21,559 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4849/9953
2025-10-30 07:45:21,562 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107819.26
2025-10-30 07:45:21,562 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107819.26 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,562 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:21,566 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,570 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:21,570 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.74, Commission=$0.00, Net=$1.74 (cash flow: +$2001.74, -$0.00, balance: $10001.74)
2025-10-30 07:45:21,571 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6278/9953
2025-10-30 07:45:21,574 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108552.64
2025-10-30 07:45:21,575 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108552.64 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,575 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:21,578 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,582 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:21,583 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.50, Commission=$0.00, Net=$-0.50 (cash flow: +$1999.50, -$0.00, balance: $9999.50)
2025-10-30 07:45:21,583 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7277/9953
2025-10-30 07:45:21,587 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109601.91
2025-10-30 07:45:21,587 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109601.91 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,587 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:21,590 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,596 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:21,596 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.14, Commission=$0.00, Net=$-4.14 (cash flow: +$1995.86, -$0.00, balance: $9995.86)
2025-10-30 07:45:21,597 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8938/9953
2025-10-30 07:45:21,600 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110785.21
2025-10-30 07:45:21,600 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110785.21 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,600 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:21,604 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,605 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:21,606 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.65, Commission=$0.00, Net=$-1.65 (cash flow: +$1998.35, -$0.00, balance: $9998.35)
2025-10-30 07:45:21,607 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1534/9953
2025-10-30 07:45:21,613 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112477.46
2025-10-30 07:45:21,614 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112477.46 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,614 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:21,616 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:21,616 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: +$2000.16, -$0.00, balance: $10000.16)
2025-10-30 07:45:21,617 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2613/9953
2025-10-30 07:45:21,619 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110423.14
2025-10-30 07:45:21,620 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110423.14 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,620 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:21,625 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,630 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:21,630 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.11, Commission=$0.00, Net=$-1.11 (cash flow: +$1998.89, -$0.00, balance: $9998.89)
2025-10-30 07:45:21,631 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8895/9953
2025-10-30 07:45:21,632 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111130.26
2025-10-30 07:45:21,633 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111130.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,633 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:21,639 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,640 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:21,640 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.92, Commission=$0.00, Net=$-0.92 (cash flow: -$2000.92, balance: $9999.08)
2025-10-30 07:45:21,642 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8628/9953
2025-10-30 07:45:21,644 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110934.81
2025-10-30 07:45:21,644 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110934.81 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,644 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:21,648 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:21,648 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.67, Commission=$0.00, Net=$-0.67 (cash flow: +$1999.33, -$0.00, balance: $9999.33)
2025-10-30 07:45:21,648 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 12/9953
2025-10-30 07:45:21,654 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108461.57
2025-10-30 07:45:21,654 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108461.57 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,654 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:21,657 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,659 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:21,659 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.74, Commission=$0.00, Net=$0.74 (cash flow: -$1999.26, balance: $10000.74)
2025-10-30 07:45:21,660 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8548/9953
2025-10-30 07:45:21,664 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111340.00
2025-10-30 07:45:21,664 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111340.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,664 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:21,669 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,675 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:21,676 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.96, Commission=$0.00, Net=$-1.96 (cash flow: -$2001.96, balance: $9998.04)
2025-10-30 07:45:21,677 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4826/9953
2025-10-30 07:45:21,680 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107769.26
2025-10-30 07:45:21,680 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107769.26 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,680 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:21,683 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:21,684 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.03, Commission=$0.00, Net=$2.03 (cash flow: +$2002.03, -$0.00, balance: $10002.03)
2025-10-30 07:45:21,685 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6407/9953
2025-10-30 07:45:21,688 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108791.85
2025-10-30 07:45:21,688 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108791.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,688 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:21,691 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:21,692 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.16, Commission=$0.00, Net=$-1.16 (cash flow: -$2001.16, balance: $9998.84)
2025-10-30 07:45:21,693 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4581/9953
2025-10-30 07:45:21,697 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107921.61
2025-10-30 07:45:21,698 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107921.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,698 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:21,701 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,702 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:21,703 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.36, Commission=$0.00, Net=$0.36 (cash flow: +$2000.36, -$0.00, balance: $10000.36)
2025-10-30 07:45:21,704 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6047/9953
2025-10-30 07:45:21,707 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107931.54
2025-10-30 07:45:21,707 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107931.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:21,707 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:21,711 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,715 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:21,715 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.02, Commission=$0.00, Net=$-2.02 (cash flow: +$1997.98, -$0.00, balance: $9997.98)
2025-10-30 07:45:21,716 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5326/9953
2025-10-30 07:45:21,718 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108569.82
2025-10-30 07:45:21,718 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108569.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:21,720 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:21,723 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:21,725 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:21,725 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.33, Commission=$0.00, Net=$2.33 (cash flow: -$1997.67, balance: $10002.33)
2025-10-30 07:45:21,726 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3571/9953
2025-10-30 07:45:21,731 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108503.00

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.41     |
|    ep_rew_mean        | 1.64e-05 |
| time/                 |          |
|    fps                | 369      |
|    iterations         | 400      |
|    time_elapsed       | 5        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -0.986   |
|    explained_variance | 0.669    |
|    learning_rate      | 0.0007   |
|    n_updates          | 399      |
|    policy_loss        | 0.642    |
|    value_loss         | 0.557    |
------------------------------------

2025-10-30 07:45:22,741 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:22,741 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.22, Commission=$0.00, Net=$0.22 (cash flow: -$1999.78, balance: $10000.22)
2025-10-30 07:45:22,742 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8714/9953
2025-10-30 07:45:22,745 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111799.98
2025-10-30 07:45:22,745 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111799.98 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,745 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:22,748 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:22,748 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.49, Commission=$0.00, Net=$-0.49 (cash flow: +$1999.51, -$0.00, balance: $9999.51)
2025-10-30 07:45:22,749 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6937/9953
2025-10-30 07:45:22,753 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108888.01
2025-10-30 07:45:22,753 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108888.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,753 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:22,756 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,761 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:22,761 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 07:45:22,762 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8201/9953
2025-10-30 07:45:22,766 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111256.91
2025-10-30 07:45:22,766 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111256.91 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,766 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:22,769 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,779 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:22,779 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.30, Commission=$0.00, Net=$-0.30 (cash flow: +$1999.70, -$0.00, balance: $9999.70)
2025-10-30 07:45:22,780 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1379/9953
2025-10-30 07:45:22,783 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113314.81
2025-10-30 07:45:22,783 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113314.81 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,783 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:22,784 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,786 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0176, signal=-1.0
2025-10-30 07:45:22,787 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.38, Commission=$0.00, Net=$-0.38 (cash flow: +$1999.62, -$0.00, balance: $9999.62)
2025-10-30 07:45:22,788 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1931/9953
2025-10-30 07:45:22,793 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112302.65
2025-10-30 07:45:22,794 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112302.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,794 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:22,795 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,799 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:22,800 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.62, Commission=$0.00, Net=$-0.62 (cash flow: -$2000.62, balance: $9999.38)
2025-10-30 07:45:22,800 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5556/9953
2025-10-30 07:45:22,804 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107969.76
2025-10-30 07:45:22,804 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107969.76 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,805 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:22,806 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,811 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:22,811 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.28, Commission=$0.00, Net=$-0.28 (cash flow: +$1999.72, -$0.00, balance: $9999.72)
2025-10-30 07:45:22,812 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4728/9953
2025-10-30 07:45:22,816 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108173.48
2025-10-30 07:45:22,817 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108173.48 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,817 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:22,821 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,826 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:22,827 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.29, Commission=$0.00, Net=$-3.29 (cash flow: -$2003.29, balance: $9996.71)
2025-10-30 07:45:22,827 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9790/9953
2025-10-30 07:45:22,830 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111327.23
2025-10-30 07:45:22,830 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111327.23 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,831 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:22,834 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,837 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:22,837 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.33, Commission=$0.00, Net=$-0.33 (cash flow: -$2000.33, balance: $9999.67)
2025-10-30 07:45:22,839 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8922/9953
2025-10-30 07:45:22,841 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110750.79
2025-10-30 07:45:22,842 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110750.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,842 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:22,845 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:22,845 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.55, Commission=$0.00, Net=$-1.55 (cash flow: -$2001.55, balance: $9998.45)
2025-10-30 07:45:22,845 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7105/9953
2025-10-30 07:45:22,852 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109562.06
2025-10-30 07:45:22,852 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109562.06 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,853 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:22,856 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,863 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:22,864 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.06, Commission=$0.00, Net=$1.06 (cash flow: +$2001.06, -$0.00, balance: $10001.06)
2025-10-30 07:45:22,864 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2565/9953
2025-10-30 07:45:22,869 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110778.00
2025-10-30 07:45:22,870 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110778.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,870 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:22,873 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,875 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:22,875 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.33, Commission=$0.00, Net=$-2.33 (cash flow: -$2002.33, balance: $9997.67)
2025-10-30 07:45:22,875 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6678/9953
2025-10-30 07:45:22,877 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109279.11
2025-10-30 07:45:22,877 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109279.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,878 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:22,882 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,886 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:22,886 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.35, Commission=$0.00, Net=$0.35 (cash flow: -$1999.65, balance: $10000.35)
2025-10-30 07:45:22,887 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6353/9953
2025-10-30 07:45:22,891 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108929.48
2025-10-30 07:45:22,891 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108929.48 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,891 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:22,893 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,895 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:22,896 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.54, Commission=$0.00, Net=$-0.54 (cash flow: +$1999.46, -$0.00, balance: $9999.46)
2025-10-30 07:45:22,897 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5961/9953
2025-10-30 07:45:22,899 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107065.34
2025-10-30 07:45:22,899 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107065.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,899 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 07:45:22,901 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,906 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0187, signal=1.0
2025-10-30 07:45:22,906 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.09, Commission=$0.00, Net=$-0.09 (cash flow: -$2000.09, balance: $9999.91)
2025-10-30 07:45:22,907 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1005/9953
2025-10-30 07:45:22,910 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113132.22
2025-10-30 07:45:22,910 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113132.22 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,910 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:22,912 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,914 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:22,914 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.83, Commission=$0.00, Net=$-1.83 (cash flow: +$1998.17, -$0.00, balance: $9998.17)
2025-10-30 07:45:22,915 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9316/9953
2025-10-30 07:45:22,919 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110110.51
2025-10-30 07:45:22,919 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110110.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,920 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:22,921 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,927 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:22,928 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.58, Commission=$0.00, Net=$2.58 (cash flow: +$2002.58, -$0.00, balance: $10002.58)
2025-10-30 07:45:22,928 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5893/9953
2025-10-30 07:45:22,932 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=106881.44
2025-10-30 07:45:22,932 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $106881.44 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,933 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 07:45:22,934 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,938 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0187, signal=1.0
2025-10-30 07:45:22,938 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.59, Commission=$0.00, Net=$-2.59 (cash flow: -$2002.59, balance: $9997.41)
2025-10-30 07:45:22,939 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6136/9953
2025-10-30 07:45:22,941 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108307.80
2025-10-30 07:45:22,942 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108307.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:22,942 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:22,944 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,946 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:22,947 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.37, Commission=$0.00, Net=$1.37 (cash flow: -$1998.63, balance: $10001.37)
2025-10-30 07:45:22,947 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5071/9953
2025-10-30 07:45:22,951 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108724.22
2025-10-30 07:45:22,952 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108724.22 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,952 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:22,954 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,957 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:22,957 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.29, Commission=$0.00, Net=$-1.29 (cash flow: +$1998.71, -$0.00, balance: $9998.71)
2025-10-30 07:45:22,958 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8210/9953
2025-10-30 07:45:22,962 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111240.00
2025-10-30 07:45:22,962 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111240.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,962 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:22,965 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,967 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:22,967 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.27, Commission=$0.00, Net=$2.27 (cash flow: +$2002.27, -$0.00, balance: $10002.27)
2025-10-30 07:45:22,968 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8037/9953
2025-10-30 07:45:22,970 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110510.00
2025-10-30 07:45:22,970 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110510.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,971 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:22,975 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:22,975 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.09, Commission=$0.00, Net=$0.09 (cash flow: +$2000.09, -$0.00, balance: $10000.09)
2025-10-30 07:45:22,976 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7803/9953
2025-10-30 07:45:22,978 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110021.94
2025-10-30 07:45:22,978 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110021.94 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:22,979 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:22,981 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:22,985 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.24     |
|    ep_rew_mean        | 1.73e-06 |
| time/                 |          |
|    fps                | 372      |
|    iterations         | 500      |
|    time_elapsed       | 6        |
|    total_timesteps    | 2500     |
| train/                |          |
|    entropy_loss       | -0.812   |
|    explained_variance | 0.123    |
|    learning_rate      | 0.0007   |
|    n_updates          | 499      |
|    policy_loss        | -0.19    |
|    value_loss         | 0.252    |
------------------------------------

2025-10-30 07:45:24,033 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108534.12
2025-10-30 07:45:24,033 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108534.12 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,033 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:24,035 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,037 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:24,038 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.07, Commission=$0.00, Net=$3.07 (cash flow: -$1996.93, balance: $10003.07)
2025-10-30 07:45:24,039 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2815/9953
2025-10-30 07:45:24,041 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109332.00
2025-10-30 07:45:24,041 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109332.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,042 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:24,047 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,050 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:24,050 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.50, Commission=$0.00, Net=$-1.50 (cash flow: +$1998.50, -$0.00, balance: $9998.50)
2025-10-30 07:45:24,051 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4642/9953
2025-10-30 07:45:24,054 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108880.01
2025-10-30 07:45:24,055 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108880.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,055 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:24,059 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,062 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:24,063 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.96, Commission=$0.00, Net=$-1.96 (cash flow: -$2001.96, balance: $9998.04)
2025-10-30 07:45:24,063 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6371/9953
2025-10-30 07:45:24,068 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108700.00
2025-10-30 07:45:24,068 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108700.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,068 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:24,069 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,071 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:24,072 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.80, Commission=$0.00, Net=$-0.80 (cash flow: -$2000.80, balance: $9999.20)
2025-10-30 07:45:24,073 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8339/9953
2025-10-30 07:45:24,074 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111426.99
2025-10-30 07:45:24,075 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111426.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,075 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:24,076 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:24,077 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.44, Commission=$0.00, Net=$-0.44 (cash flow: -$2000.44, balance: $9999.56)
2025-10-30 07:45:24,078 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2183/9953
2025-10-30 07:45:24,084 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111854.54
2025-10-30 07:45:24,084 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111854.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,084 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:24,086 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:24,086 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.66, Commission=$0.00, Net=$-0.66 (cash flow: -$2000.66, balance: $9999.34)
2025-10-30 07:45:24,087 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4983/9953
2025-10-30 07:45:24,092 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108800.00
2025-10-30 07:45:24,093 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108800.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,093 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:24,098 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,100 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:24,100 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 07:45:24,101 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 487/9953
2025-10-30 07:45:24,104 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109892.60
2025-10-30 07:45:24,105 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109892.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,105 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:24,109 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,110 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:24,111 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.19, Commission=$0.00, Net=$-0.19 (cash flow: -$2000.19, balance: $9999.81)
2025-10-30 07:45:24,111 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1906/9953
2025-10-30 07:45:24,114 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112313.59
2025-10-30 07:45:24,114 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112313.59 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,114 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:24,117 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,123 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:24,123 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: +$1999.94, -$0.00, balance: $9999.94)
2025-10-30 07:45:24,124 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7646/9953
2025-10-30 07:45:24,126 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111218.00
2025-10-30 07:45:24,126 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111218.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,127 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:24,129 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:24,129 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.19, Commission=$0.00, Net=$-0.19 (cash flow: -$2000.19, balance: $9999.81)
2025-10-30 07:45:24,130 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6607/9953
2025-10-30 07:45:24,134 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109954.90
2025-10-30 07:45:24,134 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109954.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,134 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:24,136 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,140 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:24,140 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.66, Commission=$0.00, Net=$0.66 (cash flow: -$1999.34, balance: $10000.66)
2025-10-30 07:45:24,141 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5394/9953
2025-10-30 07:45:24,145 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108151.58
2025-10-30 07:45:24,145 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108151.58 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,146 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:24,148 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:24,148 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.18, Commission=$0.00, Net=$-2.18 (cash flow: -$2002.18, balance: $9997.82)
2025-10-30 07:45:24,149 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1358/9953
2025-10-30 07:45:24,151 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113500.66
2025-10-30 07:45:24,151 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113500.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,152 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:24,154 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,159 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:24,159 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.66, Commission=$0.00, Net=$-0.66 (cash flow: +$1999.34, -$0.00, balance: $9999.34)
2025-10-30 07:45:24,160 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3999/9953
2025-10-30 07:45:24,163 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108057.81
2025-10-30 07:45:24,163 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108057.81 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,163 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:24,165 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,167 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:24,167 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.24, Commission=$0.00, Net=$0.24 (cash flow: +$2000.24, -$0.00, balance: $10000.24)
2025-10-30 07:45:24,168 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6046/9953
2025-10-30 07:45:24,172 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107928.23
2025-10-30 07:45:24,172 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107928.23 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,173 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:24,175 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,177 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:24,177 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.86, Commission=$0.00, Net=$0.86 (cash flow: -$1999.14, balance: $10000.86)
2025-10-30 07:45:24,178 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4262/9953
2025-10-30 07:45:24,180 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108080.32
2025-10-30 07:45:24,180 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108080.32 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,180 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:24,184 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,187 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:24,188 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.87, Commission=$0.00, Net=$1.87 (cash flow: -$1998.13, balance: $10001.87)
2025-10-30 07:45:24,188 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7445/9953
2025-10-30 07:45:24,192 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109986.85
2025-10-30 07:45:24,192 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109986.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,193 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:24,195 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,199 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:24,199 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.03, Commission=$0.00, Net=$-2.03 (cash flow: -$2002.03, balance: $9997.97)
2025-10-30 07:45:24,200 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4637/9953
2025-10-30 07:45:24,203 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108820.01
2025-10-30 07:45:24,203 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108820.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,204 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:24,206 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,210 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:24,210 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.10, Commission=$0.00, Net=$1.10 (cash flow: +$2001.10, -$0.00, balance: $10001.10)
2025-10-30 07:45:24,211 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7456/9953
2025-10-30 07:45:24,214 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110463.60
2025-10-30 07:45:24,215 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110463.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,215 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:24,219 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,220 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:24,221 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.86, Commission=$0.00, Net=$-0.86 (cash flow: +$1999.14, -$0.00, balance: $9999.14)
2025-10-30 07:45:24,222 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8438/9953
2025-10-30 07:45:24,224 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111046.59
2025-10-30 07:45:24,224 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111046.59 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:24,224 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:24,226 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:24,227 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.47, Commission=$0.00, Net=$-0.47 (cash flow: -$2000.47, balance: $9999.53)
2025-10-30 07:45:24,228 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1299/9953
2025-10-30 07:45:24,230 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113803.57
2025-10-30 07:45:24,231 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113803.57 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,231 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:24,235 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:24,236 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.11, Commission=$0.00, Net=$-1.11 (cash flow: +$1998.89, -$0.00, balance: $9998.89)
2025-10-30 07:45:24,236 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2548/9953
2025-10-30 07:45:24,239 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110426.13
2025-10-30 07:45:24,239 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110426.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,239 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:24,241 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:24,248 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:24,249 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.54, Commission=$0.00, Net=$4.54 (cash flow: +$2004.54, -$0.00, balance: $10004.54)
2025-10-30 07:45:24,249 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1987/9953
2025-10-30 07:45:24,251 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112156.12
2025-10-30 07:45:24,251 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112156.12 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:24,252 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:24,253 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.41     |
|    ep_rew_mean        | 1.3e-05  |
| time/                 |          |
|    fps                | 377      |
|    iterations         | 600      |
|    time_elapsed       | 7        |
|    total_timesteps    | 3000     |
| train/                |          |
|    entropy_loss       | -0.911   |
|    explained_variance | -0.164   |
|    learning_rate      | 0.0007   |
|    n_updates          | 599      |
|    policy_loss        | 0.022    |
|    value_loss         | 0.0336   |
------------------------------------

2025-10-30 07:45:25,283 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:25,284 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.63, Commission=$0.00, Net=$-2.63 (cash flow: +$1997.37, -$0.00, balance: $9997.37)
2025-10-30 07:45:25,284 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 153/9953
2025-10-30 07:45:25,288 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109364.34
2025-10-30 07:45:25,289 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109364.34 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,289 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:25,291 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:25,291 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.25, Commission=$0.00, Net=$1.25 (cash flow: +$2001.25, -$0.00, balance: $10001.25)
2025-10-30 07:45:25,292 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6176/9953
2025-10-30 07:45:25,295 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108150.61
2025-10-30 07:45:25,295 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108150.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,295 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:25,298 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:25,298 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.09, Commission=$0.00, Net=$0.09 (cash flow: +$2000.09, -$0.00, balance: $10000.09)
2025-10-30 07:45:25,299 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2439/9953
2025-10-30 07:45:25,303 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110802.73
2025-10-30 07:45:25,303 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110802.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,304 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:25,306 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:25,307 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.76, Commission=$0.00, Net=$1.76 (cash flow: +$2001.76, -$0.00, balance: $10001.76)
2025-10-30 07:45:25,307 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3034/9953
2025-10-30 07:45:25,310 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108357.96
2025-10-30 07:45:25,311 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108357.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,311 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:25,313 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,315 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:25,316 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.80, Commission=$0.00, Net=$0.80 (cash flow: +$2000.80, -$0.00, balance: $10000.80)
2025-10-30 07:45:25,317 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9033/9953
2025-10-30 07:45:25,321 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110233.87
2025-10-30 07:45:25,321 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110233.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,322 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:25,323 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,331 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:25,331 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.72, Commission=$0.00, Net=$-3.72 (cash flow: +$1996.28, -$0.00, balance: $9996.28)
2025-10-30 07:45:25,332 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7596/9953
2025-10-30 07:45:25,337 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110964.36
2025-10-30 07:45:25,337 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110964.36 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,337 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:25,338 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,341 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:25,341 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.64, Commission=$0.00, Net=$0.64 (cash flow: +$2000.64, -$0.00, balance: $10000.64)
2025-10-30 07:45:25,342 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 311/9953
2025-10-30 07:45:25,344 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108318.40
2025-10-30 07:45:25,344 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108318.40 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,345 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:25,350 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,352 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:25,352 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.67, Commission=$0.00, Net=$1.67 (cash flow: -$1998.33, balance: $10001.67)
2025-10-30 07:45:25,353 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3955/9953
2025-10-30 07:45:25,355 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108345.11
2025-10-30 07:45:25,355 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108345.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,355 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:25,357 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:25,358 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.49, Commission=$0.00, Net=$-0.49 (cash flow: +$1999.51, -$0.00, balance: $9999.51)
2025-10-30 07:45:25,359 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9372/9953
2025-10-30 07:45:25,363 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110428.07
2025-10-30 07:45:25,363 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110428.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,363 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:25,364 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,367 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:25,367 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.43, Commission=$0.00, Net=$-1.43 (cash flow: -$2001.43, balance: $9998.57)
2025-10-30 07:45:25,368 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7433/9953
2025-10-30 07:45:25,371 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109710.47
2025-10-30 07:45:25,372 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109710.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,372 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:25,375 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,383 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:25,384 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.89, Commission=$0.00, Net=$-2.89 (cash flow: -$2002.89, balance: $9997.11)
2025-10-30 07:45:25,384 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5471/9953
2025-10-30 07:45:25,387 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107700.01
2025-10-30 07:45:25,387 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107700.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,387 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:25,390 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,393 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 07:45:25,393 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.29, Commission=$0.00, Net=$1.29 (cash flow: -$1998.71, balance: $10001.29)
2025-10-30 07:45:25,394 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9725/9953
2025-10-30 07:45:25,397 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111124.15
2025-10-30 07:45:25,397 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111124.15 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,397 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:25,400 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,401 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:25,402 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.08, Commission=$0.00, Net=$-0.08 (cash flow: -$2000.08, balance: $9999.92)
2025-10-30 07:45:25,404 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7440/9953
2025-10-30 07:45:25,408 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109783.41
2025-10-30 07:45:25,408 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109783.41 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,409 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:25,412 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:25,412 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.56, Commission=$0.00, Net=$-1.56 (cash flow: -$2001.56, balance: $9998.44)
2025-10-30 07:45:25,413 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6276/9953
2025-10-30 07:45:25,417 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108509.00
2025-10-30 07:45:25,417 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108509.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,417 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:25,420 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,424 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:25,425 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.28, Commission=$0.00, Net=$0.28 (cash flow: +$2000.28, -$0.00, balance: $10000.28)
2025-10-30 07:45:25,425 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1077/9953
2025-10-30 07:45:25,429 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113445.00
2025-10-30 07:45:25,429 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113445.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,429 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:25,432 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,436 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0176, signal=-1.0
2025-10-30 07:45:25,437 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.31, Commission=$0.00, Net=$0.31 (cash flow: +$2000.31, -$0.00, balance: $10000.31)
2025-10-30 07:45:25,438 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5537/9953
2025-10-30 07:45:25,441 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108191.83
2025-10-30 07:45:25,441 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108191.83 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,441 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:25,444 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,446 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:25,446 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.45, Commission=$0.00, Net=$2.45 (cash flow: -$1997.55, balance: $10002.45)
2025-10-30 07:45:25,447 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9276/9953
2025-10-30 07:45:25,449 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109986.92
2025-10-30 07:45:25,449 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109986.92 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,450 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:25,455 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,457 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:25,457 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.95, Commission=$0.00, Net=$-1.95 (cash flow: +$1998.05, -$0.00, balance: $9998.05)
2025-10-30 07:45:25,459 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9140/9953
2025-10-30 07:45:25,461 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109976.76
2025-10-30 07:45:25,461 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109976.76 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,462 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:25,465 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,466 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:25,467 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.91, Commission=$0.00, Net=$-1.91 (cash flow: -$2001.91, balance: $9998.09)
2025-10-30 07:45:25,468 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 282/9953
2025-10-30 07:45:25,472 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108775.09
2025-10-30 07:45:25,472 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108775.09 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,473 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:25,475 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:25,475 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.00, Commission=$0.00, Net=$2.00 (cash flow: -$1998.00, balance: $10002.00)
2025-10-30 07:45:25,476 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8016/9953
2025-10-30 07:45:25,478 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110444.43
2025-10-30 07:45:25,479 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110444.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,479 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:25,483 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,484 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:25,485 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.24, Commission=$0.00, Net=$-0.24 (cash flow: -$2000.24, balance: $9999.76)
2025-10-30 07:45:25,487 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1132/9953
2025-10-30 07:45:25,491 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113331.87
2025-10-30 07:45:25,491 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113331.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:25,491 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:25,494 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,496 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:25,496 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: +$1999.79, -$0.00, balance: $9999.79)
2025-10-30 07:45:25,498 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9095/9953
2025-10-30 07:45:25,499 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110015.55
2025-10-30 07:45:25,499 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110015.55 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:25,500 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:25,502 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:25,505 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:25,506 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.18, Commission=$0.00, Net=$1.18 (cash flow: -$1998.82, balance: $10001.18)
2025-10-30 07:45:25,506 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5795/9953

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 4.23      |
|    ep_rew_mean        | -4.53e-06 |
| time/                 |           |
|    fps                | 380       |
|    iterations         | 700       |
|    time_elapsed       | 9         |
|    total_timesteps    | 3500      |
| train/                |           |
|    entropy_loss       | -0.88     |
|    explained_variance | -0.115    |
|    learning_rate      | 0.0007    |
|    n_updates          | 699       |
|    policy_loss        | -0.147    |
|    value_loss         | 0.221     |
-------------------------------------

2025-10-30 07:45:26,537 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108408.43
2025-10-30 07:45:26,537 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108408.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,537 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:26,540 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,541 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:26,541 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: +$2000.95, -$0.00, balance: $10000.95)
2025-10-30 07:45:26,542 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1773/9953
2025-10-30 07:45:26,547 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112459.01
2025-10-30 07:45:26,548 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112459.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,548 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:26,550 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,553 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:26,553 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.74, Commission=$0.00, Net=$-0.74 (cash flow: -$2000.74, balance: $9999.26)
2025-10-30 07:45:26,554 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8520/9953
2025-10-30 07:45:26,558 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111239.90
2025-10-30 07:45:26,558 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111239.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,559 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:26,561 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,563 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:26,564 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.76, Commission=$0.00, Net=$-0.76 (cash flow: -$2000.76, balance: $9999.24)
2025-10-30 07:45:26,564 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5698/9953
2025-10-30 07:45:26,565 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107862.99
2025-10-30 07:45:26,566 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107862.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,567 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:26,571 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,574 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:26,574 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:45:26,575 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1079/9953
2025-10-30 07:45:26,580 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113470.36
2025-10-30 07:45:26,581 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113470.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,581 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:26,583 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,586 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:26,586 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.61, Commission=$0.00, Net=$-0.61 (cash flow: -$2000.61, balance: $9999.39)
2025-10-30 07:45:26,587 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6799/9953
2025-10-30 07:45:26,591 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109439.60
2025-10-30 07:45:26,591 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109439.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,591 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:26,593 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,596 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:26,596 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.72, Commission=$0.00, Net=$0.72 (cash flow: -$1999.28, balance: $10000.72)
2025-10-30 07:45:26,597 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6754/9953
2025-10-30 07:45:26,598 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109649.96
2025-10-30 07:45:26,599 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109649.96 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,599 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:26,603 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,605 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:26,605 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.79, Commission=$0.00, Net=$1.79 (cash flow: -$1998.21, balance: $10001.79)
2025-10-30 07:45:26,606 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8908/9953
2025-10-30 07:45:26,609 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111113.97
2025-10-30 07:45:26,609 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111113.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,609 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:26,612 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:26,612 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.46, Commission=$0.00, Net=$-0.46 (cash flow: +$1999.54, -$0.00, balance: $9999.54)
2025-10-30 07:45:26,613 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 179/9953
2025-10-30 07:45:26,618 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108838.23
2025-10-30 07:45:26,618 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108838.23 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,618 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:26,621 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,624 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:26,624 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.87, Commission=$0.00, Net=$-0.87 (cash flow: +$1999.13, -$0.00, balance: $9999.13)
2025-10-30 07:45:26,624 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6550/9953
2025-10-30 07:45:26,628 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110119.47
2025-10-30 07:45:26,628 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110119.47 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,629 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:26,630 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,632 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:26,633 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.82, Commission=$0.00, Net=$0.82 (cash flow: +$2000.82, -$0.00, balance: $10000.82)
2025-10-30 07:45:26,634 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6770/9953
2025-10-30 07:45:26,636 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109346.97
2025-10-30 07:45:26,636 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109346.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,636 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:26,639 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,643 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:26,644 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.63, Commission=$0.00, Net=$-1.63 (cash flow: +$1998.37, -$0.00, balance: $9998.37)
2025-10-30 07:45:26,644 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4349/9953
2025-10-30 07:45:26,647 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107383.57
2025-10-30 07:45:26,647 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107383.57 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,647 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:26,649 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,653 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:26,653 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.46, Commission=$0.00, Net=$0.46 (cash flow: +$2000.46, -$0.00, balance: $10000.46)
2025-10-30 07:45:26,654 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1128/9953
2025-10-30 07:45:26,657 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113248.87
2025-10-30 07:45:26,657 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113248.87 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,657 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:26,659 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:26,659 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.42, Commission=$0.00, Net=$-0.42 (cash flow: -$2000.42, balance: $9999.58)
2025-10-30 07:45:26,660 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3750/9953
2025-10-30 07:45:26,662 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108165.01
2025-10-30 07:45:26,663 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108165.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,663 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:26,667 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:26,667 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.18, Commission=$0.00, Net=$-1.18 (cash flow: +$1998.82, -$0.00, balance: $9998.82)
2025-10-30 07:45:26,668 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7831/9953
2025-10-30 07:45:26,670 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109820.30
2025-10-30 07:45:26,671 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109820.30 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,672 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:26,673 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:26,674 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: +$2000.20, -$0.00, balance: $10000.20)
2025-10-30 07:45:26,675 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1352/9953
2025-10-30 07:45:26,682 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113508.31
2025-10-30 07:45:26,682 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113508.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,682 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:26,685 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,689 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:26,689 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: -$2000.35, balance: $9999.65)
2025-10-30 07:45:26,690 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6318/9953
2025-10-30 07:45:26,691 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108323.60
2025-10-30 07:45:26,692 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108323.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,692 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:26,693 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:26,694 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.67, Commission=$0.00, Net=$1.67 (cash flow: +$2001.67, -$0.00, balance: $10001.67)
2025-10-30 07:45:26,694 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6448/9953
2025-10-30 07:45:26,697 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109474.27
2025-10-30 07:45:26,698 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109474.27 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,698 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:26,700 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,705 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:26,705 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.38, Commission=$0.00, Net=$1.38 (cash flow: +$2001.38, -$0.00, balance: $10001.38)
2025-10-30 07:45:26,706 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4663/9953
2025-10-30 07:45:26,708 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108716.60
2025-10-30 07:45:26,709 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108716.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,709 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:26,711 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,715 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:26,716 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.16, Commission=$0.00, Net=$-1.16 (cash flow: +$1998.84, -$0.00, balance: $9998.84)
2025-10-30 07:45:26,716 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 624/9953
2025-10-30 07:45:26,719 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111900.80
2025-10-30 07:45:26,719 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111900.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,719 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:26,722 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,723 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:26,724 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.27, Commission=$0.00, Net=$0.27 (cash flow: +$2000.27, -$0.00, balance: $10000.27)
2025-10-30 07:45:26,724 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8605/9953
2025-10-30 07:45:26,726 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111200.00
2025-10-30 07:45:26,726 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111200.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,727 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:26,731 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,733 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:26,733 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.90, Commission=$0.00, Net=$-0.90 (cash flow: -$2000.90, balance: $9999.10)
2025-10-30 07:45:26,734 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6035/9953
2025-10-30 07:45:26,736 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107772.33
2025-10-30 07:45:26,736 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107772.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:26,737 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:26,738 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:26,740 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 07:45:26,741 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.39, Commission=$0.00, Net=$-2.39 (cash flow: -$2002.39, balance: $9997.61)
2025-10-30 07:45:26,741 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4038/9953
2025-10-30 07:45:26,746 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107835.34
2025-10-30 07:45:26,746 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107835.34 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:26,746 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.14     |
|    ep_rew_mean        | 4.67e-06 |
| time/                 |          |
|    fps                | 384      |
|    iterations         | 800      |
|    time_elapsed       | 10       |
|    total_timesteps    | 4000     |
| train/                |          |
|    entropy_loss       | -0.768   |
|    explained_variance | -0.36    |
|    learning_rate      | 0.0007   |
|    n_updates          | 799      |
|    policy_loss        | -0.628   |
|    value_loss         | 0.641    |
------------------------------------

2025-10-30 07:45:27,751 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113686.20
2025-10-30 07:45:27,751 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113686.20 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,752 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:27,754 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:27,755 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.32, Commission=$0.00, Net=$0.32 (cash flow: -$1999.68, balance: $10000.32)
2025-10-30 07:45:27,756 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6604/9953
2025-10-30 07:45:27,759 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110007.40
2025-10-30 07:45:27,759 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110007.40 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,759 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:27,764 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,767 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:27,767 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.02, Commission=$0.00, Net=$1.02 (cash flow: -$1998.98, balance: $10001.02)
2025-10-30 07:45:27,768 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9398/9953
2025-10-30 07:45:27,770 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110619.38
2025-10-30 07:45:27,771 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110619.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,771 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:27,775 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:27,776 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.05, Commission=$0.00, Net=$0.05 (cash flow: -$1999.95, balance: $10000.05)
2025-10-30 07:45:27,777 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3578/9953
2025-10-30 07:45:27,778 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108557.98
2025-10-30 07:45:27,779 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108557.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,779 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:27,782 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,783 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:27,784 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.43, Commission=$0.00, Net=$-0.43 (cash flow: -$2000.43, balance: $9999.57)
2025-10-30 07:45:27,785 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 740/9953
2025-10-30 07:45:27,790 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112051.00
2025-10-30 07:45:27,790 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112051.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,790 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:27,792 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:27,793 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.11, Commission=$0.00, Net=$0.11 (cash flow: +$2000.11, -$0.00, balance: $10000.11)
2025-10-30 07:45:27,794 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9537/9953
2025-10-30 07:45:27,797 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110733.65
2025-10-30 07:45:27,797 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110733.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,798 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:27,799 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,803 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:27,803 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.64, Commission=$0.00, Net=$-0.64 (cash flow: +$1999.36, -$0.00, balance: $9999.36)
2025-10-30 07:45:27,804 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 574/9953
2025-10-30 07:45:27,806 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111260.01
2025-10-30 07:45:27,807 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111260.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,807 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:27,809 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:27,810 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.31, Commission=$0.00, Net=$0.31 (cash flow: +$2000.31, -$0.00, balance: $10000.31)
2025-10-30 07:45:27,811 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9125/9953
2025-10-30 07:45:27,813 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109750.00
2025-10-30 07:45:27,814 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109750.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,814 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:27,817 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:27,817 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 07:45:27,818 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8896/9953
2025-10-30 07:45:27,824 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111181.17
2025-10-30 07:45:27,824 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111181.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,824 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:27,827 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,829 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:27,829 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.40, Commission=$0.00, Net=$-0.40 (cash flow: -$2000.40, balance: $9999.60)
2025-10-30 07:45:27,830 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5860/9953
2025-10-30 07:45:27,833 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107151.01
2025-10-30 07:45:27,833 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107151.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,833 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:27,838 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,839 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:27,839 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.04, Commission=$0.00, Net=$2.04 (cash flow: +$2002.04, -$0.00, balance: $10002.04)
2025-10-30 07:45:27,840 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2541/9953
2025-10-30 07:45:27,846 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110441.20
2025-10-30 07:45:27,846 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110441.20 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,846 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:27,847 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,850 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:27,850 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.33, Commission=$0.00, Net=$-0.33 (cash flow: -$2000.33, balance: $9999.67)
2025-10-30 07:45:27,851 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5029/9953
2025-10-30 07:45:27,853 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108992.58
2025-10-30 07:45:27,854 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $108992.58 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,854 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:27,856 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,861 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:27,861 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.26, Commission=$0.00, Net=$1.26 (cash flow: -$1998.74, balance: $10001.26)
2025-10-30 07:45:27,862 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4881/9953
2025-10-30 07:45:27,863 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107824.96
2025-10-30 07:45:27,864 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107824.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,864 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:27,866 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,868 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:27,868 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.05, Commission=$0.00, Net=$0.05 (cash flow: +$2000.05, -$0.00, balance: $10000.05)
2025-10-30 07:45:27,869 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7822/9953
2025-10-30 07:45:27,874 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109968.56
2025-10-30 07:45:27,875 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109968.56 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,875 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:27,877 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,879 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:27,879 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.70, Commission=$0.00, Net=$0.70 (cash flow: +$2000.70, -$0.00, balance: $10000.70)
2025-10-30 07:45:27,881 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1432/9953
2025-10-30 07:45:27,885 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112540.58
2025-10-30 07:45:27,885 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112540.58 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,885 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:27,888 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,889 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:27,890 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.22, Commission=$0.00, Net=$-0.22 (cash flow: +$1999.78, -$0.00, balance: $9999.78)
2025-10-30 07:45:27,891 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4599/9953
2025-10-30 07:45:27,893 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108210.38
2025-10-30 07:45:27,893 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108210.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,894 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:27,896 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,900 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:27,900 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.55, Commission=$0.00, Net=$0.55 (cash flow: +$2000.55, -$0.00, balance: $10000.55)
2025-10-30 07:45:27,901 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4373/9953
2025-10-30 07:45:27,904 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107742.01
2025-10-30 07:45:27,904 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107742.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,904 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:27,906 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,911 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 07:45:27,911 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.39, Commission=$0.00, Net=$-0.39 (cash flow: -$2000.39, balance: $9999.61)
2025-10-30 07:45:27,912 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 615/9953
2025-10-30 07:45:27,915 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111800.00
2025-10-30 07:45:27,915 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111800.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,915 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:27,917 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:27,917 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.89, Commission=$0.00, Net=$-0.89 (cash flow: -$2000.89, balance: $9999.11)
2025-10-30 07:45:27,918 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6777/9953
2025-10-30 07:45:27,923 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109184.62
2025-10-30 07:45:27,923 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109184.62 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,924 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:27,926 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,928 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:27,928 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.66, Commission=$0.00, Net=$-0.66 (cash flow: +$1999.34, -$0.00, balance: $9999.34)
2025-10-30 07:45:27,929 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9035/9953
2025-10-30 07:45:27,935 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110203.37
2025-10-30 07:45:27,935 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110203.37 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,935 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:27,938 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:27,938 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.35, Commission=$0.00, Net=$-1.35 (cash flow: +$1998.65, -$0.00, balance: $9998.65)
2025-10-30 07:45:27,939 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3532/9953
2025-10-30 07:45:27,941 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108280.97
2025-10-30 07:45:27,942 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108280.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,943 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:27,945 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,947 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:27,947 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.38, Commission=$0.00, Net=$-0.38 (cash flow: -$2000.38, balance: $9999.62)
2025-10-30 07:45:27,948 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5149/9953
2025-10-30 07:45:27,953 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108147.99
2025-10-30 07:45:27,953 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108147.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:27,954 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:27,956 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,958 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:27,958 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.86, Commission=$0.00, Net=$0.86 (cash flow: +$2000.86, -$0.00, balance: $10000.86)
2025-10-30 07:45:27,959 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8299/9953
2025-10-30 07:45:27,962 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111254.96
2025-10-30 07:45:27,963 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111254.96 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:27,963 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:27,967 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:27,968 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 4.22      |
|    ep_rew_mean        | -1.12e-05 |
| time/                 |           |
|    fps                | 384       |
|    iterations         | 900       |
|    time_elapsed       | 11        |
|    total_timesteps    | 4500      |
| train/                |           |
|    entropy_loss       | -0.746    |
|    explained_variance | 0.0949    |
|    learning_rate      | 0.0007    |
|    n_updates          | 899       |
|    policy_loss        | -0.176    |
|    value_loss         | 0.226     |
-------------------------------------

2025-10-30 07:45:29,034 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:29,034 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.30, Commission=$0.00, Net=$-1.30 (cash flow: +$1998.70, -$0.00, balance: $9998.70)
2025-10-30 07:45:29,035 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8658/9953
2025-10-30 07:45:29,037 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111006.54
2025-10-30 07:45:29,038 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111006.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,038 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:29,041 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,042 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:29,043 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.75, Commission=$0.00, Net=$-0.75 (cash flow: -$2000.75, balance: $9999.25)
2025-10-30 07:45:29,044 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4690/9953
2025-10-30 07:45:29,049 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108267.36
2025-10-30 07:45:29,049 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108267.36 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,049 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:29,052 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,054 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:29,055 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.54, Commission=$0.00, Net=$-0.54 (cash flow: +$1999.46, -$0.00, balance: $9999.46)
2025-10-30 07:45:29,055 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5970/9953
2025-10-30 07:45:29,058 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107128.39
2025-10-30 07:45:29,059 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107128.39 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,059 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:29,063 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,067 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:29,067 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.18, Commission=$0.00, Net=$1.18 (cash flow: +$2001.18, -$0.00, balance: $10001.18)
2025-10-30 07:45:29,068 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3614/9953
2025-10-30 07:45:29,071 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108632.52
2025-10-30 07:45:29,072 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108632.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,072 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:29,075 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,077 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:29,078 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.19, Commission=$0.00, Net=$-2.19 (cash flow: +$1997.81, -$0.00, balance: $9997.81)
2025-10-30 07:45:29,078 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4229/9953
2025-10-30 07:45:29,081 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107704.80
2025-10-30 07:45:29,082 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107704.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,082 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:29,083 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,089 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:29,089 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.84, Commission=$0.00, Net=$0.84 (cash flow: +$2000.84, -$0.00, balance: $10000.84)
2025-10-30 07:45:29,090 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3174/9953
2025-10-30 07:45:29,095 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108007.00
2025-10-30 07:45:29,095 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108007.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,095 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:29,099 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:29,100 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:45:29,100 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9289/9953
2025-10-30 07:45:29,104 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109924.14
2025-10-30 07:45:29,105 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109924.14 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,105 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:29,111 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,114 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:29,114 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.87, Commission=$0.00, Net=$1.87 (cash flow: +$2001.87, -$0.00, balance: $10001.87)
2025-10-30 07:45:29,115 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3915/9953
2025-10-30 07:45:29,119 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108086.54
2025-10-30 07:45:29,119 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108086.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,120 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:29,121 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,126 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:29,126 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.25, Commission=$0.00, Net=$-1.25 (cash flow: -$2001.25, balance: $9998.75)
2025-10-30 07:45:29,127 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 806/9953
2025-10-30 07:45:29,136 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112729.85
2025-10-30 07:45:29,136 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112729.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,137 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:29,138 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:29,139 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.36, Commission=$0.00, Net=$-0.36 (cash flow: -$2000.36, balance: $9999.64)
2025-10-30 07:45:29,140 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6696/9953
2025-10-30 07:45:29,142 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109503.69
2025-10-30 07:45:29,143 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109503.69 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,144 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:29,145 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:29,146 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.42, Commission=$0.00, Net=$-0.42 (cash flow: +$1999.58, -$0.00, balance: $9999.58)
2025-10-30 07:45:29,147 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3107/9953
2025-10-30 07:45:29,153 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107924.01
2025-10-30 07:45:29,154 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107924.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,154 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:29,156 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:29,156 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.48, Commission=$0.00, Net=$-1.48 (cash flow: -$2001.48, balance: $9998.52)
2025-10-30 07:45:29,157 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 686/9953
2025-10-30 07:45:29,167 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112400.00
2025-10-30 07:45:29,168 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112400.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,168 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:29,169 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,173 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:29,174 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.22, Commission=$0.00, Net=$-1.22 (cash flow: -$2001.22, balance: $9998.78)
2025-10-30 07:45:29,174 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2164/9953
2025-10-30 07:45:29,180 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112130.11
2025-10-30 07:45:29,180 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112130.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,181 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:29,182 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:29,183 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.07, Commission=$0.00, Net=$0.07 (cash flow: +$2000.07, -$0.00, balance: $10000.07)
2025-10-30 07:45:29,185 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2101/9953
2025-10-30 07:45:29,196 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112074.43
2025-10-30 07:45:29,196 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112074.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,197 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:29,201 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,213 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:29,213 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.88, Commission=$0.00, Net=$-0.88 (cash flow: -$2000.88, balance: $9999.12)
2025-10-30 07:45:29,214 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8574/9953
2025-10-30 07:45:29,219 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111104.38
2025-10-30 07:45:29,220 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111104.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,220 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:29,225 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,226 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:29,227 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.18, Commission=$0.00, Net=$0.18 (cash flow: -$1999.82, balance: $10000.18)
2025-10-30 07:45:29,228 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1960/9953
2025-10-30 07:45:29,243 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112109.62
2025-10-30 07:45:29,243 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112109.62 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,244 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:29,246 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:29,247 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 07:45:29,248 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3007/9953
2025-10-30 07:45:29,255 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108346.00
2025-10-30 07:45:29,260 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108346.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,262 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:29,268 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,275 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:29,276 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:45:29,277 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6563/9953
2025-10-30 07:45:29,278 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110205.53
2025-10-30 07:45:29,279 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110205.53 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,279 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:29,283 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:29,284 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.21, Commission=$0.00, Net=$-1.21 (cash flow: +$1998.79, -$0.00, balance: $9998.79)
2025-10-30 07:45:29,284 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1448/9953
2025-10-30 07:45:29,298 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112655.46
2025-10-30 07:45:29,298 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112655.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,299 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:29,300 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:29,300 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.10, Commission=$0.00, Net=$0.10 (cash flow: -$1999.90, balance: $10000.10)
2025-10-30 07:45:29,302 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5785/9953
2025-10-30 07:45:29,309 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107205.58
2025-10-30 07:45:29,310 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107205.58 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,310 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:29,312 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,317 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:29,318 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.28, Commission=$0.00, Net=$2.28 (cash flow: +$2002.28, -$0.00, balance: $10002.28)
2025-10-30 07:45:29,320 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2715/9953
2025-10-30 07:45:29,322 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108821.60
2025-10-30 07:45:29,323 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108821.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:29,323 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:29,332 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,334 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:29,335 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.79, Commission=$0.00, Net=$-1.79 (cash flow: +$1998.21, -$0.00, balance: $9998.21)
2025-10-30 07:45:29,336 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5138/9953
2025-10-30 07:45:29,339 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107829.56
2025-10-30 07:45:29,340 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107829.56 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:29,340 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:29,343 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:29,345 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:29,345 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.07, Commission=$0.00, Net=$1.07 (cash flow: -$1998.93, balance: $10001.07)
2025-10-30 07:45:29,346 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5086/9953
2025-10-30 07:45:29,352 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108481.66
2025-10-30 07:45:29,352 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108481.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 4.6       |
|    ep_rew_mean        | -3.96e-06 |
| time/                 |           |
|    fps                | 385       |
|    iterations         | 1000      |
|    time_elapsed       | 12        |
|    total_timesteps    | 5000      |
| train/                |           |
|    entropy_loss       | -0.93     |
|    explained_variance | -0.287    |
|    learning_rate      | 0.0007    |
|    n_updates          | 999       |
|    policy_loss        | 0.0144    |
|    value_loss         | 0.0318    |
-------------------------------------

2025-10-30 07:45:30,306 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111534.61
2025-10-30 07:45:30,306 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111534.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,307 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:30,310 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:30,310 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.93, Commission=$0.00, Net=$-0.93 (cash flow: +$1999.07, -$0.00, balance: $9999.07)
2025-10-30 07:45:30,312 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 640/9953
2025-10-30 07:45:30,315 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111944.33
2025-10-30 07:45:30,316 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111944.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,316 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:30,317 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:30,318 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 07:45:30,319 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3410/9953
2025-10-30 07:45:30,325 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108170.00
2025-10-30 07:45:30,325 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108170.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,326 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:30,329 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:30,329 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.30, Commission=$0.00, Net=$-0.30 (cash flow: -$2000.30, balance: $9999.70)
2025-10-30 07:45:30,330 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9606/9953
2025-10-30 07:45:30,334 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111102.98
2025-10-30 07:45:30,334 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111102.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,334 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:30,337 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,342 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:30,343 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.29, Commission=$0.00, Net=$2.29 (cash flow: -$1997.71, balance: $10002.29)
2025-10-30 07:45:30,344 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5873/9953
2025-10-30 07:45:30,345 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=106883.05
2025-10-30 07:45:30,346 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $106883.05 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,346 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:30,350 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,356 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:30,356 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.18, Commission=$0.00, Net=$0.18 (cash flow: +$2000.18, -$0.00, balance: $10000.18)
2025-10-30 07:45:30,357 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9892/9953
2025-10-30 07:45:30,362 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111647.76
2025-10-30 07:45:30,362 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111647.76 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,362 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:30,366 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,368 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:30,369 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.07, Commission=$0.00, Net=$0.07 (cash flow: -$1999.93, balance: $10000.07)
2025-10-30 07:45:30,369 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8655/9953
2025-10-30 07:45:30,376 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111006.54
2025-10-30 07:45:30,376 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111006.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,376 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:30,379 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:30,379 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.72, Commission=$0.00, Net=$0.72 (cash flow: -$1999.28, balance: $10000.72)
2025-10-30 07:45:30,380 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8089/9953
2025-10-30 07:45:30,385 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110358.37
2025-10-30 07:45:30,385 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110358.37 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,386 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:30,388 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,389 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:30,390 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.07, Commission=$0.00, Net=$1.07 (cash flow: +$2001.07, -$0.00, balance: $10001.07)
2025-10-30 07:45:30,391 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5703/9953
2025-10-30 07:45:30,393 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107810.00
2025-10-30 07:45:30,393 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107810.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,394 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:30,397 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,399 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:30,399 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.57, Commission=$0.00, Net=$-1.57 (cash flow: +$1998.43, -$0.00, balance: $9998.43)
2025-10-30 07:45:30,400 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5810/9953
2025-10-30 07:45:30,401 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107174.16
2025-10-30 07:45:30,402 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107174.16 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,402 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:30,405 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,410 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0187, signal=-1.0
2025-10-30 07:45:30,410 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.67, Commission=$0.00, Net=$-0.67 (cash flow: +$1999.33, -$0.00, balance: $9999.33)
2025-10-30 07:45:30,410 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4205/9953
2025-10-30 07:45:30,412 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107273.41
2025-10-30 07:45:30,413 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107273.41 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,413 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:30,415 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,417 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:30,417 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.12, Commission=$0.00, Net=$2.12 (cash flow: +$2002.12, -$0.00, balance: $10002.12)
2025-10-30 07:45:30,418 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5831/9953
2025-10-30 07:45:30,421 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=106788.00
2025-10-30 07:45:30,422 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $106788.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,422 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:30,426 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,434 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:30,434 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.49, Commission=$0.00, Net=$1.49 (cash flow: +$2001.49, -$0.00, balance: $10001.49)
2025-10-30 07:45:30,435 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1198/9953
2025-10-30 07:45:30,441 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113441.43
2025-10-30 07:45:30,441 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113441.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,442 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:30,446 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:30,446 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.80, Commission=$0.00, Net=$0.80 (cash flow: +$2000.80, -$0.00, balance: $10000.80)
2025-10-30 07:45:30,447 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2231/9953
2025-10-30 07:45:30,449 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111555.36
2025-10-30 07:45:30,449 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111555.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,449 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:30,452 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,454 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:30,454 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.99, Commission=$0.00, Net=$0.99 (cash flow: -$1999.01, balance: $10000.99)
2025-10-30 07:45:30,455 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4715/9953
2025-10-30 07:45:30,460 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108360.37
2025-10-30 07:45:30,460 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108360.37 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,461 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:30,463 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,467 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:30,469 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.27, Commission=$0.00, Net=$0.27 (cash flow: -$1999.73, balance: $10000.27)
2025-10-30 07:45:30,473 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9658/9953
2025-10-30 07:45:30,483 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111063.31
2025-10-30 07:45:30,483 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111063.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,484 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:30,486 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,488 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:30,488 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.02, Commission=$0.00, Net=$0.02 (cash flow: -$1999.98, balance: $10000.02)
2025-10-30 07:45:30,489 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5357/9953
2025-10-30 07:45:30,491 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108551.01
2025-10-30 07:45:30,492 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108551.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,492 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:30,496 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,499 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:30,499 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.52, Commission=$0.00, Net=$-0.52 (cash flow: -$2000.52, balance: $9999.48)
2025-10-30 07:45:30,500 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6518/9953
2025-10-30 07:45:30,505 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110073.60
2025-10-30 07:45:30,506 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110073.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,506 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:30,508 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:30,509 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.17, Commission=$0.00, Net=$-0.17 (cash flow: +$1999.83, -$0.00, balance: $9999.83)
2025-10-30 07:45:30,509 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3154/9953
2025-10-30 07:45:30,511 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108085.87
2025-10-30 07:45:30,512 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108085.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:30,512 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:30,515 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:30,515 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 07:45:30,516 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9386/9953
2025-10-30 07:45:30,521 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110508.50
2025-10-30 07:45:30,521 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110508.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,522 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:30,523 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:30,524 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.82, Commission=$0.00, Net=$1.82 (cash flow: -$1998.18, balance: $10001.82)
2025-10-30 07:45:30,525 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7016/9953
2025-10-30 07:45:30,527 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109060.46
2025-10-30 07:45:30,528 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109060.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,528 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:30,530 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,536 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:30,536 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.33, Commission=$0.00, Net=$-0.33 (cash flow: -$2000.33, balance: $9999.67)
2025-10-30 07:45:30,537 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8522/9953
2025-10-30 07:45:30,538 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111312.03
2025-10-30 07:45:30,539 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111312.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,539 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:30,541 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:30,542 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.53, Commission=$0.00, Net=$0.53 (cash flow: -$1999.47, balance: $10000.53)
2025-10-30 07:45:30,543 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5039/9953
2025-10-30 07:45:30,547 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108784.63
2025-10-30 07:45:30,548 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108784.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:30,548 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:30,551 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:30,556 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:30,556 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.88, Commission=$0.00, Net=$-1.88 (cash flow: -$2001.88, balance: $9998.12)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.31     |
|    ep_rew_mean        | 8.5e-07  |
| time/                 |          |
|    fps                | 387      |
|    iterations         | 1100     |
|    time_elapsed       | 14       |
|    total_timesteps    | 5500     |
| train/                |          |
|    entropy_loss       | -0.67    |
|    explained_variance | 0.376    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1099     |
|    policy_loss        | -0.391   |
|    value_loss         | 0.793    |
------------------------------------

2025-10-30 07:45:31,515 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107850.38
2025-10-30 07:45:31,515 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107850.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,515 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:31,517 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,520 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:31,520 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.23, Commission=$0.00, Net=$1.23 (cash flow: -$1998.77, balance: $10001.23)
2025-10-30 07:45:31,521 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4232/9953
2025-10-30 07:45:31,523 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107750.00
2025-10-30 07:45:31,523 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107750.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,524 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:31,528 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,531 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:31,531 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 07:45:31,532 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 818/9953
2025-10-30 07:45:31,537 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112720.00
2025-10-30 07:45:31,537 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112720.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,537 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:31,539 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,542 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0177, signal=-1.0
2025-10-30 07:45:31,543 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.25, Commission=$0.00, Net=$0.25 (cash flow: +$2000.25, -$0.00, balance: $10000.25)
2025-10-30 07:45:31,543 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9105/9953
2025-10-30 07:45:31,547 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110046.54
2025-10-30 07:45:31,547 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110046.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,548 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:31,550 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:31,550 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.69, Commission=$0.00, Net=$0.69 (cash flow: -$1999.31, balance: $10000.69)
2025-10-30 07:45:31,551 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1094/9953
2025-10-30 07:45:31,554 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113447.38
2025-10-30 07:45:31,555 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113447.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,555 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:31,558 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:31,558 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.69, Commission=$0.00, Net=$0.69 (cash flow: +$2000.69, -$0.00, balance: $10000.69)
2025-10-30 07:45:31,558 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1440/9953
2025-10-30 07:45:31,562 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112500.00
2025-10-30 07:45:31,563 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112500.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,563 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:31,565 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:31,566 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 07:45:31,566 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1596/9953
2025-10-30 07:45:31,570 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111899.09
2025-10-30 07:45:31,570 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111899.09 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,570 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:31,573 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:31,573 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.84, Commission=$0.00, Net=$0.84 (cash flow: -$1999.16, balance: $10000.84)
2025-10-30 07:45:31,574 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9160/9953
2025-10-30 07:45:31,578 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110010.65
2025-10-30 07:45:31,578 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110010.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,579 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:31,580 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,583 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:31,583 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.53, Commission=$0.00, Net=$-0.53 (cash flow: +$1999.47, -$0.00, balance: $9999.47)
2025-10-30 07:45:31,584 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 354/9953
2025-10-30 07:45:31,586 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109609.37
2025-10-30 07:45:31,586 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109609.37 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,586 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:31,591 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,597 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:31,597 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.11, Commission=$0.00, Net=$-1.11 (cash flow: -$2001.11, balance: $9998.89)
2025-10-30 07:45:31,598 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5450/9953
2025-10-30 07:45:31,601 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107904.80
2025-10-30 07:45:31,601 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107904.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,601 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:31,604 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,605 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:31,606 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.54, Commission=$0.00, Net=$1.54 (cash flow: -$1998.46, balance: $10001.54)
2025-10-30 07:45:31,607 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8221/9953
2025-10-30 07:45:31,612 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111409.04
2025-10-30 07:45:31,612 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111409.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,612 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:31,614 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,616 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 07:45:31,616 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.42, Commission=$0.00, Net=$-3.42 (cash flow: +$1996.58, -$0.00, balance: $9996.58)
2025-10-30 07:45:31,617 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5617/9953
2025-10-30 07:45:31,620 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107956.53
2025-10-30 07:45:31,620 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107956.53 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,620 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:31,624 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,626 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:31,626 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.36, Commission=$0.00, Net=$-0.36 (cash flow: +$1999.64, -$0.00, balance: $9999.64)
2025-10-30 07:45:31,627 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 786/9953
2025-10-30 07:45:31,633 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112822.08
2025-10-30 07:45:31,633 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112822.08 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,633 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:31,636 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:31,636 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.84, Commission=$0.00, Net=$-0.84 (cash flow: +$1999.16, -$0.00, balance: $9999.16)
2025-10-30 07:45:31,637 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2834/9953
2025-10-30 07:45:31,639 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109029.17
2025-10-30 07:45:31,639 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109029.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,640 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:31,642 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,647 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:31,647 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.25, Commission=$0.00, Net=$-1.25 (cash flow: +$1998.75, -$0.00, balance: $9998.75)
2025-10-30 07:45:31,648 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6707/9953
2025-10-30 07:45:31,651 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109660.00
2025-10-30 07:45:31,651 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109660.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,651 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:31,655 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,658 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:31,658 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.73, Commission=$0.00, Net=$0.73 (cash flow: -$1999.27, balance: $10000.73)
2025-10-30 07:45:31,659 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1871/9953
2025-10-30 07:45:31,664 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112264.07
2025-10-30 07:45:31,665 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112264.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,665 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:31,667 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,669 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:31,669 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.08, Commission=$0.00, Net=$-1.08 (cash flow: -$2001.08, balance: $9998.92)
2025-10-30 07:45:31,670 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5202/9953
2025-10-30 07:45:31,674 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108326.19
2025-10-30 07:45:31,674 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108326.19 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,675 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:31,677 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:31,678 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.87, Commission=$0.00, Net=$1.87 (cash flow: +$2001.87, -$0.00, balance: $10001.87)
2025-10-30 07:45:31,678 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7694/9953
2025-10-30 07:45:31,682 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110748.04
2025-10-30 07:45:31,682 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110748.04 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,682 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:31,687 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:31,687 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.78, Commission=$0.00, Net=$0.78 (cash flow: -$1999.22, balance: $10000.78)
2025-10-30 07:45:31,687 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3658/9953
2025-10-30 07:45:31,689 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108000.00
2025-10-30 07:45:31,690 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108000.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,690 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:31,692 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:31,693 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.41, Commission=$0.00, Net=$-0.41 (cash flow: +$1999.59, -$0.00, balance: $9999.59)
2025-10-30 07:45:31,693 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9744/9953
2025-10-30 07:45:31,697 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111430.31
2025-10-30 07:45:31,697 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111430.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,697 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:31,702 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,704 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:31,704 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.14, Commission=$0.00, Net=$0.14 (cash flow: -$1999.86, balance: $10000.14)
2025-10-30 07:45:31,705 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7605/9953
2025-10-30 07:45:31,708 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111110.99
2025-10-30 07:45:31,708 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111110.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,708 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:31,710 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,714 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:31,714 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.55, Commission=$0.00, Net=$0.55 (cash flow: +$2000.55, -$0.00, balance: $10000.55)
2025-10-30 07:45:31,715 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7497/9953
2025-10-30 07:45:31,717 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110020.36
2025-10-30 07:45:31,717 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110020.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:31,718 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:31,720 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:31,722 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:31,722 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.09, Commission=$0.00, Net=$2.09 (cash flow: -$1997.91, balance: $10002.09)
2025-10-30 07:45:31,723 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 495/9953
2025-10-30 07:45:31,726 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109975.89
2025-10-30 07:45:31,726 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109975.89 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:31,726 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:31,731 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:31,731 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.19, Commission=$0.00, Net=$0.19 (cash flow: +$2000.19, -$0.00, balance: $10000.19)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.07     |
|    ep_rew_mean        | 3.83e-05 |
| time/                 |          |
|    fps                | 388      |
|    iterations         | 1200     |
|    time_elapsed       | 15       |
|    total_timesteps    | 6000     |
| train/                |          |
|    entropy_loss       | -0.855   |
|    explained_variance | 0.308    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1199     |
|    policy_loss        | 0.0564   |
|    value_loss         | 0.166    |
------------------------------------

2025-10-30 07:45:32,754 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:32,754 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.86, Commission=$0.00, Net=$-2.86 (cash flow: -$2002.86, balance: $9997.14)
2025-10-30 07:45:32,755 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8582/9953
2025-10-30 07:45:32,757 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111100.00
2025-10-30 07:45:32,757 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111100.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,758 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:32,759 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,764 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:32,765 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.62, Commission=$0.00, Net=$-0.62 (cash flow: -$2000.62, balance: $9999.38)
2025-10-30 07:45:32,765 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3114/9953
2025-10-30 07:45:32,767 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108190.73
2025-10-30 07:45:32,767 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108190.73 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,767 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:32,770 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,776 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:32,776 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: -$1999.05, balance: $10000.95)
2025-10-30 07:45:32,776 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1577/9953
2025-10-30 07:45:32,783 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111818.00
2025-10-30 07:45:32,783 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111818.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,783 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:32,786 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:32,786 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.73, Commission=$0.00, Net=$0.73 (cash flow: +$2000.73, -$0.00, balance: $10000.73)
2025-10-30 07:45:32,787 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 816/9953
2025-10-30 07:45:32,792 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112720.00
2025-10-30 07:45:32,792 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112720.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,793 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:32,795 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,796 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:32,797 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.08, Commission=$0.00, Net=$-0.08 (cash flow: -$2000.08, balance: $9999.92)
2025-10-30 07:45:32,798 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3631/9953
2025-10-30 07:45:32,801 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108406.00
2025-10-30 07:45:32,801 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108406.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,801 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:32,806 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,808 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:32,808 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.10, Commission=$0.00, Net=$-0.10 (cash flow: -$2000.10, balance: $9999.90)
2025-10-30 07:45:32,809 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7727/9953
2025-10-30 07:45:32,811 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110485.86
2025-10-30 07:45:32,812 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110485.86 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,812 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:32,816 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:32,816 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.56, Commission=$0.00, Net=$-0.56 (cash flow: +$1999.44, -$0.00, balance: $9999.44)
2025-10-30 07:45:32,817 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3139/9953
2025-10-30 07:45:32,819 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107916.60
2025-10-30 07:45:32,819 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107916.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,820 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:32,822 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,824 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:32,824 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.46, Commission=$0.00, Net=$2.46 (cash flow: +$2002.46, -$0.00, balance: $10002.46)
2025-10-30 07:45:32,825 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1141/9953
2025-10-30 07:45:32,842 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113361.79
2025-10-30 07:45:32,842 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113361.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,842 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:32,844 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:32,845 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.40, Commission=$0.00, Net=$1.40 (cash flow: +$2001.40, -$0.00, balance: $10001.40)
2025-10-30 07:45:32,846 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2333/9953
2025-10-30 07:45:32,848 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111837.56
2025-10-30 07:45:32,849 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111837.56 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,849 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:32,854 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,856 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:32,857 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.28, Commission=$0.00, Net=$1.28 (cash flow: +$2001.28, -$0.00, balance: $10001.28)
2025-10-30 07:45:32,857 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8980/9953
2025-10-30 07:45:32,859 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110817.96
2025-10-30 07:45:32,859 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110817.96 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,859 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:32,864 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,871 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:32,872 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.10, Commission=$0.00, Net=$0.10 (cash flow: -$1999.90, balance: $10000.10)
2025-10-30 07:45:32,872 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5284/9953
2025-10-30 07:45:32,875 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108068.45
2025-10-30 07:45:32,876 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108068.45 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,876 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:32,880 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,883 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:32,883 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.65, Commission=$0.00, Net=$-2.65 (cash flow: +$1997.35, -$0.00, balance: $9997.35)
2025-10-30 07:45:32,884 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4482/9953
2025-10-30 07:45:32,888 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108282.93
2025-10-30 07:45:32,888 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108282.93 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,889 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:32,891 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:32,891 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.05, Commission=$0.00, Net=$0.05 (cash flow: +$2000.05, -$0.00, balance: $10000.05)
2025-10-30 07:45:32,892 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7707/9953
2025-10-30 07:45:32,896 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110604.70
2025-10-30 07:45:32,896 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110604.70 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,896 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:32,899 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:32,899 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.27, Commission=$0.00, Net=$-0.27 (cash flow: +$1999.73, -$0.00, balance: $9999.73)
2025-10-30 07:45:32,900 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 182/9953
2025-10-30 07:45:32,905 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108790.70
2025-10-30 07:45:32,905 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108790.70 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,905 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:32,906 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:32,907 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.51, Commission=$0.00, Net=$1.51 (cash flow: +$2001.51, -$0.00, balance: $10001.51)
2025-10-30 07:45:32,908 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9320/9953
2025-10-30 07:45:32,914 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110252.67
2025-10-30 07:45:32,914 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110252.67 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,914 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:32,917 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,922 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:32,922 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.10, Commission=$0.00, Net=$-2.10 (cash flow: -$2002.10, balance: $9997.90)
2025-10-30 07:45:32,923 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 765/9953
2025-10-30 07:45:32,931 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112540.58
2025-10-30 07:45:32,931 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112540.58 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,931 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:32,934 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,947 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 07:45:32,947 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.17, Commission=$0.00, Net=$-6.17 (cash flow: -$2006.17, balance: $9993.83)
2025-10-30 07:45:32,948 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4169/9953
2025-10-30 07:45:32,949 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107150.01
2025-10-30 07:45:32,950 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107150.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,950 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:32,952 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,959 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:32,959 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.88, Commission=$0.00, Net=$0.88 (cash flow: +$2000.88, -$0.00, balance: $10000.88)
2025-10-30 07:45:32,960 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9896/9953
2025-10-30 07:45:32,963 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111643.94
2025-10-30 07:45:32,963 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111643.94 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,963 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:32,968 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:32,968 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.83, Commission=$0.00, Net=$-0.83 (cash flow: +$1999.17, -$0.00, balance: $9999.17)
2025-10-30 07:45:32,969 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7118/9953
2025-10-30 07:45:32,971 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109642.30
2025-10-30 07:45:32,972 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109642.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,972 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:32,975 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,976 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:32,976 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.14, Commission=$0.00, Net=$-0.14 (cash flow: -$2000.14, balance: $9999.86)
2025-10-30 07:45:32,977 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5354/9953
2025-10-30 07:45:32,981 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108454.00
2025-10-30 07:45:32,982 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108454.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:32,982 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:32,985 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:32,986 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:32,987 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.79, Commission=$0.00, Net=$-1.79 (cash flow: -$2001.79, balance: $9998.21)
2025-10-30 07:45:32,987 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1023/9953
2025-10-30 07:45:32,995 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112805.20
2025-10-30 07:45:32,995 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112805.20 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:32,995 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:32,998 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:33,002 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:33,002 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.66, Commission=$0.00, Net=$-0.66 (cash flow: +$1999.34, -$0.00, balance: $9999.34)
2025-10-30 07:45:33,003 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6192/9953
2025-10-30 07:45:33,006 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108198.18
2025-10-30 07:45:33,007 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108198.18 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:33,007 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:33,010 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:33,010 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.21, Commission=$0.00, Net=$1.21 (cash flow: +$2001.21, -$0.00, balance: $10001.21)
2025-10-30 07:45:33,011 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8120/9953
2025-10-30 07:45:33,018 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110459.13
2025-10-30 07:45:33,018 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110459.13 (cash flow: -$2000.00, remaining: $8000.00)

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 4.92      |
|    ep_rew_mean        | -4.07e-05 |
| time/                 |           |
|    fps                | 392       |
|    iterations         | 1300      |
|    time_elapsed       | 16        |
|    total_timesteps    | 6500      |
| train/                |           |
|    entropy_loss       | -0.821    |
|    explained_variance | -0.546    |
|    learning_rate      | 0.0007    |
|    n_updates          | 1299      |
|    policy_loss        | -0.0284   |
|    value_loss         | 0.0883    |
-------------------------------------

2025-10-30 07:45:33,908 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:33,908 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.52, Commission=$0.00, Net=$-2.52 (cash flow: +$1997.48, -$0.00, balance: $9997.48)
2025-10-30 07:45:33,909 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3903/9953
2025-10-30 07:45:33,911 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108175.80
2025-10-30 07:45:33,911 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108175.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:33,912 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:33,914 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:33,923 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.17, Commission=$0.00, Net=$0.17 (cash flow: -$1999.83, balance: $10000.17)
2025-10-30 07:45:33,925 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5584/9953
2025-10-30 07:45:33,928 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108232.14
2025-10-30 07:45:33,928 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108232.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:33,929 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:33,935 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:33,939 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:33,939 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.64, Commission=$0.00, Net=$-2.64 (cash flow: -$2002.64, balance: $9997.36)
2025-10-30 07:45:33,940 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4022/9953
2025-10-30 07:45:33,941 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108228.34
2025-10-30 07:45:33,942 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108228.34 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:33,942 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:33,948 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:33,952 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:33,952 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.11, Commission=$0.00, Net=$-2.11 (cash flow: +$1997.89, -$0.00, balance: $9997.89)
2025-10-30 07:45:33,953 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7861/9953
2025-10-30 07:45:33,958 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109647.43
2025-10-30 07:45:33,958 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109647.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:33,958 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:33,962 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:33,963 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:33,963 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.72, Commission=$0.00, Net=$-0.72 (cash flow: +$1999.28, -$0.00, balance: $9999.28)
2025-10-30 07:45:33,965 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1578/9953
2025-10-30 07:45:33,972 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111818.00
2025-10-30 07:45:33,972 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111818.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:33,972 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:33,976 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:33,976 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: -$2000.73, balance: $9999.27)
2025-10-30 07:45:33,977 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1718/9953
2025-10-30 07:45:33,979 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112232.00
2025-10-30 07:45:33,980 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112232.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:33,980 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:33,984 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:33,990 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:33,991 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.07, Commission=$0.00, Net=$0.07 (cash flow: -$1999.93, balance: $10000.07)
2025-10-30 07:45:33,991 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8882/9953
2025-10-30 07:45:33,995 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111391.67
2025-10-30 07:45:33,996 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111391.67 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:33,996 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:34,000 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:34,001 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: -$1999.07, balance: $10000.93)
2025-10-30 07:45:34,001 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1843/9953
2025-10-30 07:45:34,008 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112383.30
2025-10-30 07:45:34,008 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112383.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,008 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:34,012 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,013 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:34,013 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.03, Commission=$0.00, Net=$-0.03 (cash flow: -$2000.03, balance: $9999.97)
2025-10-30 07:45:34,014 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2039/9953
2025-10-30 07:45:34,016 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112011.94
2025-10-30 07:45:34,017 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $112011.94 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,018 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:34,019 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,025 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:34,025 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.02, Commission=$0.00, Net=$-1.02 (cash flow: +$1998.98, -$0.00, balance: $9998.98)
2025-10-30 07:45:34,025 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 100/9953
2025-10-30 07:45:34,028 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109200.99
2025-10-30 07:45:34,029 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109200.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,029 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:34,035 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,038 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:34,038 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: +$1999.19, -$0.00, balance: $9999.19)
2025-10-30 07:45:34,039 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2628/9953
2025-10-30 07:45:34,042 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110039.01
2025-10-30 07:45:34,042 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110039.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,043 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:34,047 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,049 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:34,050 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.25, Commission=$0.00, Net=$0.25 (cash flow: +$2000.25, -$0.00, balance: $10000.25)
2025-10-30 07:45:34,050 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 619/9953
2025-10-30 07:45:34,056 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111852.38
2025-10-30 07:45:34,057 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111852.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,057 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:34,058 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:34,059 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.72, Commission=$0.00, Net=$0.72 (cash flow: +$2000.72, -$0.00, balance: $10000.72)
2025-10-30 07:45:34,061 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6704/9953
2025-10-30 07:45:34,068 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109648.67
2025-10-30 07:45:34,068 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109648.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,068 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:34,069 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,073 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:34,073 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.51, Commission=$0.00, Net=$0.51 (cash flow: +$2000.51, -$0.00, balance: $10000.51)
2025-10-30 07:45:34,074 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1739/9953
2025-10-30 07:45:34,079 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112249.33
2025-10-30 07:45:34,080 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112249.33 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,080 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:34,081 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,086 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:34,087 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.18, Commission=$0.00, Net=$-0.18 (cash flow: +$1999.82, -$0.00, balance: $9999.82)
2025-10-30 07:45:34,087 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2601/9953
2025-10-30 07:45:34,088 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110091.24
2025-10-30 07:45:34,089 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110091.24 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,089 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:34,091 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,096 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:34,096 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.99, Commission=$0.00, Net=$-0.99 (cash flow: -$2000.99, balance: $9999.01)
2025-10-30 07:45:34,097 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4650/9953
2025-10-30 07:45:34,101 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108970.00
2025-10-30 07:45:34,101 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108970.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,101 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:34,104 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,106 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:34,106 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.20, Commission=$0.00, Net=$2.20 (cash flow: -$1997.80, balance: $10002.20)
2025-10-30 07:45:34,107 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 661/9953
2025-10-30 07:45:34,110 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111980.11
2025-10-30 07:45:34,111 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111980.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,111 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:34,112 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:34,113 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 07:45:34,114 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7897/9953
2025-10-30 07:45:34,120 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109472.00
2025-10-30 07:45:34,120 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109472.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,120 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:34,123 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,125 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:34,125 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.06, Commission=$0.00, Net=$1.06 (cash flow: +$2001.06, -$0.00, balance: $10001.06)
2025-10-30 07:45:34,126 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9263/9953
2025-10-30 07:45:34,132 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109994.82
2025-10-30 07:45:34,132 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109994.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,133 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:34,136 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:34,140 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:34,140 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.85, Commission=$0.00, Net=$-0.85 (cash flow: -$2000.85, balance: $9999.15)
2025-10-30 07:45:34,141 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6935/9953
2025-10-30 07:45:34,143 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108994.27
2025-10-30 07:45:34,144 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $108994.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,144 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:34,147 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:34,147 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.55, Commission=$0.00, Net=$1.55 (cash flow: -$1998.45, balance: $10001.55)
2025-10-30 07:45:34,148 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4289/9953
2025-10-30 07:45:34,151 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107900.02
2025-10-30 07:45:34,151 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107900.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:34,151 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:34,155 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:34,155 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.24, Commission=$0.00, Net=$-0.24 (cash flow: -$2000.24, balance: $9999.76)
2025-10-30 07:45:34,156 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7267/9953
2025-10-30 07:45:34,158 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109530.90
2025-10-30 07:45:34,158 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109530.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:34,159 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:34,162 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:34,162 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.78, Commission=$0.00, Net=$0.78 (cash flow: +$2000.78, -$0.00, balance: $10000.78)
2025-10-30 07:45:34,163 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5893/9953
2025-10-30 07:45:34,165 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=106893.15
2025-10-30 07:45:34,165 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $106893.15 (cash flow: -$2000.00, remaining: $8000.00)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.02     |
|    ep_rew_mean        | 1.14e-05 |
| time/                 |          |
|    fps                | 390      |
|    iterations         | 1400     |
|    time_elapsed       | 17       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -0.783   |
|    explained_variance | -0.341   |
|    learning_rate      | 0.0007   |
|    n_updates          | 1399     |
|    policy_loss        | 0.133    |
|    value_loss         | 0.104    |
------------------------------------

2025-10-30 07:45:35,255 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,256 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:35,257 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.86, Commission=$0.00, Net=$2.86 (cash flow: +$2002.86, -$0.00, balance: $10002.86)
2025-10-30 07:45:35,257 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9279/9953
2025-10-30 07:45:35,259 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109958.33
2025-10-30 07:45:35,260 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109958.33 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,261 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:35,263 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,269 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:35,269 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.00, Commission=$0.00, Net=$-2.00 (cash flow: +$1998.00, -$0.00, balance: $9998.00)
2025-10-30 07:45:35,270 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 838/9953
2025-10-30 07:45:35,277 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112478.66
2025-10-30 07:45:35,277 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112478.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,277 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:35,279 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,281 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 07:45:35,282 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.64, Commission=$0.00, Net=$-1.64 (cash flow: +$1998.36, -$0.00, balance: $9998.36)
2025-10-30 07:45:35,283 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5205/9953
2025-10-30 07:45:35,287 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108435.09
2025-10-30 07:45:35,288 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108435.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,288 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:35,290 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,292 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:35,292 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: +$2000.85, -$0.00, balance: $10000.85)
2025-10-30 07:45:35,293 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2632/9953
2025-10-30 07:45:35,297 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110114.35
2025-10-30 07:45:35,298 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110114.35 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,298 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:35,300 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,302 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:35,302 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.91, Commission=$0.00, Net=$0.91 (cash flow: -$1999.09, balance: $10000.91)
2025-10-30 07:45:35,303 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 338/9953
2025-10-30 07:45:35,305 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109077.66
2025-10-30 07:45:35,305 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109077.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,305 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:35,308 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,313 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:35,313 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.95, Commission=$0.00, Net=$1.95 (cash flow: +$2001.95, -$0.00, balance: $10001.95)
2025-10-30 07:45:35,313 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1448/9953
2025-10-30 07:45:35,320 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112713.81
2025-10-30 07:45:35,320 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112713.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,320 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:35,321 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,327 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:35,327 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.13, Commission=$0.00, Net=$1.13 (cash flow: -$1998.87, balance: $10001.13)
2025-10-30 07:45:35,328 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9861/9953
2025-10-30 07:45:35,329 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111520.00
2025-10-30 07:45:35,329 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111520.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,330 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:35,332 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,338 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:45:35,338 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.01, Commission=$0.00, Net=$-2.01 (cash flow: -$2002.01, balance: $9997.99)
2025-10-30 07:45:35,339 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5244/9953
2025-10-30 07:45:35,341 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108333.38
2025-10-30 07:45:35,341 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108333.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,342 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:35,344 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,356 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:35,357 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.33, Commission=$0.00, Net=$-3.33 (cash flow: +$1996.67, -$0.00, balance: $9996.67)
2025-10-30 07:45:35,357 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1059/9953
2025-10-30 07:45:35,361 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113263.47
2025-10-30 07:45:35,361 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113263.47 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,362 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:35,366 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:35,367 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.03, Commission=$0.00, Net=$-0.03 (cash flow: +$1999.97, -$0.00, balance: $9999.97)
2025-10-30 07:45:35,367 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1142/9953
2025-10-30 07:45:35,374 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113315.00
2025-10-30 07:45:35,375 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113315.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,375 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:35,377 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,383 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0176, signal=1.0
2025-10-30 07:45:35,383 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.11, Commission=$0.00, Net=$-3.11 (cash flow: -$2003.11, balance: $9996.89)
2025-10-30 07:45:35,384 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 32/9953
2025-10-30 07:45:35,385 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108396.39
2025-10-30 07:45:35,385 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108396.39 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,386 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:35,389 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,391 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:35,391 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.07, Commission=$0.00, Net=$1.07 (cash flow: +$2001.07, -$0.00, balance: $10001.07)
2025-10-30 07:45:35,391 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1624/9953
2025-10-30 07:45:35,395 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112386.82
2025-10-30 07:45:35,396 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112386.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,396 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:35,398 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:35,398 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.34, Commission=$0.00, Net=$-0.34 (cash flow: -$2000.34, balance: $9999.66)
2025-10-30 07:45:35,399 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3694/9953
2025-10-30 07:45:35,402 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107912.14
2025-10-30 07:45:35,402 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107912.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,402 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:35,405 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,406 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:35,407 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.22, Commission=$0.00, Net=$0.22 (cash flow: -$1999.78, balance: $10000.22)
2025-10-30 07:45:35,408 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 609/9953
2025-10-30 07:45:35,413 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111666.02
2025-10-30 07:45:35,413 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111666.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,413 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:35,415 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:35,416 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.99, Commission=$0.00, Net=$0.99 (cash flow: +$2000.99, -$0.00, balance: $10000.99)
2025-10-30 07:45:35,417 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8762/9953
2025-10-30 07:45:35,420 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111740.65
2025-10-30 07:45:35,420 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111740.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,421 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:35,425 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:35,425 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.28, Commission=$0.00, Net=$3.28 (cash flow: -$1996.72, balance: $10003.28)
2025-10-30 07:45:35,426 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4177/9953
2025-10-30 07:45:35,428 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107126.44
2025-10-30 07:45:35,428 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107126.44 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,429 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 07:45:35,431 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,433 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0187, signal=1.0
2025-10-30 07:45:35,434 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.67, Commission=$0.00, Net=$0.67 (cash flow: -$1999.33, balance: $10000.67)
2025-10-30 07:45:35,434 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3458/9953
2025-10-30 07:45:35,438 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107940.85
2025-10-30 07:45:35,438 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107940.85 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,439 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:35,442 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:35,442 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.02, Commission=$0.00, Net=$-0.02 (cash flow: +$1999.98, -$0.00, balance: $9999.98)
2025-10-30 07:45:35,442 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7846/9953
2025-10-30 07:45:35,445 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109622.16
2025-10-30 07:45:35,445 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109622.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:35,446 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:35,448 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:35,449 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.16, Commission=$0.00, Net=$1.16 (cash flow: -$1998.84, balance: $10001.16)
2025-10-30 07:45:35,449 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2562/9953
2025-10-30 07:45:35,452 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110763.54
2025-10-30 07:45:35,452 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110763.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,453 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:35,457 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:35,457 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.31, Commission=$0.00, Net=$0.31 (cash flow: +$2000.31, -$0.00, balance: $10000.31)
2025-10-30 07:45:35,458 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6156/9953
2025-10-30 07:45:35,459 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108481.79
2025-10-30 07:45:35,459 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108481.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,460 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:35,462 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,464 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:35,465 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.28, Commission=$0.00, Net=$-2.28 (cash flow: +$1997.72, -$0.00, balance: $9997.72)
2025-10-30 07:45:35,465 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4282/9953
2025-10-30 07:45:35,470 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107983.99
2025-10-30 07:45:35,470 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107983.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,471 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:35,473 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:35,476 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:35,476 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.53, Commission=$0.00, Net=$-0.53 (cash flow: +$1999.47, -$0.00, balance: $9999.47)
2025-10-30 07:45:35,477 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5223/9953
2025-10-30 07:45:35,479 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108507.44
2025-10-30 07:45:35,479 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108507.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:35,479 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:35,485 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:35,485 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.15, Commission=$0.00, Net=$2.15 (cash flow: +$2002.15, -$0.00, balance: $10002.15)
2025-10-30 07:45:35,486 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 906/9953
2025-10-30 07:45:35,489 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112911.29

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.04     |
|    ep_rew_mean        | -8.1e-06 |
| time/                 |          |
|    fps                | 390      |
|    iterations         | 1500     |
|    time_elapsed       | 19       |
|    total_timesteps    | 7500     |
| train/                |          |
|    entropy_loss       | -0.938   |
|    explained_variance | -1.39    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1499     |
|    policy_loss        | -0.524   |
|    value_loss         | 0.378    |
------------------------------------

2025-10-30 07:45:36,510 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,511 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:36,512 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.18, Commission=$0.00, Net=$1.18 (cash flow: +$2001.18, -$0.00, balance: $10001.18)
2025-10-30 07:45:36,512 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3082/9953
2025-10-30 07:45:36,515 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108158.08
2025-10-30 07:45:36,515 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108158.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,516 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:36,518 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,520 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:36,520 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.59, Commission=$0.00, Net=$1.59 (cash flow: -$1998.41, balance: $10001.59)
2025-10-30 07:45:36,521 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8500/9953
2025-10-30 07:45:36,526 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111142.49
2025-10-30 07:45:36,526 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111142.49 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,526 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:36,528 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:36,529 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.54, Commission=$0.00, Net=$0.54 (cash flow: +$2000.54, -$0.00, balance: $10000.54)
2025-10-30 07:45:36,529 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3309/9953
2025-10-30 07:45:36,532 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108254.00
2025-10-30 07:45:36,532 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108254.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,533 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:36,536 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,541 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:36,541 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.23, Commission=$0.00, Net=$1.23 (cash flow: -$1998.77, balance: $10001.23)
2025-10-30 07:45:36,542 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 278/9953
2025-10-30 07:45:36,544 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108790.30
2025-10-30 07:45:36,545 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108790.30 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,545 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:36,549 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,551 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:36,552 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.59, Commission=$0.00, Net=$0.59 (cash flow: +$2000.59, -$0.00, balance: $10000.59)
2025-10-30 07:45:36,552 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1921/9953
2025-10-30 07:45:36,554 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112286.62
2025-10-30 07:45:36,555 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112286.62 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,555 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:36,558 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:36,558 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:45:36,559 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2151/9953
2025-10-30 07:45:36,563 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112244.92
2025-10-30 07:45:36,563 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112244.92 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,564 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:36,565 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:36,565 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.50, Commission=$0.00, Net=$0.50 (cash flow: -$1999.50, balance: $10000.50)
2025-10-30 07:45:36,566 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2789/9953
2025-10-30 07:45:36,569 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108858.43
2025-10-30 07:45:36,569 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108858.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,569 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:36,572 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,576 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:36,577 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.75, Commission=$0.00, Net=$-2.75 (cash flow: -$2002.75, balance: $9997.25)
2025-10-30 07:45:36,577 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5114/9953
2025-10-30 07:45:36,580 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108121.27
2025-10-30 07:45:36,580 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108121.27 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,581 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:36,583 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,588 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:36,588 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.73, Commission=$0.00, Net=$-2.73 (cash flow: +$1997.27, -$0.00, balance: $9997.27)
2025-10-30 07:45:36,589 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2358/9953
2025-10-30 07:45:36,591 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111311.52
2025-10-30 07:45:36,592 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111311.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,592 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:36,595 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:36,595 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.43, Commission=$0.00, Net=$0.43 (cash flow: +$2000.43, -$0.00, balance: $10000.43)
2025-10-30 07:45:36,596 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 439/9953
2025-10-30 07:45:36,598 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110424.83
2025-10-30 07:45:36,598 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110424.83 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,599 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:36,600 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,606 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:36,606 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.42, Commission=$0.00, Net=$1.42 (cash flow: -$1998.58, balance: $10001.42)
2025-10-30 07:45:36,607 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6450/9953
2025-10-30 07:45:36,608 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109489.93
2025-10-30 07:45:36,608 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109489.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,609 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:36,611 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,615 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:36,616 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.07, Commission=$0.00, Net=$-3.07 (cash flow: -$2003.07, balance: $9996.93)
2025-10-30 07:45:36,616 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6741/9953
2025-10-30 07:45:36,619 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109728.48
2025-10-30 07:45:36,619 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109728.48 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,619 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:36,622 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,626 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:36,627 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.78, Commission=$0.00, Net=$-3.78 (cash flow: +$1996.22, -$0.00, balance: $9996.22)
2025-10-30 07:45:36,627 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5579/9953
2025-10-30 07:45:36,630 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108219.67
2025-10-30 07:45:36,630 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108219.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,630 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:36,632 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,635 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:36,635 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: +$2000.38, -$0.00, balance: $10000.38)
2025-10-30 07:45:36,636 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2160/9953
2025-10-30 07:45:36,640 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112086.63
2025-10-30 07:45:36,640 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112086.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,640 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:36,643 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,645 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:36,646 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.80, Commission=$0.00, Net=$-0.80 (cash flow: -$2000.80, balance: $9999.20)
2025-10-30 07:45:36,647 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3154/9953
2025-10-30 07:45:36,648 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108085.87
2025-10-30 07:45:36,648 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108085.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,648 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:36,653 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:36,654 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 07:45:36,655 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1093/9953
2025-10-30 07:45:36,657 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113372.28
2025-10-30 07:45:36,658 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113372.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,658 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:36,660 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,663 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0176, signal=1.0
2025-10-30 07:45:36,663 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.02, Commission=$0.00, Net=$-2.02 (cash flow: -$2002.02, balance: $9997.98)
2025-10-30 07:45:36,664 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3161/9953
2025-10-30 07:45:36,668 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108172.55
2025-10-30 07:45:36,669 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108172.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,669 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:36,672 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,679 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:36,679 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.17, Commission=$0.00, Net=$-2.17 (cash flow: +$1997.83, -$0.00, balance: $9997.83)
2025-10-30 07:45:36,680 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3460/9953
2025-10-30 07:45:36,684 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107929.11
2025-10-30 07:45:36,684 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107929.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,684 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:36,686 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,688 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:36,689 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.54, Commission=$0.00, Net=$0.54 (cash flow: -$1999.46, balance: $10000.54)
2025-10-30 07:45:36,690 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9381/9953
2025-10-30 07:45:36,692 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110615.38
2025-10-30 07:45:36,693 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110615.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,693 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:36,694 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:36,695 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.60, Commission=$0.00, Net=$2.60 (cash flow: -$1997.40, balance: $10002.60)
2025-10-30 07:45:36,696 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8400/9953
2025-10-30 07:45:36,700 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111244.26
2025-10-30 07:45:36,701 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111244.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,701 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:36,702 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:36,703 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.28, Commission=$0.00, Net=$1.28 (cash flow: -$1998.72, balance: $10001.28)
2025-10-30 07:45:36,704 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4950/9953
2025-10-30 07:45:36,706 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108062.51
2025-10-30 07:45:36,706 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108062.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:36,707 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:36,709 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:36,711 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:36,711 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.12, Commission=$0.00, Net=$-0.12 (cash flow: -$2000.12, balance: $9999.88)
2025-10-30 07:45:36,712 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6847/9953
2025-10-30 07:45:36,716 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109494.84
2025-10-30 07:45:36,717 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109494.84 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:36,717 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:36,720 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:36,720 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.23, Commission=$0.00, Net=$-0.23 (cash flow: +$1999.77, -$0.00, balance: $9999.77)
2025-10-30 07:45:36,721 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7454/9953
2025-10-30 07:45:36,724 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110335.48

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.07     |
|    ep_rew_mean        | 7.48e-06 |
| time/                 |          |
|    fps                | 390      |
|    iterations         | 1600     |
|    time_elapsed       | 20       |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -0.891   |
|    explained_variance | 0.485    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1599     |
|    policy_loss        | -0.00325 |
|    value_loss         | 0.0216   |
------------------------------------

2025-10-30 07:45:37,789 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0177, signal=-1.0
2025-10-30 07:45:37,789 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:45:37,790 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9384/9953
2025-10-30 07:45:37,793 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110503.80
2025-10-30 07:45:37,793 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110503.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,794 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:37,796 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,801 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:37,801 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.35, Commission=$0.00, Net=$-1.35 (cash flow: +$1998.65, -$0.00, balance: $9998.65)
2025-10-30 07:45:37,802 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4401/9953
2025-10-30 07:45:37,804 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108050.42
2025-10-30 07:45:37,804 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108050.42 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,805 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:37,808 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,810 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:37,810 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.76, Commission=$0.00, Net=$0.76 (cash flow: +$2000.76, -$0.00, balance: $10000.76)
2025-10-30 07:45:37,811 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6361/9953
2025-10-30 07:45:37,816 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108800.00
2025-10-30 07:45:37,817 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108800.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,817 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:37,820 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,822 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:37,822 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.31, Commission=$0.00, Net=$-1.31 (cash flow: +$1998.69, -$0.00, balance: $9998.69)
2025-10-30 07:45:37,824 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5519/9953
2025-10-30 07:45:37,827 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107949.43
2025-10-30 07:45:37,828 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107949.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,828 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:37,832 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,834 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:37,835 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.12, Commission=$0.00, Net=$0.12 (cash flow: +$2000.12, -$0.00, balance: $10000.12)
2025-10-30 07:45:37,835 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3433/9953
2025-10-30 07:45:37,838 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108193.49
2025-10-30 07:45:37,838 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108193.49 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,839 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:37,841 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,847 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:37,848 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.17, Commission=$0.00, Net=$1.17 (cash flow: -$1998.83, balance: $10001.17)
2025-10-30 07:45:37,849 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4510/9953
2025-10-30 07:45:37,853 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107859.45
2025-10-30 07:45:37,854 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107859.45 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,854 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:37,859 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:37,860 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.69, Commission=$0.00, Net=$-0.69 (cash flow: +$1999.31, -$0.00, balance: $9999.31)
2025-10-30 07:45:37,861 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6721/9953
2025-10-30 07:45:37,864 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109676.05
2025-10-30 07:45:37,864 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109676.05 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,865 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:37,866 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,870 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:37,870 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: +$2000.95, -$0.00, balance: $10000.95)
2025-10-30 07:45:37,871 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3306/9953
2025-10-30 07:45:37,876 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108287.16
2025-10-30 07:45:37,876 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108287.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,876 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:37,879 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,881 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:37,881 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.61, Commission=$0.00, Net=$0.61 (cash flow: -$1999.39, balance: $10000.61)
2025-10-30 07:45:37,882 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 322/9953
2025-10-30 07:45:37,885 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108500.00
2025-10-30 07:45:37,885 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108500.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,886 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:37,889 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,892 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:37,892 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.39, Commission=$0.00, Net=$1.39 (cash flow: +$2001.39, -$0.00, balance: $10001.39)
2025-10-30 07:45:37,893 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3405/9953
2025-10-30 07:45:37,894 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108221.16
2025-10-30 07:45:37,895 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108221.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,895 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:37,896 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,899 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:37,900 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: -$1999.80, balance: $10000.20)
2025-10-30 07:45:37,901 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6265/9953
2025-10-30 07:45:37,902 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108498.90
2025-10-30 07:45:37,902 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108498.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,903 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:37,909 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,910 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:37,910 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.54, Commission=$0.00, Net=$0.54 (cash flow: +$2000.54, -$0.00, balance: $10000.54)
2025-10-30 07:45:37,911 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8812/9953
2025-10-30 07:45:37,914 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111595.00
2025-10-30 07:45:37,914 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111595.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,914 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:37,916 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,918 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:37,919 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.50, Commission=$0.00, Net=$-1.50 (cash flow: -$2001.50, balance: $9998.50)
2025-10-30 07:45:37,921 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 389/9953
2025-10-30 07:45:37,926 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110062.04
2025-10-30 07:45:37,926 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110062.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,926 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:37,928 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,932 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:37,932 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.84, Commission=$0.00, Net=$1.84 (cash flow: +$2001.84, -$0.00, balance: $10001.84)
2025-10-30 07:45:37,933 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1318/9953
2025-10-30 07:45:37,937 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113826.34
2025-10-30 07:45:37,937 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113826.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,938 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:37,940 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,944 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:37,944 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.13, Commission=$0.00, Net=$-0.13 (cash flow: -$2000.13, balance: $9999.87)
2025-10-30 07:45:37,945 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3593/9953
2025-10-30 07:45:37,950 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108569.00
2025-10-30 07:45:37,950 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108569.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,950 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:37,954 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,958 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:37,958 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.20, Commission=$0.00, Net=$-0.20 (cash flow: -$2000.20, balance: $9999.80)
2025-10-30 07:45:37,959 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9620/9953
2025-10-30 07:45:37,964 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111123.86
2025-10-30 07:45:37,964 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111123.86 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,965 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:37,967 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,969 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:37,970 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.09, Commission=$0.00, Net=$-1.09 (cash flow: +$1998.91, -$0.00, balance: $9998.91)
2025-10-30 07:45:37,972 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3670/9953
2025-10-30 07:45:37,974 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107990.00
2025-10-30 07:45:37,975 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107990.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,975 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:37,980 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:37,982 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:37,982 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.19, Commission=$0.00, Net=$0.19 (cash flow: +$2000.19, -$0.00, balance: $10000.19)
2025-10-30 07:45:37,983 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9246/9953
2025-10-30 07:45:37,986 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110173.20
2025-10-30 07:45:37,987 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110173.20 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:37,987 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:37,990 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:37,991 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.37, Commission=$0.00, Net=$1.37 (cash flow: -$1998.63, balance: $10001.37)
2025-10-30 07:45:37,992 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6171/9953
2025-10-30 07:45:37,998 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108134.75
2025-10-30 07:45:37,998 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108134.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:37,999 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:38,002 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:38,003 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:38,003 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.37, Commission=$0.00, Net=$-0.37 (cash flow: +$1999.63, -$0.00, balance: $9999.63)
2025-10-30 07:45:38,005 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3232/9953
2025-10-30 07:45:38,008 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108401.08
2025-10-30 07:45:38,008 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108401.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:38,008 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:38,014 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:38,014 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.04, Commission=$0.00, Net=$-0.04 (cash flow: -$2000.04, balance: $9999.96)
2025-10-30 07:45:38,015 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2978/9953
2025-10-30 07:45:38,018 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108500.00
2025-10-30 07:45:38,019 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108500.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:38,019 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:38,022 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:38,027 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:38,028 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.07, Commission=$0.00, Net=$1.07 (cash flow: +$2001.07, -$0.00, balance: $10001.07)
2025-10-30 07:45:38,029 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3348/9953
2025-10-30 07:45:38,032 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108557.78
2025-10-30 07:45:38,032 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108557.78 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:38,032 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:38,036 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:38,038 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 3.94      |
|    ep_rew_mean        | -7.88e-06 |
| time/                 |           |
|    fps                | 388       |
|    iterations         | 1700      |
|    time_elapsed       | 21        |
|    total_timesteps    | 8500      |
| train/                |           |
|    entropy_loss       | -0.942    |
|    explained_variance | -0.0135   |
|    learning_rate      | 0.0007    |
|    n_updates          | 1699      |
|    policy_loss        | -0.5      |
|    value_loss         | 0.177     |
-------------------------------------

2025-10-30 07:45:39,231 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:39,231 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.06, Commission=$0.00, Net=$2.06 (cash flow: +$2002.06, -$0.00, balance: $10002.06)
2025-10-30 07:45:39,232 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 768/9953
2025-10-30 07:45:39,236 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112540.58
2025-10-30 07:45:39,236 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112540.58 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,236 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:39,241 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,242 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:39,242 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.20, Commission=$0.00, Net=$-1.20 (cash flow: -$2001.20, balance: $9998.80)
2025-10-30 07:45:39,243 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9690/9953
2025-10-30 07:45:39,246 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111128.90
2025-10-30 07:45:39,246 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111128.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,247 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:39,249 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:39,249 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.98, Commission=$0.00, Net=$0.98 (cash flow: -$1999.02, balance: $10000.98)
2025-10-30 07:45:39,250 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5444/9953
2025-10-30 07:45:39,255 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108032.90
2025-10-30 07:45:39,255 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108032.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,256 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:39,258 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,261 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:39,262 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.39, Commission=$0.00, Net=$-3.39 (cash flow: +$1996.61, -$0.00, balance: $9996.61)
2025-10-30 07:45:39,263 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9594/9953
2025-10-30 07:45:39,268 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110953.15
2025-10-30 07:45:39,268 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110953.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,268 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:39,270 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:39,270 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.06, Commission=$0.00, Net=$1.06 (cash flow: +$2001.06, -$0.00, balance: $10001.06)
2025-10-30 07:45:39,270 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6595/9953
2025-10-30 07:45:39,274 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110084.88
2025-10-30 07:45:39,274 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110084.88 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,275 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:39,278 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,285 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:39,286 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.13, Commission=$0.00, Net=$-0.13 (cash flow: -$2000.13, balance: $9999.87)
2025-10-30 07:45:39,287 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6889/9953
2025-10-30 07:45:39,289 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109385.10
2025-10-30 07:45:39,290 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109385.10 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,291 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:39,295 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:39,295 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.76, Commission=$0.00, Net=$0.76 (cash flow: -$1999.24, balance: $10000.76)
2025-10-30 07:45:39,295 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6755/9953
2025-10-30 07:45:39,297 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109667.09
2025-10-30 07:45:39,297 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109667.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,298 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:39,301 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,305 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:39,305 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.92, Commission=$0.00, Net=$-2.92 (cash flow: +$1997.08, -$0.00, balance: $9997.08)
2025-10-30 07:45:39,306 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4383/9953
2025-10-30 07:45:39,308 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107763.11
2025-10-30 07:45:39,309 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107763.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,309 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:39,312 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,317 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 07:45:39,317 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.98, Commission=$0.00, Net=$-1.98 (cash flow: -$2001.98, balance: $9998.02)
2025-10-30 07:45:39,318 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1542/9953
2025-10-30 07:45:39,319 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112450.05
2025-10-30 07:45:39,320 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112450.05 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,321 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:39,322 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,324 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 07:45:39,325 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.53, Commission=$0.00, Net=$-1.53 (cash flow: +$1998.47, -$0.00, balance: $9998.47)
2025-10-30 07:45:39,326 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9346/9953
2025-10-30 07:45:39,328 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110434.74
2025-10-30 07:45:39,328 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110434.74 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,329 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:39,334 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:39,334 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.30, Commission=$0.00, Net=$0.30 (cash flow: -$1999.70, balance: $10000.30)
2025-10-30 07:45:39,335 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8058/9953
2025-10-30 07:45:39,337 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110238.22
2025-10-30 07:45:39,338 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110238.22 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,338 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:39,341 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,347 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:39,348 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.01, Commission=$0.00, Net=$1.01 (cash flow: +$2001.01, -$0.00, balance: $10001.01)
2025-10-30 07:45:39,349 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6138/9953
2025-10-30 07:45:39,351 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108208.16
2025-10-30 07:45:39,352 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108208.16 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,352 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:39,353 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,356 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:39,357 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.26, Commission=$0.00, Net=$2.26 (cash flow: +$2002.26, -$0.00, balance: $10002.26)
2025-10-30 07:45:39,359 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2787/9953
2025-10-30 07:45:39,362 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108758.55
2025-10-30 07:45:39,363 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108758.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,363 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:39,366 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:39,367 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.01, Commission=$0.00, Net=$2.01 (cash flow: +$2002.01, -$0.00, balance: $10002.01)
2025-10-30 07:45:39,368 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3159/9953
2025-10-30 07:45:39,370 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108201.58
2025-10-30 07:45:39,370 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108201.58 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,371 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:39,374 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,381 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:39,381 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.05, Commission=$0.00, Net=$-2.05 (cash flow: +$1997.95, -$0.00, balance: $9997.95)
2025-10-30 07:45:39,382 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5985/9953
2025-10-30 07:45:39,385 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107280.32
2025-10-30 07:45:39,385 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107280.32 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,386 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:39,388 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,392 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:39,393 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.87, Commission=$0.00, Net=$-3.87 (cash flow: +$1996.13, -$0.00, balance: $9996.13)
2025-10-30 07:45:39,393 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3805/9953
2025-10-30 07:45:39,395 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107972.96
2025-10-30 07:45:39,396 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107972.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,396 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:39,398 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,400 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:39,400 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.74, Commission=$0.00, Net=$0.74 (cash flow: +$2000.74, -$0.00, balance: $10000.74)
2025-10-30 07:45:39,401 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5143/9953
2025-10-30 07:45:39,406 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107887.92
2025-10-30 07:45:39,406 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107887.92 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,406 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:39,408 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,412 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:39,412 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.67, Commission=$0.00, Net=$2.67 (cash flow: +$2002.67, -$0.00, balance: $10002.67)
2025-10-30 07:45:39,413 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7905/9953
2025-10-30 07:45:39,414 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109790.62
2025-10-30 07:45:39,415 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109790.62 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,415 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:39,420 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,421 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:39,422 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.68, Commission=$0.00, Net=$0.68 (cash flow: +$2000.68, -$0.00, balance: $10000.68)
2025-10-30 07:45:39,423 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8774/9953
2025-10-30 07:45:39,426 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111902.00
2025-10-30 07:45:39,426 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111902.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,427 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:39,430 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:39,430 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.91, Commission=$0.00, Net=$0.91 (cash flow: +$2000.91, -$0.00, balance: $10000.91)
2025-10-30 07:45:39,431 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8408/9953
2025-10-30 07:45:39,437 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110964.52
2025-10-30 07:45:39,437 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110964.52 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,438 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:39,443 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,444 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:39,444 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.85, Commission=$0.00, Net=$1.85 (cash flow: -$1998.15, balance: $10001.85)
2025-10-30 07:45:39,445 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7683/9953
2025-10-30 07:45:39,449 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110904.36
2025-10-30 07:45:39,449 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110904.36 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:39,449 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:39,452 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,455 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 07:45:39,456 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.48, Commission=$0.00, Net=$-2.48 (cash flow: +$1997.52, -$0.00, balance: $9997.52)
2025-10-30 07:45:39,456 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2857/9953
2025-10-30 07:45:39,459 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109192.99
2025-10-30 07:45:39,459 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109192.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:39,460 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:39,461 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:39,463 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:39,464 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.21, Commission=$0.00, Net=$-1.21 (cash flow: -$2001.21, balance: $9998.79)
2025-10-30 07:45:39,464 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9573/9953

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 4.13      |
|    ep_rew_mean        | -4.55e-06 |
| time/                 |           |
|    fps                | 387       |
|    iterations         | 1800      |
|    time_elapsed       | 23        |
|    total_timesteps    | 9000      |
| train/                |           |
|    entropy_loss       | -0.749    |
|    explained_variance | 0.915     |
|    learning_rate      | 0.0007    |
|    n_updates          | 1799      |
|    policy_loss        | -0.00155  |
|    value_loss         | 0.00251   |
-------------------------------------

2025-10-30 07:45:40,543 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:40,543 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.27, Commission=$0.00, Net=$-0.27 (cash flow: -$2000.27, balance: $9999.73)
2025-10-30 07:45:40,543 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3257/9953
2025-10-30 07:45:40,545 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108183.00
2025-10-30 07:45:40,546 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108183.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,546 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:40,548 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,550 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:40,551 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.64, Commission=$0.00, Net=$-1.64 (cash flow: -$2001.64, balance: $9998.36)
2025-10-30 07:45:40,551 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4644/9953
2025-10-30 07:45:40,554 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108872.87
2025-10-30 07:45:40,554 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108872.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,554 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:40,558 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:40,559 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.54, Commission=$0.00, Net=$-0.54 (cash flow: +$1999.46, -$0.00, balance: $9999.46)
2025-10-30 07:45:40,559 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 172/9953
2025-10-30 07:45:40,561 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109045.70
2025-10-30 07:45:40,561 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109045.70 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,561 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:40,564 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:40,564 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.46, Commission=$0.00, Net=$1.46 (cash flow: -$1998.54, balance: $10001.46)
2025-10-30 07:45:40,565 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6142/9953
2025-10-30 07:45:40,567 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108297.29
2025-10-30 07:45:40,567 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108297.29 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,568 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:40,569 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,577 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:40,578 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.42, Commission=$0.00, Net=$1.42 (cash flow: +$2001.42, -$0.00, balance: $10001.42)
2025-10-30 07:45:40,578 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4715/9953
2025-10-30 07:45:40,583 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108380.00
2025-10-30 07:45:40,583 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108380.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,583 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:40,585 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:40,586 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.36, Commission=$0.00, Net=$0.36 (cash flow: -$1999.64, balance: $10000.36)
2025-10-30 07:45:40,587 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5289/9953
2025-10-30 07:45:40,588 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107955.73
2025-10-30 07:45:40,589 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107955.73 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,589 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:40,591 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,593 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:40,594 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.66, Commission=$0.00, Net=$0.66 (cash flow: -$1999.34, balance: $10000.66)
2025-10-30 07:45:40,595 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8836/9953
2025-10-30 07:45:40,599 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111354.79
2025-10-30 07:45:40,600 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111354.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,600 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:40,603 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,605 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:40,606 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.48, Commission=$0.00, Net=$0.48 (cash flow: +$2000.48, -$0.00, balance: $10000.48)
2025-10-30 07:45:40,606 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7860/9953
2025-10-30 07:45:40,608 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109636.87
2025-10-30 07:45:40,609 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109636.87 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,609 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:40,613 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:40,614 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.19, Commission=$0.00, Net=$-0.19 (cash flow: -$2000.19, balance: $9999.81)
2025-10-30 07:45:40,614 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2754/9953
2025-10-30 07:45:40,616 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109024.02
2025-10-30 07:45:40,617 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109024.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,617 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:40,619 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,622 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:40,622 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.54, Commission=$0.00, Net=$2.54 (cash flow: +$2002.54, -$0.00, balance: $10002.54)
2025-10-30 07:45:40,623 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8287/9953
2025-10-30 07:45:40,629 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111152.51
2025-10-30 07:45:40,629 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111152.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,629 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:40,631 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:40,631 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.94, Commission=$0.00, Net=$0.94 (cash flow: -$1999.06, balance: $10000.94)
2025-10-30 07:45:40,633 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3124/9953
2025-10-30 07:45:40,637 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107951.13
2025-10-30 07:45:40,637 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107951.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,637 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:40,639 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,645 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:40,645 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.19, Commission=$0.00, Net=$-1.19 (cash flow: +$1998.81, -$0.00, balance: $9998.81)
2025-10-30 07:45:40,646 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8605/9953
2025-10-30 07:45:40,649 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111207.09
2025-10-30 07:45:40,649 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111207.09 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,649 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:40,652 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:40,652 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.77, Commission=$0.00, Net=$-0.77 (cash flow: -$2000.77, balance: $9999.23)
2025-10-30 07:45:40,653 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4653/9953
2025-10-30 07:45:40,656 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108842.91
2025-10-30 07:45:40,656 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108842.91 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,656 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:40,660 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,661 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:40,662 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 07:45:40,662 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6553/9953
2025-10-30 07:45:40,665 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110148.02
2025-10-30 07:45:40,665 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110148.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,666 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:40,668 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:40,669 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.02, Commission=$0.00, Net=$1.02 (cash flow: -$1998.98, balance: $10001.02)
2025-10-30 07:45:40,669 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3058/9953
2025-10-30 07:45:40,672 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108419.60
2025-10-30 07:45:40,672 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108419.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,673 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:40,677 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:40,678 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.28, Commission=$0.00, Net=$0.28 (cash flow: -$1999.72, balance: $10000.28)
2025-10-30 07:45:40,679 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 502/9953
2025-10-30 07:45:40,681 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109936.78
2025-10-30 07:45:40,681 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109936.78 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,682 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:40,685 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,686 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:40,686 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.02, Commission=$0.00, Net=$1.02 (cash flow: -$1998.98, balance: $10001.02)
2025-10-30 07:45:40,687 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2722/9953
2025-10-30 07:45:40,689 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108830.40
2025-10-30 07:45:40,689 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108830.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,689 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:40,694 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,695 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:40,696 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.54, Commission=$0.00, Net=$1.54 (cash flow: +$2001.54, -$0.00, balance: $10001.54)
2025-10-30 07:45:40,696 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3605/9953
2025-10-30 07:45:40,699 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108614.00
2025-10-30 07:45:40,700 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108614.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,700 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:40,703 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,707 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:40,707 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.62, Commission=$0.00, Net=$0.62 (cash flow: -$1999.38, balance: $10000.62)
2025-10-30 07:45:40,708 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2832/9953
2025-10-30 07:45:40,710 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109082.65
2025-10-30 07:45:40,711 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109082.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,711 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:40,714 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,716 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:40,716 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.98, Commission=$0.00, Net=$0.98 (cash flow: -$1999.02, balance: $10000.98)
2025-10-30 07:45:40,717 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5320/9953
2025-10-30 07:45:40,721 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108221.95
2025-10-30 07:45:40,721 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108221.95 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,722 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:40,724 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,726 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:40,727 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.77, Commission=$0.00, Net=$4.77 (cash flow: +$2004.77, -$0.00, balance: $10004.77)
2025-10-30 07:45:40,727 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 50/9953
2025-10-30 07:45:40,729 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108580.01
2025-10-30 07:45:40,730 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108580.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,730 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:40,735 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:40,736 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:40,736 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: -$1999.15, balance: $10000.85)
2025-10-30 07:45:40,737 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8778/9953
2025-10-30 07:45:40,739 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111771.17
2025-10-30 07:45:40,740 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111771.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:40,740 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:40,743 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:40,743 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.27, Commission=$0.00, Net=$0.27 (cash flow: -$1999.73, balance: $10000.27)
2025-10-30 07:45:40,744 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9787/9953
2025-10-30 07:45:40,746 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111365.87
2025-10-30 07:45:40,747 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111365.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:40,747 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 4.15      |
|    ep_rew_mean        | -5.63e-06 |
| time/                 |           |
|    fps                | 387       |
|    iterations         | 1900      |
|    time_elapsed       | 24        |
|    total_timesteps    | 9500      |
| train/                |           |
|    entropy_loss       | -0.778    |
|    explained_variance | 0.321     |
|    learning_rate      | 0.0007    |
|    n_updates          | 1899      |
|    policy_loss        | 0.0267    |
|    value_loss         | 0.182     |
-------------------------------------

2025-10-30 07:45:41,860 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:41,860 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.79, Commission=$0.00, Net=$-1.79 (cash flow: +$1998.21, -$0.00, balance: $9998.21)
2025-10-30 07:45:41,861 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1400/9953
2025-10-30 07:45:41,863 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113083.13
2025-10-30 07:45:41,864 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113083.13 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:41,864 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:41,865 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:41,866 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.19, Commission=$0.00, Net=$0.19 (cash flow: -$1999.81, balance: $10000.19)
2025-10-30 07:45:41,866 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9699/9953
2025-10-30 07:45:41,870 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111135.85
2025-10-30 07:45:41,870 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111135.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:41,870 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:41,875 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,876 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:41,877 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.20, Commission=$0.00, Net=$1.20 (cash flow: -$1998.80, balance: $10001.20)
2025-10-30 07:45:41,877 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1341/9953
2025-10-30 07:45:41,880 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113538.63
2025-10-30 07:45:41,881 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113538.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:41,881 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:41,884 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:41,884 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.09, Commission=$0.00, Net=$-0.09 (cash flow: -$2000.09, balance: $9999.91)
2025-10-30 07:45:41,885 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 678/9953
2025-10-30 07:45:41,892 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112222.47
2025-10-30 07:45:41,892 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112222.47 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,892 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:41,895 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,897 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 07:45:41,897 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.08, Commission=$0.00, Net=$-1.08 (cash flow: +$1998.92, -$0.00, balance: $9998.92)
2025-10-30 07:45:41,898 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1060/9953
2025-10-30 07:45:41,902 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113263.47
2025-10-30 07:45:41,903 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113263.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:41,903 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:41,906 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:41,906 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.03, Commission=$0.00, Net=$0.03 (cash flow: -$1999.97, balance: $10000.03)
2025-10-30 07:45:41,907 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4788/9953
2025-10-30 07:45:41,909 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107740.01
2025-10-30 07:45:41,910 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107740.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,910 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:41,912 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,916 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:41,916 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.40, Commission=$0.00, Net=$2.40 (cash flow: +$2002.40, -$0.00, balance: $10002.40)
2025-10-30 07:45:41,917 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 796/9953
2025-10-30 07:45:41,920 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112680.53
2025-10-30 07:45:41,920 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112680.53 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:41,921 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:41,923 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:41,923 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.66, Commission=$0.00, Net=$0.66 (cash flow: -$1999.34, balance: $10000.66)
2025-10-30 07:45:41,924 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6315/9953
2025-10-30 07:45:41,926 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108409.87
2025-10-30 07:45:41,927 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108409.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,927 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:41,931 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,937 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:41,937 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.09, Commission=$0.00, Net=$0.09 (cash flow: +$2000.09, -$0.00, balance: $10000.09)
2025-10-30 07:45:41,937 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7692/9953
2025-10-30 07:45:41,941 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110873.00
2025-10-30 07:45:41,941 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110873.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,941 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:41,942 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:41,943 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.20, Commission=$0.00, Net=$-0.20 (cash flow: +$1999.80, -$0.00, balance: $9999.80)
2025-10-30 07:45:41,944 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4506/9953
2025-10-30 07:45:41,947 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108103.36
2025-10-30 07:45:41,947 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108103.36 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,947 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:41,952 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,954 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:41,955 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.74, Commission=$0.00, Net=$-3.74 (cash flow: +$1996.26, -$0.00, balance: $9996.26)
2025-10-30 07:45:41,955 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5086/9953
2025-10-30 07:45:41,957 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108466.52
2025-10-30 07:45:41,957 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108466.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,957 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:41,960 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,965 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:41,965 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.29, Commission=$0.00, Net=$1.29 (cash flow: +$2001.29, -$0.00, balance: $10001.29)
2025-10-30 07:45:41,966 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5227/9953
2025-10-30 07:45:41,968 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108553.16
2025-10-30 07:45:41,968 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108553.16 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,968 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:41,971 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,975 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:41,975 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.79, Commission=$0.00, Net=$0.79 (cash flow: +$2000.79, -$0.00, balance: $10000.79)
2025-10-30 07:45:41,976 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9425/9953
2025-10-30 07:45:41,980 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110699.45
2025-10-30 07:45:41,981 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110699.45 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:41,981 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:41,983 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:41,989 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:41,989 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.28, Commission=$0.00, Net=$-2.28 (cash flow: +$1997.72, -$0.00, balance: $9997.72)
2025-10-30 07:45:41,990 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8401/9953
2025-10-30 07:45:41,992 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111173.30
2025-10-30 07:45:41,993 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111173.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:41,993 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:41,995 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:41,995 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.58, Commission=$0.00, Net=$0.58 (cash flow: -$1999.42, balance: $10000.58)
2025-10-30 07:45:41,996 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8003/9953
2025-10-30 07:45:42,000 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110216.88
2025-10-30 07:45:42,001 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110216.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:42,001 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:42,003 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,006 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:42,007 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.54, Commission=$0.00, Net=$0.54 (cash flow: +$2000.54, -$0.00, balance: $10000.54)
2025-10-30 07:45:42,007 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 862/9953
2025-10-30 07:45:42,012 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112437.09
2025-10-30 07:45:42,012 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112437.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:42,012 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:42,014 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,018 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 07:45:42,018 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.80, Commission=$0.00, Net=$-2.80 (cash flow: +$1997.20, -$0.00, balance: $9997.20)
2025-10-30 07:45:42,019 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8171/9953
2025-10-30 07:45:42,023 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110970.62
2025-10-30 07:45:42,023 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110970.62 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:42,023 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:42,025 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,027 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:42,028 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.40, Commission=$0.00, Net=$-0.40 (cash flow: -$2000.40, balance: $9999.60)
2025-10-30 07:45:42,029 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4644/9953
2025-10-30 07:45:42,031 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108872.87
2025-10-30 07:45:42,031 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108872.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:42,031 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:42,034 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,038 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:42,038 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.09, Commission=$0.00, Net=$2.09 (cash flow: +$2002.09, -$0.00, balance: $10002.09)
2025-10-30 07:45:42,039 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1184/9953
2025-10-30 07:45:42,041 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113163.00
2025-10-30 07:45:42,042 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113163.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:42,042 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:42,045 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,046 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:42,046 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.51, Commission=$0.00, Net=$0.51 (cash flow: -$1999.49, balance: $10000.51)
2025-10-30 07:45:42,047 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8566/9953
2025-10-30 07:45:42,052 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111267.54
2025-10-30 07:45:42,053 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111267.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:42,053 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:42,054 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,060 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:42,060 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.39, Commission=$0.00, Net=$0.39 (cash flow: -$1999.61, balance: $10000.39)
2025-10-30 07:45:42,061 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 911/9953
2025-10-30 07:45:42,063 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112930.35
2025-10-30 07:45:42,063 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112930.35 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:42,064 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:42,066 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:42,067 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.26, Commission=$0.00, Net=$0.26 (cash flow: -$1999.74, balance: $10000.26)
2025-10-30 07:45:42,067 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2698/9953
2025-10-30 07:45:42,072 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108552.64
2025-10-30 07:45:42,072 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108552.64 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:42,072 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:42,074 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:42,077 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:42,077 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.74, Commission=$0.00, Net=$-4.74 (cash flow: +$1995.26, -$0.00, balance: $9995.26)
2025-10-30 07:45:42,078 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3006/9953
2025-10-30 07:45:42,082 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108346.00

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 4.48     |
|    ep_rew_mean        | 2.58e-05 |
| time/                 |          |
|    fps                | 387      |
|    iterations         | 2000     |
|    time_elapsed       | 25       |
|    total_timesteps    | 10000    |
| train/                |          |
|    entropy_loss       | -0.639   |
|    explained_variance | -0.238   |
|    learning_rate      | 0.0007   |
|    n_updates          | 1999     |
|    policy_loss        | 0.234    |
|    value_loss         | 0.364    |
------------------------------------

2025-10-30 07:45:43,115 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,116 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:43,116 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.34, Commission=$0.00, Net=$1.34 (cash flow: -$1998.66, balance: $10001.34)
2025-10-30 07:45:43,117 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7557/9953
2025-10-30 07:45:43,120 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110800.00
2025-10-30 07:45:43,120 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110800.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,121 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:43,123 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,124 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:43,125 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.16, Commission=$0.00, Net=$1.16 (cash flow: -$1998.84, balance: $10001.16)
2025-10-30 07:45:43,125 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9016/9953
2025-10-30 07:45:43,130 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110526.12
2025-10-30 07:45:43,131 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110526.12 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,131 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:43,134 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,137 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:43,138 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.88, Commission=$0.00, Net=$0.88 (cash flow: -$1999.12, balance: $10000.88)
2025-10-30 07:45:43,138 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8075/9953
2025-10-30 07:45:43,143 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110544.45
2025-10-30 07:45:43,143 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110544.45 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,144 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:43,147 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:43,147 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.09, Commission=$0.00, Net=$-0.09 (cash flow: -$2000.09, balance: $9999.91)
2025-10-30 07:45:43,148 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4270/9953
2025-10-30 07:45:43,150 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108160.55
2025-10-30 07:45:43,151 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108160.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,151 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,154 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,155 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.30, Commission=$0.00, Net=$-0.30 (cash flow: +$1999.70, -$0.00, balance: $9999.70)
2025-10-30 07:45:43,155 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5290/9953
2025-10-30 07:45:43,162 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107936.00
2025-10-30 07:45:43,162 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107936.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,162 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,164 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,164 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: +$2000.95, -$0.00, balance: $10000.95)
2025-10-30 07:45:43,165 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3108/9953
2025-10-30 07:45:43,167 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108003.99
2025-10-30 07:45:43,168 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108003.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,168 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,171 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,171 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.26, Commission=$0.00, Net=$0.26 (cash flow: +$2000.26, -$0.00, balance: $10000.26)
2025-10-30 07:45:43,172 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3215/9953
2025-10-30 07:45:43,176 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108261.17
2025-10-30 07:45:43,177 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108261.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,177 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,178 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,182 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,183 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.79, Commission=$0.00, Net=$1.79 (cash flow: +$2001.79, -$0.00, balance: $10001.79)
2025-10-30 07:45:43,183 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 647/9953
2025-10-30 07:45:43,187 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112136.77
2025-10-30 07:45:43,188 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112136.77 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,188 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:43,190 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,192 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:43,192 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.44, Commission=$0.00, Net=$2.44 (cash flow: -$1997.56, balance: $10002.44)
2025-10-30 07:45:43,193 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5800/9953
2025-10-30 07:45:43,195 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107319.95
2025-10-30 07:45:43,195 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107319.95 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,196 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:43,199 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,210 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:43,210 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.72, Commission=$0.00, Net=$-2.72 (cash flow: +$1997.28, -$0.00, balance: $9997.28)
2025-10-30 07:45:43,211 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8615/9953
2025-10-30 07:45:43,212 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111070.79
2025-10-30 07:45:43,213 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111070.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,214 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:43,219 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,224 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 07:45:43,225 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.35, Commission=$0.00, Net=$-4.35 (cash flow: +$1995.65, -$0.00, balance: $9995.65)
2025-10-30 07:45:43,225 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 379/9953
2025-10-30 07:45:43,229 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109815.27
2025-10-30 07:45:43,230 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109815.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,230 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:43,232 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:43,233 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.12, Commission=$0.00, Net=$-0.12 (cash flow: -$2000.12, balance: $9999.88)
2025-10-30 07:45:43,234 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6600/9953
2025-10-30 07:45:43,239 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110086.96
2025-10-30 07:45:43,239 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110086.96 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,239 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:43,243 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,245 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:43,245 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.45, Commission=$0.00, Net=$1.45 (cash flow: -$1998.55, balance: $10001.45)
2025-10-30 07:45:43,246 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5142/9953
2025-10-30 07:45:43,251 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107887.92
2025-10-30 07:45:43,251 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107887.92 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,252 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,255 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,255 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.54, Commission=$0.00, Net=$1.54 (cash flow: +$2001.54, -$0.00, balance: $10001.54)
2025-10-30 07:45:43,256 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4258/9953
2025-10-30 07:45:43,259 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107930.35
2025-10-30 07:45:43,260 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107930.35 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,260 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,264 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,265 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,265 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.25, Commission=$0.00, Net=$2.25 (cash flow: +$2002.25, -$0.00, balance: $10002.25)
2025-10-30 07:45:43,266 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 788/9953
2025-10-30 07:45:43,272 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112870.49
2025-10-30 07:45:43,272 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112870.49 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,272 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:43,275 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,277 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:43,278 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.70, Commission=$0.00, Net=$1.70 (cash flow: -$1998.30, balance: $10001.70)
2025-10-30 07:45:43,279 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3199/9953
2025-10-30 07:45:43,280 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108067.99
2025-10-30 07:45:43,281 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108067.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,281 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,282 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,290 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,290 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.00, Commission=$0.00, Net=$2.00 (cash flow: +$2002.00, -$0.00, balance: $10002.00)
2025-10-30 07:45:43,291 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3246/9953
2025-10-30 07:45:43,298 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108100.95
2025-10-30 07:45:43,298 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108100.95 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,299 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:43,302 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,305 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:43,305 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.98, Commission=$0.00, Net=$-0.98 (cash flow: -$2000.98, balance: $9999.02)
2025-10-30 07:45:43,306 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3913/9953
2025-10-30 07:45:43,312 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108133.11
2025-10-30 07:45:43,312 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108133.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,312 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,316 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,328 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,329 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.89, Commission=$0.00, Net=$1.89 (cash flow: +$2001.89, -$0.00, balance: $10001.89)
2025-10-30 07:45:43,329 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6219/9953
2025-10-30 07:45:43,333 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108143.23
2025-10-30 07:45:43,333 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108143.23 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,334 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:43,337 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,341 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:43,341 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.37, Commission=$0.00, Net=$-0.37 (cash flow: +$1999.63, -$0.00, balance: $9999.63)
2025-10-30 07:45:43,342 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 543/9953
2025-10-30 07:45:43,344 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110764.56
2025-10-30 07:45:43,344 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110764.56 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:43,344 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:43,347 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,351 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:43,352 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.19, Commission=$0.00, Net=$0.19 (cash flow: +$2000.19, -$0.00, balance: $10000.19)
2025-10-30 07:45:43,352 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7232/9953
2025-10-30 07:45:43,358 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109229.10
2025-10-30 07:45:43,358 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109229.10 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,358 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:43,362 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,365 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:43,365 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.04, Commission=$0.00, Net=$-0.04 (cash flow: -$2000.04, balance: $9999.96)
2025-10-30 07:45:43,366 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8117/9953
2025-10-30 07:45:43,372 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110478.37
2025-10-30 07:45:43,373 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110478.37 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:43,373 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:43,376 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:43,381 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:43,382 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.35, Commission=$0.00, Net=$0.35 (cash flow: -$1999.65, balance: $10000.35)
2025-10-30 07:45:43,382 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5198/9953

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 6.35     |
|    ep_rew_mean        | 2.77e-05 |
| time/                 |          |
|    fps                | 392      |
|    iterations         | 2100     |
|    time_elapsed       | 26       |
|    total_timesteps    | 10500    |
| train/                |          |
|    entropy_loss       | -0.0622  |
|    explained_variance | 0.468    |
|    learning_rate      | 0.0007   |
|    n_updates          | 2099     |
|    policy_loss        | -0.00682 |
|    value_loss         | 0.468    |
------------------------------------

2025-10-30 07:45:44,129 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:44,129 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-10.84, Commission=$0.00, Net=$-10.84 (cash flow: +$1989.16, -$0.00, balance: $9989.16)
2025-10-30 07:45:44,130 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7554/9953
2025-10-30 07:45:44,135 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110800.00
2025-10-30 07:45:44,135 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110800.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,136 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:44,138 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,139 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:44,140 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.83, Commission=$0.00, Net=$-0.83 (cash flow: -$2000.83, balance: $9999.17)
2025-10-30 07:45:44,140 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4183/9953
2025-10-30 07:45:44,145 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107165.88
2025-10-30 07:45:44,145 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107165.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,146 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:44,148 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,155 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:44,155 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.63, Commission=$0.00, Net=$2.63 (cash flow: +$2002.63, -$0.00, balance: $10002.63)
2025-10-30 07:45:44,156 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4914/9953
2025-10-30 07:45:44,158 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107853.13
2025-10-30 07:45:44,158 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107853.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,159 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:44,161 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:44,162 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.56, Commission=$0.00, Net=$1.56 (cash flow: +$2001.56, -$0.00, balance: $10001.56)
2025-10-30 07:45:44,163 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4362/9953
2025-10-30 07:45:44,165 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107550.00
2025-10-30 07:45:44,165 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107550.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,166 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:44,170 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,172 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:44,173 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.91, Commission=$0.00, Net=$1.91 (cash flow: +$2001.91, -$0.00, balance: $10001.91)
2025-10-30 07:45:44,173 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2063/9953
2025-10-30 07:45:44,175 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112069.99
2025-10-30 07:45:44,176 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112069.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,176 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:44,178 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,192 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:44,192 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.30, Commission=$0.00, Net=$0.30 (cash flow: -$1999.70, balance: $10000.30)
2025-10-30 07:45:44,193 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5956/9953
2025-10-30 07:45:44,196 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=106917.57
2025-10-30 07:45:44,196 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $106917.57 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,196 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:44,201 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:44,201 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.41, Commission=$0.00, Net=$3.41 (cash flow: +$2003.41, -$0.00, balance: $10003.41)
2025-10-30 07:45:44,202 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1451/9953
2025-10-30 07:45:44,204 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112749.86
2025-10-30 07:45:44,204 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112749.86 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,204 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:44,206 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,212 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:44,212 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.77, Commission=$0.00, Net=$1.77 (cash flow: -$1998.23, balance: $10001.77)
2025-10-30 07:45:44,213 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3840/9953
2025-10-30 07:45:44,215 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107666.39
2025-10-30 07:45:44,216 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107666.39 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,216 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:44,219 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,228 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:44,229 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.75, Commission=$0.00, Net=$1.75 (cash flow: +$2001.75, -$0.00, balance: $10001.75)
2025-10-30 07:45:44,229 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1114/9953
2025-10-30 07:45:44,230 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113336.74
2025-10-30 07:45:44,231 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113336.74 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,231 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:44,236 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,242 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:44,242 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.84, Commission=$0.00, Net=$2.84 (cash flow: -$1997.16, balance: $10002.84)
2025-10-30 07:45:44,243 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6896/9953
2025-10-30 07:45:44,244 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109197.29
2025-10-30 07:45:44,245 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109197.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,246 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:44,248 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,250 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:44,250 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.92, Commission=$0.00, Net=$0.92 (cash flow: -$1999.08, balance: $10000.92)
2025-10-30 07:45:44,251 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4833/9953
2025-10-30 07:45:44,253 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107870.39
2025-10-30 07:45:44,254 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107870.39 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,254 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:44,260 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,275 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:44,276 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.07, Commission=$0.00, Net=$1.07 (cash flow: +$2001.07, -$0.00, balance: $10001.07)
2025-10-30 07:45:44,276 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6778/9953
2025-10-30 07:45:44,278 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109150.00
2025-10-30 07:45:44,279 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109150.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,280 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:44,284 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:44,284 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.03, Commission=$0.00, Net=$0.03 (cash flow: -$1999.97, balance: $10000.03)
2025-10-30 07:45:44,285 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3262/9953
2025-10-30 07:45:44,287 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108230.40
2025-10-30 07:45:44,288 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108230.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,288 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:44,290 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,292 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:44,292 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: +$2000.38, -$0.00, balance: $10000.38)
2025-10-30 07:45:44,293 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4901/9953
2025-10-30 07:45:44,296 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107771.40
2025-10-30 07:45:44,296 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107771.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,296 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:44,301 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,306 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:44,306 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.28, Commission=$0.00, Net=$1.28 (cash flow: +$2001.28, -$0.00, balance: $10001.28)
2025-10-30 07:45:44,307 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5639/9953
2025-10-30 07:45:44,309 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107871.44
2025-10-30 07:45:44,310 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107871.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,310 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:44,312 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,320 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:44,320 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.40, Commission=$0.00, Net=$1.40 (cash flow: +$2001.40, -$0.00, balance: $10001.40)
2025-10-30 07:45:44,321 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1562/9953
2025-10-30 07:45:44,325 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112000.00
2025-10-30 07:45:44,325 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,325 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:44,327 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,331 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:44,331 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: -$1999.07, balance: $10000.93)
2025-10-30 07:45:44,331 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7125/9953
2025-10-30 07:45:44,336 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109610.93
2025-10-30 07:45:44,337 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109610.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,337 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:44,340 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:44,340 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.29, Commission=$0.00, Net=$1.29 (cash flow: -$1998.71, balance: $10001.29)
2025-10-30 07:45:44,341 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2164/9953
2025-10-30 07:45:44,343 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112130.11
2025-10-30 07:45:44,344 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112130.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,344 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:44,347 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,352 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:44,352 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.59, Commission=$0.00, Net=$0.59 (cash flow: -$1999.41, balance: $10000.59)
2025-10-30 07:45:44,353 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6087/9953
2025-10-30 07:45:44,358 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107665.33
2025-10-30 07:45:44,358 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107665.33 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,358 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:44,360 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,364 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:44,364 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.10, Commission=$0.00, Net=$2.10 (cash flow: +$2002.10, -$0.00, balance: $10002.10)
2025-10-30 07:45:44,364 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8233/9953
2025-10-30 07:45:44,366 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111186.89
2025-10-30 07:45:44,366 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111186.89 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,367 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:44,372 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,373 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:44,374 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.22, Commission=$0.00, Net=$0.22 (cash flow: -$1999.78, balance: $10000.22)
2025-10-30 07:45:44,374 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 674/9953
2025-10-30 07:45:44,379 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112271.15
2025-10-30 07:45:44,379 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112271.15 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,379 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:44,382 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,386 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:44,387 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.28, Commission=$0.00, Net=$-0.28 (cash flow: -$2000.28, balance: $9999.72)
2025-10-30 07:45:44,388 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1546/9953
2025-10-30 07:45:44,392 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112275.59
2025-10-30 07:45:44,392 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112275.59 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,393 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:44,395 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,399 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:44,400 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.57, Commission=$0.00, Net=$0.57 (cash flow: -$1999.43, balance: $10000.57)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 8.76     |
|    ep_rew_mean        | -8.7e-07 |
| time/                 |          |
|    fps                | 398      |
|    iterations         | 2200     |
|    time_elapsed       | 27       |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -0.637   |
|    explained_variance | 0.092    |
|    learning_rate      | 0.0007   |
|    n_updates          | 2199     |
|    policy_loss        | -0.621   |
|    value_loss         | 0.74     |
------------------------------------

2025-10-30 07:45:44,948 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:44,948 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.64, Commission=$0.00, Net=$-1.64 (cash flow: -$2001.64, balance: $9998.36)
2025-10-30 07:45:44,949 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8837/9953
2025-10-30 07:45:44,952 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111290.99
2025-10-30 07:45:44,952 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111290.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,952 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:44,956 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,958 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:44,958 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.63, Commission=$0.00, Net=$-1.63 (cash flow: -$2001.63, balance: $9998.37)
2025-10-30 07:45:44,958 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 626/9953
2025-10-30 07:45:44,960 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111916.00
2025-10-30 07:45:44,961 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111916.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:44,961 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:44,964 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:44,967 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:44,967 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: -$2000.06, balance: $9999.94)
2025-10-30 07:45:44,968 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5572/9953
2025-10-30 07:45:44,975 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108319.56
2025-10-30 07:45:44,975 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108319.56 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:44,975 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:44,977 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,029 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:45,029 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-8.80, Commission=$0.00, Net=$-8.80 (cash flow: +$1991.20, -$0.00, balance: $9991.20)
2025-10-30 07:45:45,030 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2216/9953
2025-10-30 07:45:45,032 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111776.00
2025-10-30 07:45:45,033 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111776.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,033 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:45,035 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,039 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:45:45,039 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.61, Commission=$0.00, Net=$-0.61 (cash flow: -$2000.61, balance: $9999.39)
2025-10-30 07:45:45,040 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2381/9953
2025-10-30 07:45:45,042 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111111.10
2025-10-30 07:45:45,042 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111111.10 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,043 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:45,045 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,047 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:45,047 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.67, Commission=$0.00, Net=$1.67 (cash flow: -$1998.33, balance: $10001.67)
2025-10-30 07:45:45,048 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2222/9953
2025-10-30 07:45:45,050 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111735.82
2025-10-30 07:45:45,051 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111735.82 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,051 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:45,056 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,057 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 07:45:45,057 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.67, Commission=$0.00, Net=$0.67 (cash flow: +$2000.67, -$0.00, balance: $10000.67)
2025-10-30 07:45:45,058 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1509/9953
2025-10-30 07:45:45,060 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112910.53
2025-10-30 07:45:45,061 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112910.53 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,061 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:45,063 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,068 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:45,068 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.49, Commission=$0.00, Net=$2.49 (cash flow: -$1997.51, balance: $10002.49)
2025-10-30 07:45:45,069 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9194/9953
2025-10-30 07:45:45,071 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110229.99
2025-10-30 07:45:45,071 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110229.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,072 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:45,074 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,083 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:45,084 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.14, Commission=$0.00, Net=$1.14 (cash flow: +$2001.14, -$0.00, balance: $10001.14)
2025-10-30 07:45:45,084 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4319/9953
2025-10-30 07:45:45,086 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107926.92
2025-10-30 07:45:45,087 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107926.92 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,088 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:45,089 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,094 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:45,094 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.25, Commission=$0.00, Net=$0.25 (cash flow: +$2000.25, -$0.00, balance: $10000.25)
2025-10-30 07:45:45,095 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3351/9953
2025-10-30 07:45:45,096 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108675.54
2025-10-30 07:45:45,097 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108675.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,097 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:45,100 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,183 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:45,183 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-12.36, Commission=$0.00, Net=$-12.36 (cash flow: +$1987.64, -$0.00, balance: $9987.64)
2025-10-30 07:45:45,184 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9253/9953
2025-10-30 07:45:45,185 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110006.24
2025-10-30 07:45:45,186 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110006.24 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,187 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:45,189 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,191 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:45,191 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.11, Commission=$0.00, Net=$-1.11 (cash flow: +$1998.89, -$0.00, balance: $9998.89)
2025-10-30 07:45:45,192 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7674/9953
2025-10-30 07:45:45,197 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110939.15
2025-10-30 07:45:45,197 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110939.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,197 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:45,199 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:45,200 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.09, Commission=$0.00, Net=$2.09 (cash flow: +$2002.09, -$0.00, balance: $10002.09)
2025-10-30 07:45:45,201 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4459/9953
2025-10-30 07:45:45,203 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107957.43
2025-10-30 07:45:45,203 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107957.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,204 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:45,207 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,213 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:45,213 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.51, Commission=$0.00, Net=$3.51 (cash flow: +$2003.51, -$0.00, balance: $10003.51)
2025-10-30 07:45:45,214 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7569/9953
2025-10-30 07:45:45,218 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110841.03
2025-10-30 07:45:45,219 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110841.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,219 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:45,220 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,228 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:45,228 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.61, Commission=$0.00, Net=$-0.61 (cash flow: -$2000.61, balance: $9999.39)
2025-10-30 07:45:45,229 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1566/9953
2025-10-30 07:45:45,230 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111948.17
2025-10-30 07:45:45,231 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111948.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,232 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:45,234 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,243 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:45,244 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.88, Commission=$0.00, Net=$0.88 (cash flow: -$1999.12, balance: $10000.88)
2025-10-30 07:45:45,244 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6601/9953
2025-10-30 07:45:45,250 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110044.33
2025-10-30 07:45:45,250 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110044.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,250 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:45,252 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,256 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:45,256 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.63, Commission=$0.00, Net=$1.63 (cash flow: -$1998.37, balance: $10001.63)
2025-10-30 07:45:45,257 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2697/9953
2025-10-30 07:45:45,261 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108621.03
2025-10-30 07:45:45,262 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108621.03 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,262 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:45,265 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,277 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:45,277 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.94, Commission=$0.00, Net=$3.94 (cash flow: +$2003.94, -$0.00, balance: $10003.94)
2025-10-30 07:45:45,278 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5001/9953
2025-10-30 07:45:45,282 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108944.03
2025-10-30 07:45:45,282 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108944.03 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,283 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:45,285 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,300 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:45,300 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.03, Commission=$0.00, Net=$2.03 (cash flow: +$2002.03, -$0.00, balance: $10002.03)
2025-10-30 07:45:45,301 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1893/9953
2025-10-30 07:45:45,303 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112346.20
2025-10-30 07:45:45,303 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112346.20 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,304 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:45,308 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,316 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:45,316 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.21, Commission=$0.00, Net=$0.21 (cash flow: -$1999.79, balance: $10000.21)
2025-10-30 07:45:45,316 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5061/9953
2025-10-30 07:45:45,321 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109120.82
2025-10-30 07:45:45,321 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109120.82 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,322 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:45,323 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,380 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:45,380 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-20.21, Commission=$0.00, Net=$-20.21 (cash flow: +$1979.79, -$0.00, balance: $9979.79)
2025-10-30 07:45:45,381 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 563/9953
2025-10-30 07:45:45,385 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110990.00
2025-10-30 07:45:45,385 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110990.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,386 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:45,387 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,390 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:45:45,391 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.27, Commission=$0.00, Net=$-0.27 (cash flow: -$2000.27, balance: $9999.73)
2025-10-30 07:45:45,392 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1002/9953
2025-10-30 07:45:45,394 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113191.67
2025-10-30 07:45:45,394 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113191.67 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,395 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 11.2      |
|    ep_rew_mean        | -2.68e-05 |
| time/                 |           |
|    fps                | 406       |
|    iterations         | 2300      |
|    time_elapsed       | 28        |
|    total_timesteps    | 11500     |
| train/                |           |
|    entropy_loss       | -0.135    |
|    explained_variance | -0.0724   |
|    learning_rate      | 0.0007    |
|    n_updates          | 2299      |
|    policy_loss        | 0.00794   |
|    value_loss         | 0.245     |
-------------------------------------

2025-10-30 07:45:45,679 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:45,679 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.68, Commission=$0.00, Net=$2.68 (cash flow: +$2002.68, -$0.00, balance: $10002.68)
2025-10-30 07:45:45,680 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1541/9953
2025-10-30 07:45:45,682 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112542.33
2025-10-30 07:45:45,682 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112542.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,683 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:45,684 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:45,685 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.64, Commission=$0.00, Net=$1.64 (cash flow: -$1998.36, balance: $10001.64)
2025-10-30 07:45:45,686 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5765/9953
2025-10-30 07:45:45,690 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107246.72
2025-10-30 07:45:45,691 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107246.72 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,691 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:45,694 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,716 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:45,717 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.49, Commission=$0.00, Net=$2.49 (cash flow: +$2002.49, -$0.00, balance: $10002.49)
2025-10-30 07:45:45,718 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8293/9953
2025-10-30 07:45:45,721 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111184.58
2025-10-30 07:45:45,721 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111184.58 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,721 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:45,726 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,732 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:45,732 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.47, Commission=$0.00, Net=$0.47 (cash flow: -$1999.53, balance: $10000.47)
2025-10-30 07:45:45,733 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7602/9953
2025-10-30 07:45:45,735 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111037.68
2025-10-30 07:45:45,736 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111037.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,736 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:45,738 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,743 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:45,743 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.32, Commission=$0.00, Net=$-1.32 (cash flow: -$2001.32, balance: $9998.68)
2025-10-30 07:45:45,744 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 419/9953
2025-10-30 07:45:45,747 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110417.52
2025-10-30 07:45:45,748 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110417.52 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,748 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:45,752 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:45,753 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.04, Commission=$0.00, Net=$-1.04 (cash flow: -$2001.04, balance: $9998.96)
2025-10-30 07:45:45,753 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8610/9953
2025-10-30 07:45:45,757 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111139.46
2025-10-30 07:45:45,757 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111139.46 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,757 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:45,760 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:45,760 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.51, Commission=$0.00, Net=$-0.51 (cash flow: +$1999.49, -$0.00, balance: $9999.49)
2025-10-30 07:45:45,761 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1478/9953
2025-10-30 07:45:45,763 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112447.00
2025-10-30 07:45:45,763 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112447.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,764 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:45,768 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,776 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 07:45:45,776 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.81, Commission=$0.00, Net=$-6.81 (cash flow: -$2006.81, balance: $9993.19)
2025-10-30 07:45:45,776 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6507/9953
2025-10-30 07:45:45,779 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109941.81
2025-10-30 07:45:45,779 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109941.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,780 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:45,785 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,787 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:45,788 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.85, Commission=$0.00, Net=$-2.85 (cash flow: -$2002.85, balance: $9997.15)
2025-10-30 07:45:45,788 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3018/9953
2025-10-30 07:45:45,790 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108349.42
2025-10-30 07:45:45,791 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108349.42 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,791 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:45,796 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,799 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:45,799 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.75, Commission=$0.00, Net=$2.75 (cash flow: +$2002.75, -$0.00, balance: $10002.75)
2025-10-30 07:45:45,800 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7678/9953
2025-10-30 07:45:45,804 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111083.36
2025-10-30 07:45:45,804 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111083.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,804 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:45,806 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,810 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:45,810 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.53, Commission=$0.00, Net=$2.53 (cash flow: -$1997.47, balance: $10002.53)
2025-10-30 07:45:45,811 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6301/9953
2025-10-30 07:45:45,815 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108618.00
2025-10-30 07:45:45,815 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108618.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,815 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:45,818 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,820 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:45,820 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.31, Commission=$0.00, Net=$0.31 (cash flow: +$2000.31, -$0.00, balance: $10000.31)
2025-10-30 07:45:45,821 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2993/9953
2025-10-30 07:45:45,823 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108494.40
2025-10-30 07:45:45,823 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108494.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,824 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:45,826 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,836 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:45,836 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.54, Commission=$0.00, Net=$1.54 (cash flow: +$2001.54, -$0.00, balance: $10001.54)
2025-10-30 07:45:45,837 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8073/9953
2025-10-30 07:45:45,839 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110607.07
2025-10-30 07:45:45,839 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110607.07 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,840 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:45,844 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,847 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:45,847 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.04, Commission=$0.00, Net=$-1.04 (cash flow: +$1998.96, -$0.00, balance: $9998.96)
2025-10-30 07:45:45,848 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5245/9953
2025-10-30 07:45:45,849 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108268.46
2025-10-30 07:45:45,850 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108268.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,850 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:45,852 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,856 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:45,857 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.73, Commission=$0.00, Net=$1.73 (cash flow: -$1998.27, balance: $10001.73)
2025-10-30 07:45:45,858 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5873/9953
2025-10-30 07:45:45,860 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=106883.05
2025-10-30 07:45:45,860 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $106883.05 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,861 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:45,862 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,877 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:45,878 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.89, Commission=$0.00, Net=$2.89 (cash flow: +$2002.89, -$0.00, balance: $10002.89)
2025-10-30 07:45:45,879 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6256/9953
2025-10-30 07:45:45,880 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108375.71
2025-10-30 07:45:45,880 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108375.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,881 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:45,886 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,888 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:45,889 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.01, Commission=$0.00, Net=$-0.01 (cash flow: +$1999.99, -$0.00, balance: $9999.99)
2025-10-30 07:45:45,889 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6205/9953
2025-10-30 07:45:45,892 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108171.78
2025-10-30 07:45:45,892 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108171.78 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,892 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:45,898 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,909 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:45,910 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.09, Commission=$0.00, Net=$-0.09 (cash flow: +$1999.91, -$0.00, balance: $9999.91)
2025-10-30 07:45:45,910 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4503/9953
2025-10-30 07:45:45,912 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107964.01
2025-10-30 07:45:45,913 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107964.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,914 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:45,915 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,918 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:45:45,918 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.13, Commission=$0.00, Net=$-2.13 (cash flow: -$2002.13, balance: $9997.87)
2025-10-30 07:45:45,919 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9468/9953
2025-10-30 07:45:45,923 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110764.98
2025-10-30 07:45:45,924 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110764.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:45,924 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:45,926 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,934 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:45,934 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.51, Commission=$0.00, Net=$-4.51 (cash flow: -$2004.51, balance: $9995.49)
2025-10-30 07:45:45,935 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2629/9953
2025-10-30 07:45:45,939 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110039.01
2025-10-30 07:45:45,939 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110039.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,939 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:45,941 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,943 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:45,944 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.21, Commission=$0.00, Net=$0.21 (cash flow: +$2000.21, -$0.00, balance: $10000.21)
2025-10-30 07:45:45,944 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1900/9953
2025-10-30 07:45:45,946 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112319.83
2025-10-30 07:45:45,947 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112319.83 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,947 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:45,950 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 07:45:45,950 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.08, Commission=$0.00, Net=$-0.08 (cash flow: +$1999.92, -$0.00, balance: $9999.92)
2025-10-30 07:45:45,951 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4629/9953
2025-10-30 07:45:45,955 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108662.10
2025-10-30 07:45:45,955 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108662.10 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:45,956 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:45,957 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:45,965 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:45,965 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.11, Commission=$0.00, Net=$5.11 (cash flow: +$2005.11, -$0.00, balance: $10005.11)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 13.4     |
|    ep_rew_mean        | -2.8e-05 |
| time/                 |          |
|    fps                | 415      |
|    iterations         | 2400     |
|    time_elapsed       | 28       |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -0.158   |
|    explained_variance | 0.449    |
|    learning_rate      | 0.0007   |
|    n_updates          | 2399     |
|    policy_loss        | -0.0574  |
|    value_loss         | 0.821    |
------------------------------------

2025-10-30 07:45:46,299 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:46,300 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.11, Commission=$0.00, Net=$0.11 (cash flow: +$2000.11, -$0.00, balance: $10000.11)
2025-10-30 07:45:46,300 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8452/9953
2025-10-30 07:45:46,302 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110881.55
2025-10-30 07:45:46,302 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110881.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,303 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:46,308 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:46,308 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.51, Commission=$0.00, Net=$0.51 (cash flow: +$2000.51, -$0.00, balance: $10000.51)
2025-10-30 07:45:46,308 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8486/9953
2025-10-30 07:45:46,310 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110816.17
2025-10-30 07:45:46,311 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110816.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,311 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:46,313 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,315 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:46,316 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.68, Commission=$0.00, Net=$1.68 (cash flow: +$2001.68, -$0.00, balance: $10001.68)
2025-10-30 07:45:46,316 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5210/9953
2025-10-30 07:45:46,319 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108482.61
2025-10-30 07:45:46,320 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108482.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,320 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:46,324 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,336 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:46,336 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.44, Commission=$0.00, Net=$2.44 (cash flow: +$2002.44, -$0.00, balance: $10002.44)
2025-10-30 07:45:46,337 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6189/9953
2025-10-30 07:45:46,341 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108188.76
2025-10-30 07:45:46,341 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108188.76 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,341 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:46,344 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,347 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:46,347 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.39, Commission=$0.00, Net=$1.39 (cash flow: +$2001.39, -$0.00, balance: $10001.39)
2025-10-30 07:45:46,348 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6555/9953
2025-10-30 07:45:46,351 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110126.00
2025-10-30 07:45:46,352 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110126.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,352 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:46,354 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,357 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:46,358 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.80, Commission=$0.00, Net=$2.80 (cash flow: +$2002.80, -$0.00, balance: $10002.80)
2025-10-30 07:45:46,358 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 184/9953
2025-10-30 07:45:46,364 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108850.00
2025-10-30 07:45:46,364 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108850.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,364 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:46,365 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,487 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:46,487 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.43, Commission=$0.00, Net=$1.43 (cash flow: +$2001.43, -$0.00, balance: $10001.43)
2025-10-30 07:45:46,488 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1181/9953
2025-10-30 07:45:46,492 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113273.21
2025-10-30 07:45:46,492 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113273.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,492 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:46,494 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,500 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:46,500 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.46, Commission=$0.00, Net=$2.46 (cash flow: -$1997.54, balance: $10002.46)
2025-10-30 07:45:46,501 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3544/9953
2025-10-30 07:45:46,504 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108471.34
2025-10-30 07:45:46,504 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108471.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,504 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:46,506 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,511 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 07:45:46,512 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.30, Commission=$0.00, Net=$-1.30 (cash flow: -$2001.30, balance: $9998.70)
2025-10-30 07:45:46,512 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8261/9953
2025-10-30 07:45:46,515 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111201.15
2025-10-30 07:45:46,515 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111201.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,515 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:46,517 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,519 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:46,519 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.26, Commission=$0.00, Net=$-1.26 (cash flow: +$1998.74, -$0.00, balance: $9998.74)
2025-10-30 07:45:46,520 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 796/9953
2025-10-30 07:45:46,525 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112680.53
2025-10-30 07:45:46,526 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112680.53 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,526 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:46,529 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:46,529 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.66, Commission=$0.00, Net=$0.66 (cash flow: -$1999.34, balance: $10000.66)
2025-10-30 07:45:46,530 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3721/9953
2025-10-30 07:45:46,532 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107926.88
2025-10-30 07:45:46,533 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107926.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,533 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:46,537 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,541 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:46,541 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.35, Commission=$0.00, Net=$0.35 (cash flow: +$2000.35, -$0.00, balance: $10000.35)
2025-10-30 07:45:46,542 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6948/9953
2025-10-30 07:45:46,544 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108805.74
2025-10-30 07:45:46,545 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108805.74 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,545 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:46,546 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,551 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:46,551 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.55, Commission=$0.00, Net=$3.55 (cash flow: +$2003.55, -$0.00, balance: $10003.55)
2025-10-30 07:45:46,552 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8702/9953
2025-10-30 07:45:46,556 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111589.77
2025-10-30 07:45:46,556 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111589.77 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,557 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:46,561 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:46,561 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.29, Commission=$0.00, Net=$-2.29 (cash flow: -$2002.29, balance: $9997.71)
2025-10-30 07:45:46,562 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9093/9953
2025-10-30 07:45:46,564 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110071.27
2025-10-30 07:45:46,564 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110071.27 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,565 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:46,567 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,576 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:46,577 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.39, Commission=$0.00, Net=$-0.39 (cash flow: +$1999.61, -$0.00, balance: $9999.61)
2025-10-30 07:45:46,577 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5634/9953
2025-10-30 07:45:46,580 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107843.08
2025-10-30 07:45:46,580 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107843.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,580 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:46,583 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,585 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:46,585 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.97, Commission=$0.00, Net=$1.97 (cash flow: -$1998.03, balance: $10001.97)
2025-10-30 07:45:46,586 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9753/9953
2025-10-30 07:45:46,590 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111319.00
2025-10-30 07:45:46,591 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111319.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,591 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:46,593 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,596 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:46,596 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: -$1999.62, balance: $10000.38)
2025-10-30 07:45:46,597 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2419/9953
2025-10-30 07:45:46,601 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110886.66
2025-10-30 07:45:46,602 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110886.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,602 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:46,604 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,606 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 07:45:46,606 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.94, Commission=$0.00, Net=$-0.94 (cash flow: +$1999.06, -$0.00, balance: $9999.06)
2025-10-30 07:45:46,607 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2954/9953
2025-10-30 07:45:46,611 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108239.97
2025-10-30 07:45:46,612 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108239.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,612 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:46,615 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,617 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:46,617 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.89, Commission=$0.00, Net=$-0.89 (cash flow: +$1999.11, -$0.00, balance: $9999.11)
2025-10-30 07:45:46,618 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1898/9953
2025-10-30 07:45:46,623 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112350.17
2025-10-30 07:45:46,623 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112350.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,623 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:46,625 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:46,626 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.54, Commission=$0.00, Net=$0.54 (cash flow: -$1999.46, balance: $10000.54)
2025-10-30 07:45:46,627 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1131/9953
2025-10-30 07:45:46,629 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113317.48
2025-10-30 07:45:46,630 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113317.48 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,630 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:46,633 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,639 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:46,639 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.47, Commission=$0.00, Net=$1.47 (cash flow: -$1998.53, balance: $10001.47)
2025-10-30 07:45:46,640 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 992/9953
2025-10-30 07:45:46,643 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113225.15
2025-10-30 07:45:46,643 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113225.15 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,643 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:46,648 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,654 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:46,655 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.02, Commission=$0.00, Net=$1.02 (cash flow: -$1998.98, balance: $10001.02)
2025-10-30 07:45:46,656 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3294/9953
2025-10-30 07:45:46,658 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108032.41
2025-10-30 07:45:46,659 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108032.41 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,659 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:46,662 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,669 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:46,669 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.13, Commission=$0.00, Net=$3.13 (cash flow: +$2003.13, -$0.00, balance: $10003.13)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 14.3     |
|    ep_rew_mean        | 2.96e-05 |
| time/                 |          |
|    fps                | 422      |
|    iterations         | 2500     |
|    time_elapsed       | 29       |
|    total_timesteps    | 12500    |
| train/                |          |
|    entropy_loss       | -0.669   |
|    explained_variance | -1.03    |
|    learning_rate      | 0.0007   |
|    n_updates          | 2499     |
|    policy_loss        | -0.122   |
|    value_loss         | 0.0975   |
------------------------------------

2025-10-30 07:45:46,926 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:46,926 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: -$1999.62, balance: $10000.38)
2025-10-30 07:45:46,927 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6254/9953
2025-10-30 07:45:46,931 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108375.71
2025-10-30 07:45:46,931 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108375.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,932 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:46,933 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,938 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:46,939 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.23, Commission=$0.00, Net=$0.23 (cash flow: +$2000.23, -$0.00, balance: $10000.23)
2025-10-30 07:45:46,939 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6449/9953
2025-10-30 07:45:46,942 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109461.27
2025-10-30 07:45:46,942 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109461.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,942 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:46,944 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,946 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:46,946 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.62, Commission=$0.00, Net=$-1.62 (cash flow: -$2001.62, balance: $9998.38)
2025-10-30 07:45:46,947 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5961/9953
2025-10-30 07:45:46,951 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107065.34
2025-10-30 07:45:46,951 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107065.34 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,952 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:46,953 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,973 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:46,974 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.02, Commission=$0.00, Net=$4.02 (cash flow: +$2004.02, -$0.00, balance: $10004.02)
2025-10-30 07:45:46,974 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7282/9953
2025-10-30 07:45:46,979 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109370.21
2025-10-30 07:45:46,979 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109370.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,979 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:46,982 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,983 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:46,984 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.82, Commission=$0.00, Net=$-3.82 (cash flow: -$2003.82, balance: $9996.18)
2025-10-30 07:45:46,985 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7582/9953
2025-10-30 07:45:46,988 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110862.56
2025-10-30 07:45:46,988 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110862.56 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:46,989 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:46,993 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:46,994 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:46,995 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.76, Commission=$0.00, Net=$1.76 (cash flow: +$2001.76, -$0.00, balance: $10001.76)
2025-10-30 07:45:46,996 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7440/9953
2025-10-30 07:45:46,998 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109759.99
2025-10-30 07:45:46,999 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109759.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:46,999 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:47,001 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:47,001 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.43, Commission=$0.00, Net=$-0.43 (cash flow: -$2000.43, balance: $9999.57)
2025-10-30 07:45:47,002 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3890/9953
2025-10-30 07:45:47,005 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108167.16
2025-10-30 07:45:47,005 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108167.16 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,006 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:47,011 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,023 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:47,023 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.13, Commission=$0.00, Net=$0.13 (cash flow: +$2000.13, -$0.00, balance: $10000.13)
2025-10-30 07:45:47,024 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8097/9953
2025-10-30 07:45:47,029 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110489.23
2025-10-30 07:45:47,029 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110489.23 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,029 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:47,033 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,034 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:47,034 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.91, Commission=$0.00, Net=$1.91 (cash flow: +$2001.91, -$0.00, balance: $10001.91)
2025-10-30 07:45:47,035 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 440/9953
2025-10-30 07:45:47,038 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110393.67
2025-10-30 07:45:47,038 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110393.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,039 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:47,041 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,047 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:47,047 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.86, Commission=$0.00, Net=$-0.86 (cash flow: +$1999.14, -$0.00, balance: $9999.14)
2025-10-30 07:45:47,048 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5779/9953
2025-10-30 07:45:47,050 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107119.99
2025-10-30 07:45:47,051 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107119.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,051 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:47,054 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,064 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:47,065 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.88, Commission=$0.00, Net=$3.88 (cash flow: +$2003.88, -$0.00, balance: $10003.88)
2025-10-30 07:45:47,066 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7575/9953
2025-10-30 07:45:47,068 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110838.00
2025-10-30 07:45:47,069 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110838.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,069 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:47,072 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:47,073 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.67, Commission=$0.00, Net=$-0.67 (cash flow: -$2000.67, balance: $9999.33)
2025-10-30 07:45:47,073 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1962/9953
2025-10-30 07:45:47,078 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112215.84
2025-10-30 07:45:47,078 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112215.84 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,078 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:47,081 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,084 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:47,084 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.46, Commission=$0.00, Net=$0.46 (cash flow: -$1999.54, balance: $10000.46)
2025-10-30 07:45:47,085 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9785/9953
2025-10-30 07:45:47,088 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111250.08
2025-10-30 07:45:47,089 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111250.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,089 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:47,094 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:47,094 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.54, Commission=$0.00, Net=$-1.54 (cash flow: -$2001.54, balance: $9998.46)
2025-10-30 07:45:47,095 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2651/9953
2025-10-30 07:45:47,097 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109626.72
2025-10-30 07:45:47,098 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109626.72 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,098 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:47,101 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,103 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:47,103 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.98, Commission=$0.00, Net=$0.98 (cash flow: +$2000.98, -$0.00, balance: $10000.98)
2025-10-30 07:45:47,104 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7798/9953
2025-10-30 07:45:47,109 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109863.60
2025-10-30 07:45:47,110 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109863.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,110 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:47,111 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:47,112 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.48, Commission=$0.00, Net=$2.48 (cash flow: +$2002.48, -$0.00, balance: $10002.48)
2025-10-30 07:45:47,114 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6515/9953
2025-10-30 07:45:47,115 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110174.60
2025-10-30 07:45:47,116 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110174.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,116 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:47,120 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,121 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:47,121 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.99, Commission=$0.00, Net=$1.99 (cash flow: -$1998.01, balance: $10001.99)
2025-10-30 07:45:47,122 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1276/9953
2025-10-30 07:45:47,127 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113789.64
2025-10-30 07:45:47,127 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113789.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,128 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:47,130 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,132 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:47,132 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: -$1999.15, balance: $10000.85)
2025-10-30 07:45:47,134 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3339/9953
2025-10-30 07:45:47,136 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108359.85
2025-10-30 07:45:47,137 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108359.85 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,137 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:47,138 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,148 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:47,149 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.65, Commission=$0.00, Net=$3.65 (cash flow: +$2003.65, -$0.00, balance: $10003.65)
2025-10-30 07:45:47,149 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 348/9953
2025-10-30 07:45:47,155 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109450.00
2025-10-30 07:45:47,155 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109450.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,155 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:47,158 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,160 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:47,160 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.23, Commission=$0.00, Net=$-2.23 (cash flow: -$2002.23, balance: $9997.77)
2025-10-30 07:45:47,161 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 80/9953
2025-10-30 07:45:47,162 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109258.00
2025-10-30 07:45:47,163 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109258.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,164 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:47,169 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:47,169 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.70, Commission=$0.00, Net=$0.70 (cash flow: +$2000.70, -$0.00, balance: $10000.70)
2025-10-30 07:45:47,170 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3217/9953
2025-10-30 07:45:47,172 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108322.99
2025-10-30 07:45:47,173 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108322.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,173 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:47,176 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,179 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:47,179 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.92, Commission=$0.00, Net=$-0.92 (cash flow: -$2000.92, balance: $9999.08)
2025-10-30 07:45:47,180 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3744/9953
2025-10-30 07:45:47,185 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108065.54
2025-10-30 07:45:47,185 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108065.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,185 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:47,188 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,191 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:47,192 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.41, Commission=$0.00, Net=$1.41 (cash flow: +$2001.41, -$0.00, balance: $10001.41)
2025-10-30 07:45:47,192 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5486/9953

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 12.7     |
|    ep_rew_mean        | 7.77e-05 |
| time/                 |          |
|    fps                | 427      |
|    iterations         | 2600     |
|    time_elapsed       | 30       |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -0.134   |
|    explained_variance | -0.702   |
|    learning_rate      | 0.0007   |
|    n_updates          | 2599     |
|    policy_loss        | 0.0976   |
|    value_loss         | 0.239    |
------------------------------------

2025-10-30 07:45:47,717 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:47,717 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.72, Commission=$0.00, Net=$4.72 (cash flow: +$2004.72, -$0.00, balance: $10004.72)
2025-10-30 07:45:47,718 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3944/9953
2025-10-30 07:45:47,720 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108080.00
2025-10-30 07:45:47,721 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108080.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,721 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:47,723 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,732 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:47,732 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.30, Commission=$0.00, Net=$3.30 (cash flow: +$2003.30, -$0.00, balance: $10003.30)
2025-10-30 07:45:47,733 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6028/9953
2025-10-30 07:45:47,735 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107626.20
2025-10-30 07:45:47,736 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107626.20 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,736 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:47,739 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,748 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:47,749 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.11, Commission=$0.00, Net=$5.11 (cash flow: +$2005.11, -$0.00, balance: $10005.11)
2025-10-30 07:45:47,749 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7306/9953
2025-10-30 07:45:47,752 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109980.00
2025-10-30 07:45:47,752 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109980.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,753 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:47,755 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,783 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:47,783 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-5.09, Commission=$0.00, Net=$-5.09 (cash flow: +$1994.91, -$0.00, balance: $9994.91)
2025-10-30 07:45:47,784 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7083/9953
2025-10-30 07:45:47,788 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109278.61
2025-10-30 07:45:47,789 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109278.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,789 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:47,791 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,798 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:47,798 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.77, Commission=$0.00, Net=$2.77 (cash flow: +$2002.77, -$0.00, balance: $10002.77)
2025-10-30 07:45:47,798 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8473/9953
2025-10-30 07:45:47,803 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110991.34
2025-10-30 07:45:47,803 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110991.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,804 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:47,806 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,808 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:47,809 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.83, Commission=$0.00, Net=$1.83 (cash flow: -$1998.17, balance: $10001.83)
2025-10-30 07:45:47,810 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3642/9953
2025-10-30 07:45:47,812 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108326.55
2025-10-30 07:45:47,812 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108326.55 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,812 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:47,817 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,820 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:47,821 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.89, Commission=$0.00, Net=$1.89 (cash flow: -$1998.11, balance: $10001.89)
2025-10-30 07:45:47,821 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2088/9953
2025-10-30 07:45:47,826 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112075.52
2025-10-30 07:45:47,826 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112075.52 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:47,826 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:47,829 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:47,840 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:47,840 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.46, Commission=$0.00, Net=$3.46 (cash flow: -$1996.54, balance: $10003.46)
2025-10-30 07:45:47,841 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4681/9953
2025-10-30 07:45:47,843 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108505.88
2025-10-30 07:45:47,843 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108505.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:47,844 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:47,849 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,055 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:48,055 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-8.25, Commission=$0.00, Net=$-8.25 (cash flow: +$1991.75, -$0.00, balance: $9991.75)
2025-10-30 07:45:48,056 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8502/9953
2025-10-30 07:45:48,058 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111172.70
2025-10-30 07:45:48,058 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111172.70 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,059 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:48,061 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,066 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:48,067 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.21, Commission=$0.00, Net=$1.21 (cash flow: -$1998.79, balance: $10001.21)
2025-10-30 07:45:48,067 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7104/9953
2025-10-30 07:45:48,069 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109499.98
2025-10-30 07:45:48,069 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109499.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,070 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:48,073 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:48,073 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.26, Commission=$0.00, Net=$0.26 (cash flow: -$1999.74, balance: $10000.26)
2025-10-30 07:45:48,074 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1032/9953
2025-10-30 07:45:48,079 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112750.81
2025-10-30 07:45:48,079 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112750.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,079 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:48,081 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,107 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 07:45:48,107 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-9.39, Commission=$0.00, Net=$-9.39 (cash flow: -$2009.39, balance: $9990.61)
2025-10-30 07:45:48,108 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3069/9953
2025-10-30 07:45:48,110 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108289.42
2025-10-30 07:45:48,110 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108289.42 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,111 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:48,113 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 12.9      |
|    ep_rew_mean        | 7.43e-05  |
| time/                 |           |
|    fps                | 437       |
|    iterations         | 2700      |
|    time_elapsed       | 30        |
|    total_timesteps    | 13500     |
| train/                |           |
|    entropy_loss       | -0.0158   |
|    explained_variance | 0.387     |
|    learning_rate      | 0.0007    |
|    n_updates          | 2699      |
|    policy_loss        | -0.000524 |
|    value_loss         | 0.0836    |
-------------------------------------

2025-10-30 07:45:48,238 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:48,238 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.27, Commission=$0.00, Net=$1.27 (cash flow: +$2001.27, -$0.00, balance: $10001.27)
2025-10-30 07:45:48,239 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7181/9953
2025-10-30 07:45:48,241 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109098.01
2025-10-30 07:45:48,242 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109098.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,242 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:48,245 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:48,245 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.64, Commission=$0.00, Net=$1.64 (cash flow: +$2001.64, -$0.00, balance: $10001.64)
2025-10-30 07:45:48,246 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6038/9953
2025-10-30 07:45:48,251 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107798.36
2025-10-30 07:45:48,252 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107798.36 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,252 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:48,255 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,328 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:48,328 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.14, Commission=$0.00, Net=$-0.14 (cash flow: +$1999.86, -$0.00, balance: $9999.86)
2025-10-30 07:45:48,329 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7590/9953
2025-10-30 07:45:48,333 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110793.44
2025-10-30 07:45:48,334 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110793.44 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,334 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:48,338 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,340 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:48,340 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.57, Commission=$0.00, Net=$-0.57 (cash flow: -$2000.57, balance: $9999.43)
2025-10-30 07:45:48,341 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7200/9953
2025-10-30 07:45:48,343 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108881.07
2025-10-30 07:45:48,345 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108881.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,345 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:48,348 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:48,348 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.23, Commission=$0.00, Net=$-0.23 (cash flow: -$2000.23, balance: $9999.77)
2025-10-30 07:45:48,349 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5230/9953
2025-10-30 07:45:48,354 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108595.99
2025-10-30 07:45:48,354 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108595.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,354 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:48,357 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,363 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:48,363 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.25, Commission=$0.00, Net=$-1.25 (cash flow: +$1998.75, -$0.00, balance: $9998.75)
2025-10-30 07:45:48,364 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8036/9953
2025-10-30 07:45:48,368 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110510.00
2025-10-30 07:45:48,368 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110510.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,368 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:48,371 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:48,372 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.09, Commission=$0.00, Net=$-0.09 (cash flow: -$2000.09, balance: $9999.91)
2025-10-30 07:45:48,373 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8028/9953
2025-10-30 07:45:48,376 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110677.55
2025-10-30 07:45:48,376 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110677.55 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,377 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:48,382 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,383 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:48,383 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.13, Commission=$0.00, Net=$1.13 (cash flow: -$1998.87, balance: $10001.13)
2025-10-30 07:45:48,385 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9941/9953
2025-10-30 07:45:48,388 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111724.26
2025-10-30 07:45:48,388 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111724.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,389 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:48,392 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,393 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:48,393 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.44, Commission=$0.00, Net=$-0.44 (cash flow: -$2000.44, balance: $9999.56)
2025-10-30 07:45:48,395 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3365/9953
2025-10-30 07:45:48,400 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108540.00
2025-10-30 07:45:48,400 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108540.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,400 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:48,403 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,697 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:48,698 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-11.19, Commission=$0.00, Net=$-11.19 (cash flow: +$1988.81, -$0.00, balance: $9988.81)
2025-10-30 07:45:48,698 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3625/9953
2025-10-30 07:45:48,700 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108400.00
2025-10-30 07:45:48,700 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108400.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,701 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:48,704 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 16.8     |
|    ep_rew_mean        | 5.37e-05 |
| time/                 |          |
|    fps                | 445      |
|    iterations         | 2800     |
|    time_elapsed       | 31       |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -0.102   |
|    explained_variance | -0.491   |
|    learning_rate      | 0.0007   |
|    n_updates          | 2799     |
|    policy_loss        | 0.00798  |
|    value_loss         | 0.153    |
------------------------------------

2025-10-30 07:45:48,919 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:48,920 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-7.38, Commission=$0.00, Net=$-7.38 (cash flow: +$1992.62, -$0.00, balance: $9992.62)
2025-10-30 07:45:48,921 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 527/9953
2025-10-30 07:45:48,923 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110239.99
2025-10-30 07:45:48,924 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110239.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,924 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:48,929 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,931 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:48,931 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.37, Commission=$0.00, Net=$2.37 (cash flow: +$2002.37, -$0.00, balance: $10002.37)
2025-10-30 07:45:48,932 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7270/9953
2025-10-30 07:45:48,933 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109551.65
2025-10-30 07:45:48,934 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109551.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,934 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:48,937 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:48,937 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.63, Commission=$0.00, Net=$0.63 (cash flow: -$1999.37, balance: $10000.63)
2025-10-30 07:45:48,938 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9600/9953
2025-10-30 07:45:48,943 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111039.01
2025-10-30 07:45:48,944 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111039.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:48,944 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:48,946 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,948 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:48,949 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.65, Commission=$0.00, Net=$-0.65 (cash flow: -$2000.65, balance: $9999.35)
2025-10-30 07:45:48,949 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8226/9953
2025-10-30 07:45:48,951 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111159.98
2025-10-30 07:45:48,951 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111159.98 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,952 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:48,957 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,959 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:48,959 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.90, Commission=$0.00, Net=$-0.90 (cash flow: +$1999.10, -$0.00, balance: $9999.10)
2025-10-30 07:45:48,960 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4545/9953
2025-10-30 07:45:48,963 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108302.65
2025-10-30 07:45:48,963 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108302.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,963 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:48,965 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:48,974 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:48,974 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.67, Commission=$0.00, Net=$2.67 (cash flow: +$2002.67, -$0.00, balance: $10002.67)
2025-10-30 07:45:48,975 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6091/9953
2025-10-30 07:45:48,977 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107778.48
2025-10-30 07:45:48,977 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107778.48 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:48,978 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:48,981 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,004 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:49,004 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.97, Commission=$0.00, Net=$3.97 (cash flow: +$2003.97, -$0.00, balance: $10003.97)
2025-10-30 07:45:49,005 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5737/9953
2025-10-30 07:45:49,009 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107652.00
2025-10-30 07:45:49,009 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107652.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,009 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:49,011 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,021 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:49,021 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.25, Commission=$0.00, Net=$0.25 (cash flow: +$2000.25, -$0.00, balance: $10000.25)
2025-10-30 07:45:49,022 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6461/9953
2025-10-30 07:45:49,024 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109737.50
2025-10-30 07:45:49,025 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109737.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,025 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:49,027 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:49,027 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.92, Commission=$0.00, Net=$1.92 (cash flow: -$1998.08, balance: $10001.92)
2025-10-30 07:45:49,028 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5638/9953
2025-10-30 07:45:49,033 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107731.68
2025-10-30 07:45:49,033 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107731.68 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,033 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:49,036 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,046 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:49,046 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.66, Commission=$0.00, Net=$5.66 (cash flow: +$2005.66, -$0.00, balance: $10005.66)
2025-10-30 07:45:49,047 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2384/9953
2025-10-30 07:45:49,049 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111000.00
2025-10-30 07:45:49,049 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,050 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:49,051 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,054 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:49,055 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.97, Commission=$0.00, Net=$1.97 (cash flow: -$1998.03, balance: $10001.97)
2025-10-30 07:45:49,056 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1351/9953
2025-10-30 07:45:49,060 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113413.64
2025-10-30 07:45:49,061 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113413.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,061 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:49,062 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,065 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:49,066 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.30, Commission=$0.00, Net=$-0.30 (cash flow: -$2000.30, balance: $9999.70)
2025-10-30 07:45:49,066 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6248/9953
2025-10-30 07:45:49,069 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108253.73
2025-10-30 07:45:49,069 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108253.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,070 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:49,074 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,083 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:49,083 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.48, Commission=$0.00, Net=$2.48 (cash flow: +$2002.48, -$0.00, balance: $10002.48)
2025-10-30 07:45:49,084 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3513/9953
2025-10-30 07:45:49,087 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108103.03
2025-10-30 07:45:49,088 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108103.03 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,088 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:49,091 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,108 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:49,109 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.68, Commission=$0.00, Net=$3.68 (cash flow: +$2003.68, -$0.00, balance: $10003.68)
2025-10-30 07:45:49,109 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 339/9953
2025-10-30 07:45:49,111 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109091.32
2025-10-30 07:45:49,112 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109091.32 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,112 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:49,114 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,118 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:49,119 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.70, Commission=$0.00, Net=$1.70 (cash flow: +$2001.70, -$0.00, balance: $10001.70)
2025-10-30 07:45:49,119 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6901/9953
2025-10-30 07:45:49,121 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109324.07
2025-10-30 07:45:49,122 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109324.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,122 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:49,125 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,127 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:49,127 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.44, Commission=$0.00, Net=$0.44 (cash flow: -$1999.56, balance: $10000.44)
2025-10-30 07:45:49,127 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3289/9953
2025-10-30 07:45:49,129 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108101.99
2025-10-30 07:45:49,130 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108101.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,131 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:49,135 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:49,135 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.82, Commission=$0.00, Net=$0.82 (cash flow: -$1999.18, balance: $10000.82)
2025-10-30 07:45:49,136 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4129/9953
2025-10-30 07:45:49,139 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107402.50
2025-10-30 07:45:49,139 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107402.50 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,139 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:49,142 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,225 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:49,225 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.63, Commission=$0.00, Net=$5.63 (cash flow: +$2005.63, -$0.00, balance: $10005.63)
2025-10-30 07:45:49,225 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 991/9953
2025-10-30 07:45:49,228 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113274.67
2025-10-30 07:45:49,229 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113274.67 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,229 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:49,232 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,233 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:49,233 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.44, Commission=$0.00, Net=$0.44 (cash flow: -$1999.56, balance: $10000.44)
2025-10-30 07:45:49,234 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1183/9953
2025-10-30 07:45:49,239 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113211.94
2025-10-30 07:45:49,239 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113211.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,239 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:49,242 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,244 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:49,244 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.37, Commission=$0.00, Net=$-0.37 (cash flow: -$2000.37, balance: $9999.63)
2025-10-30 07:45:49,244 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7096/9953
2025-10-30 07:45:49,251 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109389.72
2025-10-30 07:45:49,251 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109389.72 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,251 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:49,254 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:49,254 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.01, Commission=$0.00, Net=$-0.01 (cash flow: -$2000.01, balance: $9999.99)
2025-10-30 07:45:49,256 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3120/9953
2025-10-30 07:45:49,258 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108107.19
2025-10-30 07:45:49,259 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108107.19 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,259 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:49,262 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 20.3     |
|    ep_rew_mean        | 6.57e-05 |
| time/                 |          |
|    fps                | 453      |
|    iterations         | 2900     |
|    time_elapsed       | 31       |
|    total_timesteps    | 14500    |
| train/                |          |
|    entropy_loss       | -0.0126  |
|    explained_variance | -0.0447  |
|    learning_rate      | 0.0007   |
|    n_updates          | 2899     |
|    policy_loss        | 0.000812 |
|    value_loss         | 0.265    |
------------------------------------

2025-10-30 07:45:49,341 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:49,341 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.89, Commission=$0.00, Net=$4.89 (cash flow: +$2004.89, -$0.00, balance: $10004.89)
2025-10-30 07:45:49,342 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7179/9953
2025-10-30 07:45:49,345 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109081.50
2025-10-30 07:45:49,345 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109081.50 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,346 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:49,349 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,395 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:49,395 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.02, Commission=$0.00, Net=$3.02 (cash flow: +$2003.02, -$0.00, balance: $10003.02)
2025-10-30 07:45:49,396 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9104/9953
2025-10-30 07:45:49,398 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110035.33
2025-10-30 07:45:49,399 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110035.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,399 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:49,401 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,403 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:49,403 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.49, Commission=$0.00, Net=$0.49 (cash flow: -$1999.51, balance: $10000.49)
2025-10-30 07:45:49,404 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4483/9953
2025-10-30 07:45:49,409 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108285.43
2025-10-30 07:45:49,410 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108285.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,411 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:49,413 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,472 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:49,472 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: +$2000.85, -$0.00, balance: $10000.85)
2025-10-30 07:45:49,473 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7292/9953
2025-10-30 07:45:49,477 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109486.39
2025-10-30 07:45:49,478 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109486.39 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,478 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:49,479 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,484 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:49,484 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$7.04, Commission=$0.00, Net=$7.04 (cash flow: +$2007.04, -$0.00, balance: $10007.04)
2025-10-30 07:45:49,485 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5264/9953
2025-10-30 07:45:49,489 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108514.95
2025-10-30 07:45:49,489 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108514.95 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,490 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:49,492 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,575 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:49,575 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.76, Commission=$0.00, Net=$1.76 (cash flow: +$2001.76, -$0.00, balance: $10001.76)
2025-10-30 07:45:49,576 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7931/9953
2025-10-30 07:45:49,579 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110111.42
2025-10-30 07:45:49,579 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110111.42 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,580 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:49,581 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,588 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:49,588 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.66, Commission=$0.00, Net=$1.66 (cash flow: -$1998.34, balance: $10001.66)
2025-10-30 07:45:49,589 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2182/9953
2025-10-30 07:45:49,591 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111845.32
2025-10-30 07:45:49,592 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111845.32 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,592 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:49,595 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,598 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:45:49,599 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.82, Commission=$0.00, Net=$-0.82 (cash flow: -$2000.82, balance: $9999.18)
2025-10-30 07:45:49,599 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1507/9953
2025-10-30 07:45:49,603 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112910.00
2025-10-30 07:45:49,603 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112910.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,603 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:49,606 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,607 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:49,608 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.01, Commission=$0.00, Net=$-0.01 (cash flow: -$2000.01, balance: $9999.99)
2025-10-30 07:45:49,608 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3274/9953
2025-10-30 07:45:49,610 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108248.00
2025-10-30 07:45:49,611 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108248.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,612 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:49,616 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,678 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:49,678 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.72, Commission=$0.00, Net=$5.72 (cash flow: +$2005.72, -$0.00, balance: $10005.72)
2025-10-30 07:45:49,679 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8680/9953
2025-10-30 07:45:49,681 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111030.00
2025-10-30 07:45:49,682 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111030.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,683 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:49,688 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,691 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:49,691 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.05, Commission=$0.00, Net=$0.05 (cash flow: -$1999.95, balance: $10000.05)
2025-10-30 07:45:49,692 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2596/9953
2025-10-30 07:45:49,694 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110100.00
2025-10-30 07:45:49,695 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110100.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,695 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:49,700 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,702 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:49,702 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.70, Commission=$0.00, Net=$0.70 (cash flow: +$2000.70, -$0.00, balance: $10000.70)
2025-10-30 07:45:49,703 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 233/9953
2025-10-30 07:45:49,705 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108483.75
2025-10-30 07:45:49,706 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108483.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,707 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:49,709 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,744 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:49,744 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.70, Commission=$0.00, Net=$2.70 (cash flow: +$2002.70, -$0.00, balance: $10002.70)
2025-10-30 07:45:49,745 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 72/9953
2025-10-30 07:45:49,750 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108892.59
2025-10-30 07:45:49,750 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108892.59 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,750 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:49,752 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,760 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:49,760 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$6.71, Commission=$0.00, Net=$6.71 (cash flow: +$2006.71, -$0.00, balance: $10006.71)
2025-10-30 07:45:49,761 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6064/9953
2025-10-30 07:45:49,765 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107612.82
2025-10-30 07:45:49,765 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107612.82 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,765 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:49,770 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,813 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:49,813 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.03, Commission=$0.00, Net=$5.03 (cash flow: +$2005.03, -$0.00, balance: $10005.03)
2025-10-30 07:45:49,814 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6501/9953
2025-10-30 07:45:49,817 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109831.05
2025-10-30 07:45:49,818 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109831.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:49,818 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 24.6     |
|    ep_rew_mean        | 0.000103 |
| time/                 |          |
|    fps                | 461      |
|    iterations         | 3000     |
|    time_elapsed       | 32       |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -0.2     |
|    explained_variance | 0.45     |
|    learning_rate      | 0.0007   |
|    n_updates          | 2999     |
|    policy_loss        | -0.00497 |
|    value_loss         | 0.00742  |
------------------------------------

2025-10-30 07:45:49,825 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:49,826 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:49,827 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.07, Commission=$0.00, Net=$-0.07 (cash flow: -$2000.07, balance: $9999.93)
2025-10-30 07:45:49,827 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5796/9953
2025-10-30 07:45:49,831 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107352.89
2025-10-30 07:45:49,832 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107352.89 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:49,832 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:49,835 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,040 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:50,041 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.09, Commission=$0.00, Net=$5.09 (cash flow: +$2005.09, -$0.00, balance: $10005.09)
2025-10-30 07:45:50,041 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3505/9953
2025-10-30 07:45:50,046 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108024.46
2025-10-30 07:45:50,046 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108024.46 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,046 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:50,048 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,072 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:50,072 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.04, Commission=$0.00, Net=$5.04 (cash flow: +$2005.04, -$0.00, balance: $10005.04)
2025-10-30 07:45:50,073 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8372/9953
2025-10-30 07:45:50,075 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111500.00
2025-10-30 07:45:50,076 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111500.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,077 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:50,081 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,083 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:50,083 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.85, Commission=$0.00, Net=$1.85 (cash flow: -$1998.15, balance: $10001.85)
2025-10-30 07:45:50,085 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6264/9953
2025-10-30 07:45:50,086 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108475.40
2025-10-30 07:45:50,087 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108475.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,087 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:50,088 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,115 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:50,116 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.09, Commission=$0.00, Net=$3.09 (cash flow: +$2003.09, -$0.00, balance: $10003.09)
2025-10-30 07:45:50,116 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5722/9953
2025-10-30 07:45:50,118 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107519.03
2025-10-30 07:45:50,119 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107519.03 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,120 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:50,121 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,132 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 07:45:50,133 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.27, Commission=$0.00, Net=$2.27 (cash flow: +$2002.27, -$0.00, balance: $10002.27)
2025-10-30 07:45:50,133 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4631/9953
2025-10-30 07:45:50,139 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108867.43
2025-10-30 07:45:50,139 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108867.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,139 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:50,141 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,187 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:50,188 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-9.32, Commission=$0.00, Net=$-9.32 (cash flow: +$1990.68, -$0.00, balance: $9990.68)
2025-10-30 07:45:50,189 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5781/9953
2025-10-30 07:45:50,191 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107107.72
2025-10-30 07:45:50,192 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107107.72 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,192 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:50,194 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,209 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:50,209 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.92, Commission=$0.00, Net=$5.92 (cash flow: +$2005.92, -$0.00, balance: $10005.92)
2025-10-30 07:45:50,210 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4854/9953
2025-10-30 07:45:50,212 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108002.66
2025-10-30 07:45:50,213 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108002.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,213 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:50,215 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,289 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:50,289 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.38, Commission=$0.00, Net=$1.38 (cash flow: +$2001.38, -$0.00, balance: $10001.38)
2025-10-30 07:45:50,291 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5965/9953
2025-10-30 07:45:50,293 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107055.54
2025-10-30 07:45:50,293 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107055.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,294 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:45:50,296 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,306 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:45:50,307 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.55, Commission=$0.00, Net=$2.55 (cash flow: +$2002.55, -$0.00, balance: $10002.55)
2025-10-30 07:45:50,308 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7677/9953
2025-10-30 07:45:50,310 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111054.08
2025-10-30 07:45:50,310 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111054.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,311 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:50,313 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,315 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:50,315 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: -$2000.73, balance: $9999.27)
2025-10-30 07:45:50,316 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1686/9953
2025-10-30 07:45:50,320 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112470.98
2025-10-30 07:45:50,320 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112470.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,321 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:50,322 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,332 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:50,332 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: -$1999.80, balance: $10000.20)
2025-10-30 07:45:50,333 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8631/9953
2025-10-30 07:45:50,340 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110608.33
2025-10-30 07:45:50,340 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110608.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,340 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:50,342 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,343 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:50,343 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.35, Commission=$0.00, Net=$-4.35 (cash flow: -$2004.35, balance: $9995.65)
2025-10-30 07:45:50,344 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7248/9953
2025-10-30 07:45:50,345 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109622.51
2025-10-30 07:45:50,345 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109622.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,346 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:50,349 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,355 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:50,355 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.02, Commission=$0.00, Net=$-4.02 (cash flow: -$2004.02, balance: $9995.98)
2025-10-30 07:45:50,356 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3220/9953
2025-10-30 07:45:50,358 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108373.00
2025-10-30 07:45:50,358 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108373.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,359 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:50,360 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 28.8     |
|    ep_rew_mean        | 0.0001   |
| time/                 |          |
|    fps                | 469      |
|    iterations         | 3100     |
|    time_elapsed       | 33       |
|    total_timesteps    | 15500    |
| train/                |          |
|    entropy_loss       | -0.453   |
|    explained_variance | 0.674    |
|    learning_rate      | 0.0007   |
|    n_updates          | 3099     |
|    policy_loss        | -0.125   |
|    value_loss         | 0.631    |
------------------------------------

2025-10-30 07:45:50,368 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:50,368 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.64, Commission=$0.00, Net=$-0.64 (cash flow: -$2000.64, balance: $9999.36)
2025-10-30 07:45:50,369 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 195/9953
2025-10-30 07:45:50,371 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108651.89
2025-10-30 07:45:50,372 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108651.89 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,372 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:50,373 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,376 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:50,377 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.69, Commission=$0.00, Net=$2.69 (cash flow: -$1997.31, balance: $10002.69)
2025-10-30 07:45:50,378 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3376/9953
2025-10-30 07:45:50,383 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108348.83
2025-10-30 07:45:50,384 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108348.83 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,384 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:50,387 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,401 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:50,402 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.82, Commission=$0.00, Net=$1.82 (cash flow: -$1998.18, balance: $10001.82)
2025-10-30 07:45:50,404 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1889/9953
2025-10-30 07:45:50,409 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112350.56
2025-10-30 07:45:50,410 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112350.56 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,410 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:50,413 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,424 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:50,424 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.01, Commission=$0.00, Net=$0.01 (cash flow: -$1999.99, balance: $10000.01)
2025-10-30 07:45:50,425 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2302/9953
2025-10-30 07:45:50,429 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111739.42
2025-10-30 07:45:50,429 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111739.42 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,430 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:50,435 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,441 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:50,441 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.87, Commission=$0.00, Net=$1.87 (cash flow: -$1998.13, balance: $10001.87)
2025-10-30 07:45:50,442 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1146/9953
2025-10-30 07:45:50,444 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113315.00
2025-10-30 07:45:50,445 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113315.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,445 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:50,447 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,456 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:50,457 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.83, Commission=$0.00, Net=$-0.83 (cash flow: -$2000.83, balance: $9999.17)
2025-10-30 07:45:50,457 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2732/9953
2025-10-30 07:45:50,460 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109166.11
2025-10-30 07:45:50,460 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109166.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,461 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:50,463 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,469 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:50,470 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.48, Commission=$0.00, Net=$0.48 (cash flow: -$1999.52, balance: $10000.48)
2025-10-30 07:45:50,470 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1084/9953
2025-10-30 07:45:50,473 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113500.00
2025-10-30 07:45:50,474 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113500.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,474 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:50,479 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,485 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:50,485 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.28, Commission=$0.00, Net=$1.28 (cash flow: -$1998.72, balance: $10001.28)
2025-10-30 07:45:50,486 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5093/9953
2025-10-30 07:45:50,489 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108369.66
2025-10-30 07:45:50,490 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108369.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,490 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:50,493 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,560 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:50,560 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.22, Commission=$0.00, Net=$2.22 (cash flow: +$2002.22, -$0.00, balance: $10002.22)
2025-10-30 07:45:50,561 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1091/9953
2025-10-30 07:45:50,562 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113409.34
2025-10-30 07:45:50,563 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113409.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,563 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:50,569 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,583 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:50,583 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.44, Commission=$0.00, Net=$-0.44 (cash flow: -$2000.44, balance: $9999.56)
2025-10-30 07:45:50,584 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9615/9953
2025-10-30 07:45:50,586 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110912.28
2025-10-30 07:45:50,587 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110912.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,587 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:50,592 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,607 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:50,607 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: -$2000.81, balance: $9999.19)
2025-10-30 07:45:50,608 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4335/9953
2025-10-30 07:45:50,611 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107508.24
2025-10-30 07:45:50,611 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107508.24 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,612 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:50,614 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,632 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:50,632 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.22, Commission=$0.00, Net=$0.22 (cash flow: +$2000.22, -$0.00, balance: $10000.22)
2025-10-30 07:45:50,633 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5817/9953
2025-10-30 07:45:50,635 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107270.00
2025-10-30 07:45:50,636 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107270.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,637 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:50,638 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,662 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:50,662 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-8.24, Commission=$0.00, Net=$-8.24 (cash flow: +$1991.76, -$0.00, balance: $9991.76)
2025-10-30 07:45:50,663 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 705/9953
2025-10-30 07:45:50,665 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112242.20
2025-10-30 07:45:50,665 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112242.20 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,666 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 07:45:50,668 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,674 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 07:45:50,675 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.25, Commission=$0.00, Net=$-0.25 (cash flow: +$1999.75, -$0.00, balance: $9999.75)
2025-10-30 07:45:50,675 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5518/9953
2025-10-30 07:45:50,677 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107910.39
2025-10-30 07:45:50,678 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107910.39 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,679 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:50,681 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,686 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:50,686 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.09, Commission=$0.00, Net=$2.09 (cash flow: +$2002.09, -$0.00, balance: $10002.09)
2025-10-30 07:45:50,687 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8008/9953
2025-10-30 07:45:50,690 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110273.16
2025-10-30 07:45:50,690 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110273.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,691 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:50,693 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,711 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:50,712 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-7.33, Commission=$0.00, Net=$-7.33 (cash flow: -$2007.33, balance: $9992.67)
2025-10-30 07:45:50,712 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 498/9953
2025-10-30 07:45:50,718 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109936.78
2025-10-30 07:45:50,718 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109936.78 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,719 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:50,720 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,723 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:50,724 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.95, Commission=$0.00, Net=$-0.95 (cash flow: -$2000.95, balance: $9999.05)
2025-10-30 07:45:50,724 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5646/9953
2025-10-30 07:45:50,730 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107978.00
2025-10-30 07:45:50,731 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107978.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,731 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:50,733 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:50,733 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.08, Commission=$0.00, Net=$1.08 (cash flow: +$2001.08, -$0.00, balance: $10001.08)
2025-10-30 07:45:50,735 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6618/9953
2025-10-30 07:45:50,738 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109768.12
2025-10-30 07:45:50,738 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109768.12 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,739 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:50,742 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,748 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:50,749 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.11, Commission=$0.00, Net=$0.11 (cash flow: -$1999.89, balance: $10000.11)
2025-10-30 07:45:50,749 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5007/9953
2025-10-30 07:45:50,752 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108760.00
2025-10-30 07:45:50,753 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108760.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:50,753 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:50,756 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:50,756 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.11, Commission=$0.00, Net=$1.11 (cash flow: -$1998.89, balance: $10001.11)
2025-10-30 07:45:50,757 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 787/9953
2025-10-30 07:45:50,761 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112870.49
2025-10-30 07:45:50,761 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112870.49 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,762 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:50,766 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,858 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:50,858 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.26, Commission=$0.00, Net=$-0.26 (cash flow: +$1999.74, -$0.00, balance: $9999.74)
2025-10-30 07:45:50,859 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5574/9953
2025-10-30 07:45:50,861 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108154.11
2025-10-30 07:45:50,861 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108154.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,862 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:50,864 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:50,866 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:50,866 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: +$1999.94, -$0.00, balance: $9999.94)
2025-10-30 07:45:50,867 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5160/9953
2025-10-30 07:45:50,872 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108439.15
2025-10-30 07:45:50,873 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108439.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:50,873 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:50,876 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 26.4     |
|    ep_rew_mean        | 6.01e-05 |
| time/                 |          |
|    fps                | 473      |
|    iterations         | 3200     |
|    time_elapsed       | 33       |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -0.5     |
|    explained_variance | -1.34    |
|    learning_rate      | 0.0007   |
|    n_updates          | 3199     |
|    policy_loss        | 0.077    |
|    value_loss         | 0.0866   |
------------------------------------

2025-10-30 07:45:51,116 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:51,117 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.26, Commission=$0.00, Net=$-4.26 (cash flow: -$2004.26, balance: $9995.74)
2025-10-30 07:45:51,117 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1199/9953
2025-10-30 07:45:51,120 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113293.26
2025-10-30 07:45:51,120 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113293.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,121 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:51,123 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,130 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 07:45:51,130 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.30, Commission=$0.00, Net=$-4.30 (cash flow: -$2004.30, balance: $9995.70)
2025-10-30 07:45:51,131 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3185/9953
2025-10-30 07:45:51,133 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108085.00
2025-10-30 07:45:51,134 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108085.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,134 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:51,139 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,149 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:51,150 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.13, Commission=$0.00, Net=$-0.13 (cash flow: -$2000.13, balance: $9999.87)
2025-10-30 07:45:51,151 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1949/9953
2025-10-30 07:45:51,154 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112247.57
2025-10-30 07:45:51,154 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112247.57 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,154 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:51,156 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,164 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:51,164 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.21, Commission=$0.00, Net=$1.21 (cash flow: -$1998.79, balance: $10001.21)
2025-10-30 07:45:51,165 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1036/9953
2025-10-30 07:45:51,170 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112796.20
2025-10-30 07:45:51,170 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112796.20 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,171 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:51,173 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,181 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:51,181 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.23, Commission=$0.00, Net=$-2.23 (cash flow: -$2002.23, balance: $9997.77)
2025-10-30 07:45:51,182 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6459/9953
2025-10-30 07:45:51,184 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109674.11
2025-10-30 07:45:51,185 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109674.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:51,185 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:51,190 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,197 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:51,197 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.78, Commission=$0.00, Net=$1.78 (cash flow: +$2001.78, -$0.00, balance: $10001.78)
2025-10-30 07:45:51,198 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6820/9953
2025-10-30 07:45:51,203 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109547.00
2025-10-30 07:45:51,203 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109547.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,203 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:51,206 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,208 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:51,208 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.47, Commission=$0.00, Net=$2.47 (cash flow: -$1997.53, balance: $10002.47)
2025-10-30 07:45:51,209 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2116/9953
2025-10-30 07:45:51,213 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112159.99
2025-10-30 07:45:51,213 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112159.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,213 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:51,218 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,230 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:51,230 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: -$2000.81, balance: $9999.19)
2025-10-30 07:45:51,231 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7465/9953
2025-10-30 07:45:51,236 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110484.49
2025-10-30 07:45:51,236 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110484.49 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,236 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:51,239 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,244 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:51,244 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.13, Commission=$0.00, Net=$-1.13 (cash flow: -$2001.13, balance: $9998.87)
2025-10-30 07:45:51,245 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7029/9953
2025-10-30 07:45:51,247 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109061.72
2025-10-30 07:45:51,248 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109061.72 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,248 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:51,251 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,266 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:51,267 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.63, Commission=$0.00, Net=$4.63 (cash flow: -$1995.37, balance: $10004.63)
2025-10-30 07:45:51,267 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9785/9953
2025-10-30 07:45:51,269 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111250.08
2025-10-30 07:45:51,269 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111250.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,269 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:51,271 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:51,272 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.54, Commission=$0.00, Net=$-1.54 (cash flow: -$2001.54, balance: $9998.46)
2025-10-30 07:45:51,273 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9106/9953
2025-10-30 07:45:51,278 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110008.30
2025-10-30 07:45:51,278 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110008.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,279 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:51,281 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:51,281 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.34, Commission=$0.00, Net=$-2.34 (cash flow: -$2002.34, balance: $9997.66)
2025-10-30 07:45:51,283 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1323/9953
2025-10-30 07:45:51,285 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113824.00
2025-10-30 07:45:51,286 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113824.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,286 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:51,289 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,290 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:51,291 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.18, Commission=$0.00, Net=$0.18 (cash flow: -$1999.82, balance: $10000.18)
2025-10-30 07:45:51,292 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7777/9953
2025-10-30 07:45:51,298 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110247.99
2025-10-30 07:45:51,299 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110247.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:51,299 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:51,303 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:51,304 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.91, Commission=$0.00, Net=$0.91 (cash flow: +$2000.91, -$0.00, balance: $10000.91)
2025-10-30 07:45:51,304 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3129/9953
2025-10-30 07:45:51,306 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107886.80
2025-10-30 07:45:51,306 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107886.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:51,307 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:51,310 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,313 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:51,313 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.40, Commission=$0.00, Net=$1.40 (cash flow: +$2001.40, -$0.00, balance: $10001.40)
2025-10-30 07:45:51,314 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8019/9953
2025-10-30 07:45:51,317 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110472.61
2025-10-30 07:45:51,318 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110472.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:51,318 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:51,320 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,327 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:51,327 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.28, Commission=$0.00, Net=$2.28 (cash flow: +$2002.28, -$0.00, balance: $10002.28)
2025-10-30 07:45:51,328 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2437/9953
2025-10-30 07:45:51,332 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110751.50
2025-10-30 07:45:51,332 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110751.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,332 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:51,336 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,338 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:51,338 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.69, Commission=$0.00, Net=$-2.69 (cash flow: -$2002.69, balance: $9997.31)
2025-10-30 07:45:51,338 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2342/9953
2025-10-30 07:45:51,341 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111617.33
2025-10-30 07:45:51,341 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111617.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,342 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:51,344 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,350 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:45:51,350 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.48, Commission=$0.00, Net=$-2.48 (cash flow: -$2002.48, balance: $9997.52)
2025-10-30 07:45:51,351 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2361/9953
2025-10-30 07:45:51,353 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111285.51
2025-10-30 07:45:51,354 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111285.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:51,354 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:51,357 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,360 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:51,361 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.08, Commission=$0.00, Net=$1.08 (cash flow: +$2001.08, -$0.00, balance: $10001.08)
2025-10-30 07:45:51,361 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8647/9953
2025-10-30 07:45:51,366 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110937.77
2025-10-30 07:45:51,366 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110937.77 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:51,366 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:51,368 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,371 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 07:45:51,372 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.11, Commission=$0.00, Net=$0.11 (cash flow: +$2000.11, -$0.00, balance: $10000.11)
2025-10-30 07:45:51,373 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4285/9953
2025-10-30 07:45:51,375 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108026.88
2025-10-30 07:45:51,376 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108026.88 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,376 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:51,379 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,380 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:51,380 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.69, Commission=$0.00, Net=$0.69 (cash flow: -$1999.31, balance: $10000.69)
2025-10-30 07:45:51,381 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2831/9953
2025-10-30 07:45:51,386 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109082.65
2025-10-30 07:45:51,386 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109082.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,387 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:51,389 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,392 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:51,392 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.52, Commission=$0.00, Net=$1.52 (cash flow: -$1998.48, balance: $10001.52)
2025-10-30 07:45:51,393 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5286/9953
2025-10-30 07:45:51,397 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108063.17
2025-10-30 07:45:51,398 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108063.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:51,398 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:51,401 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:51,403 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 10       |
|    ep_rew_mean        | 3.84e-05 |
| time/                 |          |
|    fps                | 475      |
|    iterations         | 3300     |
|    time_elapsed       | 34       |
|    total_timesteps    | 16500    |
| train/                |          |
|    entropy_loss       | -0.118   |
|    explained_variance | 0.468    |
|    learning_rate      | 0.0007   |
|    n_updates          | 3299     |
|    policy_loss        | 0.000201 |
|    value_loss         | 0.11     |
------------------------------------

2025-10-30 07:45:52,007 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:52,007 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.31, Commission=$0.00, Net=$4.31 (cash flow: +$2004.31, -$0.00, balance: $10004.31)
2025-10-30 07:45:52,008 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2927/9953
2025-10-30 07:45:52,009 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108645.61
2025-10-30 07:45:52,010 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108645.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,010 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:52,015 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,204 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:52,205 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-8.96, Commission=$0.00, Net=$-8.96 (cash flow: +$1991.04, -$0.00, balance: $9991.04)
2025-10-30 07:45:52,205 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1432/9953
2025-10-30 07:45:52,207 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112583.50
2025-10-30 07:45:52,207 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112583.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:52,208 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:52,210 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,219 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:52,219 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.48, Commission=$0.00, Net=$1.48 (cash flow: -$1998.52, balance: $10001.48)
2025-10-30 07:45:52,220 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9349/9953
2025-10-30 07:45:52,222 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110320.30
2025-10-30 07:45:52,223 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110320.30 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,223 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:52,225 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,231 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 07:45:52,232 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.74, Commission=$0.00, Net=$-0.74 (cash flow: +$1999.26, -$0.00, balance: $9999.26)
2025-10-30 07:45:52,232 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2707/9953
2025-10-30 07:45:52,237 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108606.63
2025-10-30 07:45:52,237 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108606.63 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,237 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:52,239 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,243 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:52,243 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.28, Commission=$0.00, Net=$4.28 (cash flow: +$2004.28, -$0.00, balance: $10004.28)
2025-10-30 07:45:52,244 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 422/9953
2025-10-30 07:45:52,248 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110474.78
2025-10-30 07:45:52,249 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110474.78 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,249 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:52,250 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,346 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:52,346 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.53, Commission=$0.00, Net=$5.53 (cash flow: +$2005.53, -$0.00, balance: $10005.53)
2025-10-30 07:45:52,347 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1236/9953
2025-10-30 07:45:52,350 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113702.95
2025-10-30 07:45:52,350 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113702.95 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:52,351 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:52,352 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,357 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:52,357 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.30, Commission=$0.00, Net=$1.30 (cash flow: -$1998.70, balance: $10001.30)
2025-10-30 07:45:52,358 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7681/9953
2025-10-30 07:45:52,360 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111045.30
2025-10-30 07:45:52,360 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111045.30 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,361 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:45:52,362 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 13.4      |
|    ep_rew_mean        | 4.47e-05  |
| time/                 |           |
|    fps                | 483       |
|    iterations         | 3400      |
|    time_elapsed       | 35        |
|    total_timesteps    | 17000     |
| train/                |           |
|    entropy_loss       | -0.00403  |
|    explained_variance | -0.00051  |
|    learning_rate      | 0.0007    |
|    n_updates          | 3399      |
|    policy_loss        | -0.000203 |
|    value_loss         | 0.37      |
-------------------------------------

2025-10-30 07:45:52,774 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:45:52,775 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.72, Commission=$0.00, Net=$3.72 (cash flow: +$2003.72, -$0.00, balance: $10003.72)
2025-10-30 07:45:52,776 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5275/9953
2025-10-30 07:45:52,780 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108000.00
2025-10-30 07:45:52,780 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:52,781 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:52,782 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,784 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:52,785 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.21, Commission=$0.00, Net=$1.21 (cash flow: -$1998.79, balance: $10001.21)
2025-10-30 07:45:52,787 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5521/9953
2025-10-30 07:45:52,790 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108004.00
2025-10-30 07:45:52,790 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108004.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:52,791 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:52,796 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,797 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:52,797 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.46, Commission=$0.00, Net=$1.46 (cash flow: -$1998.54, balance: $10001.46)
2025-10-30 07:45:52,798 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6548/9953
2025-10-30 07:45:52,801 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110099.19
2025-10-30 07:45:52,802 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110099.19 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,802 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:52,805 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,871 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:52,871 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.49, Commission=$0.00, Net=$-6.49 (cash flow: +$1993.51, -$0.00, balance: $9993.51)
2025-10-30 07:45:52,872 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7473/9953
2025-10-30 07:45:52,875 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110419.65
2025-10-30 07:45:52,876 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110419.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,876 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:52,878 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 18.4      |
|    ep_rew_mean        | 4.11e-05  |
| time/                 |           |
|    fps                | 492       |
|    iterations         | 3500      |
|    time_elapsed       | 35        |
|    total_timesteps    | 17500     |
| train/                |           |
|    entropy_loss       | -0.0198   |
|    explained_variance | 0.132     |
|    learning_rate      | 0.0007    |
|    n_updates          | 3499      |
|    policy_loss        | -0.000361 |
|    value_loss         | 0.0459    |
-------------------------------------

2025-10-30 07:45:52,933 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:52,934 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.45, Commission=$0.00, Net=$-3.45 (cash flow: +$1996.55, -$0.00, balance: $9996.55)
2025-10-30 07:45:52,934 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5636/9953
2025-10-30 07:45:52,937 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107736.84
2025-10-30 07:45:52,938 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107736.84 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,938 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:52,941 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,951 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:52,951 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.90, Commission=$0.00, Net=$3.90 (cash flow: +$2003.90, -$0.00, balance: $10003.90)
2025-10-30 07:45:52,952 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9907/9953
2025-10-30 07:45:52,956 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111632.89
2025-10-30 07:45:52,956 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111632.89 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:52,956 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:52,958 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,973 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:52,973 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.56, Commission=$0.00, Net=$-2.56 (cash flow: -$2002.56, balance: $9997.44)
2025-10-30 07:45:52,974 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 483/9953
2025-10-30 07:45:52,976 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109855.45
2025-10-30 07:45:52,977 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109855.45 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:52,977 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:52,981 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:52,985 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:52,985 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.68, Commission=$0.00, Net=$0.68 (cash flow: +$2000.68, -$0.00, balance: $10000.68)
2025-10-30 07:45:52,986 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6606/9953
2025-10-30 07:45:52,988 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109988.80
2025-10-30 07:45:52,989 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109988.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:52,989 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:52,994 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,001 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:53,001 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.76, Commission=$0.00, Net=$2.76 (cash flow: -$1997.24, balance: $10002.76)
2025-10-30 07:45:53,002 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4385/9953
2025-10-30 07:45:53,005 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107872.73
2025-10-30 07:45:53,005 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107872.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,005 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:53,010 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,020 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 07:45:53,021 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.36, Commission=$0.00, Net=$2.36 (cash flow: +$2002.36, -$0.00, balance: $10002.36)
2025-10-30 07:45:53,021 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5733/9953
2025-10-30 07:45:53,024 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107641.00
2025-10-30 07:45:53,024 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107641.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,025 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:53,028 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,056 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 07:45:53,057 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$7.33, Commission=$0.00, Net=$7.33 (cash flow: -$1992.67, balance: $10007.33)
2025-10-30 07:45:53,058 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6578/9953
2025-10-30 07:45:53,060 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110114.01
2025-10-30 07:45:53,061 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110114.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,061 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:53,065 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,079 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:53,079 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.53, Commission=$0.00, Net=$0.53 (cash flow: -$1999.47, balance: $10000.53)
2025-10-30 07:45:53,080 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3874/9953
2025-10-30 07:45:53,084 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107976.61
2025-10-30 07:45:53,084 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107976.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,084 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:53,090 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,106 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:53,106 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.47, Commission=$0.00, Net=$4.47 (cash flow: +$2004.47, -$0.00, balance: $10004.47)
2025-10-30 07:45:53,107 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5120/9953
2025-10-30 07:45:53,111 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107890.99
2025-10-30 07:45:53,111 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107890.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,112 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:53,115 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,140 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:53,140 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.34, Commission=$0.00, Net=$5.34 (cash flow: +$2005.34, -$0.00, balance: $10005.34)
2025-10-30 07:45:53,141 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8246/9953
2025-10-30 07:45:53,144 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111234.32
2025-10-30 07:45:53,144 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111234.32 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,144 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:53,147 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,153 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:53,154 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.01, Commission=$0.00, Net=$3.01 (cash flow: -$1996.99, balance: $10003.01)
2025-10-30 07:45:53,154 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 978/9953
2025-10-30 07:45:53,155 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113299.00
2025-10-30 07:45:53,156 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113299.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,156 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:45:53,161 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,172 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:45:53,172 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.43, Commission=$0.00, Net=$0.43 (cash flow: -$1999.57, balance: $10000.43)
2025-10-30 07:45:53,173 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6776/9953
2025-10-30 07:45:53,174 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109234.31
2025-10-30 07:45:53,174 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109234.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,175 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:53,176 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,181 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:53,182 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.57, Commission=$0.00, Net=$1.57 (cash flow: -$1998.43, balance: $10001.57)
2025-10-30 07:45:53,182 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2066/9953
2025-10-30 07:45:53,184 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112049.47
2025-10-30 07:45:53,185 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112049.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,185 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:53,188 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,240 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:53,241 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.75, Commission=$0.00, Net=$-2.75 (cash flow: -$2002.75, balance: $9997.25)
2025-10-30 07:45:53,241 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3841/9953
2025-10-30 07:45:53,243 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107699.99
2025-10-30 07:45:53,244 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107699.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,245 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:53,247 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,252 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 07:45:53,252 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.43, Commission=$0.00, Net=$0.43 (cash flow: -$1999.57, balance: $10000.43)
2025-10-30 07:45:53,253 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3918/9953
2025-10-30 07:45:53,255 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108138.88
2025-10-30 07:45:53,256 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108138.88 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,256 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:53,260 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,266 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:53,266 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.89, Commission=$0.00, Net=$-0.89 (cash flow: -$2000.89, balance: $9999.11)
2025-10-30 07:45:53,267 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7959/9953
2025-10-30 07:45:53,270 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110034.26
2025-10-30 07:45:53,271 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110034.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,271 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:53,275 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,300 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:53,300 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.97, Commission=$0.00, Net=$-2.97 (cash flow: -$2002.97, balance: $9997.03)
2025-10-30 07:45:53,301 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6911/9953
2025-10-30 07:45:53,303 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109316.88
2025-10-30 07:45:53,303 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109316.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,304 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:53,307 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,365 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:45:53,365 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.92, Commission=$0.00, Net=$-2.92 (cash flow: +$1997.08, -$0.00, balance: $9997.08)
2025-10-30 07:45:53,366 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6665/9953
2025-10-30 07:45:53,368 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109461.51
2025-10-30 07:45:53,369 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109461.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,370 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:53,373 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,382 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:53,382 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.59, Commission=$0.00, Net=$0.59 (cash flow: -$1999.41, balance: $10000.59)
2025-10-30 07:45:53,383 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8346/9953
2025-10-30 07:45:53,386 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111430.33
2025-10-30 07:45:53,387 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111430.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,387 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:53,390 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,404 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:53,405 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: -$2000.81, balance: $9999.19)
2025-10-30 07:45:53,405 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4896/9953
2025-10-30 07:45:53,407 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107796.29
2025-10-30 07:45:53,409 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107796.29 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,409 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:53,411 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,440 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:53,440 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.56, Commission=$0.00, Net=$4.56 (cash flow: +$2004.56, -$0.00, balance: $10004.56)
2025-10-30 07:45:53,441 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1167/9953
2025-10-30 07:45:53,443 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113445.02
2025-10-30 07:45:53,444 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113445.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,445 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:53,450 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,491 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:53,492 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.74, Commission=$0.00, Net=$3.74 (cash flow: -$1996.26, balance: $10003.74)
2025-10-30 07:45:53,493 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7656/9953
2025-10-30 07:45:53,496 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111212.92
2025-10-30 07:45:53,497 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111212.92 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 20.2     |
|    ep_rew_mean        | 7.29e-05 |
| time/                 |          |
|    fps                | 497      |
|    iterations         | 3600     |
|    time_elapsed       | 36       |
|    total_timesteps    | 18000    |
| train/                |          |
|    entropy_loss       | -0.186   |
|    explained_variance | -0.321   |
|    learning_rate      | 0.0007   |
|    n_updates          | 3599     |
|    policy_loss        | 0.00919  |
|    value_loss         | 0.0656   |
------------------------------------

2025-10-30 07:45:53,515 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:53,515 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: -$1999.05, balance: $10000.95)
2025-10-30 07:45:53,516 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7290/9953
2025-10-30 07:45:53,518 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109530.03
2025-10-30 07:45:53,519 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109530.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,519 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:53,521 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,524 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:53,525 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.59, Commission=$0.00, Net=$-2.59 (cash flow: -$2002.59, balance: $9997.41)
2025-10-30 07:45:53,526 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8434/9953
2025-10-30 07:45:53,530 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110948.97
2025-10-30 07:45:53,530 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110948.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,531 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:53,533 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,543 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:53,543 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.00, Commission=$0.00, Net=$-1.00 (cash flow: -$2001.00, balance: $9999.00)
2025-10-30 07:45:53,544 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7329/9953
2025-10-30 07:45:53,547 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109600.43
2025-10-30 07:45:53,548 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109600.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,548 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:53,550 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,559 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:53,560 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.82, Commission=$0.00, Net=$1.82 (cash flow: +$2001.82, -$0.00, balance: $10001.82)
2025-10-30 07:45:53,560 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 417/9953
2025-10-30 07:45:53,564 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110261.00
2025-10-30 07:45:53,564 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110261.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,564 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:53,566 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,568 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:53,568 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.21, Commission=$0.00, Net=$-2.21 (cash flow: -$2002.21, balance: $9997.79)
2025-10-30 07:45:53,569 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8720/9953
2025-10-30 07:45:53,573 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111726.83
2025-10-30 07:45:53,574 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111726.83 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,574 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:45:53,577 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,593 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:45:53,593 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.86, Commission=$0.00, Net=$3.86 (cash flow: +$2003.86, -$0.00, balance: $10003.86)
2025-10-30 07:45:53,594 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1327/9953
2025-10-30 07:45:53,596 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113766.01
2025-10-30 07:45:53,596 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113766.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,597 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:53,601 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,608 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:53,608 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.91, Commission=$0.00, Net=$2.91 (cash flow: -$1997.09, balance: $10002.91)
2025-10-30 07:45:53,609 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 983/9953
2025-10-30 07:45:53,611 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113326.29
2025-10-30 07:45:53,612 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113326.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,612 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:53,614 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,623 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:53,624 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.35, Commission=$0.00, Net=$1.35 (cash flow: -$1998.65, balance: $10001.35)
2025-10-30 07:45:53,624 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6684/9953
2025-10-30 07:45:53,627 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109253.07
2025-10-30 07:45:53,627 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109253.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,628 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:53,632 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,642 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:53,642 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.52, Commission=$0.00, Net=$-4.52 (cash flow: -$2004.52, balance: $9995.48)
2025-10-30 07:45:53,643 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1279/9953
2025-10-30 07:45:53,645 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113688.01
2025-10-30 07:45:53,646 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113688.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,646 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 07:45:53,649 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,660 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 07:45:53,660 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.39, Commission=$0.00, Net=$-0.39 (cash flow: +$1999.61, -$0.00, balance: $9999.61)
2025-10-30 07:45:53,660 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3552/9953
2025-10-30 07:45:53,665 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108410.65
2025-10-30 07:45:53,665 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108410.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,665 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:53,668 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,677 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:53,677 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.24, Commission=$0.00, Net=$1.24 (cash flow: +$2001.24, -$0.00, balance: $10001.24)
2025-10-30 07:45:53,678 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2946/9953
2025-10-30 07:45:53,681 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108382.66
2025-10-30 07:45:53,681 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108382.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,681 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:53,683 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,698 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:53,699 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.62, Commission=$0.00, Net=$3.62 (cash flow: -$1996.38, balance: $10003.62)
2025-10-30 07:45:53,699 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8431/9953
2025-10-30 07:45:53,701 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111038.41
2025-10-30 07:45:53,701 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111038.41 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,702 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:53,703 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,736 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:53,737 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.09, Commission=$0.00, Net=$1.09 (cash flow: -$1998.91, balance: $10001.09)
2025-10-30 07:45:53,738 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5220/9953
2025-10-30 07:45:53,740 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108340.51
2025-10-30 07:45:53,740 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108340.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,741 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:53,742 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,779 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:53,779 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.20, Commission=$0.00, Net=$5.20 (cash flow: +$2005.20, -$0.00, balance: $10005.20)
2025-10-30 07:45:53,780 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9654/9953
2025-10-30 07:45:53,784 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110826.53
2025-10-30 07:45:53,784 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110826.53 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,784 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:53,786 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,793 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:53,793 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.63, Commission=$0.00, Net=$-3.63 (cash flow: -$2003.63, balance: $9996.37)
2025-10-30 07:45:53,794 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2246/9953
2025-10-30 07:45:53,796 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111598.47
2025-10-30 07:45:53,797 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111598.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,797 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:53,800 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:53,800 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: -$1999.05, balance: $10000.95)
2025-10-30 07:45:53,801 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1300/9953
2025-10-30 07:45:53,803 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113740.61
2025-10-30 07:45:53,803 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113740.61 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,804 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:53,809 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:53,810 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.31, Commission=$0.00, Net=$-1.31 (cash flow: -$2001.31, balance: $9998.69)
2025-10-30 07:45:53,810 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6152/9953
2025-10-30 07:45:53,813 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108451.76
2025-10-30 07:45:53,813 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108451.76 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,814 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:53,816 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,914 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:53,914 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.57, Commission=$0.00, Net=$-1.57 (cash flow: +$1998.43, -$0.00, balance: $9998.43)
2025-10-30 07:45:53,915 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7712/9953
2025-10-30 07:45:53,917 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110510.99
2025-10-30 07:45:53,918 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110510.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,918 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:53,921 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,923 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:53,924 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.44, Commission=$0.00, Net=$1.44 (cash flow: -$1998.56, balance: $10001.44)
2025-10-30 07:45:53,925 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5508/9953
2025-10-30 07:45:53,929 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107513.71
2025-10-30 07:45:53,929 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107513.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,930 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:45:53,932 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,944 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:45:53,944 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$8.11, Commission=$0.00, Net=$8.11 (cash flow: +$2008.11, -$0.00, balance: $10008.11)
2025-10-30 07:45:53,945 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6593/9953
2025-10-30 07:45:53,947 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110038.54
2025-10-30 07:45:53,947 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110038.54 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:53,947 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:53,950 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,972 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:45:53,972 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.92, Commission=$0.00, Net=$4.92 (cash flow: -$1995.08, balance: $10004.92)
2025-10-30 07:45:53,973 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1022/9953
2025-10-30 07:45:53,975 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113138.01
2025-10-30 07:45:53,976 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113138.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,976 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:45:53,979 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:53,989 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:45:53,990 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.53, Commission=$0.00, Net=$-6.53 (cash flow: +$1993.47, -$0.00, balance: $9993.47)
2025-10-30 07:45:53,991 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 336/9953
2025-10-30 07:45:53,995 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109065.00
2025-10-30 07:45:53,995 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109065.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:53,995 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:53,998 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 23.4     |
|    ep_rew_mean        | 0.000106 |
| time/                 |          |
|    fps                | 502      |
|    iterations         | 3700     |
|    time_elapsed       | 36       |
|    total_timesteps    | 18500    |
| train/                |          |
|    entropy_loss       | -0.0617  |
|    explained_variance | 0.0869   |
|    learning_rate      | 0.0007   |
|    n_updates          | 3699     |
|    policy_loss        | -0.00842 |
|    value_loss         | 0.537    |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 23.4      |
|    ep_rew_mean        | 0.000106  |
| time/                 |           |
|    fps                | 510       |
|    iterations         | 3800      |
|    time_elapsed       | 37        |
|    total_timesteps    | 19000     |
| train/                |           |
|    entropy_loss       | -0.00173  |
|    explained_variance | 0.286     |
|    learning_rate      | 0.0007    |
|    n_updates          | 3799      |
|    policy_loss        | -2.53e-05 |
|    value_loss         | 0.12      |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 23.4      |
|    ep_rew_mean        | 0.000106  |
| time/                 |           |
|    fps                | 518       |
|    iterations         | 3900      |
|    time_elapsed       | 37        |
|    total_timesteps    | 19500     |
| train/                |           |
|    entropy_loss       | -0.0018   |
|    explained_variance | 0.0968    |
|    learning_rate      | 0.0007    |
|    n_updates          | 3899      |
|    policy_loss        | -3.81e-05 |
|    value_loss         | 0.0676    |
-------------------------------------

2025-10-30 07:45:55,287 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 07:45:55,287 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$6.02, Commission=$0.00, Net=$6.02 (cash flow: +$2006.02, -$0.00, balance: $10006.02)
2025-10-30 07:45:55,288 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 29/9953
2025-10-30 07:45:55,289 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108400.02
2025-10-30 07:45:55,290 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108400.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,290 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:55,293 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,298 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:55,298 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.07, Commission=$0.00, Net=$0.07 (cash flow: -$1999.93, balance: $10000.07)
2025-10-30 07:45:55,299 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4526/9953
2025-10-30 07:45:55,301 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107698.99
2025-10-30 07:45:55,302 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107698.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,302 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:55,304 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,309 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 07:45:55,309 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.98, Commission=$0.00, Net=$-2.98 (cash flow: -$2002.98, balance: $9997.02)
2025-10-30 07:45:55,310 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1624/9953
2025-10-30 07:45:55,313 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112386.82
2025-10-30 07:45:55,313 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112386.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,314 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:55,316 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,324 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:55,324 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.27, Commission=$0.00, Net=$1.27 (cash flow: -$1998.73, balance: $10001.27)
2025-10-30 07:45:55,325 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2136/9953
2025-10-30 07:45:55,328 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112195.10
2025-10-30 07:45:55,329 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112195.10 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,329 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:55,333 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,345 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:55,345 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.84, Commission=$0.00, Net=$-0.84 (cash flow: -$2000.84, balance: $9999.16)
2025-10-30 07:45:55,346 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3360/9953
2025-10-30 07:45:55,348 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108542.87
2025-10-30 07:45:55,348 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108542.87 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,349 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:45:55,351 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,358 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:45:55,358 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.66, Commission=$0.00, Net=$1.66 (cash flow: -$1998.34, balance: $10001.66)
2025-10-30 07:45:55,359 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9542/9953
2025-10-30 07:45:55,363 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110707.00
2025-10-30 07:45:55,364 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110707.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,364 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:55,368 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,398 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:55,398 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.80, Commission=$0.00, Net=$-2.80 (cash flow: -$2002.80, balance: $9997.20)
2025-10-30 07:45:55,399 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4329/9953
2025-10-30 07:45:55,401 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107697.00
2025-10-30 07:45:55,401 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107697.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:55,401 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:55,405 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:55,411 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 07:45:55,411 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.51, Commission=$0.00, Net=$3.51 (cash flow: -$1996.49, balance: $10003.51)
2025-10-30 07:45:55,412 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2659/9953
2025-10-30 07:45:55,415 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109677.19
2025-10-30 07:45:55,415 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109677.19 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:55,415 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:55,420 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 37.3     |
|    ep_rew_mean        | 0.000107 |
| time/                 |          |
|    fps                | 524      |
|    iterations         | 4000     |
|    time_elapsed       | 38       |
|    total_timesteps    | 20000    |
| train/                |          |
|    entropy_loss       | -0.00256 |
|    explained_variance | 0.154    |
|    learning_rate      | 0.0007   |
|    n_updates          | 3999     |
|    policy_loss        | 0.000167 |
|    value_loss         | 0.467    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 37.3     |
|    ep_rew_mean        | 0.000107 |
| time/                 |          |
|    fps                | 531      |
|    iterations         | 4100     |
|    time_elapsed       | 38       |
|    total_timesteps    | 20500    |
| train/                |          |
|    entropy_loss       | -0.00485 |
|    explained_variance | -0.0975  |
|    learning_rate      | 0.0007   |
|    n_updates          | 4099     |
|    policy_loss        | 2.65e-06 |
|    value_loss         | 0.0337   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 37.3      |
|    ep_rew_mean        | 0.000107  |
| time/                 |           |
|    fps                | 538       |
|    iterations         | 4200      |
|    time_elapsed       | 38        |
|    total_timesteps    | 21000     |
| train/                |           |
|    entropy_loss       | -0.00623  |
|    explained_variance | -0.0738   |
|    learning_rate      | 0.0007    |
|    n_updates          | 4199      |
|    policy_loss        | -7.39e-06 |
|    value_loss         | 0.0058    |
-------------------------------------

2025-10-30 07:45:56,321 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:56,321 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-30.83, Commission=$0.00, Net=$-30.83 (cash flow: +$1969.17, -$0.00, balance: $9969.17)
2025-10-30 07:45:56,322 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 776/9953
2025-10-30 07:45:56,324 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112574.91
2025-10-30 07:45:56,324 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112574.91 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,325 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:56,327 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:56,361 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:56,361 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.87, Commission=$0.00, Net=$-1.87 (cash flow: -$2001.87, balance: $9998.13)
2025-10-30 07:45:56,362 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 732/9953
2025-10-30 07:45:56,364 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111773.38
2025-10-30 07:45:56,364 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111773.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,365 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:56,367 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:56,372 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:56,372 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.63, Commission=$0.00, Net=$-2.63 (cash flow: -$2002.63, balance: $9997.37)
2025-10-30 07:45:56,372 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6922/9953
2025-10-30 07:45:56,375 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109147.00
2025-10-30 07:45:56,375 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109147.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:56,376 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:45:56,377 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:56,410 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 07:45:56,411 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.19, Commission=$0.00, Net=$-2.19 (cash flow: +$1997.81, -$0.00, balance: $9997.81)
2025-10-30 07:45:56,412 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2041/9953
2025-10-30 07:45:56,414 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111984.36
2025-10-30 07:45:56,414 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111984.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,415 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:56,416 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:56,524 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:56,525 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.08, Commission=$0.00, Net=$-2.08 (cash flow: -$2002.08, balance: $9997.92)
2025-10-30 07:45:56,526 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3514/9953
2025-10-30 07:45:56,530 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108103.03
2025-10-30 07:45:56,530 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108103.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,531 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:56,533 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:56,752 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:56,753 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.36, Commission=$0.00, Net=$-1.36 (cash flow: -$2001.36, balance: $9998.64)
2025-10-30 07:45:56,753 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9089/9953
2025-10-30 07:45:56,757 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109906.99
2025-10-30 07:45:56,757 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109906.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,757 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:45:56,760 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 52.6     |
|    ep_rew_mean        | 6.11e-05 |
| time/                 |          |
|    fps                | 545      |
|    iterations         | 4300     |
|    time_elapsed       | 39       |
|    total_timesteps    | 21500    |
| train/                |          |
|    entropy_loss       | -0.814   |
|    explained_variance | 0.431    |
|    learning_rate      | 0.0007   |
|    n_updates          | 4299     |
|    policy_loss        | -0.489   |
|    value_loss         | 0.563    |
------------------------------------

2025-10-30 07:45:56,773 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:45:56,773 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.99, Commission=$0.00, Net=$-0.99 (cash flow: -$2000.99, balance: $9999.01)
2025-10-30 07:45:56,774 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1270/9953
2025-10-30 07:45:56,778 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113720.24
2025-10-30 07:45:56,778 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113720.24 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,778 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:45:56,782 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:56,976 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:45:56,976 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$16.71, Commission=$0.00, Net=$16.71 (cash flow: -$1983.29, balance: $10016.71)
2025-10-30 07:45:56,977 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9474/9953
2025-10-30 07:45:56,979 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110949.70
2025-10-30 07:45:56,979 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110949.70 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:56,980 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:45:56,984 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 54.6     |
|    ep_rew_mean        | 7.23e-05 |
| time/                 |          |
|    fps                | 551      |
|    iterations         | 4400     |
|    time_elapsed       | 39       |
|    total_timesteps    | 22000    |
| train/                |          |
|    entropy_loss       | -0.00965 |
|    explained_variance | -1.33    |
|    learning_rate      | 0.0007   |
|    n_updates          | 4399     |
|    policy_loss        | -7.4e-05 |
|    value_loss         | 0.0182   |
------------------------------------

2025-10-30 07:45:57,348 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:45:57,348 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-14.89, Commission=$0.00, Net=$-14.89 (cash flow: -$2014.89, balance: $9985.11)
2025-10-30 07:45:57,349 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9390/9953
2025-10-30 07:45:57,351 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110497.77
2025-10-30 07:45:57,352 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110497.77 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:57,352 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:57,355 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:57,491 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 07:45:57,491 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-9.66, Commission=$0.00, Net=$-9.66 (cash flow: -$2009.66, balance: $9990.34)
2025-10-30 07:45:57,492 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7458/9953
2025-10-30 07:45:57,497 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110463.60
2025-10-30 07:45:57,497 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110463.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:57,497 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:57,499 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:57,522 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:57,522 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$9.05, Commission=$0.00, Net=$9.05 (cash flow: -$1990.95, balance: $10009.05)
2025-10-30 07:45:57,523 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5248/9953
2025-10-30 07:45:57,527 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108135.20
2025-10-30 07:45:57,527 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108135.20 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:57,528 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:57,531 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:57,532 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:57,532 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.46, Commission=$0.00, Net=$1.46 (cash flow: +$2001.46, -$0.00, balance: $10001.46)
2025-10-30 07:45:57,533 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1814/9953
2025-10-30 07:45:57,536 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112501.18
2025-10-30 07:45:57,536 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112501.18 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:57,537 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:45:57,539 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 61        |
|    ep_rew_mean        | 5.3e-05   |
| time/                 |           |
|    fps                | 558       |
|    iterations         | 4500      |
|    time_elapsed       | 40        |
|    total_timesteps    | 22500     |
| train/                |           |
|    entropy_loss       | -0.0121   |
|    explained_variance | -1.25     |
|    learning_rate      | 0.0007    |
|    n_updates          | 4499      |
|    policy_loss        | -0.000332 |
|    value_loss         | 0.0531    |
-------------------------------------

2025-10-30 07:45:57,688 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:45:57,688 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$7.27, Commission=$0.00, Net=$7.27 (cash flow: -$1992.73, balance: $10007.27)
2025-10-30 07:45:57,689 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2732/9953
2025-10-30 07:45:57,694 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109166.11
2025-10-30 07:45:57,694 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109166.11 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:57,695 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:57,697 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:57,705 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 07:45:57,705 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.15, Commission=$0.00, Net=$0.15 (cash flow: -$1999.85, balance: $10000.15)
2025-10-30 07:45:57,705 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7471/9953
2025-10-30 07:45:57,710 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110524.28
2025-10-30 07:45:57,710 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110524.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:57,710 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:57,712 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:57,798 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:57,798 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.45, Commission=$0.00, Net=$-6.45 (cash flow: -$2006.45, balance: $9993.55)
2025-10-30 07:45:57,799 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3948/9953
2025-10-30 07:45:57,803 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108126.25
2025-10-30 07:45:57,803 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108126.25 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:57,804 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:57,805 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:57,813 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:57,813 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.45, Commission=$0.00, Net=$-1.45 (cash flow: -$2001.45, balance: $9998.55)
2025-10-30 07:45:57,814 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7777/9953
2025-10-30 07:45:57,818 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110432.68
2025-10-30 07:45:57,818 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110432.68 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:57,819 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:45:57,821 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:58,028 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:45:58,029 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.22, Commission=$0.00, Net=$4.22 (cash flow: +$2004.22, -$0.00, balance: $10004.22)
2025-10-30 07:45:58,029 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9934/9953
2025-10-30 07:45:58,031 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111771.00
2025-10-30 07:45:58,031 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111771.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:58,031 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:58,033 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:58,049 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8799/9953
2025-10-30 07:45:58,051 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111491.06
2025-10-30 07:45:58,051 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111491.06 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:58,051 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:58,056 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 66.3     |
|    ep_rew_mean        | 5.47e-05 |
| time/                 |          |
|    fps                | 564      |
|    iterations         | 4600     |
|    time_elapsed       | 40       |
|    total_timesteps    | 23000    |
| train/                |          |
|    entropy_loss       | -0.142   |
|    explained_variance | 0.05     |
|    learning_rate      | 0.0007   |
|    n_updates          | 4599     |
|    policy_loss        | 0.0111   |
|    value_loss         | 0.102    |
------------------------------------

2025-10-30 07:45:58,195 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:58,195 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$14.94, Commission=$0.00, Net=$14.94 (cash flow: -$1985.06, balance: $10014.94)
2025-10-30 07:45:58,196 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7490/9953
2025-10-30 07:45:58,198 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110003.88
2025-10-30 07:45:58,198 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110003.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:58,199 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:58,201 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:58,238 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:58,238 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.52, Commission=$0.00, Net=$3.52 (cash flow: +$2003.52, -$0.00, balance: $10003.52)
2025-10-30 07:45:58,239 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3617/9953
2025-10-30 07:45:58,243 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108487.30
2025-10-30 07:45:58,243 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108487.30 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:58,243 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:58,246 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 68.4      |
|    ep_rew_mean        | 7.38e-05  |
| time/                 |           |
|    fps                | 570       |
|    iterations         | 4700      |
|    time_elapsed       | 41        |
|    total_timesteps    | 23500     |
| train/                |           |
|    entropy_loss       | -0.0154   |
|    explained_variance | 0.354     |
|    learning_rate      | 0.0007    |
|    n_updates          | 4699      |
|    policy_loss        | -0.000188 |
|    value_loss         | 0.01      |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 68.4      |
|    ep_rew_mean        | 7.38e-05  |
| time/                 |           |
|    fps                | 577       |
|    iterations         | 4800      |
|    time_elapsed       | 41        |
|    total_timesteps    | 24000     |
| train/                |           |
|    entropy_loss       | -0.0175   |
|    explained_variance | -1.34     |
|    learning_rate      | 0.0007    |
|    n_updates          | 4799      |
|    policy_loss        | -0.000333 |
|    value_loss         | 0.018     |
-------------------------------------

2025-10-30 07:45:58,975 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:58,976 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.63, Commission=$0.00, Net=$-1.63 (cash flow: +$1998.37, -$0.00, balance: $9998.37)
2025-10-30 07:45:58,976 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7139/9953
2025-10-30 07:45:58,978 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109396.55
2025-10-30 07:45:58,979 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109396.55 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:58,980 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:58,984 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:58,986 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:58,987 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.01, Commission=$0.00, Net=$2.01 (cash flow: -$1997.99, balance: $10002.01)
2025-10-30 07:45:58,987 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3657/9953
2025-10-30 07:45:58,989 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108036.00
2025-10-30 07:45:58,989 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108036.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:58,990 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:58,991 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,221 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:45:59,222 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.44, Commission=$0.00, Net=$-2.44 (cash flow: -$2002.44, balance: $9997.56)
2025-10-30 07:45:59,222 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2265/9953
2025-10-30 07:45:59,224 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111982.48
2025-10-30 07:45:59,225 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111982.48 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:59,225 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:45:59,228 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 79.7      |
|    ep_rew_mean        | 6.91e-05  |
| time/                 |           |
|    fps                | 583       |
|    iterations         | 4900      |
|    time_elapsed       | 42        |
|    total_timesteps    | 24500     |
| train/                |           |
|    entropy_loss       | -0.00758  |
|    explained_variance | 0.144     |
|    learning_rate      | 0.0007    |
|    n_updates          | 4899      |
|    policy_loss        | -7.55e-05 |
|    value_loss         | 0.0632    |
-------------------------------------

2025-10-30 07:45:59,429 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:45:59,430 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$33.38, Commission=$0.00, Net=$33.38 (cash flow: -$1966.62, balance: $10033.38)
2025-10-30 07:45:59,430 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4967/9953
2025-10-30 07:45:59,432 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108400.51
2025-10-30 07:45:59,432 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108400.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:59,433 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:45:59,436 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,453 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:45:59,454 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$7.37, Commission=$0.00, Net=$7.37 (cash flow: +$2007.37, -$0.00, balance: $10007.37)
2025-10-30 07:45:59,454 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7265/9953
2025-10-30 07:45:59,458 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109645.90
2025-10-30 07:45:59,459 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109645.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:59,459 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:59,461 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,528 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:45:59,528 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.77, Commission=$0.00, Net=$5.77 (cash flow: +$2005.77, -$0.00, balance: $10005.77)
2025-10-30 07:45:59,529 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3047/9953
2025-10-30 07:45:59,531 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108411.02
2025-10-30 07:45:59,531 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108411.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:59,532 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:45:59,536 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,690 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:45:59,690 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.77, Commission=$0.00, Net=$-6.77 (cash flow: +$1993.23, -$0.00, balance: $9993.23)
2025-10-30 07:45:59,691 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7952/9953
2025-10-30 07:45:59,696 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110020.28
2025-10-30 07:45:59,696 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110020.28 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:45:59,696 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:45:59,699 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,748 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 07:45:59,748 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.74, Commission=$0.00, Net=$5.74 (cash flow: +$2005.74, -$0.00, balance: $10005.74)
2025-10-30 07:45:59,749 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 397/9953
2025-10-30 07:45:59,751 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110291.05
2025-10-30 07:45:59,752 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110291.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:59,752 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:45:59,754 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 85.3      |
|    ep_rew_mean        | 0.000105  |
| time/                 |           |
|    fps                | 588       |
|    iterations         | 5000      |
|    time_elapsed       | 42        |
|    total_timesteps    | 25000     |
| train/                |           |
|    entropy_loss       | -0.0178   |
|    explained_variance | -0.159    |
|    learning_rate      | 0.0007    |
|    n_updates          | 4999      |
|    policy_loss        | -0.000411 |
|    value_loss         | 0.0616    |
-------------------------------------

2025-10-30 07:45:59,857 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:45:59,858 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.96, Commission=$0.00, Net=$5.96 (cash flow: -$1994.04, balance: $10005.96)
2025-10-30 07:45:59,858 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3845/9953
2025-10-30 07:45:59,862 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107656.63
2025-10-30 07:45:59,862 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107656.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:59,863 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:45:59,867 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,880 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 07:45:59,880 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.85, Commission=$0.00, Net=$-2.85 (cash flow: -$2002.85, balance: $9997.15)
2025-10-30 07:45:59,881 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5018/9953
2025-10-30 07:45:59,883 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109016.21
2025-10-30 07:45:59,884 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109016.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:59,884 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:45:59,887 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:45:59,922 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 07:45:59,922 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.47, Commission=$0.00, Net=$0.47 (cash flow: -$1999.53, balance: $10000.47)
2025-10-30 07:45:59,923 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3703/9953
2025-10-30 07:45:59,927 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107900.00
2025-10-30 07:45:59,928 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107900.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:45:59,928 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:45:59,930 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:00,079 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:00,080 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.96, Commission=$0.00, Net=$-4.96 (cash flow: -$2004.96, balance: $9995.04)
2025-10-30 07:46:00,080 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3894/9953
2025-10-30 07:46:00,082 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108217.91
2025-10-30 07:46:00,083 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108217.91 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:00,084 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:00,087 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:00,126 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:00,126 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.41, Commission=$0.00, Net=$2.41 (cash flow: -$1997.59, balance: $10002.41)
2025-10-30 07:46:00,127 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9088/9953
2025-10-30 07:46:00,128 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109744.26
2025-10-30 07:46:00,129 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109744.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:00,129 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:46:00,132 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:00,150 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 07:46:00,150 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-7.16, Commission=$0.00, Net=$-7.16 (cash flow: -$2007.16, balance: $9992.84)
2025-10-30 07:46:00,151 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3040/9953
2025-10-30 07:46:00,153 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108357.94
2025-10-30 07:46:00,153 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108357.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:00,154 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:00,156 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 86.7     |
|    ep_rew_mean        | 9.59e-05 |
| time/                 |          |
|    fps                | 594      |
|    iterations         | 5100     |
|    time_elapsed       | 42       |
|    total_timesteps    | 25500    |
| train/                |          |
|    entropy_loss       | -0.0235  |
|    explained_variance | 0.226    |
|    learning_rate      | 0.0007   |
|    n_updates          | 5099     |
|    policy_loss        | 0.000587 |
|    value_loss         | 0.0365   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 86.7      |
|    ep_rew_mean        | 9.59e-05  |
| time/                 |           |
|    fps                | 600       |
|    iterations         | 5200      |
|    time_elapsed       | 43        |
|    total_timesteps    | 26000     |
| train/                |           |
|    entropy_loss       | -0.00534  |
|    explained_variance | 0.483     |
|    learning_rate      | 0.0007    |
|    n_updates          | 5199      |
|    policy_loss        | -1.54e-05 |
|    value_loss         | 0.00581   |
-------------------------------------

2025-10-30 07:46:00,990 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:00,990 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$7.15, Commission=$0.00, Net=$7.15 (cash flow: -$1992.85, balance: $10007.15)
2025-10-30 07:46:00,991 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8003/9953
2025-10-30 07:46:00,992 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110216.88
2025-10-30 07:46:00,993 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110216.88 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:00,994 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:46:00,999 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:01,020 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:46:01,021 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-6.95, Commission=$0.00, Net=$-6.95 (cash flow: -$2006.95, balance: $9993.05)
2025-10-30 07:46:01,021 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2948/9953
2025-10-30 07:46:01,023 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108320.03
2025-10-30 07:46:01,023 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108320.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:01,024 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:01,029 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 97       |
|    ep_rew_mean        | 9.54e-05 |
| time/                 |          |
|    fps                | 605      |
|    iterations         | 5300     |
|    time_elapsed       | 43       |
|    total_timesteps    | 26500    |
| train/                |          |
|    entropy_loss       | -0.0106  |
|    explained_variance | 0.483    |
|    learning_rate      | 0.0007   |
|    n_updates          | 5299     |
|    policy_loss        | 0.000686 |
|    value_loss         | 0.29     |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 97       |
|    ep_rew_mean        | 9.54e-05 |
| time/                 |          |
|    fps                | 611      |
|    iterations         | 5400     |
|    time_elapsed       | 44       |
|    total_timesteps    | 27000    |
| train/                |          |
|    entropy_loss       | -0.00352 |
|    explained_variance | 0.265    |
|    learning_rate      | 0.0007   |
|    n_updates          | 5399     |
|    policy_loss        | 0.000103 |
|    value_loss         | 0.136    |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 97        |
|    ep_rew_mean        | 9.54e-05  |
| time/                 |           |
|    fps                | 617       |
|    iterations         | 5500      |
|    time_elapsed       | 44        |
|    total_timesteps    | 27500     |
| train/                |           |
|    entropy_loss       | -0.00287  |
|    explained_variance | 0.381     |
|    learning_rate      | 0.0007    |
|    n_updates          | 5499      |
|    policy_loss        | -2.47e-05 |
|    value_loss         | 0.0117    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 97       |
|    ep_rew_mean        | 9.54e-05 |
| time/                 |          |
|    fps                | 622      |
|    iterations         | 5600     |
|    time_elapsed       | 44       |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -0.00419 |
|    explained_variance | 0.654    |
|    learning_rate      | 0.0007   |
|    n_updates          | 5599     |
|    policy_loss        | 0.000142 |
|    value_loss         | 0.0888   |
------------------------------------

2025-10-30 07:46:02,440 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:02,440 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-5.90, Commission=$0.00, Net=$-5.90 (cash flow: -$2005.90, balance: $9994.10)
2025-10-30 07:46:02,441 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2359/9953
2025-10-30 07:46:02,445 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111335.63
2025-10-30 07:46:02,445 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111335.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:02,446 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:02,448 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 114       |
|    ep_rew_mean        | 8.53e-05  |
| time/                 |           |
|    fps                | 627       |
|    iterations         | 5700      |
|    time_elapsed       | 45        |
|    total_timesteps    | 28500     |
| train/                |           |
|    entropy_loss       | -0.00241  |
|    explained_variance | 0.0922    |
|    learning_rate      | 0.0007    |
|    n_updates          | 5699      |
|    policy_loss        | -0.000128 |
|    value_loss         | 0.276     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 114       |
|    ep_rew_mean        | 8.53e-05  |
| time/                 |           |
|    fps                | 632       |
|    iterations         | 5800      |
|    time_elapsed       | 45        |
|    total_timesteps    | 29000     |
| train/                |           |
|    entropy_loss       | -0.00159  |
|    explained_variance | -0.132    |
|    learning_rate      | 0.0007    |
|    n_updates          | 5799      |
|    policy_loss        | -2.04e-05 |
|    value_loss         | 0.0467    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 114       |
|    ep_rew_mean        | 8.53e-05  |
| time/                 |           |
|    fps                | 637       |
|    iterations         | 5900      |
|    time_elapsed       | 46        |
|    total_timesteps    | 29500     |
| train/                |           |
|    entropy_loss       | -0.00151  |
|    explained_variance | -0.26     |
|    learning_rate      | 0.0007    |
|    n_updates          | 5899      |
|    policy_loss        | -3.38e-07 |
|    value_loss         | 0.00843   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 114       |
|    ep_rew_mean        | 8.53e-05  |
| time/                 |           |
|    fps                | 641       |
|    iterations         | 6000      |
|    time_elapsed       | 46        |
|    total_timesteps    | 30000     |
| train/                |           |
|    entropy_loss       | -0.00423  |
|    explained_variance | 0.08      |
|    learning_rate      | 0.0007    |
|    n_updates          | 5999      |
|    policy_loss        | -0.000205 |
|    value_loss         | 0.214     |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 114      |
|    ep_rew_mean        | 8.53e-05 |
| time/                 |          |
|    fps                | 646      |
|    iterations         | 6100     |
|    time_elapsed       | 47       |
|    total_timesteps    | 30500    |
| train/                |          |
|    entropy_loss       | -0.00158 |
|    explained_variance | -0.1     |
|    learning_rate      | 0.0007   |
|    n_updates          | 6099     |
|    policy_loss        | 4.83e-05 |
|    value_loss         | 0.124    |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 114       |
|    ep_rew_mean        | 8.53e-05  |
| time/                 |           |
|    fps                | 650       |
|    iterations         | 6200      |
|    time_elapsed       | 47        |
|    total_timesteps    | 31000     |
| train/                |           |
|    entropy_loss       | -0.0027   |
|    explained_variance | 0.138     |
|    learning_rate      | 0.0007    |
|    n_updates          | 6199      |
|    policy_loss        | -0.000271 |
|    value_loss         | 0.864     |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 114      |
|    ep_rew_mean        | 8.53e-05 |
| time/                 |          |
|    fps                | 653      |
|    iterations         | 6300     |
|    time_elapsed       | 48       |
|    total_timesteps    | 31500    |
| train/                |          |
|    entropy_loss       | -0.00138 |
|    explained_variance | 0.115    |
|    learning_rate      | 0.0007   |
|    n_updates          | 6299     |
|    policy_loss        | 2.92e-05 |
|    value_loss         | 0.0728   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 114      |
|    ep_rew_mean        | 8.53e-05 |
| time/                 |          |
|    fps                | 657      |
|    iterations         | 6400     |
|    time_elapsed       | 48       |
|    total_timesteps    | 32000    |
| train/                |          |
|    entropy_loss       | -0.00145 |
|    explained_variance | 0.61     |
|    learning_rate      | 0.0007   |
|    n_updates          | 6399     |
|    policy_loss        | 2.39e-05 |
|    value_loss         | 0.0298   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 114       |
|    ep_rew_mean        | 8.53e-05  |
| time/                 |           |
|    fps                | 660       |
|    iterations         | 6500      |
|    time_elapsed       | 49        |
|    total_timesteps    | 32500     |
| train/                |           |
|    entropy_loss       | -0.00261  |
|    explained_variance | 0.149     |
|    learning_rate      | 0.0007    |
|    n_updates          | 6499      |
|    policy_loss        | -1.59e-05 |
|    value_loss         | 0.0124    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 114      |
|    ep_rew_mean        | 8.53e-05 |
| time/                 |          |
|    fps                | 663      |
|    iterations         | 6600     |
|    time_elapsed       | 49       |
|    total_timesteps    | 33000    |
| train/                |          |
|    entropy_loss       | -0.00547 |
|    explained_variance | 0.147    |
|    learning_rate      | 0.0007   |
|    n_updates          | 6599     |
|    policy_loss        | 0.000135 |
|    value_loss         | 0.0605   |
------------------------------------

2025-10-30 07:46:07,463 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:46:07,463 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$6.75, Commission=$0.00, Net=$6.75 (cash flow: -$1993.25, balance: $10006.75)
2025-10-30 07:46:07,464 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8744/9953
2025-10-30 07:46:07,466 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112000.00
2025-10-30 07:46:07,466 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:07,467 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:07,470 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 165       |
|    ep_rew_mean        | 8.67e-05  |
| time/                 |           |
|    fps                | 666       |
|    iterations         | 6700      |
|    time_elapsed       | 50        |
|    total_timesteps    | 33500     |
| train/                |           |
|    entropy_loss       | -0.00287  |
|    explained_variance | -0.0253   |
|    learning_rate      | 0.0007    |
|    n_updates          | 6699      |
|    policy_loss        | -7.34e-05 |
|    value_loss         | 0.0677    |
-------------------------------------

2025-10-30 07:46:07,857 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:46:07,858 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$26.83, Commission=$0.00, Net=$26.83 (cash flow: -$1973.17, balance: $10026.83)
2025-10-30 07:46:07,859 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9238/9953
2025-10-30 07:46:07,861 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110345.66
2025-10-30 07:46:07,861 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110345.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:07,862 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:46:07,867 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:07,964 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:46:07,964 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.20, Commission=$0.00, Net=$-0.20 (cash flow: +$1999.80, -$0.00, balance: $9999.80)
2025-10-30 07:46:07,965 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7861/9953
2025-10-30 07:46:07,967 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109647.43
2025-10-30 07:46:07,967 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109647.43 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:07,968 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:07,971 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 166      |
|    ep_rew_mean        | 0.000108 |
| time/                 |          |
|    fps                | 670      |
|    iterations         | 6800     |
|    time_elapsed       | 50       |
|    total_timesteps    | 34000    |
| train/                |          |
|    entropy_loss       | -0.0291  |
|    explained_variance | 0.575    |
|    learning_rate      | 0.0007   |
|    n_updates          | 6799     |
|    policy_loss        | 0.000139 |
|    value_loss         | 0.00618  |
------------------------------------

2025-10-30 07:46:08,081 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:08,082 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$13.11, Commission=$0.00, Net=$13.11 (cash flow: +$2013.11, -$0.00, balance: $10013.11)
2025-10-30 07:46:08,082 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1865/9953
2025-10-30 07:46:08,084 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112279.21
2025-10-30 07:46:08,084 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112279.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:08,085 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:46:08,087 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 167       |
|    ep_rew_mean        | 0.00012   |
| time/                 |           |
|    fps                | 675       |
|    iterations         | 6900      |
|    time_elapsed       | 51        |
|    total_timesteps    | 34500     |
| train/                |           |
|    entropy_loss       | -0.0083   |
|    explained_variance | 0.358     |
|    learning_rate      | 0.0007    |
|    n_updates          | 6899      |
|    policy_loss        | -0.000238 |
|    value_loss         | 0.0664    |
-------------------------------------

2025-10-30 07:46:08,750 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:46:08,751 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$56.31, Commission=$0.00, Net=$56.31 (cash flow: -$1943.69, balance: $10056.31)
2025-10-30 07:46:08,752 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8042/9953
2025-10-30 07:46:08,753 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110609.84
2025-10-30 07:46:08,754 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110609.84 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:08,754 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:46:08,757 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 175      |
|    ep_rew_mean        | 0.000175 |
| time/                 |          |
|    fps                | 679      |
|    iterations         | 7000     |
|    time_elapsed       | 51       |
|    total_timesteps    | 35000    |
| train/                |          |
|    entropy_loss       | -0.00632 |
|    explained_variance | 0.416    |
|    learning_rate      | 0.0007   |
|    n_updates          | 6999     |
|    policy_loss        | 9.78e-05 |
|    value_loss         | 0.035    |
------------------------------------

2025-10-30 07:46:08,887 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:46:08,888 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-12.43, Commission=$0.00, Net=$-12.43 (cash flow: -$2012.43, balance: $9987.57)
2025-10-30 07:46:08,888 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7251/9953
2025-10-30 07:46:08,890 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109721.09
2025-10-30 07:46:08,891 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109721.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:08,892 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:08,893 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:09,102 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:09,102 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 07:46:09,103 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4716/9953
2025-10-30 07:46:09,107 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108360.37
2025-10-30 07:46:09,107 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108360.37 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:09,108 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:09,109 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:09,165 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:09,166 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$12.60, Commission=$0.00, Net=$12.60 (cash flow: -$1987.40, balance: $10012.60)
2025-10-30 07:46:09,167 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 418/9953
2025-10-30 07:46:09,169 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110261.00
2025-10-30 07:46:09,169 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110261.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:09,170 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:46:09,175 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 178      |
|    ep_rew_mean        | 0.000181 |
| time/                 |          |
|    fps                | 683      |
|    iterations         | 7100     |
|    time_elapsed       | 51       |
|    total_timesteps    | 35500    |
| train/                |          |
|    entropy_loss       | -0.0274  |
|    explained_variance | 0.445    |
|    learning_rate      | 0.0007   |
|    n_updates          | 7099     |
|    policy_loss        | 0.00135  |
|    value_loss         | 0.19     |
------------------------------------

2025-10-30 07:46:09,285 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 07:46:09,286 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-11.74, Commission=$0.00, Net=$-11.74 (cash flow: -$2011.74, balance: $9988.26)
2025-10-30 07:46:09,286 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4620/9953
2025-10-30 07:46:09,290 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108500.00
2025-10-30 07:46:09,291 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108500.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:09,291 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:46:09,293 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 180      |
|    ep_rew_mean        | 0.000172 |
| time/                 |          |
|    fps                | 687      |
|    iterations         | 7200     |
|    time_elapsed       | 52       |
|    total_timesteps    | 36000    |
| train/                |          |
|    entropy_loss       | -0.014   |
|    explained_variance | 0.0572   |
|    learning_rate      | 0.0007   |
|    n_updates          | 7199     |
|    policy_loss        | 0.000307 |
|    value_loss         | 0.0265   |
------------------------------------

2025-10-30 07:46:09,739 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:46:09,739 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.84, Commission=$0.00, Net=$-1.84 (cash flow: -$2001.84, balance: $9998.16)
2025-10-30 07:46:09,740 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5459/9953
2025-10-30 07:46:09,744 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107810.99
2025-10-30 07:46:09,745 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107810.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:09,745 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:46:09,747 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:10,020 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:46:10,020 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-8.46, Commission=$0.00, Net=$-8.46 (cash flow: +$1991.54, -$0.00, balance: $9991.54)
2025-10-30 07:46:10,021 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5123/9953
2025-10-30 07:46:10,025 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107877.73
2025-10-30 07:46:10,025 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107877.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:10,025 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:10,028 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 188      |
|    ep_rew_mean        | 0.000158 |
| time/                 |          |
|    fps                | 691      |
|    iterations         | 7300     |
|    time_elapsed       | 52       |
|    total_timesteps    | 36500    |
| train/                |          |
|    entropy_loss       | -0.0547  |
|    explained_variance | 0.137    |
|    learning_rate      | 0.0007   |
|    n_updates          | 7299     |
|    policy_loss        | 0.00132  |
|    value_loss         | 0.0442   |
------------------------------------

2025-10-30 07:46:10,099 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:10,099 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$11.28, Commission=$0.00, Net=$11.28 (cash flow: +$2011.28, -$0.00, balance: $10011.28)
2025-10-30 07:46:10,100 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 577/9953
2025-10-30 07:46:10,102 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111277.33
2025-10-30 07:46:10,103 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111277.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:10,103 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:10,105 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 189       |
|    ep_rew_mean        | 0.000167  |
| time/                 |           |
|    fps                | 695       |
|    iterations         | 7400      |
|    time_elapsed       | 53        |
|    total_timesteps    | 37000     |
| train/                |           |
|    entropy_loss       | -0.00538  |
|    explained_variance | -0.125    |
|    learning_rate      | 0.0007    |
|    n_updates          | 7399      |
|    policy_loss        | -0.000166 |
|    value_loss         | 0.0789    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 189      |
|    ep_rew_mean        | 0.000167 |
| time/                 |          |
|    fps                | 699      |
|    iterations         | 7500     |
|    time_elapsed       | 53       |
|    total_timesteps    | 37500    |
| train/                |          |
|    entropy_loss       | -0.00298 |
|    explained_variance | -0.0511  |
|    learning_rate      | 0.0007   |
|    n_updates          | 7499     |
|    policy_loss        | 5.5e-05  |
|    value_loss         | 0.064    |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 189       |
|    ep_rew_mean        | 0.000167  |
| time/                 |           |
|    fps                | 703       |
|    iterations         | 7600      |
|    time_elapsed       | 54        |
|    total_timesteps    | 38000     |
| train/                |           |
|    entropy_loss       | -0.00327  |
|    explained_variance | -1.01     |
|    learning_rate      | 0.0007    |
|    n_updates          | 7599      |
|    policy_loss        | -6.13e-05 |
|    value_loss         | 0.0329    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 189       |
|    ep_rew_mean        | 0.000167  |
| time/                 |           |
|    fps                | 706       |
|    iterations         | 7700      |
|    time_elapsed       | 54        |
|    total_timesteps    | 38500     |
| train/                |           |
|    entropy_loss       | -0.00241  |
|    explained_variance | 0.319     |
|    learning_rate      | 0.0007    |
|    n_updates          | 7699      |
|    policy_loss        | -2.84e-05 |
|    value_loss         | 0.0221    |
-------------------------------------

2025-10-30 07:46:11,946 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:46:11,946 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$43.90, Commission=$0.00, Net=$43.90 (cash flow: -$1956.10, balance: $10043.90)
2025-10-30 07:46:11,947 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4533/9953
2025-10-30 07:46:11,950 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107873.93
2025-10-30 07:46:11,951 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107873.93 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:11,951 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:11,954 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:12,105 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:12,105 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$9.29, Commission=$0.00, Net=$9.29 (cash flow: +$2009.29, -$0.00, balance: $10009.29)
2025-10-30 07:46:12,106 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3924/9953
2025-10-30 07:46:12,108 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108186.74
2025-10-30 07:46:12,109 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108186.74 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:12,109 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:12,112 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:12,127 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:12,127 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: +$1999.65, -$0.00, balance: $9999.65)
2025-10-30 07:46:12,128 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9783/9953
2025-10-30 07:46:12,130 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111271.57
2025-10-30 07:46:12,131 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111271.57 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:12,131 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:12,134 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 212      |
|    ep_rew_mean        | 0.000208 |
| time/                 |          |
|    fps                | 709      |
|    iterations         | 7800     |
|    time_elapsed       | 54       |
|    total_timesteps    | 39000    |
| train/                |          |
|    entropy_loss       | -0.0012  |
|    explained_variance | -0.00774 |
|    learning_rate      | 0.0007   |
|    n_updates          | 7799     |
|    policy_loss        | 3.22e-05 |
|    value_loss         | 0.078    |
------------------------------------

2025-10-30 07:46:12,280 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8754/9953
2025-10-30 07:46:12,282 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111961.40
2025-10-30 07:46:12,282 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111961.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:12,282 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:46:12,285 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:12,303 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:46:12,304 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.06, Commission=$0.00, Net=$-1.06 (cash flow: +$1998.94, -$0.00, balance: $9998.94)
2025-10-30 07:46:12,304 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8651/9953
2025-10-30 07:46:12,306 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110944.00
2025-10-30 07:46:12,307 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110944.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:12,308 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:12,313 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 213      |
|    ep_rew_mean        | 0.000191 |
| time/                 |          |
|    fps                | 713      |
|    iterations         | 7900     |
|    time_elapsed       | 55       |
|    total_timesteps    | 39500    |
| train/                |          |
|    entropy_loss       | -0.0169  |
|    explained_variance | 0.255    |
|    learning_rate      | 0.0007   |
|    n_updates          | 7899     |
|    policy_loss        | 0.00103  |
|    value_loss         | 0.261    |
------------------------------------

2025-10-30 07:46:12,730 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:46:12,730 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$18.25, Commission=$0.00, Net=$18.25 (cash flow: -$1981.75, balance: $10018.25)
2025-10-30 07:46:12,731 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1340/9953
2025-10-30 07:46:12,736 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113533.43
2025-10-30 07:46:12,736 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113533.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:12,736 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:46:12,738 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:12,967 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:46:12,968 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$27.01, Commission=$0.00, Net=$27.01 (cash flow: -$1972.99, balance: $10027.01)
2025-10-30 07:46:12,969 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6732/9953
2025-10-30 07:46:12,973 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109714.00
2025-10-30 07:46:12,973 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109714.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:12,974 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:46:12,975 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:13,004 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:46:13,005 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$5.27, Commission=$0.00, Net=$5.27 (cash flow: -$1994.73, balance: $10005.27)
2025-10-30 07:46:13,006 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7146/9953
2025-10-30 07:46:13,007 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109409.79
2025-10-30 07:46:13,008 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109409.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:13,008 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:46:13,011 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:13,019 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:46:13,019 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.80, Commission=$0.00, Net=$1.80 (cash flow: +$2001.80, -$0.00, balance: $10001.80)
2025-10-30 07:46:13,020 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2768/9953
2025-10-30 07:46:13,025 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108880.85
2025-10-30 07:46:13,025 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108880.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:13,026 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:46:13,029 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:13,045 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 07:46:13,045 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.25, Commission=$0.00, Net=$2.25 (cash flow: -$1997.75, balance: $10002.25)
2025-10-30 07:46:13,046 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3385/9953
2025-10-30 07:46:13,050 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108243.00
2025-10-30 07:46:13,050 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108243.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:13,051 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:13,053 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 220      |
|    ep_rew_mean        | 0.000246 |
| time/                 |          |
|    fps                | 715      |
|    iterations         | 8000     |
|    time_elapsed       | 55       |
|    total_timesteps    | 40000    |
| train/                |          |
|    entropy_loss       | -0.00265 |
|    explained_variance | -0.596   |
|    learning_rate      | 0.0007   |
|    n_updates          | 7999     |
|    policy_loss        | 3.28e-05 |
|    value_loss         | 0.0441   |
------------------------------------

2025-10-30 07:46:13,537 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:13,537 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.87, Commission=$0.00, Net=$2.87 (cash flow: -$1997.13, balance: $10002.87)
2025-10-30 07:46:13,538 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2805/9953
2025-10-30 07:46:13,540 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109164.58
2025-10-30 07:46:13,540 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109164.58 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:13,541 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:46:13,544 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:13,561 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:46:13,561 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.37, Commission=$0.00, Net=$1.37 (cash flow: +$2001.37, -$0.00, balance: $10001.37)
2025-10-30 07:46:13,562 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2766/9953
2025-10-30 07:46:13,563 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108961.24
2025-10-30 07:46:13,563 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108961.24 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:13,564 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:13,566 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:13,580 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:13,580 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.71, Commission=$0.00, Net=$-2.71 (cash flow: +$1997.29, -$0.00, balance: $9997.29)
2025-10-30 07:46:13,581 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3436/9953
2025-10-30 07:46:13,583 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108194.46
2025-10-30 07:46:13,583 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108194.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:13,584 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:13,586 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 225       |
|    ep_rew_mean        | 0.000253  |
| time/                 |           |
|    fps                | 719       |
|    iterations         | 8100      |
|    time_elapsed       | 56        |
|    total_timesteps    | 40500     |
| train/                |           |
|    entropy_loss       | -0.00113  |
|    explained_variance | 0.0722    |
|    learning_rate      | 0.0007    |
|    n_updates          | 8099      |
|    policy_loss        | -5.49e-06 |
|    value_loss         | 0.00832   |
-------------------------------------

2025-10-30 07:46:13,934 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 07:46:13,934 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$8.74, Commission=$0.00, Net=$8.74 (cash flow: -$1991.26, balance: $10008.74)
2025-10-30 07:46:13,935 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9150/9953
2025-10-30 07:46:13,937 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110013.28
2025-10-30 07:46:13,938 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110013.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:13,938 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:46:13,940 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 229       |
|    ep_rew_mean        | 0.000263  |
| time/                 |           |
|    fps                | 722       |
|    iterations         | 8200      |
|    time_elapsed       | 56        |
|    total_timesteps    | 41000     |
| train/                |           |
|    entropy_loss       | -0.000802 |
|    explained_variance | 0.161     |
|    learning_rate      | 0.0007    |
|    n_updates          | 8199      |
|    policy_loss        | -4e-05    |
|    value_loss         | 0.287     |
-------------------------------------

2025-10-30 07:46:14,345 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 07:46:14,345 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-12.79, Commission=$0.00, Net=$-12.79 (cash flow: -$2012.79, balance: $9987.21)
2025-10-30 07:46:14,346 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2348/9953
2025-10-30 07:46:14,350 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111664.87
2025-10-30 07:46:14,350 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111664.87 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:14,350 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:14,354 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:14,393 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 07:46:14,394 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$17.66, Commission=$0.00, Net=$17.66 (cash flow: -$1982.34, balance: $10017.66)
2025-10-30 07:46:14,394 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 792/9953
2025-10-30 07:46:14,398 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112706.05
2025-10-30 07:46:14,399 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112706.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:14,399 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:46:14,400 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 234       |
|    ep_rew_mean        | 0.000259  |
| time/                 |           |
|    fps                | 726       |
|    iterations         | 8300      |
|    time_elapsed       | 57        |
|    total_timesteps    | 41500     |
| train/                |           |
|    entropy_loss       | -0.000387 |
|    explained_variance | -0.103    |
|    learning_rate      | 0.0007    |
|    n_updates          | 8299      |
|    policy_loss        | 3.22e-06  |
|    value_loss         | 0.0139    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 234       |
|    ep_rew_mean        | 0.000259  |
| time/                 |           |
|    fps                | 729       |
|    iterations         | 8400      |
|    time_elapsed       | 57        |
|    total_timesteps    | 42000     |
| train/                |           |
|    entropy_loss       | -0.000322 |
|    explained_variance | -0.209    |
|    learning_rate      | 0.0007    |
|    n_updates          | 8399      |
|    policy_loss        | -2.2e-06  |
|    value_loss         | 0.0114    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 234       |
|    ep_rew_mean        | 0.000259  |
| time/                 |           |
|    fps                | 732       |
|    iterations         | 8500      |
|    time_elapsed       | 57        |
|    total_timesteps    | 42500     |
| train/                |           |
|    entropy_loss       | -0.000407 |
|    explained_variance | 0.181     |
|    learning_rate      | 0.0007    |
|    n_updates          | 8499      |
|    policy_loss        | 3.12e-06  |
|    value_loss         | 0.0129    |
-------------------------------------

2025-10-30 07:46:15,670 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:46:15,670 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$17.29, Commission=$0.00, Net=$17.29 (cash flow: -$1982.71, balance: $10017.29)
2025-10-30 07:46:15,671 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2432/9953
2025-10-30 07:46:15,675 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110848.07
2025-10-30 07:46:15,676 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110848.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:15,676 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:15,678 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 249      |
|    ep_rew_mean        | 0.000276 |
| time/                 |          |
|    fps                | 735      |
|    iterations         | 8600     |
|    time_elapsed       | 58       |
|    total_timesteps    | 43000    |
| train/                |          |
|    entropy_loss       | -0.00252 |
|    explained_variance | -0.132   |
|    learning_rate      | 0.0007   |
|    n_updates          | 8599     |
|    policy_loss        | -6.7e-05 |
|    value_loss         | 0.51     |
------------------------------------

2025-10-30 07:46:15,877 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:46:15,878 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$31.21, Commission=$0.00, Net=$31.21 (cash flow: -$1968.79, balance: $10031.21)
2025-10-30 07:46:15,878 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6743/9953
2025-10-30 07:46:15,880 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109600.09
2025-10-30 07:46:15,880 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109600.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:15,881 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:15,884 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:15,888 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:15,889 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.51, Commission=$0.00, Net=$-1.51 (cash flow: +$1998.49, -$0.00, balance: $9998.49)
2025-10-30 07:46:15,889 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3655/9953
2025-10-30 07:46:15,891 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108109.93
2025-10-30 07:46:15,892 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108109.93 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:15,893 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:15,894 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:15,901 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:15,901 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.77, Commission=$0.00, Net=$-2.77 (cash flow: +$1997.23, -$0.00, balance: $9997.23)
2025-10-30 07:46:15,902 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3495/9953
2025-10-30 07:46:15,903 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108050.01
2025-10-30 07:46:15,904 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108050.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:15,904 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 07:46:15,909 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 251       |
|    ep_rew_mean        | 0.000304  |
| time/                 |           |
|    fps                | 739       |
|    iterations         | 8700      |
|    time_elapsed       | 58        |
|    total_timesteps    | 43500     |
| train/                |           |
|    entropy_loss       | -0.000193 |
|    explained_variance | -0.134    |
|    learning_rate      | 0.0007    |
|    n_updates          | 8699      |
|    policy_loss        | 4.44e-06  |
|    value_loss         | 0.0878    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 251       |
|    ep_rew_mean        | 0.000304  |
| time/                 |           |
|    fps                | 742       |
|    iterations         | 8800      |
|    time_elapsed       | 59        |
|    total_timesteps    | 44000     |
| train/                |           |
|    entropy_loss       | -0.000464 |
|    explained_variance | 0.000203  |
|    learning_rate      | 0.0007    |
|    n_updates          | 8799      |
|    policy_loss        | 1.45e-05  |
|    value_loss         | 0.285     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 251       |
|    ep_rew_mean        | 0.000304  |
| time/                 |           |
|    fps                | 745       |
|    iterations         | 8900      |
|    time_elapsed       | 59        |
|    total_timesteps    | 44500     |
| train/                |           |
|    entropy_loss       | -0.000777 |
|    explained_variance | 0.165     |
|    learning_rate      | 0.0007    |
|    n_updates          | 8899      |
|    policy_loss        | 3.25e-05  |
|    value_loss         | 0.104     |
-------------------------------------

2025-10-30 07:46:17,036 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 07:46:17,036 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$6.29, Commission=$0.00, Net=$6.29 (cash flow: -$1993.71, balance: $10006.29)
2025-10-30 07:46:17,037 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7586/9953
2025-10-30 07:46:17,038 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110908.39
2025-10-30 07:46:17,039 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110908.39 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:17,040 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:17,042 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:17,254 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:46:17,254 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$24.50, Commission=$0.00, Net=$24.50 (cash flow: -$1975.50, balance: $10024.50)
2025-10-30 07:46:17,255 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1813/9953
2025-10-30 07:46:17,257 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112480.29
2025-10-30 07:46:17,258 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112480.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:17,258 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:46:17,260 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 267       |
|    ep_rew_mean        | 0.000334  |
| time/                 |           |
|    fps                | 748       |
|    iterations         | 9000      |
|    time_elapsed       | 60        |
|    total_timesteps    | 45000     |
| train/                |           |
|    entropy_loss       | -0.000264 |
|    explained_variance | 0.269     |
|    learning_rate      | 0.0007    |
|    n_updates          | 8999      |
|    policy_loss        | 2.92e-07  |
|    value_loss         | 0.00197   |
-------------------------------------

2025-10-30 07:46:17,743 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:46:17,743 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$30.62, Commission=$0.00, Net=$30.62 (cash flow: -$1969.38, balance: $10030.62)
2025-10-30 07:46:17,744 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6713/9953
2025-10-30 07:46:17,746 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109620.00
2025-10-30 07:46:17,746 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109620.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:17,747 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 07:46:17,749 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 273       |
|    ep_rew_mean        | 0.000361  |
| time/                 |           |
|    fps                | 751       |
|    iterations         | 9100      |
|    time_elapsed       | 60        |
|    total_timesteps    | 45500     |
| train/                |           |
|    entropy_loss       | -9.97e-05 |
|    explained_variance | -0.226    |
|    learning_rate      | 0.0007    |
|    n_updates          | 9099      |
|    policy_loss        | -3.58e-06 |
|    value_loss         | 0.339     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 273       |
|    ep_rew_mean        | 0.000361  |
| time/                 |           |
|    fps                | 754       |
|    iterations         | 9200      |
|    time_elapsed       | 60        |
|    total_timesteps    | 46000     |
| train/                |           |
|    entropy_loss       | -0.000148 |
|    explained_variance | 0.57      |
|    learning_rate      | 0.0007    |
|    n_updates          | 9199      |
|    policy_loss        | 2.09e-06  |
|    value_loss         | 0.0658    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 273       |
|    ep_rew_mean        | 0.000361  |
| time/                 |           |
|    fps                | 757       |
|    iterations         | 9300      |
|    time_elapsed       | 61        |
|    total_timesteps    | 46500     |
| train/                |           |
|    entropy_loss       | -0.000101 |
|    explained_variance | 0.166     |
|    learning_rate      | 0.0007    |
|    n_updates          | 9299      |
|    policy_loss        | 1.92e-06  |
|    value_loss         | 0.0714    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 273       |
|    ep_rew_mean        | 0.000361  |
| time/                 |           |
|    fps                | 760       |
|    iterations         | 9400      |
|    time_elapsed       | 61        |
|    total_timesteps    | 47000     |
| train/                |           |
|    entropy_loss       | -0.000143 |
|    explained_variance | 0.095     |
|    learning_rate      | 0.0007    |
|    n_updates          | 9399      |
|    policy_loss        | 1.08e-07  |
|    value_loss         | 0.00546   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 273       |
|    ep_rew_mean        | 0.000361  |
| time/                 |           |
|    fps                | 763       |
|    iterations         | 9500      |
|    time_elapsed       | 62        |
|    total_timesteps    | 47500     |
| train/                |           |
|    entropy_loss       | -0.000142 |
|    explained_variance | 0.0306    |
|    learning_rate      | 0.0007    |
|    n_updates          | 9499      |
|    policy_loss        | -2.92e-06 |
|    value_loss         | 0.161     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 273       |
|    ep_rew_mean        | 0.000361  |
| time/                 |           |
|    fps                | 765       |
|    iterations         | 9600      |
|    time_elapsed       | 62        |
|    total_timesteps    | 48000     |
| train/                |           |
|    entropy_loss       | -0.000126 |
|    explained_variance | -0.0607   |
|    learning_rate      | 0.0007    |
|    n_updates          | 9599      |
|    policy_loss        | 2.92e-06  |
|    value_loss         | 0.0972    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 273      |
|    ep_rew_mean        | 0.000361 |
| time/                 |          |
|    fps                | 767      |
|    iterations         | 9700     |
|    time_elapsed       | 63       |
|    total_timesteps    | 48500    |
| train/                |          |
|    entropy_loss       | -0.00016 |
|    explained_variance | -0.154   |
|    learning_rate      | 0.0007   |
|    n_updates          | 9699     |
|    policy_loss        | 1.36e-06 |
|    value_loss         | 0.0198   |
------------------------------------

2025-10-30 07:46:20,635 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8225/9953
2025-10-30 07:46:20,637 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111207.19
2025-10-30 07:46:20,637 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111207.19 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:20,637 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:20,639 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 305       |
|    ep_rew_mean        | 0.000322  |
| time/                 |           |
|    fps                | 770       |
|    iterations         | 9800      |
|    time_elapsed       | 63        |
|    total_timesteps    | 49000     |
| train/                |           |
|    entropy_loss       | -9.7e-05  |
|    explained_variance | -0.000962 |
|    learning_rate      | 0.0007    |
|    n_updates          | 9799      |
|    policy_loss        | -3.44e-07 |
|    value_loss         | 0.018     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 305       |
|    ep_rew_mean        | 0.000322  |
| time/                 |           |
|    fps                | 773       |
|    iterations         | 9900      |
|    time_elapsed       | 64        |
|    total_timesteps    | 49500     |
| train/                |           |
|    entropy_loss       | -0.0153   |
|    explained_variance | 0.226     |
|    learning_rate      | 0.0007    |
|    n_updates          | 9899      |
|    policy_loss        | -0.000763 |
|    value_loss         | 0.295     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 305       |
|    ep_rew_mean        | 0.000322  |
| time/                 |           |
|    fps                | 775       |
|    iterations         | 10000     |
|    time_elapsed       | 64        |
|    total_timesteps    | 50000     |
| train/                |           |
|    entropy_loss       | -8.7e-05  |
|    explained_variance | -0.0185   |
|    learning_rate      | 0.0007    |
|    n_updates          | 9999      |
|    policy_loss        | -1.15e-06 |
|    value_loss         | 0.0641    |
-------------------------------------

2025-10-30 07:46:22,087 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2564/9953
2025-10-30 07:46:22,088 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110845.99
2025-10-30 07:46:22,088 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110845.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:22,089 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:22,094 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:22,182 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 07:46:22,182 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$31.18, Commission=$0.00, Net=$31.18 (cash flow: -$1968.82, balance: $10031.18)
2025-10-30 07:46:22,183 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8365/9953
2025-10-30 07:46:22,187 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111483.69
2025-10-30 07:46:22,187 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111483.69 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:22,188 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:22,190 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 324       |
|    ep_rew_mean        | 0.000349  |
| time/                 |           |
|    fps                | 778       |
|    iterations         | 10100     |
|    time_elapsed       | 64        |
|    total_timesteps    | 50500     |
| train/                |           |
|    entropy_loss       | -0.000103 |
|    explained_variance | 0.0267    |
|    learning_rate      | 0.0007    |
|    n_updates          | 10099     |
|    policy_loss        | -1.46e-06 |
|    value_loss         | 0.0563    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 324       |
|    ep_rew_mean        | 0.000349  |
| time/                 |           |
|    fps                | 781       |
|    iterations         | 10200     |
|    time_elapsed       | 65        |
|    total_timesteps    | 51000     |
| train/                |           |
|    entropy_loss       | -8.42e-05 |
|    explained_variance | -0.134    |
|    learning_rate      | 0.0007    |
|    n_updates          | 10199     |
|    policy_loss        | -1.97e-06 |
|    value_loss         | 0.107     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 324       |
|    ep_rew_mean        | 0.000349  |
| time/                 |           |
|    fps                | 783       |
|    iterations         | 10300     |
|    time_elapsed       | 65        |
|    total_timesteps    | 51500     |
| train/                |           |
|    entropy_loss       | -0.00014  |
|    explained_variance | -0.0398   |
|    learning_rate      | 0.0007    |
|    n_updates          | 10299     |
|    policy_loss        | -3.95e-06 |
|    value_loss         | 0.143     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 324       |
|    ep_rew_mean        | 0.000349  |
| time/                 |           |
|    fps                | 786       |
|    iterations         | 10400     |
|    time_elapsed       | 66        |
|    total_timesteps    | 52000     |
| train/                |           |
|    entropy_loss       | -9.57e-05 |
|    explained_variance | 0.137     |
|    learning_rate      | 0.0007    |
|    n_updates          | 10399     |
|    policy_loss        | 1.62e-06  |
|    value_loss         | 0.0621    |
-------------------------------------

2025-10-30 07:46:23,536 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7475/9953
2025-10-30 07:46:23,538 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110343.75
2025-10-30 07:46:23,538 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110343.75 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:23,538 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:46:23,541 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 339       |
|    ep_rew_mean        | 0.000344  |
| time/                 |           |
|    fps                | 788       |
|    iterations         | 10500     |
|    time_elapsed       | 66        |
|    total_timesteps    | 52500     |
| train/                |           |
|    entropy_loss       | -9.85e-05 |
|    explained_variance | 0.18      |
|    learning_rate      | 0.0007    |
|    n_updates          | 10499     |
|    policy_loss        | -2.59e-06 |
|    value_loss         | 0.186     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 339       |
|    ep_rew_mean        | 0.000344  |
| time/                 |           |
|    fps                | 791       |
|    iterations         | 10600     |
|    time_elapsed       | 67        |
|    total_timesteps    | 53000     |
| train/                |           |
|    entropy_loss       | -8.87e-05 |
|    explained_variance | 0.212     |
|    learning_rate      | 0.0007    |
|    n_updates          | 10599     |
|    policy_loss        | 3.67e-07  |
|    value_loss         | 0.0171    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 339       |
|    ep_rew_mean        | 0.000344  |
| time/                 |           |
|    fps                | 793       |
|    iterations         | 10700     |
|    time_elapsed       | 67        |
|    total_timesteps    | 53500     |
| train/                |           |
|    entropy_loss       | -5.82e-05 |
|    explained_variance | 0.191     |
|    learning_rate      | 0.0007    |
|    n_updates          | 10699     |
|    policy_loss        | -7.73e-07 |
|    value_loss         | 0.0442    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 339       |
|    ep_rew_mean        | 0.000344  |
| time/                 |           |
|    fps                | 795       |
|    iterations         | 10800     |
|    time_elapsed       | 67        |
|    total_timesteps    | 54000     |
| train/                |           |
|    entropy_loss       | -5.93e-05 |
|    explained_variance | 0.197     |
|    learning_rate      | 0.0007    |
|    n_updates          | 10799     |
|    policy_loss        | 2.01e-06  |
|    value_loss         | 0.298     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 339       |
|    ep_rew_mean        | 0.000344  |
| time/                 |           |
|    fps                | 797       |
|    iterations         | 10900     |
|    time_elapsed       | 68        |
|    total_timesteps    | 54500     |
| train/                |           |
|    entropy_loss       | -0.000102 |
|    explained_variance | 0.254     |
|    learning_rate      | 0.0007    |
|    n_updates          | 10899     |
|    policy_loss        | -7.81e-07 |
|    value_loss         | 0.0144    |
-------------------------------------

2025-10-30 07:46:25,687 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2331/9953
2025-10-30 07:46:25,688 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111998.62
2025-10-30 07:46:25,688 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111998.62 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:25,689 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:25,694 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 364       |
|    ep_rew_mean        | 0.000316  |
| time/                 |           |
|    fps                | 799       |
|    iterations         | 11000     |
|    time_elapsed       | 68        |
|    total_timesteps    | 55000     |
| train/                |           |
|    entropy_loss       | -0.00114  |
|    explained_variance | -0.0964   |
|    learning_rate      | 0.0007    |
|    n_updates          | 10999     |
|    policy_loss        | -2.33e-05 |
|    value_loss         | 0.0386    |
-------------------------------------

2025-10-30 07:46:26,217 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:46:26,218 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$62.48, Commission=$0.00, Net=$62.48 (cash flow: -$1937.52, balance: $10062.48)
2025-10-30 07:46:26,218 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7058/9953
2025-10-30 07:46:26,220 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108953.03
2025-10-30 07:46:26,221 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108953.03 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:26,221 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:26,223 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:26,230 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:26,230 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.19, Commission=$0.00, Net=$3.19 (cash flow: +$2003.19, -$0.00, balance: $10003.19)
2025-10-30 07:46:26,231 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7595/9953
2025-10-30 07:46:26,233 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110825.24
2025-10-30 07:46:26,233 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110825.24 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:26,233 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:26,236 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 370       |
|    ep_rew_mean        | 0.000375  |
| time/                 |           |
|    fps                | 802       |
|    iterations         | 11100     |
|    time_elapsed       | 69        |
|    total_timesteps    | 55500     |
| train/                |           |
|    entropy_loss       | -0.000239 |
|    explained_variance | -0.195    |
|    learning_rate      | 0.0007    |
|    n_updates          | 11099     |
|    policy_loss        | -5.4e-06  |
|    value_loss         | 0.0598    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 370       |
|    ep_rew_mean        | 0.000375  |
| time/                 |           |
|    fps                | 804       |
|    iterations         | 11200     |
|    time_elapsed       | 69        |
|    total_timesteps    | 56000     |
| train/                |           |
|    entropy_loss       | -7.91e-05 |
|    explained_variance | 0.151     |
|    learning_rate      | 0.0007    |
|    n_updates          | 11199     |
|    policy_loss        | 1.58e-06  |
|    value_loss         | 0.0852    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 370       |
|    ep_rew_mean        | 0.000375  |
| time/                 |           |
|    fps                | 806       |
|    iterations         | 11300     |
|    time_elapsed       | 70        |
|    total_timesteps    | 56500     |
| train/                |           |
|    entropy_loss       | -7.16e-05 |
|    explained_variance | -0.184    |
|    learning_rate      | 0.0007    |
|    n_updates          | 11299     |
|    policy_loss        | 2.86e-06  |
|    value_loss         | 0.289     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 370       |
|    ep_rew_mean        | 0.000375  |
| time/                 |           |
|    fps                | 808       |
|    iterations         | 11400     |
|    time_elapsed       | 70        |
|    total_timesteps    | 57000     |
| train/                |           |
|    entropy_loss       | -8.73e-05 |
|    explained_variance | 0.0332    |
|    learning_rate      | 0.0007    |
|    n_updates          | 11399     |
|    policy_loss        | -4.43e-07 |
|    value_loss         | 0.033     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 370       |
|    ep_rew_mean        | 0.000375  |
| time/                 |           |
|    fps                | 810       |
|    iterations         | 11500     |
|    time_elapsed       | 70        |
|    total_timesteps    | 57500     |
| train/                |           |
|    entropy_loss       | -0.000106 |
|    explained_variance | 0.375     |
|    learning_rate      | 0.0007    |
|    n_updates          | 11499     |
|    policy_loss        | -1.44e-06 |
|    value_loss         | 0.0526    |
-------------------------------------

2025-10-30 07:46:28,319 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1739/9953
2025-10-30 07:46:28,322 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112290.66
2025-10-30 07:46:28,323 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112290.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:28,323 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:46:28,325 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 393       |
|    ep_rew_mean        | 0.000363  |
| time/                 |           |
|    fps                | 812       |
|    iterations         | 11600     |
|    time_elapsed       | 71        |
|    total_timesteps    | 58000     |
| train/                |           |
|    entropy_loss       | -8.94e-05 |
|    explained_variance | 0.08      |
|    learning_rate      | 0.0007    |
|    n_updates          | 11599     |
|    policy_loss        | -2.06e-06 |
|    value_loss         | 0.13      |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 393      |
|    ep_rew_mean        | 0.000363 |
| time/                 |          |
|    fps                | 814      |
|    iterations         | 11700    |
|    time_elapsed       | 71       |
|    total_timesteps    | 58500    |
| train/                |          |
|    entropy_loss       | -0.0204  |
|    explained_variance | -0.183   |
|    learning_rate      | 0.0007   |
|    n_updates          | 11699    |
|    policy_loss        | 0.00112  |
|    value_loss         | 0.149    |
------------------------------------

2025-10-30 07:46:29,116 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 07:46:29,116 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$64.42, Commission=$0.00, Net=$64.42 (cash flow: -$1935.58, balance: $10064.42)
2025-10-30 07:46:29,117 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 463/9953
2025-10-30 07:46:29,121 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110056.40
2025-10-30 07:46:29,121 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110056.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:29,121 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:29,123 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:29,135 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:29,135 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.64, Commission=$0.00, Net=$-4.64 (cash flow: +$1995.36, -$0.00, balance: $9995.36)
2025-10-30 07:46:29,136 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4803/9953
2025-10-30 07:46:29,138 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108086.01
2025-10-30 07:46:29,138 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108086.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:29,139 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:29,141 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:29,147 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:29,147 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.66, Commission=$0.00, Net=$-1.66 (cash flow: +$1998.34, -$0.00, balance: $9998.34)
2025-10-30 07:46:29,147 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4781/9953
2025-10-30 07:46:29,150 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107700.28
2025-10-30 07:46:29,151 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107700.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:29,151 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 07:46:29,153 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 817       |
|    iterations         | 11800     |
|    time_elapsed       | 72        |
|    total_timesteps    | 59000     |
| train/                |           |
|    entropy_loss       | -9.19e-05 |
|    explained_variance | -0.151    |
|    learning_rate      | 0.0007    |
|    n_updates          | 11799     |
|    policy_loss        | 2.75e-06  |
|    value_loss         | 0.223     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 819       |
|    iterations         | 11900     |
|    time_elapsed       | 72        |
|    total_timesteps    | 59500     |
| train/                |           |
|    entropy_loss       | -0.000176 |
|    explained_variance | -1.35     |
|    learning_rate      | 0.0007    |
|    n_updates          | 11899     |
|    policy_loss        | 6.14e-07  |
|    value_loss         | 0.00237   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 821       |
|    iterations         | 12000     |
|    time_elapsed       | 73        |
|    total_timesteps    | 60000     |
| train/                |           |
|    entropy_loss       | -9.22e-05 |
|    explained_variance | 0.429     |
|    learning_rate      | 0.0007    |
|    n_updates          | 11999     |
|    policy_loss        | 2.37e-07  |
|    value_loss         | 0.00216   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 823       |
|    iterations         | 12100     |
|    time_elapsed       | 73        |
|    total_timesteps    | 60500     |
| train/                |           |
|    entropy_loss       | -0.000173 |
|    explained_variance | 0.0019    |
|    learning_rate      | 0.0007    |
|    n_updates          | 12099     |
|    policy_loss        | -3.57e-07 |
|    value_loss         | 0.0272    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 824       |
|    iterations         | 12200     |
|    time_elapsed       | 73        |
|    total_timesteps    | 61000     |
| train/                |           |
|    entropy_loss       | -0.000143 |
|    explained_variance | 0.0797    |
|    learning_rate      | 0.0007    |
|    n_updates          | 12199     |
|    policy_loss        | -3.9e-06  |
|    value_loss         | 0.205     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 826       |
|    iterations         | 12300     |
|    time_elapsed       | 74        |
|    total_timesteps    | 61500     |
| train/                |           |
|    entropy_loss       | -0.000173 |
|    explained_variance | -0.0441   |
|    learning_rate      | 0.0007    |
|    n_updates          | 12299     |
|    policy_loss        | -2.99e-06 |
|    value_loss         | 0.155     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 827       |
|    iterations         | 12400     |
|    time_elapsed       | 74        |
|    total_timesteps    | 62000     |
| train/                |           |
|    entropy_loss       | -0.000294 |
|    explained_variance | 0.0195    |
|    learning_rate      | 0.0007    |
|    n_updates          | 12399     |
|    policy_loss        | -9.78e-07 |
|    value_loss         | 0.0481    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 828       |
|    iterations         | 12500     |
|    time_elapsed       | 75        |
|    total_timesteps    | 62500     |
| train/                |           |
|    entropy_loss       | -0.000945 |
|    explained_variance | -24.2     |
|    learning_rate      | 0.0007    |
|    n_updates          | 12499     |
|    policy_loss        | -7.07e-07 |
|    value_loss         | 0.00023   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 829       |
|    iterations         | 12600     |
|    time_elapsed       | 75        |
|    total_timesteps    | 63000     |
| train/                |           |
|    entropy_loss       | -0.000104 |
|    explained_variance | -0.0742   |
|    learning_rate      | 0.0007    |
|    n_updates          | 12599     |
|    policy_loss        | 6.35e-07  |
|    value_loss         | 0.0308    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 402       |
|    ep_rew_mean        | 0.000423  |
| time/                 |           |
|    fps                | 829       |
|    iterations         | 12700     |
|    time_elapsed       | 76        |
|    total_timesteps    | 63500     |
| train/                |           |
|    entropy_loss       | -0.000432 |
|    explained_variance | 0.166     |
|    learning_rate      | 0.0007    |
|    n_updates          | 12699     |
|    policy_loss        | 8.74e-06  |
|    value_loss         | 0.0626    |
-------------------------------------

2025-10-30 07:46:34,076 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6978/9953
2025-10-30 07:46:34,077 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109134.33
2025-10-30 07:46:34,078 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109134.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:34,078 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:46:34,080 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 454       |
|    ep_rew_mean        | 0.000347  |
| time/                 |           |
|    fps                | 831       |
|    iterations         | 12800     |
|    time_elapsed       | 77        |
|    total_timesteps    | 64000     |
| train/                |           |
|    entropy_loss       | -9.07e-05 |
|    explained_variance | -0.231    |
|    learning_rate      | 0.0007    |
|    n_updates          | 12799     |
|    policy_loss        | 5.65e-07  |
|    value_loss         | 0.0849    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 454       |
|    ep_rew_mean        | 0.000347  |
| time/                 |           |
|    fps                | 833       |
|    iterations         | 12900     |
|    time_elapsed       | 77        |
|    total_timesteps    | 64500     |
| train/                |           |
|    entropy_loss       | -6.32e-05 |
|    explained_variance | 0.102     |
|    learning_rate      | 0.0007    |
|    n_updates          | 12899     |
|    policy_loss        | -8.38e-07 |
|    value_loss         | 0.0763    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 454       |
|    ep_rew_mean        | 0.000347  |
| time/                 |           |
|    fps                | 835       |
|    iterations         | 13000     |
|    time_elapsed       | 77        |
|    total_timesteps    | 65000     |
| train/                |           |
|    entropy_loss       | -0.000103 |
|    explained_variance | 0.0359    |
|    learning_rate      | 0.0007    |
|    n_updates          | 12999     |
|    policy_loss        | -1.44e-06 |
|    value_loss         | 0.092     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 454       |
|    ep_rew_mean        | 0.000347  |
| time/                 |           |
|    fps                | 836       |
|    iterations         | 13100     |
|    time_elapsed       | 78        |
|    total_timesteps    | 65500     |
| train/                |           |
|    entropy_loss       | -0.000104 |
|    explained_variance | 0.0825    |
|    learning_rate      | 0.0007    |
|    n_updates          | 13099     |
|    policy_loss        | -6.23e-06 |
|    value_loss         | 0.595     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 454       |
|    ep_rew_mean        | 0.000347  |
| time/                 |           |
|    fps                | 838       |
|    iterations         | 13200     |
|    time_elapsed       | 78        |
|    total_timesteps    | 66000     |
| train/                |           |
|    entropy_loss       | -6.41e-05 |
|    explained_variance | 0.0215    |
|    learning_rate      | 0.0007    |
|    n_updates          | 13199     |
|    policy_loss        | -8.76e-07 |
|    value_loss         | 0.0639    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 454       |
|    ep_rew_mean        | 0.000347  |
| time/                 |           |
|    fps                | 839       |
|    iterations         | 13300     |
|    time_elapsed       | 79        |
|    total_timesteps    | 66500     |
| train/                |           |
|    entropy_loss       | -0.000115 |
|    explained_variance | 0.174     |
|    learning_rate      | 0.0007    |
|    n_updates          | 13299     |
|    policy_loss        | -1.45e-06 |
|    value_loss         | 0.0479    |
-------------------------------------

2025-10-30 07:46:36,698 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6026/9953
2025-10-30 07:46:36,700 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107607.72
2025-10-30 07:46:36,700 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107607.72 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:36,701 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:46:36,703 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:36,723 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:46:36,724 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.90, Commission=$0.00, Net=$2.90 (cash flow: +$2002.90, -$0.00, balance: $10002.90)
2025-10-30 07:46:36,724 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3103/9953
2025-10-30 07:46:36,726 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107997.94
2025-10-30 07:46:36,727 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107997.94 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:36,727 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:36,729 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:36,735 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:36,735 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.11, Commission=$0.00, Net=$0.11 (cash flow: +$2000.11, -$0.00, balance: $10000.11)
2025-10-30 07:46:36,736 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6735/9953
2025-10-30 07:46:36,738 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109721.48
2025-10-30 07:46:36,738 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109721.48 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:36,739 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:36,741 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:36,758 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:36,758 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.40, Commission=$0.00, Net=$-0.40 (cash flow: +$1999.60, -$0.00, balance: $9999.60)
2025-10-30 07:46:36,759 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4012/9953
2025-10-30 07:46:36,761 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108030.99
2025-10-30 07:46:36,761 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108030.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:36,762 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:36,764 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 483       |
|    ep_rew_mean        | 0.00029   |
| time/                 |           |
|    fps                | 841       |
|    iterations         | 13400     |
|    time_elapsed       | 79        |
|    total_timesteps    | 67000     |
| train/                |           |
|    entropy_loss       | -0.0611   |
|    explained_variance | 0.122     |
|    learning_rate      | 0.0007    |
|    n_updates          | 13399     |
|    policy_loss        | -0.000786 |
|    value_loss         | 0.0193    |
-------------------------------------

2025-10-30 07:46:37,000 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:37,000 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.89, Commission=$0.00, Net=$-2.89 (cash flow: +$1997.11, -$0.00, balance: $9997.11)
2025-10-30 07:46:37,001 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5848/9953
2025-10-30 07:46:37,003 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107027.51
2025-10-30 07:46:37,003 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107027.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:37,003 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:46:37,005 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:37,021 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:46:37,021 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.22, Commission=$0.00, Net=$4.22 (cash flow: +$2004.22, -$0.00, balance: $10004.22)
2025-10-30 07:46:37,022 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6181/9953
2025-10-30 07:46:37,024 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108032.09
2025-10-30 07:46:37,025 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108032.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:37,025 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:37,030 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:37,089 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:37,090 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$6.37, Commission=$0.00, Net=$6.37 (cash flow: +$2006.37, -$0.00, balance: $10006.37)
2025-10-30 07:46:37,090 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 290/9953
2025-10-30 07:46:37,093 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108635.17
2025-10-30 07:46:37,093 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108635.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:37,094 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:37,096 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:37,150 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:37,150 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$19.43, Commission=$0.00, Net=$19.43 (cash flow: +$2019.43, -$0.00, balance: $10019.43)
2025-10-30 07:46:37,151 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2626/9953
2025-10-30 07:46:37,153 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110015.51
2025-10-30 07:46:37,154 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110015.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:37,154 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:37,156 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 487       |
|    ep_rew_mean        | 0.000306  |
| time/                 |           |
|    fps                | 842       |
|    iterations         | 13500     |
|    time_elapsed       | 80        |
|    total_timesteps    | 67500     |
| train/                |           |
|    entropy_loss       | -0.0165   |
|    explained_variance | -0.79     |
|    learning_rate      | 0.0007    |
|    n_updates          | 13499     |
|    policy_loss        | -0.000143 |
|    value_loss         | 0.0262    |
-------------------------------------

2025-10-30 07:46:37,446 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:37,447 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-28.69, Commission=$0.00, Net=$-28.69 (cash flow: +$1971.31, -$0.00, balance: $9971.31)
2025-10-30 07:46:37,447 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8547/9953
2025-10-30 07:46:37,449 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111369.90
2025-10-30 07:46:37,449 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111369.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:37,449 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:46:37,455 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 477      |
|    ep_rew_mean        | 0.000271 |
| time/                 |          |
|    fps                | 844      |
|    iterations         | 13600    |
|    time_elapsed       | 80       |
|    total_timesteps    | 68000    |
| train/                |          |
|    entropy_loss       | -0.0312  |
|    explained_variance | -0.0361  |
|    learning_rate      | 0.0007   |
|    n_updates          | 13599    |
|    policy_loss        | 0.000552 |
|    value_loss         | 0.0305   |
------------------------------------

2025-10-30 07:46:37,915 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:46:37,915 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-28.84, Commission=$0.00, Net=$-28.84 (cash flow: +$1971.16, -$0.00, balance: $9971.16)
2025-10-30 07:46:37,916 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7582/9953
2025-10-30 07:46:37,917 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110872.66
2025-10-30 07:46:37,918 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110872.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:37,918 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:37,921 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 482       |
|    ep_rew_mean        | 0.000242  |
| time/                 |           |
|    fps                | 846       |
|    iterations         | 13700     |
|    time_elapsed       | 80        |
|    total_timesteps    | 68500     |
| train/                |           |
|    entropy_loss       | -0.000272 |
|    explained_variance | -0.0238   |
|    learning_rate      | 0.0007    |
|    n_updates          | 13699     |
|    policy_loss        | 3.48e-07  |
|    value_loss         | 0.0592    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 482       |
|    ep_rew_mean        | 0.000242  |
| time/                 |           |
|    fps                | 848       |
|    iterations         | 13800     |
|    time_elapsed       | 81        |
|    total_timesteps    | 69000     |
| train/                |           |
|    entropy_loss       | -8.05e-05 |
|    explained_variance | 0.407     |
|    learning_rate      | 0.0007    |
|    n_updates          | 13799     |
|    policy_loss        | -9.95e-07 |
|    value_loss         | 0.0278    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 482       |
|    ep_rew_mean        | 0.000242  |
| time/                 |           |
|    fps                | 850       |
|    iterations         | 13900     |
|    time_elapsed       | 81        |
|    total_timesteps    | 69500     |
| train/                |           |
|    entropy_loss       | -0.000126 |
|    explained_variance | 0.051     |
|    learning_rate      | 0.0007    |
|    n_updates          | 13899     |
|    policy_loss        | 3.36e-06  |
|    value_loss         | 0.24      |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 482       |
|    ep_rew_mean        | 0.000242  |
| time/                 |           |
|    fps                | 851       |
|    iterations         | 14000     |
|    time_elapsed       | 82        |
|    total_timesteps    | 70000     |
| train/                |           |
|    entropy_loss       | -0.000153 |
|    explained_variance | 0.0903    |
|    learning_rate      | 0.0007    |
|    n_updates          | 13999     |
|    policy_loss        | -6.12e-07 |
|    value_loss         | 0.0252    |
-------------------------------------

2025-10-30 07:46:39,987 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8945/9953
2025-10-30 07:46:39,988 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110652.02
2025-10-30 07:46:39,988 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110652.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:39,988 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:46:39,990 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 506      |
|    ep_rew_mean        | 0.000231 |
| time/                 |          |
|    fps                | 852      |
|    iterations         | 14100    |
|    time_elapsed       | 82       |
|    total_timesteps    | 70500    |
| train/                |          |
|    entropy_loss       | -0.0896  |
|    explained_variance | 0.542    |
|    learning_rate      | 0.0007   |
|    n_updates          | 14099    |
|    policy_loss        | -0.00346 |
|    value_loss         | 0.0362   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 506       |
|    ep_rew_mean        | 0.000231  |
| time/                 |           |
|    fps                | 854       |
|    iterations         | 14200     |
|    time_elapsed       | 83        |
|    total_timesteps    | 71000     |
| train/                |           |
|    entropy_loss       | -0.000124 |
|    explained_variance | 0.0274    |
|    learning_rate      | 0.0007    |
|    n_updates          | 14199     |
|    policy_loss        | 1.03e-06  |
|    value_loss         | 0.0162    |
-------------------------------------

2025-10-30 07:46:40,810 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4317/9953
2025-10-30 07:46:40,812 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107912.37
2025-10-30 07:46:40,812 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107912.37 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:40,812 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:40,814 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 516       |
|    ep_rew_mean        | 0.00021   |
| time/                 |           |
|    fps                | 856       |
|    iterations         | 14300     |
|    time_elapsed       | 83        |
|    total_timesteps    | 71500     |
| train/                |           |
|    entropy_loss       | -7.87e-05 |
|    explained_variance | 0.0108    |
|    learning_rate      | 0.0007    |
|    n_updates          | 14299     |
|    policy_loss        | -9.03e-07 |
|    value_loss         | 0.0327    |
-------------------------------------

2025-10-30 07:46:40,836 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:40,836 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-7.29, Commission=$0.00, Net=$-7.29 (cash flow: +$1992.71, -$0.00, balance: $9992.71)
2025-10-30 07:46:40,837 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 443/9953
2025-10-30 07:46:40,840 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110298.80
2025-10-30 07:46:40,841 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110298.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:40,841 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:46:40,843 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:40,853 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:46:40,853 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.55, Commission=$0.00, Net=$-2.55 (cash flow: +$1997.45, -$0.00, balance: $9997.45)
2025-10-30 07:46:40,853 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2453/9953
2025-10-30 07:46:40,855 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111009.88
2025-10-30 07:46:40,856 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111009.88 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:40,857 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:46:40,858 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:40,872 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:46:40,872 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.82, Commission=$0.00, Net=$-4.82 (cash flow: +$1995.18, -$0.00, balance: $9995.18)
2025-10-30 07:46:40,873 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8773/9953
2025-10-30 07:46:40,878 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111783.18
2025-10-30 07:46:40,878 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111783.18 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:40,878 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:40,880 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:41,098 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:46:41,099 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$29.92, Commission=$0.00, Net=$29.92 (cash flow: -$1970.08, balance: $10029.92)
2025-10-30 07:46:41,099 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8551/9953
2025-10-30 07:46:41,101 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111388.25
2025-10-30 07:46:41,102 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111388.25 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:41,102 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:46:41,105 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:46:41,106 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.35, Commission=$0.00, Net=$0.35 (cash flow: +$2000.35, -$0.00, balance: $10000.35)
2025-10-30 07:46:41,107 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1305/9953
2025-10-30 07:46:41,109 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113900.47
2025-10-30 07:46:41,110 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113900.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:41,110 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 07:46:41,112 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 508       |
|    ep_rew_mean        | 0.000255  |
| time/                 |           |
|    fps                | 857       |
|    iterations         | 14400     |
|    time_elapsed       | 83        |
|    total_timesteps    | 72000     |
| train/                |           |
|    entropy_loss       | -8.73e-05 |
|    explained_variance | -0.325    |
|    learning_rate      | 0.0007    |
|    n_updates          | 14399     |
|    policy_loss        | -1.87e-06 |
|    value_loss         | 0.143     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 508       |
|    ep_rew_mean        | 0.000255  |
| time/                 |           |
|    fps                | 859       |
|    iterations         | 14500     |
|    time_elapsed       | 84        |
|    total_timesteps    | 72500     |
| train/                |           |
|    entropy_loss       | -0.000325 |
|    explained_variance | -0.0125   |
|    learning_rate      | 0.0007    |
|    n_updates          | 14499     |
|    policy_loss        | -4.83e-06 |
|    value_loss         | 0.0187    |
-------------------------------------

2025-10-30 07:46:41,865 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 07:46:41,866 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$38.01, Commission=$0.00, Net=$38.01 (cash flow: -$1961.99, balance: $10038.01)
2025-10-30 07:46:41,867 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9741/9953
2025-10-30 07:46:41,869 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111387.81
2025-10-30 07:46:41,869 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111387.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:41,870 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:41,873 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:42,041 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5953/9953
2025-10-30 07:46:42,043 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107068.70
2025-10-30 07:46:42,043 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0187 @ $107068.70 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:42,043 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0187
2025-10-30 07:46:42,045 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:42,051 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0187
2025-10-30 07:46:42,052 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.36, Commission=$0.00, Net=$1.36 (cash flow: +$2001.36, -$0.00, balance: $10001.36)
2025-10-30 07:46:42,052 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2809/9953
2025-10-30 07:46:42,054 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109218.85
2025-10-30 07:46:42,054 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109218.85 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:42,054 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:46:42,057 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:42,063 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:46:42,063 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.29, Commission=$0.00, Net=$3.29 (cash flow: +$2003.29, -$0.00, balance: $10003.29)
2025-10-30 07:46:42,064 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9756/9953
2025-10-30 07:46:42,065 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111245.97
2025-10-30 07:46:42,066 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111245.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:42,066 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:46:42,068 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:42,078 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:46:42,078 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.09, Commission=$0.00, Net=$-0.09 (cash flow: +$1999.91, -$0.00, balance: $9999.91)
2025-10-30 07:46:42,079 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6145/9953
2025-10-30 07:46:42,080 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108297.54
2025-10-30 07:46:42,081 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108297.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:42,081 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:42,086 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:42,088 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:42,088 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.84, Commission=$0.00, Net=$0.84 (cash flow: +$2000.84, -$0.00, balance: $10000.84)
2025-10-30 07:46:42,088 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9553/9953
2025-10-30 07:46:42,091 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110941.42
2025-10-30 07:46:42,092 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110941.42 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:42,092 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:42,094 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 515       |
|    ep_rew_mean        | 0.000304  |
| time/                 |           |
|    fps                | 860       |
|    iterations         | 14600     |
|    time_elapsed       | 84        |
|    total_timesteps    | 73000     |
| train/                |           |
|    entropy_loss       | -3.85e-05 |
|    explained_variance | -0.138    |
|    learning_rate      | 0.0007    |
|    n_updates          | 14599     |
|    policy_loss        | 6.46e-07  |
|    value_loss         | 0.121     |
-------------------------------------

2025-10-30 07:46:42,412 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9061/9953
2025-10-30 07:46:42,413 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110078.61
2025-10-30 07:46:42,414 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110078.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:42,414 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:42,416 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:42,417 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.59, Commission=$0.00, Net=$0.59 (cash flow: +$2000.59, -$0.00, balance: $10000.59)
2025-10-30 07:46:42,417 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7226/9953
2025-10-30 07:46:42,420 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108945.00
2025-10-30 07:46:42,420 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108945.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:42,420 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:42,423 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:42,427 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:42,428 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.30, Commission=$0.00, Net=$3.30 (cash flow: +$2003.30, -$0.00, balance: $10003.30)
2025-10-30 07:46:42,428 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 834/9953
2025-10-30 07:46:42,430 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112680.00
2025-10-30 07:46:42,430 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112680.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:42,430 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:46:42,432 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000302  |
| time/                 |           |
|    fps                | 862       |
|    iterations         | 14700     |
|    time_elapsed       | 85        |
|    total_timesteps    | 73500     |
| train/                |           |
|    entropy_loss       | -2.91e-05 |
|    explained_variance | -0.538    |
|    learning_rate      | 0.0007    |
|    n_updates          | 14699     |
|    policy_loss        | 3.4e-07   |
|    value_loss         | 0.0338    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000302  |
| time/                 |           |
|    fps                | 864       |
|    iterations         | 14800     |
|    time_elapsed       | 85        |
|    total_timesteps    | 74000     |
| train/                |           |
|    entropy_loss       | -2.47e-05 |
|    explained_variance | 0.181     |
|    learning_rate      | 0.0007    |
|    n_updates          | 14799     |
|    policy_loss        | 2.27e-07  |
|    value_loss         | 0.0571    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000302  |
| time/                 |           |
|    fps                | 865       |
|    iterations         | 14900     |
|    time_elapsed       | 86        |
|    total_timesteps    | 74500     |
| train/                |           |
|    entropy_loss       | -3.83e-05 |
|    explained_variance | 0.239     |
|    learning_rate      | 0.0007    |
|    n_updates          | 14899     |
|    policy_loss        | 4.99e-08  |
|    value_loss         | 0.000986  |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000302  |
| time/                 |           |
|    fps                | 867       |
|    iterations         | 15000     |
|    time_elapsed       | 86        |
|    total_timesteps    | 75000     |
| train/                |           |
|    entropy_loss       | -0.000627 |
|    explained_variance | 0.199     |
|    learning_rate      | 0.0007    |
|    n_updates          | 14999     |
|    policy_loss        | -1.59e-05 |
|    value_loss         | 0.0554    |
-------------------------------------

2025-10-30 07:46:43,882 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:46:43,883 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$37.93, Commission=$0.00, Net=$37.93 (cash flow: -$1962.07, balance: $10037.93)
2025-10-30 07:46:43,883 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4414/9953
2025-10-30 07:46:43,885 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107969.83
2025-10-30 07:46:43,886 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107969.83 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:43,886 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:43,889 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:43,889 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.04, Commission=$0.00, Net=$1.04 (cash flow: +$2001.04, -$0.00, balance: $10001.04)
2025-10-30 07:46:43,891 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 845/9953
2025-10-30 07:46:43,892 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112411.93
2025-10-30 07:46:43,893 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112411.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:43,893 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 07:46:43,898 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 527       |
|    ep_rew_mean        | 0.000331  |
| time/                 |           |
|    fps                | 868       |
|    iterations         | 15100     |
|    time_elapsed       | 86        |
|    total_timesteps    | 75500     |
| train/                |           |
|    entropy_loss       | -2.13e-05 |
|    explained_variance | -0.146    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15099     |
|    policy_loss        | 1.85e-07  |
|    value_loss         | 0.0402    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 527       |
|    ep_rew_mean        | 0.000331  |
| time/                 |           |
|    fps                | 870       |
|    iterations         | 15200     |
|    time_elapsed       | 87        |
|    total_timesteps    | 76000     |
| train/                |           |
|    entropy_loss       | -3.12e-05 |
|    explained_variance | -0.0374   |
|    learning_rate      | 0.0007    |
|    n_updates          | 15199     |
|    policy_loss        | -1.59e-07 |
|    value_loss         | 0.0152    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 527       |
|    ep_rew_mean        | 0.000331  |
| time/                 |           |
|    fps                | 871       |
|    iterations         | 15300     |
|    time_elapsed       | 87        |
|    total_timesteps    | 76500     |
| train/                |           |
|    entropy_loss       | -3.72e-05 |
|    explained_variance | 0.0451    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15299     |
|    policy_loss        | -3.73e-07 |
|    value_loss         | 0.0348    |
-------------------------------------

2025-10-30 07:46:45,198 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 07:46:45,198 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$32.06, Commission=$0.00, Net=$32.06 (cash flow: -$1967.94, balance: $10032.06)
2025-10-30 07:46:45,199 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 500/9953
2025-10-30 07:46:45,203 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109980.09
2025-10-30 07:46:45,203 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109980.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:45,204 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:45,205 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:45,206 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.40, Commission=$0.00, Net=$-0.40 (cash flow: +$1999.60, -$0.00, balance: $9999.60)
2025-10-30 07:46:45,207 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2562/9953
2025-10-30 07:46:45,210 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110763.54
2025-10-30 07:46:45,210 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110763.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:45,211 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:46:45,212 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:46:45,213 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.31, Commission=$0.00, Net=$0.31 (cash flow: +$2000.31, -$0.00, balance: $10000.31)
2025-10-30 07:46:45,213 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 19/9953
2025-10-30 07:46:45,216 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108417.13
2025-10-30 07:46:45,216 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108417.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:45,217 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:45,222 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:45,223 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:45,223 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.14, Commission=$0.00, Net=$0.14 (cash flow: +$2000.14, -$0.00, balance: $10000.14)
2025-10-30 07:46:45,224 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6472/9953
2025-10-30 07:46:45,227 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109862.26
2025-10-30 07:46:45,228 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109862.26 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:45,228 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:45,230 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:45,230 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.93, Commission=$0.00, Net=$-1.93 (cash flow: +$1998.07, -$0.00, balance: $9998.07)
2025-10-30 07:46:45,231 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7280/9953
2025-10-30 07:46:45,236 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109462.53
2025-10-30 07:46:45,236 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109462.53 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:45,236 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:46:45,239 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:46:45,239 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.60, Commission=$0.00, Net=$-1.60 (cash flow: +$1998.40, -$0.00, balance: $9998.40)
2025-10-30 07:46:45,240 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5284/9953
2025-10-30 07:46:45,246 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107999.41
2025-10-30 07:46:45,247 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107999.41 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:45,247 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:45,249 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:45,250 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.03, Commission=$0.00, Net=$0.03 (cash flow: +$2000.03, -$0.00, balance: $10000.03)
2025-10-30 07:46:45,251 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1032/9953
2025-10-30 07:46:45,253 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112750.81
2025-10-30 07:46:45,254 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112750.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:45,254 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:46:45,257 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 535       |
|    ep_rew_mean        | 0.000339  |
| time/                 |           |
|    fps                | 872       |
|    iterations         | 15400     |
|    time_elapsed       | 88        |
|    total_timesteps    | 77000     |
| train/                |           |
|    entropy_loss       | -2.46e-05 |
|    explained_variance | 0.138     |
|    learning_rate      | 0.0007    |
|    n_updates          | 15399     |
|    policy_loss        | 1.99e-07  |
|    value_loss         | 0.0138    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 535       |
|    ep_rew_mean        | 0.000339  |
| time/                 |           |
|    fps                | 874       |
|    iterations         | 15500     |
|    time_elapsed       | 88        |
|    total_timesteps    | 77500     |
| train/                |           |
|    entropy_loss       | -3.49e-05 |
|    explained_variance | -0.365    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15499     |
|    policy_loss        | 1.08e-07  |
|    value_loss         | 0.00528   |
-------------------------------------

2025-10-30 07:46:46,241 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 07:46:46,242 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$18.00, Commission=$0.00, Net=$18.00 (cash flow: -$1982.00, balance: $10018.00)
2025-10-30 07:46:46,242 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4338/9953
2025-10-30 07:46:46,245 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107519.01
2025-10-30 07:46:46,246 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107519.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:46,246 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:46:46,251 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:46:46,251 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.54, Commission=$0.00, Net=$-0.54 (cash flow: +$1999.46, -$0.00, balance: $9999.46)
2025-10-30 07:46:46,252 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4173/9953
2025-10-30 07:46:46,254 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107197.00
2025-10-30 07:46:46,254 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107197.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:46,255 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 07:46:46,257 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:46,262 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0187, signal=1.0
2025-10-30 07:46:46,263 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.55, Commission=$0.00, Net=$0.55 (cash flow: -$1999.45, balance: $10000.55)
2025-10-30 07:46:46,263 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4623/9953
2025-10-30 07:46:46,265 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108639.52
2025-10-30 07:46:46,266 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108639.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:46,266 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:46,268 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:46,269 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.11, Commission=$0.00, Net=$1.11 (cash flow: +$2001.11, -$0.00, balance: $10001.11)
2025-10-30 07:46:46,270 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2756/9953
2025-10-30 07:46:46,278 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109081.67
2025-10-30 07:46:46,278 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109081.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:46,278 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:46:46,283 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:46:46,283 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.18, Commission=$0.00, Net=$-0.18 (cash flow: +$1999.82, -$0.00, balance: $9999.82)
2025-10-30 07:46:46,284 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9933/9953
2025-10-30 07:46:46,286 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111770.69
2025-10-30 07:46:46,287 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111770.69 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:46,287 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:46,290 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:46,305 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1140/9953
2025-10-30 07:46:46,308 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113282.05
2025-10-30 07:46:46,308 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113282.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:46,309 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 07:46:46,311 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 532       |
|    ep_rew_mean        | 0.000317  |
| time/                 |           |
|    fps                | 875       |
|    iterations         | 15600     |
|    time_elapsed       | 89        |
|    total_timesteps    | 78000     |
| train/                |           |
|    entropy_loss       | -3.32e-05 |
|    explained_variance | -0.662    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15599     |
|    policy_loss        | 2.87e-08  |
|    value_loss         | 0.0176    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 532       |
|    ep_rew_mean        | 0.000317  |
| time/                 |           |
|    fps                | 877       |
|    iterations         | 15700     |
|    time_elapsed       | 89        |
|    total_timesteps    | 78500     |
| train/                |           |
|    entropy_loss       | -4.13e-05 |
|    explained_variance | 0.0689    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15699     |
|    policy_loss        | -3.96e-07 |
|    value_loss         | 0.0203    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 532       |
|    ep_rew_mean        | 0.000317  |
| time/                 |           |
|    fps                | 878       |
|    iterations         | 15800     |
|    time_elapsed       | 89        |
|    total_timesteps    | 79000     |
| train/                |           |
|    entropy_loss       | -4.43e-05 |
|    explained_variance | -0.134    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15799     |
|    policy_loss        | 5.63e-07  |
|    value_loss         | 0.0727    |
-------------------------------------

2025-10-30 07:46:47,335 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 07:46:47,335 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$42.46, Commission=$0.00, Net=$42.46 (cash flow: -$1957.54, balance: $10042.46)
2025-10-30 07:46:47,336 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 568/9953
2025-10-30 07:46:47,338 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111033.60
2025-10-30 07:46:47,338 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111033.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:47,339 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:47,344 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 544       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 880       |
|    iterations         | 15900     |
|    time_elapsed       | 90        |
|    total_timesteps    | 79500     |
| train/                |           |
|    entropy_loss       | -6.54e-05 |
|    explained_variance | -0.322    |
|    learning_rate      | 0.0007    |
|    n_updates          | 15899     |
|    policy_loss        | -6.98e-07 |
|    value_loss         | 0.0629    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 544       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 881       |
|    iterations         | 16000     |
|    time_elapsed       | 90        |
|    total_timesteps    | 80000     |
| train/                |           |
|    entropy_loss       | -5.26e-05 |
|    explained_variance | -0.11     |
|    learning_rate      | 0.0007    |
|    n_updates          | 15999     |
|    policy_loss        | -2.45e-06 |
|    value_loss         | 0.542     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 544       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 883       |
|    iterations         | 16100     |
|    time_elapsed       | 91        |
|    total_timesteps    | 80500     |
| train/                |           |
|    entropy_loss       | -7.11e-05 |
|    explained_variance | -0.0885   |
|    learning_rate      | 0.0007    |
|    n_updates          | 16099     |
|    policy_loss        | 1.67e-07  |
|    value_loss         | 0.00451   |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 544       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 884       |
|    iterations         | 16200     |
|    time_elapsed       | 91        |
|    total_timesteps    | 81000     |
| train/                |           |
|    entropy_loss       | -0.000132 |
|    explained_variance | 0.276     |
|    learning_rate      | 0.0007    |
|    n_updates          | 16199     |
|    policy_loss        | 1.67e-06  |
|    value_loss         | 0.0506    |
-------------------------------------

2025-10-30 07:46:49,150 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 07:46:49,150 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$49.32, Commission=$0.00, Net=$49.32 (cash flow: -$1950.68, balance: $10049.32)
2025-10-30 07:46:49,151 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5300/9953
2025-10-30 07:46:49,156 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108020.09
2025-10-30 07:46:49,156 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108020.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,157 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:49,158 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:49,159 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.67, Commission=$0.00, Net=$0.67 (cash flow: +$2000.67, -$0.00, balance: $10000.67)
2025-10-30 07:46:49,160 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9499/9953
2025-10-30 07:46:49,162 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111030.00
2025-10-30 07:46:49,163 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111030.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:49,164 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:46:49,165 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 563       |
|    ep_rew_mean        | 0.000405  |
| time/                 |           |
|    fps                | 885       |
|    iterations         | 16300     |
|    time_elapsed       | 92        |
|    total_timesteps    | 81500     |
| train/                |           |
|    entropy_loss       | -5.01e-05 |
|    explained_variance | -0.986    |
|    learning_rate      | 0.0007    |
|    n_updates          | 16299     |
|    policy_loss        | -8.47e-07 |
|    value_loss         | 0.0389    |
-------------------------------------

2025-10-30 07:46:49,536 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 432/9953
2025-10-30 07:46:49,539 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110531.75
2025-10-30 07:46:49,540 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110531.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,540 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 07:46:49,542 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:46:49,544 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 07:46:49,544 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.53, Commission=$0.00, Net=$-0.53 (cash flow: +$1999.47, -$0.00, balance: $9999.47)
2025-10-30 07:46:49,545 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2933/9953
2025-10-30 07:46:49,551 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108493.51
2025-10-30 07:46:49,551 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108493.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,551 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:49,554 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:49,554 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.28, Commission=$0.00, Net=$-0.28 (cash flow: +$1999.72, -$0.00, balance: $9999.72)
2025-10-30 07:46:49,556 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5207/9953
2025-10-30 07:46:49,558 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108481.15
2025-10-30 07:46:49,559 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108481.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,559 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:46:49,561 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:46:49,562 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.09, Commission=$0.00, Net=$0.09 (cash flow: +$2000.09, -$0.00, balance: $10000.09)
2025-10-30 07:46:49,563 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 472/9953
2025-10-30 07:46:49,568 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109877.80
2025-10-30 07:46:49,569 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109877.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,569 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:46:49,570 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:46:49,571 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.78, Commission=$0.00, Net=$-0.78 (cash flow: +$1999.22, -$0.00, balance: $9999.22)
2025-10-30 07:46:49,572 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3253/9953
2025-10-30 07:46:49,574 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108126.04
2025-10-30 07:46:49,574 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108126.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,575 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:49,578 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:49,579 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.70, Commission=$0.00, Net=$0.70 (cash flow: +$2000.70, -$0.00, balance: $10000.70)
2025-10-30 07:46:49,579 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4946/9953
2025-10-30 07:46:49,584 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108228.96
2025-10-30 07:46:49,584 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108228.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,584 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:49,586 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:49,586 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.90, Commission=$0.00, Net=$-0.90 (cash flow: +$1999.10, -$0.00, balance: $9999.10)
2025-10-30 07:46:49,587 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7153/9953
2025-10-30 07:46:49,591 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109494.86
2025-10-30 07:46:49,591 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109494.86 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:49,592 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 07:46:49,593 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 07:46:49,593 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.30, Commission=$0.00, Net=$-0.30 (cash flow: +$1999.70, -$0.00, balance: $9999.70)
2025-10-30 07:46:49,594 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2083/9953
2025-10-30 07:46:49,600 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112030.70
2025-10-30 07:46:49,600 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112030.70 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:49,600 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:49,602 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 553       |
|    ep_rew_mean        | 0.000397  |
| time/                 |           |
|    fps                | 886       |
|    iterations         | 16400     |
|    time_elapsed       | 92        |
|    total_timesteps    | 82000     |
| train/                |           |
|    entropy_loss       | -4.31e-05 |
|    explained_variance | -0.32     |
|    learning_rate      | 0.0007    |
|    n_updates          | 16399     |
|    policy_loss        | 1.68e-06  |
|    value_loss         | 0.356     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 553       |
|    ep_rew_mean        | 0.000397  |
| time/                 |           |
|    fps                | 887       |
|    iterations         | 16500     |
|    time_elapsed       | 92        |
|    total_timesteps    | 82500     |
| train/                |           |
|    entropy_loss       | -0.000198 |
|    explained_variance | -0.135    |
|    learning_rate      | 0.0007    |
|    n_updates          | 16499     |
|    policy_loss        | -8.87e-06 |
|    value_loss         | 0.293     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 553       |
|    ep_rew_mean        | 0.000397  |
| time/                 |           |
|    fps                | 889       |
|    iterations         | 16600     |
|    time_elapsed       | 93        |
|    total_timesteps    | 83000     |
| train/                |           |
|    entropy_loss       | -0.000171 |
|    explained_variance | -0.412    |
|    learning_rate      | 0.0007    |
|    n_updates          | 16599     |
|    policy_loss        | 2.88e-06  |
|    value_loss         | 0.0496    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 553       |
|    ep_rew_mean        | 0.000397  |
| time/                 |           |
|    fps                | 890       |
|    iterations         | 16700     |
|    time_elapsed       | 93        |
|    total_timesteps    | 83500     |
| train/                |           |
|    entropy_loss       | -0.000878 |
|    explained_variance | -0.179    |
|    learning_rate      | 0.0007    |
|    n_updates          | 16699     |
|    policy_loss        | 1.94e-05  |
|    value_loss         | 0.0661    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 553       |
|    ep_rew_mean        | 0.000397  |
| time/                 |           |
|    fps                | 891       |
|    iterations         | 16800     |
|    time_elapsed       | 94        |
|    total_timesteps    | 84000     |
| train/                |           |
|    entropy_loss       | -0.000844 |
|    explained_variance | -0.0675   |
|    learning_rate      | 0.0007    |
|    n_updates          | 16799     |
|    policy_loss        | -1.07e-05 |
|    value_loss         | 0.0183    |
-------------------------------------

2025-10-30 07:46:51,875 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 07:46:51,875 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$60.92, Commission=$0.00, Net=$60.92 (cash flow: -$1939.08, balance: $10060.92)
2025-10-30 07:46:51,876 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3679/9953
2025-10-30 07:46:51,879 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108058.22
2025-10-30 07:46:51,879 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108058.22 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:51,880 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:46:51,882 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:46:51,882 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: +$1999.94, -$0.00, balance: $9999.94)
2025-10-30 07:46:51,883 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8556/9953
2025-10-30 07:46:51,888 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111474.59
2025-10-30 07:46:51,888 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111474.59 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:51,888 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:46:51,890 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000456  |
| time/                 |           |
|    fps                | 892       |
|    iterations         | 16900     |
|    time_elapsed       | 94        |
|    total_timesteps    | 84500     |
| train/                |           |
|    entropy_loss       | -1.79e-05 |
|    explained_variance | -0.154    |
|    learning_rate      | 0.0007    |
|    n_updates          | 16899     |
|    policy_loss        | -7.13e-07 |
|    value_loss         | 0.606     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000456  |
| time/                 |           |
|    fps                | 893       |
|    iterations         | 17000     |
|    time_elapsed       | 95        |
|    total_timesteps    | 85000     |
| train/                |           |
|    entropy_loss       | -1.67e-05 |
|    explained_variance | -0.0636   |
|    learning_rate      | 0.0007    |
|    n_updates          | 16999     |
|    policy_loss        | 1.87e-08  |
|    value_loss         | 0.012     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 510       |
|    ep_rew_mean        | 0.000456  |
| time/                 |           |
|    fps                | 894       |
|    iterations         | 17100     |
|    time_elapsed       | 95        |
|    total_timesteps    | 85500     |
| train/                |           |
|    entropy_loss       | -1.89e-05 |
|    explained_variance | 0.0415    |
|    learning_rate      | 0.0007    |
|    n_updates          | 17099     |
|    policy_loss        | -4.23e-07 |
|    value_loss         | 0.137     |
-------------------------------------

2025-10-30 07:46:53,050 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5171/9953
2025-10-30 07:46:53,051 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108488.08
2025-10-30 07:46:53,052 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108488.08 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:53,052 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:46:53,054 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 896       |
|    iterations         | 17200     |
|    time_elapsed       | 95        |
|    total_timesteps    | 86000     |
| train/                |           |
|    entropy_loss       | -3.51e-05 |
|    explained_variance | -0.0187   |
|    learning_rate      | 0.0007    |
|    n_updates          | 17199     |
|    policy_loss        | 1.3e-07   |
|    value_loss         | 0.0753    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 897       |
|    iterations         | 17300     |
|    time_elapsed       | 96        |
|    total_timesteps    | 86500     |
| train/                |           |
|    entropy_loss       | -4.79e-05 |
|    explained_variance | 0.35      |
|    learning_rate      | 0.0007    |
|    n_updates          | 17299     |
|    policy_loss        | 5.9e-07   |
|    value_loss         | 0.0369    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 898       |
|    iterations         | 17400     |
|    time_elapsed       | 96        |
|    total_timesteps    | 87000     |
| train/                |           |
|    entropy_loss       | -0.000137 |
|    explained_variance | -0.141    |
|    learning_rate      | 0.0007    |
|    n_updates          | 17399     |
|    policy_loss        | -1.6e-06  |
|    value_loss         | 0.0534    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 899       |
|    iterations         | 17500     |
|    time_elapsed       | 97        |
|    total_timesteps    | 87500     |
| train/                |           |
|    entropy_loss       | -6.73e-05 |
|    explained_variance | -0.0949   |
|    learning_rate      | 0.0007    |
|    n_updates          | 17499     |
|    policy_loss        | -1.86e-06 |
|    value_loss         | 0.15      |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 900       |
|    iterations         | 17600     |
|    time_elapsed       | 97        |
|    total_timesteps    | 88000     |
| train/                |           |
|    entropy_loss       | -3.58e-05 |
|    explained_variance | 0.0676    |
|    learning_rate      | 0.0007    |
|    n_updates          | 17599     |
|    policy_loss        | -1.31e-06 |
|    value_loss         | 0.375     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 901       |
|    iterations         | 17700     |
|    time_elapsed       | 98        |
|    total_timesteps    | 88500     |
| train/                |           |
|    entropy_loss       | -7.09e-05 |
|    explained_variance | -0.00616  |
|    learning_rate      | 0.0007    |
|    n_updates          | 17699     |
|    policy_loss        | 1.42e-06  |
|    value_loss         | 0.081     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 901       |
|    iterations         | 17800     |
|    time_elapsed       | 98        |
|    total_timesteps    | 89000     |
| train/                |           |
|    entropy_loss       | -0.000298 |
|    explained_variance | -0.0264   |
|    learning_rate      | 0.0007    |
|    n_updates          | 17799     |
|    policy_loss        | 3.89e-06  |
|    value_loss         | 0.165     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 902       |
|    iterations         | 17900     |
|    time_elapsed       | 99        |
|    total_timesteps    | 89500     |
| train/                |           |
|    entropy_loss       | -7.65e-05 |
|    explained_variance | 0.0841    |
|    learning_rate      | 0.0007    |
|    n_updates          | 17899     |
|    policy_loss        | -2.7e-07  |
|    value_loss         | 0.0162    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 519       |
|    ep_rew_mean        | 0.000426  |
| time/                 |           |
|    fps                | 902       |
|    iterations         | 18000     |
|    time_elapsed       | 99        |
|    total_timesteps    | 90000     |
| train/                |           |
|    entropy_loss       | -0.000108 |
|    explained_variance | 0.0664    |
|    learning_rate      | 0.0007    |
|    n_updates          | 17999     |
|    policy_loss        | 2.01e-06  |
|    value_loss         | 0.0646    |
-------------------------------------

2025-10-30 07:46:57,585 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2237/9953
2025-10-30 07:46:57,586 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111362.34
2025-10-30 07:46:57,586 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111362.34 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:46:57,587 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 07:46:57,589 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 07:46:57,590 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.66, Commission=$0.00, Net=$0.66 (cash flow: +$2000.66, -$0.00, balance: $10000.66)
2025-10-30 07:46:57,591 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7147/9953
2025-10-30 07:46:57,594 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109516.00
2025-10-30 07:46:57,594 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109516.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:46:57,595 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 564       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 902       |
|    iterations         | 18100     |
|    time_elapsed       | 100       |
|    total_timesteps    | 90500     |
| train/                |           |
|    entropy_loss       | -7.3e-05  |
|    explained_variance | -0.0293   |
|    learning_rate      | 0.0007    |
|    n_updates          | 18099     |
|    policy_loss        | -1.01e-06 |
|    value_loss         | 0.0456    |
-------------------------------------

2025-10-30 07:46:57,601 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 564       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 903       |
|    iterations         | 18200     |
|    time_elapsed       | 100       |
|    total_timesteps    | 91000     |
| train/                |           |
|    entropy_loss       | -2.16e-05 |
|    explained_variance | -0.0765   |
|    learning_rate      | 0.0007    |
|    n_updates          | 18199     |
|    policy_loss        | -4.86e-07 |
|    value_loss         | 0.177     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 564       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 905       |
|    iterations         | 18300     |
|    time_elapsed       | 101       |
|    total_timesteps    | 91500     |
| train/                |           |
|    entropy_loss       | -2.93e-05 |
|    explained_variance | -0.0801   |
|    learning_rate      | 0.0007    |
|    n_updates          | 18299     |
|    policy_loss        | -6.37e-07 |
|    value_loss         | 0.089     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 564       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 906       |
|    iterations         | 18400     |
|    time_elapsed       | 101       |
|    total_timesteps    | 92000     |
| train/                |           |
|    entropy_loss       | -3.35e-05 |
|    explained_variance | -0.241    |
|    learning_rate      | 0.0007    |
|    n_updates          | 18399     |
|    policy_loss        | -5.91e-07 |
|    value_loss         | 0.109     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 564       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 906       |
|    iterations         | 18500     |
|    time_elapsed       | 101       |
|    total_timesteps    | 92500     |
| train/                |           |
|    entropy_loss       | -3.12e-05 |
|    explained_variance | -0.0777   |
|    learning_rate      | 0.0007    |
|    n_updates          | 18499     |
|    policy_loss        | 2.81e-08  |
|    value_loss         | 0.0468    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 564       |
|    ep_rew_mean        | 0.000354  |
| time/                 |           |
|    fps                | 907       |
|    iterations         | 18600     |
|    time_elapsed       | 102       |
|    total_timesteps    | 93000     |
| train/                |           |
|    entropy_loss       | -0.000226 |
|    explained_variance | 0.201     |
|    learning_rate      | 0.0007    |
|    n_updates          | 18599     |
|    policy_loss        | -8.26e-07 |
|    value_loss         | 0.0453    |
-------------------------------------

2025-10-30 07:47:00,066 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4559/9953
2025-10-30 07:47:00,071 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108310.00
2025-10-30 07:47:00,071 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108310.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:00,071 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:47:00,073 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:47:00,073 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.77, Commission=$0.00, Net=$-0.77 (cash flow: +$1999.23, -$0.00, balance: $9999.23)
2025-10-30 07:47:00,074 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1018/9953
2025-10-30 07:47:00,080 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113129.25
2025-10-30 07:47:00,080 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113129.25 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:00,080 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 07:47:00,082 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 07:47:00,082 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.01, Commission=$0.00, Net=$0.01 (cash flow: +$2000.01, -$0.00, balance: $10000.01)
2025-10-30 07:47:00,083 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3986/9953
2025-10-30 07:47:00,087 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108207.78
2025-10-30 07:47:00,087 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108207.78 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:00,088 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:47:00,090 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:47:00,091 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: +$2000.16, -$0.00, balance: $10000.16)
2025-10-30 07:47:00,091 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2790/9953
2025-10-30 07:47:00,096 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108942.01
2025-10-30 07:47:00,096 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108942.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:00,096 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 07:47:00,098 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 07:47:00,099 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.36, Commission=$0.00, Net=$1.36 (cash flow: +$2001.36, -$0.00, balance: $10001.36)
2025-10-30 07:47:00,100 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8767/9953
2025-10-30 07:47:00,103 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111596.96
2025-10-30 07:47:00,103 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111596.96 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:47:00,103 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 07:47:00,106 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 578       |
|    ep_rew_mean        | 0.000271  |
| time/                 |           |
|    fps                | 908       |
|    iterations         | 18700     |
|    time_elapsed       | 102       |
|    total_timesteps    | 93500     |
| train/                |           |
|    entropy_loss       | -8.04e-06 |
|    explained_variance | 0.0586    |
|    learning_rate      | 0.0007    |
|    n_updates          | 18699     |
|    policy_loss        | 4.73e-08  |
|    value_loss         | 0.0235    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 578       |
|    ep_rew_mean        | 0.000271  |
| time/                 |           |
|    fps                | 909       |
|    iterations         | 18800     |
|    time_elapsed       | 103       |
|    total_timesteps    | 94000     |
| train/                |           |
|    entropy_loss       | -7.15e-06 |
|    explained_variance | -0.0267   |
|    learning_rate      | 0.0007    |
|    n_updates          | 18799     |
|    policy_loss        | -0        |
|    value_loss         | 0.0686    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 578      |
|    ep_rew_mean        | 0.000271 |
| time/                 |          |
|    fps                | 910      |
|    iterations         | 18900    |
|    time_elapsed       | 103      |
|    total_timesteps    | 94500    |
| train/                |          |
|    entropy_loss       | -9.1e-06 |
|    explained_variance | -0.258   |
|    learning_rate      | 0.0007   |
|    n_updates          | 18899    |
|    policy_loss        | 6.25e-09 |
|    value_loss         | 0.0207   |
------------------------------------

2025-10-30 07:47:01,077 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9354/9953
2025-10-30 07:47:01,079 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110284.17
2025-10-30 07:47:01,080 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110284.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:47:01,080 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 07:47:01,082 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 584       |
|    ep_rew_mean        | 0.000271  |
| time/                 |           |
|    fps                | 912       |
|    iterations         | 19000     |
|    time_elapsed       | 104       |
|    total_timesteps    | 95000     |
| train/                |           |
|    entropy_loss       | -1.68e-05 |
|    explained_variance | -0.289    |
|    learning_rate      | 0.0007    |
|    n_updates          | 18999     |
|    policy_loss        | 3.05e-08  |
|    value_loss         | 0.0219    |
-------------------------------------

2025-10-30 07:47:01,557 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3773/9953
2025-10-30 07:47:01,560 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108088.04
2025-10-30 07:47:01,561 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108088.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:01,561 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:47:01,563 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:47:01,565 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:47:01,565 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.61, Commission=$0.00, Net=$1.61 (cash flow: +$2001.61, -$0.00, balance: $10001.61)
2025-10-30 07:47:01,566 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4772/9953
2025-10-30 07:47:01,568 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107550.00
2025-10-30 07:47:01,569 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107550.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:01,569 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 07:47:01,571 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:47:01,578 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 07:47:01,578 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.42, Commission=$0.00, Net=$2.42 (cash flow: +$2002.42, -$0.00, balance: $10002.42)
2025-10-30 07:47:01,579 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7321/9953
2025-10-30 07:47:01,583 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109850.73
2025-10-30 07:47:01,584 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109850.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:01,584 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 07:47:01,586 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 07:47:01,586 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.59, Commission=$0.00, Net=$0.59 (cash flow: +$2000.59, -$0.00, balance: $10000.59)
2025-10-30 07:47:01,587 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4408/9953
2025-10-30 07:47:01,589 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108044.86
2025-10-30 07:47:01,590 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108044.86 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:01,590 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:47:01,593 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:47:01,593 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.66, Commission=$0.00, Net=$-1.66 (cash flow: +$1998.34, -$0.00, balance: $9998.34)
2025-10-30 07:47:01,594 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9711/9953
2025-10-30 07:47:01,596 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111055.30
2025-10-30 07:47:01,596 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111055.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:47:01,597 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 07:47:01,602 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:47:01,793 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7117/9953
2025-10-30 07:47:01,795 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109581.26
2025-10-30 07:47:01,796 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109581.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:47:01,796 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 07:47:01,799 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 563      |
|    ep_rew_mean        | 0.000188 |
| time/                 |          |
|    fps                | 913      |
|    iterations         | 19100    |
|    time_elapsed       | 104      |
|    total_timesteps    | 95500    |
| train/                |          |
|    entropy_loss       | -4.9e-05 |
|    explained_variance | 0.134    |
|    learning_rate      | 0.0007   |
|    n_updates          | 19099    |
|    policy_loss        | 8.25e-07 |
|    value_loss         | 0.0669   |
------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 563       |
|    ep_rew_mean        | 0.000188  |
| time/                 |           |
|    fps                | 914       |
|    iterations         | 19200     |
|    time_elapsed       | 104       |
|    total_timesteps    | 96000     |
| train/                |           |
|    entropy_loss       | -1.7e-05  |
|    explained_variance | 0.0884    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19199     |
|    policy_loss        | -5.46e-07 |
|    value_loss         | 0.216     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 563       |
|    ep_rew_mean        | 0.000188  |
| time/                 |           |
|    fps                | 915       |
|    iterations         | 19300     |
|    time_elapsed       | 105       |
|    total_timesteps    | 96500     |
| train/                |           |
|    entropy_loss       | -2.23e-05 |
|    explained_variance | 0.0871    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19299     |
|    policy_loss        | 2.86e-07  |
|    value_loss         | 0.061     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 563       |
|    ep_rew_mean        | 0.000188  |
| time/                 |           |
|    fps                | 916       |
|    iterations         | 19400     |
|    time_elapsed       | 105       |
|    total_timesteps    | 97000     |
| train/                |           |
|    entropy_loss       | -0.000536 |
|    explained_variance | 0.217     |
|    learning_rate      | 0.0007    |
|    n_updates          | 19399     |
|    policy_loss        | -5.81e-06 |
|    value_loss         | 0.201     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 563       |
|    ep_rew_mean        | 0.000188  |
| time/                 |           |
|    fps                | 916       |
|    iterations         | 19500     |
|    time_elapsed       | 106       |
|    total_timesteps    | 97500     |
| train/                |           |
|    entropy_loss       | -1.28e-05 |
|    explained_variance | 0.204     |
|    learning_rate      | 0.0007    |
|    n_updates          | 19499     |
|    policy_loss        | 2.81e-07  |
|    value_loss         | 0.102     |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 563       |
|    ep_rew_mean        | 0.000188  |
| time/                 |           |
|    fps                | 917       |
|    iterations         | 19600     |
|    time_elapsed       | 106       |
|    total_timesteps    | 98000     |
| train/                |           |
|    entropy_loss       | -2.04e-05 |
|    explained_variance | 0.0778    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19599     |
|    policy_loss        | 1.08e-07  |
|    value_loss         | 0.0311    |
-------------------------------------

2025-10-30 07:47:04,305 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2082/9953
2025-10-30 07:47:04,309 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112038.15
2025-10-30 07:47:04,309 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $112038.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:04,309 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 07:47:04,311 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:47:04,314 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 07:47:04,314 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: +$1999.65, -$0.00, balance: $9999.65)
2025-10-30 07:47:04,315 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3127/9953
2025-10-30 07:47:04,320 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107841.21
2025-10-30 07:47:04,320 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107841.21 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:04,320 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:47:04,322 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 07:47:04,328 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:47:04,328 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.75, Commission=$0.00, Net=$2.75 (cash flow: +$2002.75, -$0.00, balance: $10002.75)
2025-10-30 07:47:04,329 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 224/9953
2025-10-30 07:47:04,332 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108325.65
2025-10-30 07:47:04,332 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108325.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 07:47:04,332 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 07:47:04,335 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 07:47:04,335 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.79, Commission=$0.00, Net=$0.79 (cash flow: +$2000.79, -$0.00, balance: $10000.79)
2025-10-30 07:47:04,336 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5360/9953
2025-10-30 07:47:04,338 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108610.39
2025-10-30 07:47:04,338 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108610.39 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 07:47:04,339 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 07:47:04,343 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 584       |
|    ep_rew_mean        | 0.000104  |
| time/                 |           |
|    fps                | 918       |
|    iterations         | 19700     |
|    time_elapsed       | 107       |
|    total_timesteps    | 98500     |
| train/                |           |
|    entropy_loss       | -5.15e-05 |
|    explained_variance | -0.202    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19699     |
|    policy_loss        | -1.9e-06  |
|    value_loss         | 0.0923    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 584       |
|    ep_rew_mean        | 0.000104  |
| time/                 |           |
|    fps                | 919       |
|    iterations         | 19800     |
|    time_elapsed       | 107       |
|    total_timesteps    | 99000     |
| train/                |           |
|    entropy_loss       | -1.72e-05 |
|    explained_variance | -0.019    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19799     |
|    policy_loss        | -1.85e-07 |
|    value_loss         | 0.0873    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 584       |
|    ep_rew_mean        | 0.000104  |
| time/                 |           |
|    fps                | 920       |
|    iterations         | 19900     |
|    time_elapsed       | 108       |
|    total_timesteps    | 99500     |
| train/                |           |
|    entropy_loss       | -1.45e-05 |
|    explained_variance | 0.0936    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19899     |
|    policy_loss        | 2.04e-07  |
|    value_loss         | 0.0598    |
-------------------------------------
-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 584       |
|    ep_rew_mean        | 0.000104  |
| time/                 |           |
|    fps                | 921       |
|    iterations         | 20000     |
|    time_elapsed       | 108       |
|    total_timesteps    | 100000    |
| train/                |           |
|    entropy_loss       | -1.65e-05 |
|    explained_variance | 0.0278    |
|    learning_rate      | 0.0007    |
|    n_updates          | 19999     |
|    policy_loss        | -6.34e-08 |
|    value_loss         | 0.0285    |
-------------------------------------

In [68]:
from typing import Any, Union
import sys
import numpy as np
from stable_baselines3.common.logger import HumanOutputFormat, KVWriter, Logger

class MLflowOutputFormat(KVWriter):
    """
    Dumps key/value pairs into MLflow's numeric format.
    """

    def write(
        self,
        key_values: dict[str, Any],
        key_excluded: dict[str, Union[str, tuple[str, ...]]],
        step: int = 0,
    ) -> None:

        for (key, value), (_, excluded) in zip(
            sorted(key_values.items()), sorted(key_excluded.items())
        ):

            if excluded is not None and "mlflow" in excluded:
                continue

            if isinstance(value, np.ScalarType):
                if not isinstance(value, str):
                    mlflow.log_metric(key, value, step)


loggers = Logger(
    folder=None,
    output_formats=[HumanOutputFormat(sys.stdout), MLflowOutputFormat()],
)

In [71]:
# Create log dir where evaluation results will be saved
eval_log_dir = "./eval_logs/"
os.makedirs(eval_log_dir, exist_ok=True)
eval_env = make_monitored_env()
n_training_envs = 1

2025-10-30 08:21:29,722 - rl_trading_lab.environment.trading_env - INFO - TradingEnv initialized: randomize_start=True, hold_closes_position=True, one_trade_mode=True, min_episode_length=2, reward_type=returns, data_length=9954

In [72]:
# Create callback that evaluates agent for 5 episodes every 500 training environment steps.
# When using multiple training environments, agent will be evaluated every
# eval_freq calls to train_env.step(), thus it will be evaluated every
# (eval_freq * n_envs) training steps. See EvalCallback doc for more information.
eval_callback = EvalCallback(eval_env, best_model_save_path=eval_log_dir,
                              log_path=eval_log_dir, eval_freq=max(1000 // n_training_envs, 1),
                              n_eval_episodes=5, deterministic=True,
                              render=False)

In [73]:
with mlflow.start_run(run_name="A2C"):
    model = A2C(
        "MlpPolicy",
        env=make_monitored_env(),
        verbose=1,
        tensorboard_log="./tb_log/"
    )
    model.set_logger(loggers)
    model.learn(total_timesteps=10000, log_interval=100, callback=eval_callback)
    # mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=10)
    print()

2025-10-30 08:22:21,293 - rl_trading_lab.environment.trading_env - INFO - TradingEnv initialized: randomize_start=True, hold_closes_position=True, one_trade_mode=True, min_episode_length=2, reward_type=returns, data_length=9954
2025-10-30 08:22:21,297 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4819/9953
2025-10-30 08:22:21,299 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107918.59
2025-10-30 08:22:21,300 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107918.59 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,300 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,302 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,303 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:22:21,304 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.13, Commission=$0.00, Net=$-1.13 (cash flow: +$1998.87, -$0.00, balance: $9998.87)
2025-10-30 08:22:21,304 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6241/9953
2025-10-30 08:22:21,306 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108274.31
2025-10-30 08:22:21,306 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108274.31 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,307 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,309 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:22:21,310 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.69, Commission=$0.00, Net=$0.69 (cash flow: +$2000.69, -$0.00, balance: $10000.69)
2025-10-30 08:22:21,311 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7986/9953
2025-10-30 08:22:21,316 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110080.00
2025-10-30 08:22:21,316 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110080.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,317 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:22:21,319 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,320 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:22:21,320 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.58, Commission=$0.00, Net=$-3.58 (cash flow: -$2003.58, balance: $9996.42)
2025-10-30 08:22:21,321 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1688/9953
2025-10-30 08:22:21,322 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112496.60
2025-10-30 08:22:21,323 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112496.60 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,324 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:22:21,327 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,332 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:22:21,334 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.13, Commission=$0.00, Net=$0.13 (cash flow: +$2000.13, -$0.00, balance: $10000.13)
2025-10-30 08:22:21,335 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4080/9953
2025-10-30 08:22:21,338 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107848.44
2025-10-30 08:22:21,338 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107848.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,339 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,342 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:22:21,343 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.04, Commission=$0.00, Net=$0.04 (cash flow: +$2000.04, -$0.00, balance: $10000.04)
2025-10-30 08:22:21,344 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2134/9953
2025-10-30 08:22:21,351 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112209.23
2025-10-30 08:22:21,351 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112209.23 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,352 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:22:21,353 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:22:21,354 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.17, Commission=$0.00, Net=$0.17 (cash flow: -$1999.83, balance: $10000.17)
2025-10-30 08:22:21,355 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3863/9953
2025-10-30 08:22:21,358 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107721.79
2025-10-30 08:22:21,358 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107721.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,359 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:22:21,365 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:22:21,365 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.01, Commission=$0.00, Net=$2.01 (cash flow: +$2002.01, -$0.00, balance: $10002.01)
2025-10-30 08:22:21,366 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6549/9953
2025-10-30 08:22:21,368 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110071.13
2025-10-30 08:22:21,369 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110071.13 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,369 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:22:21,372 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,374 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:22:21,374 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.34, Commission=$0.00, Net=$-2.34 (cash flow: -$2002.34, balance: $9997.66)
2025-10-30 08:22:21,375 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2324/9953
2025-10-30 08:22:21,380 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111836.00
2025-10-30 08:22:21,381 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111836.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,381 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:22:21,383 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,386 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:22:21,387 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.83, Commission=$0.00, Net=$-1.83 (cash flow: -$2001.83, balance: $9998.17)
2025-10-30 08:22:21,388 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4687/9953
2025-10-30 08:22:21,390 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108240.54
2025-10-30 08:22:21,390 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108240.54 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,390 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,395 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:22:21,396 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.75, Commission=$0.00, Net=$-0.75 (cash flow: +$1999.25, -$0.00, balance: $9999.25)
2025-10-30 08:22:21,397 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5395/9953
2025-10-30 08:22:21,400 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108327.57
2025-10-30 08:22:21,401 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108327.57 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,401 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,403 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,407 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:22:21,408 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.98, Commission=$0.00, Net=$-0.98 (cash flow: +$1999.02, -$0.00, balance: $9999.02)
2025-10-30 08:22:21,409 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2673/9953
2025-10-30 08:22:21,411 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109334.09
2025-10-30 08:22:21,411 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109334.09 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,412 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:22:21,414 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,415 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:22:21,415 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.61, Commission=$0.00, Net=$2.61 (cash flow: -$1997.39, balance: $10002.61)
2025-10-30 08:22:21,416 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8355/9953
2025-10-30 08:22:21,421 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111354.82
2025-10-30 08:22:21,422 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111354.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,422 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:22:21,425 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,426 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:22:21,427 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.65, Commission=$0.00, Net=$-0.65 (cash flow: -$2000.65, balance: $9999.35)
2025-10-30 08:22:21,428 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3576/9953
2025-10-30 08:22:21,429 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108505.99
2025-10-30 08:22:21,430 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108505.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,430 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:22:21,433 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,437 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:22:21,438 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.94, Commission=$0.00, Net=$-0.94 (cash flow: -$2000.94, balance: $9999.06)
2025-10-30 08:22:21,439 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7401/9953
2025-10-30 08:22:21,441 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109831.35
2025-10-30 08:22:21,441 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109831.35 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,442 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:22:21,444 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,449 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:22:21,449 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.06, Commission=$0.00, Net=$-1.06 (cash flow: +$1998.94, -$0.00, balance: $9998.94)
2025-10-30 08:22:21,450 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5712/9953
2025-10-30 08:22:21,453 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107664.91
2025-10-30 08:22:21,453 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107664.91 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,453 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:22:21,455 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,461 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:22:21,462 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.15, Commission=$0.00, Net=$-2.15 (cash flow: +$1997.85, -$0.00, balance: $9997.85)
2025-10-30 08:22:21,463 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3733/9953
2025-10-30 08:22:21,466 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108154.10
2025-10-30 08:22:21,467 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108154.10 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,467 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,469 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,472 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:22:21,473 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.08, Commission=$0.00, Net=$-0.08 (cash flow: +$1999.92, -$0.00, balance: $9999.92)
2025-10-30 08:22:21,473 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9080/9953
2025-10-30 08:22:21,486 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109774.00
2025-10-30 08:22:21,486 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109774.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,486 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:22:21,489 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:22:21,489 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.87, Commission=$0.00, Net=$-0.87 (cash flow: -$2000.87, balance: $9999.13)
2025-10-30 08:22:21,490 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4795/9953
2025-10-30 08:22:21,492 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108106.00
2025-10-30 08:22:21,492 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108106.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,493 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,495 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:22:21,495 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.74, Commission=$0.00, Net=$1.74 (cash flow: +$2001.74, -$0.00, balance: $10001.74)

Using cpu device
Wrapping the env in a DummyVecEnv.

2025-10-30 08:22:21,496 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2365/9953
2025-10-30 08:22:21,502 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111237.71
2025-10-30 08:22:21,502 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111237.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,502 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:22:21,504 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:22:21,504 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: +$2000.20, -$0.00, balance: $10000.20)
2025-10-30 08:22:21,505 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8974/9953
2025-10-30 08:22:21,507 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110848.47
2025-10-30 08:22:21,507 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110848.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,508 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:22:21,510 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:22:21,511 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.48, Commission=$0.00, Net=$-0.48 (cash flow: -$2000.48, balance: $9999.52)
2025-10-30 08:22:21,511 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 165/9953
2025-10-30 08:22:21,517 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109027.29
2025-10-30 08:22:21,517 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109027.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,518 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:22:21,520 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,521 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:22:21,522 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.64, Commission=$0.00, Net=$0.64 (cash flow: -$1999.36, balance: $10000.64)
2025-10-30 08:22:21,523 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7/9953
2025-10-30 08:22:21,525 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108430.35
2025-10-30 08:22:21,525 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108430.35 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,525 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:22:21,529 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,531 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:22:21,532 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.17, Commission=$0.00, Net=$2.17 (cash flow: -$1997.83, balance: $10002.17)
2025-10-30 08:22:21,532 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8194/9953
2025-10-30 08:22:21,536 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111323.55
2025-10-30 08:22:21,536 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111323.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,537 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:22:21,541 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,542 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:22:21,543 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: +$2000.20, -$0.00, balance: $10000.20)
2025-10-30 08:22:21,544 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4680/9953
2025-10-30 08:22:21,546 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108551.44
2025-10-30 08:22:21,547 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108551.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,547 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:22:21,549 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,553 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 08:22:21,554 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.86, Commission=$0.00, Net=$-1.86 (cash flow: +$1998.14, -$0.00, balance: $9998.14)
2025-10-30 08:22:21,555 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3545/9953
2025-10-30 08:22:21,559 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108509.05
2025-10-30 08:22:21,559 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108509.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,559 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:22:21,562 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,566 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:22:21,567 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.28, Commission=$0.00, Net=$1.28 (cash flow: -$1998.72, balance: $10001.28)
2025-10-30 08:22:21,568 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1727/9953
2025-10-30 08:22:21,570 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112209.61
2025-10-30 08:22:21,570 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112209.61 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,570 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:22:21,572 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,573 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:22:21,574 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.06, Commission=$0.00, Net=$1.06 (cash flow: -$1998.94, balance: $10001.06)
2025-10-30 08:22:21,574 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9509/9953
2025-10-30 08:22:21,579 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110953.00
2025-10-30 08:22:21,579 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110953.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,580 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:22:21,583 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,585 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:22:21,586 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.36, Commission=$0.00, Net=$0.36 (cash flow: +$2000.36, -$0.00, balance: $10000.36)
2025-10-30 08:22:21,588 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3940/9953
2025-10-30 08:22:21,599 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108080.00
2025-10-30 08:22:21,601 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108080.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,601 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:22:21,603 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,614 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:22:21,614 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.37, Commission=$0.00, Net=$1.37 (cash flow: +$2001.37, -$0.00, balance: $10001.37)
2025-10-30 08:22:21,616 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8284/9953
2025-10-30 08:22:21,618 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111255.13
2025-10-30 08:22:21,618 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111255.13 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,619 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:22:21,623 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:22:21,623 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 08:22:21,624 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8108/9953
2025-10-30 08:22:21,626 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110760.01
2025-10-30 08:22:21,627 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110760.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,627 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:22:21,629 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 08:22:21,629 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.01, Commission=$0.00, Net=$-1.01 (cash flow: +$1998.99, -$0.00, balance: $9998.99)
2025-10-30 08:22:21,630 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1948/9953
2025-10-30 08:22:21,635 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112247.57
2025-10-30 08:22:21,636 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112247.57 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,636 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:22:21,639 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:22:21,639 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.12, Commission=$0.00, Net=$-0.12 (cash flow: -$2000.12, balance: $9999.88)
2025-10-30 08:22:21,640 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7113/9953
2025-10-30 08:22:21,643 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109550.01
2025-10-30 08:22:21,643 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109550.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,643 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:22:21,646 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:22:21,646 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 08:22:21,647 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 946/9953
2025-10-30 08:22:21,652 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113115.85
2025-10-30 08:22:21,652 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113115.85 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,653 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:22:21,655 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,656 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0177, signal=-1.0
2025-10-30 08:22:21,656 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.52, Commission=$0.00, Net=$0.52 (cash flow: +$2000.52, -$0.00, balance: $10000.52)
2025-10-30 08:22:21,657 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6209/9953
2025-10-30 08:22:21,662 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108250.43
2025-10-30 08:22:21,662 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108250.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,663 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:22:21,665 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,666 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:22:21,667 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.03, Commission=$0.00, Net=$1.03 (cash flow: -$1998.97, balance: $10001.03)
2025-10-30 08:22:21,668 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3980/9953
2025-10-30 08:22:21,670 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108254.00
2025-10-30 08:22:21,671 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108254.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,671 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:22:21,675 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,678 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:22:21,678 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: -$1999.80, balance: $10000.20)
2025-10-30 08:22:21,679 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 643/9953
2025-10-30 08:22:21,683 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112005.75
2025-10-30 08:22:21,684 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $112005.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,684 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:22:21,685 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,688 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:22:21,688 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.83, Commission=$0.00, Net=$1.83 (cash flow: +$2001.83, -$0.00, balance: $10001.83)
2025-10-30 08:22:21,689 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6042/9953
2025-10-30 08:22:21,692 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107815.21
2025-10-30 08:22:21,692 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107815.21 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,693 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:22:21,697 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,698 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:22:21,698 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.08, Commission=$0.00, Net=$1.08 (cash flow: +$2001.08, -$0.00, balance: $10001.08)
2025-10-30 08:22:21,700 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2654/9953
2025-10-30 08:22:21,702 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109621.19
2025-10-30 08:22:21,703 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109621.19 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:21,703 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:22:21,705 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,710 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:22:21,710 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.89, Commission=$0.00, Net=$0.89 (cash flow: +$2000.89, -$0.00, balance: $10000.89)
2025-10-30 08:22:21,711 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3788/9953
2025-10-30 08:22:21,713 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108239.33
2025-10-30 08:22:21,713 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108239.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,714 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:22:21,716 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,719 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:22:21,719 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.12, Commission=$0.00, Net=$0.12 (cash flow: -$1999.88, balance: $10000.12)
2025-10-30 08:22:21,720 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4942/9953
2025-10-30 08:22:21,724 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108278.01
2025-10-30 08:22:21,725 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108278.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,725 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:22:21,727 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:21,729 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:22:21,729 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.91, Commission=$0.00, Net=$0.91 (cash flow: -$1999.09, balance: $10000.91)
2025-10-30 08:22:21,730 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5883/9953
2025-10-30 08:22:21,736 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=106909.40
2025-10-30 08:22:21,736 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $106909.40 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:21,736 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187

Eval num_timesteps=500, episode_reward=0.00 +/- 0.00
Episode length: 7142.20 +/- 1718.37
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 7.14e+03 |
|    mean_reward        | 0        |
| time/                 |          |
|    total_timesteps    | 500      |
| train/                |          |
|    entropy_loss       | -1.07    |
|    explained_variance | 0.327    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 0.0302   |
|    value_loss         | 0.00171  |
------------------------------------
New best mean reward!
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.62     |
|    ep_rew_mean     | 4.55e-06 |
| time/              |          |
|    fps             | 19       |
|    iterations      | 100      |
|    time_elapsed    | 25       |
|    total_timesteps | 500      |
---------------------------------

2025-10-30 08:22:46,502 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109979.79
2025-10-30 08:22:46,502 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109979.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,503 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:22:46,505 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,507 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:22:46,507 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.46, Commission=$0.00, Net=$-0.46 (cash flow: +$1999.54, -$0.00, balance: $9999.54)
2025-10-30 08:22:46,508 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5957/9953
2025-10-30 08:22:46,513 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107141.76
2025-10-30 08:22:46,514 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107141.76 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,514 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:22:46,517 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,518 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:22:46,519 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.74, Commission=$0.00, Net=$0.74 (cash flow: -$1999.26, balance: $10000.74)
2025-10-30 08:22:46,519 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 125/9953
2025-10-30 08:22:46,521 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108901.31
2025-10-30 08:22:46,522 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108901.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,523 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:22:46,525 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:22:46,526 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.99, Commission=$0.00, Net=$-0.99 (cash flow: -$2000.99, balance: $9999.01)
2025-10-30 08:22:46,527 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 966/9953
2025-10-30 08:22:46,532 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113273.01
2025-10-30 08:22:46,533 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113273.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,533 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:22:46,535 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 08:22:46,535 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.96, Commission=$0.00, Net=$-0.96 (cash flow: +$1999.04, -$0.00, balance: $9999.04)
2025-10-30 08:22:46,537 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9766/9953
2025-10-30 08:22:46,539 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111241.16
2025-10-30 08:22:46,540 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111241.16 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,540 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:22:46,543 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:22:46,544 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.70, Commission=$0.00, Net=$-0.70 (cash flow: +$1999.30, -$0.00, balance: $9999.30)
2025-10-30 08:22:46,545 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8718/9953
2025-10-30 08:22:46,552 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111726.83
2025-10-30 08:22:46,552 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111726.83 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,553 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:22:46,555 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,561 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 08:22:46,562 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.80, Commission=$0.00, Net=$-2.80 (cash flow: +$1997.20, -$0.00, balance: $9997.20)
2025-10-30 08:22:46,563 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9898/9953
2025-10-30 08:22:46,566 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111597.67
2025-10-30 08:22:46,567 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111597.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,568 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:22:46,573 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,582 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:22:46,582 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.44, Commission=$0.00, Net=$-0.44 (cash flow: +$1999.56, -$0.00, balance: $9999.56)
2025-10-30 08:22:46,583 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 143/9953
2025-10-30 08:22:46,589 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109255.64
2025-10-30 08:22:46,592 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109255.64 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,593 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:22:46,596 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:22:46,597 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.86, Commission=$0.00, Net=$0.86 (cash flow: +$2000.86, -$0.00, balance: $10000.86)
2025-10-30 08:22:46,599 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1375/9953
2025-10-30 08:22:46,609 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113253.09
2025-10-30 08:22:46,610 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113253.09 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,610 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:22:46,612 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 08:22:46,612 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.09, Commission=$0.00, Net=$1.09 (cash flow: +$2001.09, -$0.00, balance: $10001.09)
2025-10-30 08:22:46,619 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7092/9953
2025-10-30 08:22:46,623 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109430.38
2025-10-30 08:22:46,625 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109430.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,625 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:22:46,628 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,639 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 08:22:46,640 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 08:22:46,641 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2173/9953
2025-10-30 08:22:46,646 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112100.71
2025-10-30 08:22:46,647 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112100.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,647 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:22:46,650 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,656 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:22:46,657 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.22, Commission=$0.00, Net=$-4.22 (cash flow: +$1995.78, -$0.00, balance: $9995.78)
2025-10-30 08:22:46,658 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2688/9953
2025-10-30 08:22:46,662 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108854.66
2025-10-30 08:22:46,663 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108854.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,664 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:22:46,668 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,675 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:22:46,676 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.72, Commission=$0.00, Net=$2.72 (cash flow: -$1997.28, balance: $10002.72)
2025-10-30 08:22:46,676 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2469/9953
2025-10-30 08:22:46,680 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110742.28
2025-10-30 08:22:46,680 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110742.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,681 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:22:46,683 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:22:46,683 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: -$1999.62, balance: $10000.38)
2025-10-30 08:22:46,684 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4792/9953
2025-10-30 08:22:46,691 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107999.89
2025-10-30 08:22:46,691 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107999.89 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,692 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:22:46,694 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,696 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:22:46,696 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.97, Commission=$0.00, Net=$-1.97 (cash flow: -$2001.97, balance: $9998.03)
2025-10-30 08:22:46,697 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2921/9953
2025-10-30 08:22:46,699 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108630.69
2025-10-30 08:22:46,700 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108630.69 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,700 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:22:46,704 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:22:46,705 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.07, Commission=$0.00, Net=$-0.07 (cash flow: +$1999.93, -$0.00, balance: $9999.93)
2025-10-30 08:22:46,705 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1239/9953
2025-10-30 08:22:46,712 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113629.10
2025-10-30 08:22:46,712 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113629.10 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,712 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 08:22:46,716 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176
2025-10-30 08:22:46,716 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.15, Commission=$0.00, Net=$-0.15 (cash flow: -$2000.15, balance: $9999.85)
2025-10-30 08:22:46,718 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4360/9953
2025-10-30 08:22:46,724 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107524.06
2025-10-30 08:22:46,724 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107524.06 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,724 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:22:46,727 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,729 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:22:46,729 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: +$1999.89, -$0.00, balance: $9999.89)
2025-10-30 08:22:46,730 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9657/9953
2025-10-30 08:22:46,738 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111027.48
2025-10-30 08:22:46,738 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111027.48 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,739 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:22:46,741 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:22:46,745 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:22:46,746 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.63, Commission=$0.00, Net=$0.63 (cash flow: +$2000.63, -$0.00, balance: $10000.63)
2025-10-30 08:22:46,747 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1085/9953
2025-10-30 08:22:46,752 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113445.00
2025-10-30 08:22:46,753 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113445.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,753 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 08:22:46,756 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 08:22:46,757 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.25, Commission=$0.00, Net=$0.25 (cash flow: +$2000.25, -$0.00, balance: $10000.25)
2025-10-30 08:22:46,759 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1598/9953
2025-10-30 08:22:46,760 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111851.93
2025-10-30 08:22:46,761 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111851.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,761 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:22:46,764 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:22:46,764 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.65, Commission=$0.00, Net=$-2.65 (cash flow: -$2002.65, balance: $9997.35)
2025-10-30 08:22:46,765 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9061/9953
2025-10-30 08:22:46,773 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110078.61
2025-10-30 08:22:46,773 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110078.61 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,774 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:22:46,776 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:22:46,777 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.59, Commission=$0.00, Net=$-0.59 (cash flow: -$2000.59, balance: $9999.41)
2025-10-30 08:22:46,778 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6478/9953
2025-10-30 08:22:46,780 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109891.26
2025-10-30 08:22:46,781 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109891.26 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,781 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:22:46,784 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:22:46,784 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.79, Commission=$0.00, Net=$0.79 (cash flow: +$2000.79, -$0.00, balance: $10000.79)
2025-10-30 08:22:46,785 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3426/9953
2025-10-30 08:22:46,789 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108205.68
2025-10-30 08:22:46,789 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108205.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:22:46,790 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:22:46,795 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:22:46,796 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.51, Commission=$0.00, Net=$0.51 (cash flow: -$1999.49, balance: $10000.51)
2025-10-30 08:22:46,797 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2153/9953
2025-10-30 08:22:46,800 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112236.52
2025-10-30 08:22:46,800 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112236.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:22:46,801 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178

Eval num_timesteps=1000, episode_reward=0.00 +/- 0.00
Episode length: 7543.60 +/- 2230.12
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 7.54e+03 |
|    mean_reward        | 0        |
| time/                 |          |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -1.07    |
|    explained_variance | -0.346   |
|    learning_rate      | 0.0007   |
|    n_updates          | 199      |
|    policy_loss        | 0.0224   |
|    value_loss         | 0.00266  |
------------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 3.56      |
|    ep_rew_mean     | -1.72e-05 |
| time/              |           |
|    fps             | 19        |
|    iterations      | 200       |
|    time_elapsed    | 52        |
|    total_timesteps | 1000      |
----------------------------------

2025-10-30 08:23:13,699 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110500.96
2025-10-30 08:23:13,699 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110500.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,699 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:23:13,702 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,705 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:23:13,705 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.60, Commission=$0.00, Net=$0.60 (cash flow: +$2000.60, -$0.00, balance: $10000.60)
2025-10-30 08:23:13,706 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8985/9953
2025-10-30 08:23:13,710 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110859.80
2025-10-30 08:23:13,710 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110859.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,710 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:13,712 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,714 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:23:13,715 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: -$1999.15, balance: $10000.85)
2025-10-30 08:23:13,716 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1213/9953
2025-10-30 08:23:13,721 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113608.68
2025-10-30 08:23:13,721 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113608.68 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,721 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 08:23:13,723 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 08:23:13,723 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.15, Commission=$0.00, Net=$-0.15 (cash flow: +$1999.85, -$0.00, balance: $9999.85)
2025-10-30 08:23:13,724 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7032/9953
2025-10-30 08:23:13,729 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109030.56
2025-10-30 08:23:13,729 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109030.56 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,730 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:23:13,734 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:23:13,735 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: +$1999.79, -$0.00, balance: $9999.79)
2025-10-30 08:23:13,736 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1126/9953
2025-10-30 08:23:13,739 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113248.87
2025-10-30 08:23:13,740 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113248.87 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,740 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:23:13,745 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 08:23:13,745 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.42, Commission=$0.00, Net=$-0.42 (cash flow: -$2000.42, balance: $9999.58)
2025-10-30 08:23:13,746 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1603/9953
2025-10-30 08:23:13,747 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111939.47
2025-10-30 08:23:13,748 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111939.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,748 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:23:13,750 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,755 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:23:13,755 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.08, Commission=$0.00, Net=$-2.08 (cash flow: -$2002.08, balance: $9997.92)
2025-10-30 08:23:13,756 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9755/9953
2025-10-30 08:23:13,761 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111245.97
2025-10-30 08:23:13,761 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111245.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,762 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:13,763 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,766 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:23:13,766 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.51, Commission=$0.00, Net=$-1.51 (cash flow: -$2001.51, balance: $9998.49)
2025-10-30 08:23:13,767 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2484/9953
2025-10-30 08:23:13,769 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111014.00
2025-10-30 08:23:13,769 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111014.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,769 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:13,775 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,777 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:23:13,777 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.88, Commission=$0.00, Net=$0.88 (cash flow: -$1999.12, balance: $10000.88)
2025-10-30 08:23:13,778 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2362/9953
2025-10-30 08:23:13,780 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111286.31
2025-10-30 08:23:13,780 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111286.31 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,780 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:23:13,783 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,785 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:23:13,785 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.81, Commission=$0.00, Net=$0.81 (cash flow: +$2000.81, -$0.00, balance: $10000.81)
2025-10-30 08:23:13,786 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 264/9953
2025-10-30 08:23:13,791 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108527.85
2025-10-30 08:23:13,791 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108527.85 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,791 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:23:13,794 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,797 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:23:13,797 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.91, Commission=$0.00, Net=$-1.91 (cash flow: +$1998.09, -$0.00, balance: $9998.09)
2025-10-30 08:23:13,798 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5503/9953
2025-10-30 08:23:13,801 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107654.93
2025-10-30 08:23:13,801 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107654.93 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,801 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:23:13,806 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,808 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:23:13,808 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.95, Commission=$0.00, Net=$-1.95 (cash flow: +$1998.05, -$0.00, balance: $9998.05)
2025-10-30 08:23:13,809 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3286/9953
2025-10-30 08:23:13,812 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108072.00
2025-10-30 08:23:13,812 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108072.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,813 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:23:13,814 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,819 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:23:13,819 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.56, Commission=$0.00, Net=$-0.56 (cash flow: -$2000.56, balance: $9999.44)
2025-10-30 08:23:13,820 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2115/9953
2025-10-30 08:23:13,822 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112115.55
2025-10-30 08:23:13,822 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112115.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,823 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:23:13,825 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,827 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:23:13,828 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.79, Commission=$0.00, Net=$0.79 (cash flow: +$2000.79, -$0.00, balance: $10000.79)
2025-10-30 08:23:13,829 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3935/9953
2025-10-30 08:23:13,835 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108306.39
2025-10-30 08:23:13,835 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108306.39 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,836 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:23:13,841 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,843 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:23:13,843 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.08, Commission=$0.00, Net=$2.08 (cash flow: -$1997.92, balance: $10002.08)
2025-10-30 08:23:13,844 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5036/9953
2025-10-30 08:23:13,845 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108852.81
2025-10-30 08:23:13,846 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108852.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,847 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:23:13,848 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:23:13,848 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.71, Commission=$0.00, Net=$-0.71 (cash flow: -$2000.71, balance: $9999.29)
2025-10-30 08:23:13,850 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7005/9953
2025-10-30 08:23:13,856 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109124.94
2025-10-30 08:23:13,856 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109124.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,856 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:23:13,860 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:23:13,861 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: -$1999.84, balance: $10000.16)
2025-10-30 08:23:13,861 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6396/9953
2025-10-30 08:23:13,865 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108685.79
2025-10-30 08:23:13,865 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108685.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,866 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:23:13,868 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:23:13,868 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.13, Commission=$0.00, Net=$-0.13 (cash flow: -$2000.13, balance: $9999.87)
2025-10-30 08:23:13,869 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5439/9953
2025-10-30 08:23:13,876 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108163.41
2025-10-30 08:23:13,876 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108163.41 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,876 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:23:13,880 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:23:13,880 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: +$1999.94, -$0.00, balance: $9999.94)
2025-10-30 08:23:13,881 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5251/9953
2025-10-30 08:23:13,886 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108162.13
2025-10-30 08:23:13,886 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108162.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,887 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:23:13,892 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:23:13,892 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.17, Commission=$0.00, Net=$-0.17 (cash flow: +$1999.83, -$0.00, balance: $9999.83)
2025-10-30 08:23:13,893 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 251/9953
2025-10-30 08:23:13,897 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108631.67
2025-10-30 08:23:13,897 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108631.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,898 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:23:13,902 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,905 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:23:13,906 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.26, Commission=$0.00, Net=$-2.26 (cash flow: +$1997.74, -$0.00, balance: $9997.74)
2025-10-30 08:23:13,907 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5272/9953
2025-10-30 08:23:13,910 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108175.00
2025-10-30 08:23:13,910 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108175.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:13,911 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:23:13,912 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,915 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:23:13,915 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.58, Commission=$0.00, Net=$-2.58 (cash flow: +$1997.42, -$0.00, balance: $9997.42)
2025-10-30 08:23:13,917 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9678/9953
2025-10-30 08:23:13,922 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111031.79
2025-10-30 08:23:13,922 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111031.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,922 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:13,924 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,928 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:23:13,928 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.57, Commission=$0.00, Net=$0.57 (cash flow: -$1999.43, balance: $10000.57)
2025-10-30 08:23:13,929 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7952/9953
2025-10-30 08:23:13,932 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109933.63
2025-10-30 08:23:13,933 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109933.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:13,933 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:23:13,938 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:13,941 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0

Eval num_timesteps=1500, episode_reward=0.00 +/- 0.00
Episode length: 7238.40 +/- 2404.73
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 7.24e+03 |
|    mean_reward        | 0        |
| time/                 |          |
|    total_timesteps    | 1500     |
| train/                |          |
|    entropy_loss       | -1.09    |
|    explained_variance | 0.661    |
|    learning_rate      | 0.0007   |
|    n_updates          | 299      |
|    policy_loss        | -0.00201 |
|    value_loss         | 7.64e-06 |
------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.62     |
|    ep_rew_mean     | 4.91e-06 |
| time/              |          |
|    fps             | 19       |
|    iterations      | 300      |
|    time_elapsed    | 78       |
|    total_timesteps | 1500     |
---------------------------------

2025-10-30 08:23:39,799 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,801 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:23:39,801 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.47, Commission=$0.00, Net=$0.47 (cash flow: +$2000.47, -$0.00, balance: $10000.47)
2025-10-30 08:23:39,802 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 149/9953
2025-10-30 08:23:39,804 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109263.99
2025-10-30 08:23:39,804 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109263.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,805 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:23:39,808 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,810 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:23:39,810 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.57, Commission=$0.00, Net=$-1.57 (cash flow: -$2001.57, balance: $9998.43)
2025-10-30 08:23:39,811 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4751/9953
2025-10-30 08:23:39,816 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107960.00
2025-10-30 08:23:39,817 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107960.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,817 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:23:39,818 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,820 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:23:39,821 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 08:23:39,823 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2647/9953
2025-10-30 08:23:39,825 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109687.08
2025-10-30 08:23:39,826 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109687.08 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,826 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:23:39,828 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,833 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:23:39,834 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.17, Commission=$0.00, Net=$-1.17 (cash flow: +$1998.83, -$0.00, balance: $9998.83)
2025-10-30 08:23:39,835 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9600/9953
2025-10-30 08:23:39,837 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111039.01
2025-10-30 08:23:39,838 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111039.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,838 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:39,842 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,844 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:23:39,845 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.65, Commission=$0.00, Net=$-0.65 (cash flow: -$2000.65, balance: $9999.35)
2025-10-30 08:23:39,846 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5402/9953
2025-10-30 08:23:39,851 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108157.45
2025-10-30 08:23:39,851 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108157.45 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,851 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:23:39,854 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:23:39,854 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.04, Commission=$0.00, Net=$-1.04 (cash flow: +$1998.96, -$0.00, balance: $9998.96)
2025-10-30 08:23:39,855 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2907/9953
2025-10-30 08:23:39,858 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109096.52
2025-10-30 08:23:39,859 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109096.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,859 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:23:39,861 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,864 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:23:39,865 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.77, Commission=$0.00, Net=$-1.77 (cash flow: +$1998.23, -$0.00, balance: $9998.23)
2025-10-30 08:23:39,866 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6898/9953
2025-10-30 08:23:39,870 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109147.00
2025-10-30 08:23:39,870 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109147.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,871 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:23:39,872 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:23:39,873 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.05, Commission=$0.00, Net=$-0.05 (cash flow: -$2000.05, balance: $9999.95)
2025-10-30 08:23:39,875 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9550/9953
2025-10-30 08:23:39,882 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110941.42
2025-10-30 08:23:39,882 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110941.42 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,883 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:39,885 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,886 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:23:39,887 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.11, Commission=$0.00, Net=$-1.11 (cash flow: -$2001.11, balance: $9998.89)
2025-10-30 08:23:39,888 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5398/9953
2025-10-30 08:23:39,890 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108282.31
2025-10-30 08:23:39,890 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108282.31 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,891 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:23:39,895 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,900 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:23:39,900 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.31, Commission=$0.00, Net=$-2.31 (cash flow: +$1997.69, -$0.00, balance: $9997.69)
2025-10-30 08:23:39,901 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 509/9953
2025-10-30 08:23:39,903 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109986.75
2025-10-30 08:23:39,903 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109986.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,904 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:23:39,906 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,911 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:23:39,912 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.16, Commission=$0.00, Net=$-0.16 (cash flow: +$1999.84, -$0.00, balance: $9999.84)
2025-10-30 08:23:39,912 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2532/9953
2025-10-30 08:23:39,915 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110261.31
2025-10-30 08:23:39,916 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110261.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,916 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:23:39,919 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,924 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:23:39,925 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.81, Commission=$0.00, Net=$-2.81 (cash flow: -$2002.81, balance: $9997.19)
2025-10-30 08:23:39,926 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 518/9953
2025-10-30 08:23:39,928 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109878.41
2025-10-30 08:23:39,928 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109878.41 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,929 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:23:39,932 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,935 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:23:39,936 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.00, Commission=$0.00, Net=$-1.00 (cash flow: -$2001.00, balance: $9999.00)
2025-10-30 08:23:39,937 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7067/9953
2025-10-30 08:23:39,942 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109131.53
2025-10-30 08:23:39,943 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109131.53 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,943 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:23:39,946 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:23:39,947 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.34, Commission=$0.00, Net=$1.34 (cash flow: -$1998.66, balance: $10001.34)
2025-10-30 08:23:39,949 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6151/9953
2025-10-30 08:23:39,951 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108455.76
2025-10-30 08:23:39,952 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108455.76 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,952 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:23:39,955 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,958 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 08:23:39,958 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.43, Commission=$0.00, Net=$-1.43 (cash flow: +$1998.57, -$0.00, balance: $9998.57)
2025-10-30 08:23:39,959 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2336/9953
2025-10-30 08:23:39,964 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111889.68
2025-10-30 08:23:39,965 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111889.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,965 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:23:39,967 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,969 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:23:39,969 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.61, Commission=$0.00, Net=$0.61 (cash flow: -$1999.39, balance: $10000.61)
2025-10-30 08:23:39,970 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5740/9953
2025-10-30 08:23:39,975 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107637.21
2025-10-30 08:23:39,975 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107637.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:39,975 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:23:39,980 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:23:39,980 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.27, Commission=$0.00, Net=$-0.27 (cash flow: -$2000.27, balance: $9999.73)
2025-10-30 08:23:39,981 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 855/9953
2025-10-30 08:23:39,985 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112420.80
2025-10-30 08:23:39,986 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112420.80 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,986 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:23:39,988 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:39,993 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:23:39,993 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.27, Commission=$0.00, Net=$-1.27 (cash flow: +$1998.73, -$0.00, balance: $9998.73)
2025-10-30 08:23:39,994 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5129/9953
2025-10-30 08:23:39,998 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108018.00
2025-10-30 08:23:39,998 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108018.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:39,999 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:23:40,001 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:40,003 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:23:40,003 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: +$1999.19, -$0.00, balance: $9999.19)
2025-10-30 08:23:40,004 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4954/9953
2025-10-30 08:23:40,012 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108280.94
2025-10-30 08:23:40,012 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108280.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:40,012 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:23:40,014 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:40,019 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:23:40,019 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.50, Commission=$0.00, Net=$-0.50 (cash flow: -$2000.50, balance: $9999.50)
2025-10-30 08:23:40,020 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8675/9953
2025-10-30 08:23:40,021 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111054.00
2025-10-30 08:23:40,022 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111054.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:40,023 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:23:40,026 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:40,029 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:23:40,030 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: +$2000.16, -$0.00, balance: $10000.16)
2025-10-30 08:23:40,031 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9806/9953
2025-10-30 08:23:40,033 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111309.79
2025-10-30 08:23:40,033 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111309.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:40,034 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:40,039 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:23:40,039 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.27, Commission=$0.00, Net=$-0.27 (cash flow: -$2000.27, balance: $9999.73)
2025-10-30 08:23:40,040 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9403/9953
2025-10-30 08:23:40,044 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110770.04
2025-10-30 08:23:40,044 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110770.04 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:40,044 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:23:40,046 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:40,051 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181

Eval num_timesteps=2000, episode_reward=-0.00 +/- 0.00
Episode length: 636.40 +/- 1041.65
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 636       |
|    mean_reward        | -4.98e-05 |
| time/                 |           |
|    total_timesteps    | 2000      |
| train/                |           |
|    entropy_loss       | -1.09     |
|    explained_variance | -3.49e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 399       |
|    policy_loss        | -0.00786  |
|    value_loss         | 5.08e-05  |
-------------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 3.59      |
|    ep_rew_mean     | -1.69e-05 |
| time/              |           |
|    fps             | 24        |
|    iterations      | 400       |
|    time_elapsed    | 81        |
|    total_timesteps | 2000      |
----------------------------------

2025-10-30 08:23:42,915 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:42,918 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:23:42,918 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.28, Commission=$0.00, Net=$-0.28 (cash flow: +$1999.72, -$0.00, balance: $9999.72)
2025-10-30 08:23:42,919 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 734/9953
2025-10-30 08:23:42,924 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111920.51
2025-10-30 08:23:42,925 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111920.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:42,925 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:23:42,926 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:23:42,927 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.01, Commission=$0.00, Net=$-0.01 (cash flow: -$2000.01, balance: $9999.99)
2025-10-30 08:23:42,928 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1634/9953
2025-10-30 08:23:42,931 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112352.79
2025-10-30 08:23:42,931 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112352.79 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:42,932 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:23:42,934 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:42,940 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:23:42,940 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.65, Commission=$0.00, Net=$-0.65 (cash flow: +$1999.35, -$0.00, balance: $9999.35)
2025-10-30 08:23:42,941 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5725/9953
2025-10-30 08:23:42,943 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107549.66
2025-10-30 08:23:42,943 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107549.66 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:42,944 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:23:42,946 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:42,952 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:23:42,952 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.74, Commission=$0.00, Net=$1.74 (cash flow: +$2001.74, -$0.00, balance: $10001.74)
2025-10-30 08:23:42,953 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2220/9953
2025-10-30 08:23:42,955 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111818.52
2025-10-30 08:23:42,956 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111818.52 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:42,956 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:23:42,958 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:42,960 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:23:42,961 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.48, Commission=$0.00, Net=$1.48 (cash flow: -$1998.52, balance: $10001.48)
2025-10-30 08:23:42,962 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5936/9953
2025-10-30 08:23:42,966 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107566.61
2025-10-30 08:23:42,967 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107566.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:42,967 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:23:42,969 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:42,970 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:23:42,971 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.14, Commission=$0.00, Net=$1.14 (cash flow: +$2001.14, -$0.00, balance: $10001.14)
2025-10-30 08:23:42,972 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9048/9953
2025-10-30 08:23:42,978 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110000.00
2025-10-30 08:23:42,979 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110000.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:42,979 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:23:42,981 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:23:42,981 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 08:23:42,982 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6075/9953
2025-10-30 08:23:42,985 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107661.64
2025-10-30 08:23:42,985 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107661.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:42,986 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:23:42,991 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:23:42,992 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.63, Commission=$0.00, Net=$-0.63 (cash flow: -$2000.63, balance: $9999.37)
2025-10-30 08:23:42,993 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5333/9953
2025-10-30 08:23:42,994 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108422.73
2025-10-30 08:23:42,995 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108422.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:42,995 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:23:42,997 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,004 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:23:43,005 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.79, Commission=$0.00, Net=$0.79 (cash flow: +$2000.79, -$0.00, balance: $10000.79)
2025-10-30 08:23:43,005 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7879/9953
2025-10-30 08:23:43,013 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109545.65
2025-10-30 08:23:43,014 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109545.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,014 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:23:43,016 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,021 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:23:43,021 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.52, Commission=$0.00, Net=$1.52 (cash flow: -$1998.48, balance: $10001.52)
2025-10-30 08:23:43,022 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8756/9953
2025-10-30 08:23:43,024 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111719.14
2025-10-30 08:23:43,025 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111719.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,025 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:23:43,027 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:23:43,028 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.36, Commission=$0.00, Net=$-1.36 (cash flow: -$2001.36, balance: $9998.64)
2025-10-30 08:23:43,028 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4169/9953
2025-10-30 08:23:43,034 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107150.01
2025-10-30 08:23:43,034 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107150.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,034 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:23:43,036 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,038 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:23:43,039 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.56, Commission=$0.00, Net=$-0.56 (cash flow: -$2000.56, balance: $9999.44)
2025-10-30 08:23:43,040 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 345/9953
2025-10-30 08:23:43,043 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109284.68
2025-10-30 08:23:43,043 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109284.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,043 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:23:43,048 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,050 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:23:43,050 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.38, Commission=$0.00, Net=$0.38 (cash flow: -$1999.62, balance: $10000.38)
2025-10-30 08:23:43,050 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5053/9953
2025-10-30 08:23:43,053 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108941.00
2025-10-30 08:23:43,053 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108941.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,053 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:23:43,056 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,060 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:23:43,060 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.06, Commission=$0.00, Net=$-2.06 (cash flow: -$2002.06, balance: $9997.94)
2025-10-30 08:23:43,061 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5790/9953
2025-10-30 08:23:43,064 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107380.25
2025-10-30 08:23:43,065 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107380.25 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:43,065 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:23:43,068 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,071 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:23:43,072 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.83, Commission=$0.00, Net=$0.83 (cash flow: +$2000.83, -$0.00, balance: $10000.83)
2025-10-30 08:23:43,073 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4542/9953
2025-10-30 08:23:43,075 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108151.65
2025-10-30 08:23:43,075 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108151.65 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,075 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:23:43,078 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,080 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:23:43,081 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.79, Commission=$0.00, Net=$-2.79 (cash flow: -$2002.79, balance: $9997.21)
2025-10-30 08:23:43,082 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3353/9953
2025-10-30 08:23:43,087 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108500.00
2025-10-30 08:23:43,087 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108500.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:43,088 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:23:43,090 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:23:43,090 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.19, Commission=$0.00, Net=$1.19 (cash flow: +$2001.19, -$0.00, balance: $10001.19)
2025-10-30 08:23:43,091 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6899/9953
2025-10-30 08:23:43,093 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109149.98
2025-10-30 08:23:43,094 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109149.98 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:43,094 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:23:43,096 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,101 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:23:43,102 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.19, Commission=$0.00, Net=$3.19 (cash flow: +$2003.19, -$0.00, balance: $10003.19)
2025-10-30 08:23:43,102 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1876/9953
2025-10-30 08:23:43,104 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112324.75
2025-10-30 08:23:43,104 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112324.75 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,105 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:23:43,107 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,110 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:23:43,110 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.70, Commission=$0.00, Net=$-0.70 (cash flow: -$2000.70, balance: $9999.30)
2025-10-30 08:23:43,111 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3068/9953
2025-10-30 08:23:43,112 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108300.17
2025-10-30 08:23:43,113 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108300.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,113 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:23:43,119 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,121 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:23:43,121 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.61, Commission=$0.00, Net=$0.61 (cash flow: -$1999.39, balance: $10000.61)
2025-10-30 08:23:43,122 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6829/9953
2025-10-30 08:23:43,124 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109609.43
2025-10-30 08:23:43,125 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109609.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,125 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:23:43,127 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:23:43,128 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.76, Commission=$0.00, Net=$-0.76 (cash flow: -$2000.76, balance: $9999.24)
2025-10-30 08:23:43,129 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8108/9953
2025-10-30 08:23:43,131 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110760.01
2025-10-30 08:23:43,131 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110760.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:23:43,131 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:23:43,137 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,138 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 08:23:43,139 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.98, Commission=$0.00, Net=$-1.98 (cash flow: +$1998.02, -$0.00, balance: $9998.02)
2025-10-30 08:23:43,139 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8592/9953
2025-10-30 08:23:43,142 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111261.99
2025-10-30 08:23:43,142 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111261.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:23:43,143 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:23:43,145 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:23:43,150 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:23:43,151 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.37, Commission=$0.00, Net=$2.37 (cash flow: -$1997.63, balance: $10002.37)

Eval num_timesteps=2500, episode_reward=0.00 +/- 0.00
Episode length: 7759.40 +/- 2239.86
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 7.76e+03  |
|    mean_reward        | 0         |
| time/                 |           |
|    total_timesteps    | 2500      |
| train/                |           |
|    entropy_loss       | -1.09     |
|    explained_variance | -1.31     |
|    learning_rate      | 0.0007    |
|    n_updates          | 499       |
|    policy_loss        | -0.000412 |
|    value_loss         | 2.96e-06  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.69     |
|    ep_rew_mean     | 1.3e-05  |
| time/              |          |
|    fps             | 22       |
|    iterations      | 500      |
|    time_elapsed    | 109      |
|    total_timesteps | 2500     |
---------------------------------

2025-10-30 08:24:10,980 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109489.93
2025-10-30 08:24:10,980 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109489.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:10,980 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:10,982 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:10,985 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:24:10,985 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.53, Commission=$0.00, Net=$-3.53 (cash flow: -$2003.53, balance: $9996.47)
2025-10-30 08:24:10,986 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8411/9953
2025-10-30 08:24:10,988 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110951.50
2025-10-30 08:24:10,988 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110951.50 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:10,989 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:10,993 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:10,994 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:10,995 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.05, Commission=$0.00, Net=$0.05 (cash flow: +$2000.05, -$0.00, balance: $10000.05)
2025-10-30 08:24:10,995 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 361/9953
2025-10-30 08:24:10,998 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109769.47
2025-10-30 08:24:10,999 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109769.47 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:10,999 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:11,001 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,002 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:24:11,003 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.05, Commission=$0.00, Net=$-2.05 (cash flow: +$1997.95, -$0.00, balance: $9997.95)
2025-10-30 08:24:11,004 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6831/9953
2025-10-30 08:24:11,010 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109701.89
2025-10-30 08:24:11,010 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109701.89 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,011 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:11,012 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:24:11,013 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.37, Commission=$0.00, Net=$-0.37 (cash flow: +$1999.63, -$0.00, balance: $9999.63)
2025-10-30 08:24:11,014 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 246/9953
2025-10-30 08:24:11,016 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108616.99
2025-10-30 08:24:11,016 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108616.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,016 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:11,019 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,021 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:11,021 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.10, Commission=$0.00, Net=$-0.10 (cash flow: -$2000.10, balance: $9999.90)
2025-10-30 08:24:11,022 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9717/9953
2025-10-30 08:24:11,028 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111042.28
2025-10-30 08:24:11,029 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111042.28 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,029 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:11,031 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,033 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:11,034 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.22, Commission=$0.00, Net=$-0.22 (cash flow: +$1999.78, -$0.00, balance: $9999.78)
2025-10-30 08:24:11,035 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6359/9953
2025-10-30 08:24:11,040 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108761.91
2025-10-30 08:24:11,040 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108761.91 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,041 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:11,042 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,044 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:11,045 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.32, Commission=$0.00, Net=$-1.32 (cash flow: -$2001.32, balance: $9998.68)
2025-10-30 08:24:11,046 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 899/9953
2025-10-30 08:24:11,049 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112855.99
2025-10-30 08:24:11,050 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112855.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,050 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:24:11,054 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,057 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 08:24:11,057 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.19, Commission=$0.00, Net=$1.19 (cash flow: +$2001.19, -$0.00, balance: $10001.19)
2025-10-30 08:24:11,057 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3037/9953
2025-10-30 08:24:11,059 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108357.94
2025-10-30 08:24:11,060 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108357.94 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,060 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:11,063 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:11,063 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 08:24:11,064 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8586/9953
2025-10-30 08:24:11,066 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111134.45
2025-10-30 08:24:11,067 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111134.45 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,067 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:11,072 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,074 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:24:11,075 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: -$2000.73, balance: $9999.27)
2025-10-30 08:24:11,075 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6512/9953
2025-10-30 08:24:11,079 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110163.52
2025-10-30 08:24:11,080 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110163.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,080 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:11,084 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,086 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:24:11,086 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.08, Commission=$0.00, Net=$0.08 (cash flow: +$2000.08, -$0.00, balance: $10000.08)
2025-10-30 08:24:11,087 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1370/9953
2025-10-30 08:24:11,090 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113536.31
2025-10-30 08:24:11,091 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113536.31 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,091 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 08:24:11,094 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 08:24:11,095 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.33, Commission=$0.00, Net=$0.33 (cash flow: +$2000.33, -$0.00, balance: $10000.33)
2025-10-30 08:24:11,095 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6618/9953
2025-10-30 08:24:11,101 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109822.00
2025-10-30 08:24:11,102 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109822.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,102 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:11,104 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:11,104 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.36, Commission=$0.00, Net=$-0.36 (cash flow: -$2000.36, balance: $9999.64)
2025-10-30 08:24:11,105 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4807/9953
2025-10-30 08:24:11,109 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107996.03
2025-10-30 08:24:11,109 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107996.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,110 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:11,113 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,117 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:11,117 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.42, Commission=$0.00, Net=$0.42 (cash flow: -$1999.58, balance: $10000.42)
2025-10-30 08:24:11,118 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9205/9953
2025-10-30 08:24:11,125 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110512.91
2025-10-30 08:24:11,125 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110512.91 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,125 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:24:11,127 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,133 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 08:24:11,134 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.90, Commission=$0.00, Net=$-2.90 (cash flow: +$1997.10, -$0.00, balance: $9997.10)
2025-10-30 08:24:11,135 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 876/9953
2025-10-30 08:24:11,136 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112463.83
2025-10-30 08:24:11,137 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112463.83 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,137 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:11,139 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,141 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:24:11,141 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.78, Commission=$0.00, Net=$-2.78 (cash flow: -$2002.78, balance: $9997.22)
2025-10-30 08:24:11,142 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3315/9953
2025-10-30 08:24:11,144 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108184.93
2025-10-30 08:24:11,145 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108184.93 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,145 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:11,150 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:11,151 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.17, Commission=$0.00, Net=$1.17 (cash flow: +$2001.17, -$0.00, balance: $10001.17)
2025-10-30 08:24:11,152 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3720/9953
2025-10-30 08:24:11,154 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107963.81
2025-10-30 08:24:11,154 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107963.81 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,155 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:11,156 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:11,157 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.68, Commission=$0.00, Net=$-0.68 (cash flow: +$1999.32, -$0.00, balance: $9999.32)
2025-10-30 08:24:11,158 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1905/9953
2025-10-30 08:24:11,165 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112296.04
2025-10-30 08:24:11,166 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112296.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,166 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:11,169 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,171 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:24:11,171 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.46, Commission=$0.00, Net=$-0.46 (cash flow: +$1999.54, -$0.00, balance: $9999.54)
2025-10-30 08:24:11,179 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9114/9953
2025-10-30 08:24:11,181 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110082.23
2025-10-30 08:24:11,181 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110082.23 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,182 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:11,186 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,188 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:24:11,188 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.27, Commission=$0.00, Net=$-2.27 (cash flow: +$1997.73, -$0.00, balance: $9997.73)
2025-10-30 08:24:11,189 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8443/9953
2025-10-30 08:24:11,196 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111033.91
2025-10-30 08:24:11,196 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111033.91 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,196 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:11,198 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:11,199 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.02, Commission=$0.00, Net=$2.02 (cash flow: -$1997.98, balance: $10002.02)
2025-10-30 08:24:11,200 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2232/9953
2025-10-30 08:24:11,202 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111515.24
2025-10-30 08:24:11,202 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111515.24 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:11,203 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:11,205 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:11,207 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:24:11,207 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.28, Commission=$0.00, Net=$0.28 (cash flow: -$1999.72, balance: $10000.28)
2025-10-30 08:24:11,208 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8862/9953
2025-10-30 08:24:11,213 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111281.46
2025-10-30 08:24:11,213 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111281.46 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:11,214 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:11,216 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180

Eval num_timesteps=3000, episode_reward=0.00 +/- 0.00
Episode length: 2166.20 +/- 1018.71
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 2.17e+03 |
|    mean_reward        | 0        |
| time/                 |          |
|    total_timesteps    | 3000     |
| train/                |          |
|    entropy_loss       | -1.09    |
|    explained_variance | -3.32    |
|    learning_rate      | 0.0007   |
|    n_updates          | 599      |
|    policy_loss        | 0.00615  |
|    value_loss         | 2.78e-05 |
------------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 3.39      |
|    ep_rew_mean     | -7.11e-06 |
| time/              |           |
|    fps             | 25        |
|    iterations      | 600       |
|    time_elapsed    | 116       |
|    total_timesteps | 3000      |
----------------------------------

2025-10-30 08:24:17,955 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:17,956 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.23, Commission=$0.00, Net=$-1.23 (cash flow: +$1998.77, -$0.00, balance: $9998.77)
2025-10-30 08:24:17,957 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6301/9953
2025-10-30 08:24:17,958 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108618.00
2025-10-30 08:24:17,959 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108618.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:17,959 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:17,961 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:24:17,962 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.17, Commission=$0.00, Net=$0.17 (cash flow: +$2000.17, -$0.00, balance: $10000.17)
2025-10-30 08:24:17,963 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6988/9953
2025-10-30 08:24:17,968 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108897.68
2025-10-30 08:24:17,968 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108897.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:17,969 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:17,971 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:17,972 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:17,973 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.39, Commission=$0.00, Net=$-1.39 (cash flow: -$2001.39, balance: $9998.61)
2025-10-30 08:24:17,974 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5922/9953
2025-10-30 08:24:17,976 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107311.32
2025-10-30 08:24:17,976 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107311.32 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:17,977 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:24:17,979 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:17,982 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:24:17,983 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.28, Commission=$0.00, Net=$1.28 (cash flow: +$2001.28, -$0.00, balance: $10001.28)
2025-10-30 08:24:17,984 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5243/9953
2025-10-30 08:24:17,987 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108268.46
2025-10-30 08:24:17,987 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108268.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:17,988 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:17,990 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:17,990 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.66, Commission=$0.00, Net=$0.66 (cash flow: -$1999.34, balance: $10000.66)
2025-10-30 08:24:17,991 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9607/9953
2025-10-30 08:24:17,996 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111060.46
2025-10-30 08:24:17,996 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111060.46 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:17,997 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:17,999 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,000 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:18,001 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.53, Commission=$0.00, Net=$-1.53 (cash flow: +$1998.47, -$0.00, balance: $9998.47)
2025-10-30 08:24:18,002 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 959/9953
2025-10-30 08:24:18,004 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113110.31
2025-10-30 08:24:18,004 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113110.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,004 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:24:18,008 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,011 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 08:24:18,011 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.82, Commission=$0.00, Net=$-0.82 (cash flow: -$2000.82, balance: $9999.18)
2025-10-30 08:24:18,012 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1787/9953
2025-10-30 08:24:18,015 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112469.13
2025-10-30 08:24:18,016 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112469.13 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,016 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:18,018 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,022 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:24:18,022 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.08, Commission=$0.00, Net=$-1.08 (cash flow: +$1998.92, -$0.00, balance: $9998.92)
2025-10-30 08:24:18,023 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3717/9953
2025-10-30 08:24:18,026 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108000.00
2025-10-30 08:24:18,026 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,027 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:18,029 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:18,029 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 08:24:18,030 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 467/9953
2025-10-30 08:24:18,032 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109890.78
2025-10-30 08:24:18,032 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109890.78 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,033 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:18,035 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:18,035 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.08, Commission=$0.00, Net=$0.08 (cash flow: -$1999.92, balance: $10000.08)
2025-10-30 08:24:18,037 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8337/9953
2025-10-30 08:24:18,041 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111417.99
2025-10-30 08:24:18,042 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111417.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,042 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:18,045 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,047 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:18,048 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.61, Commission=$0.00, Net=$0.61 (cash flow: +$2000.61, -$0.00, balance: $10000.61)
2025-10-30 08:24:18,048 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7093/9953
2025-10-30 08:24:18,052 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109390.38
2025-10-30 08:24:18,052 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109390.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,053 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:18,054 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:24:18,055 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: -$2000.73, balance: $9999.27)
2025-10-30 08:24:18,055 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 336/9953
2025-10-30 08:24:18,057 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109065.00
2025-10-30 08:24:18,057 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109065.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,057 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:24:18,058 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:24:18,058 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.77, Commission=$0.00, Net=$-0.77 (cash flow: +$1999.23, -$0.00, balance: $9999.23)
2025-10-30 08:24:18,059 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3156/9953
2025-10-30 08:24:18,062 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108150.05
2025-10-30 08:24:18,063 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108150.05 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,063 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:18,064 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,065 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:18,066 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.95, Commission=$0.00, Net=$0.95 (cash flow: +$2000.95, -$0.00, balance: $10000.95)
2025-10-30 08:24:18,066 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4488/9953
2025-10-30 08:24:18,067 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108340.59
2025-10-30 08:24:18,068 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108340.59 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,068 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:18,069 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,072 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:18,072 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.07, Commission=$0.00, Net=$2.07 (cash flow: -$1997.93, balance: $10002.07)
2025-10-30 08:24:18,073 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8009/9953
2025-10-30 08:24:18,074 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110273.16
2025-10-30 08:24:18,075 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110273.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,075 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:18,076 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:24:18,076 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: -$2000.06, balance: $9999.94)
2025-10-30 08:24:18,077 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1006/9953
2025-10-30 08:24:18,078 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113132.22
2025-10-30 08:24:18,078 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113132.22 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,078 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:24:18,079 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,083 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 08:24:18,083 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.83, Commission=$0.00, Net=$1.83 (cash flow: -$1998.17, balance: $10001.83)
2025-10-30 08:24:18,084 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8657/9953
2025-10-30 08:24:18,091 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111048.00
2025-10-30 08:24:18,091 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111048.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,092 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:18,094 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,095 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:18,096 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.24, Commission=$0.00, Net=$2.24 (cash flow: +$2002.24, -$0.00, balance: $10002.24)
2025-10-30 08:24:18,096 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9713/9953
2025-10-30 08:24:18,099 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111095.25
2025-10-30 08:24:18,099 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111095.25 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,100 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:18,103 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:18,103 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.55, Commission=$0.00, Net=$0.55 (cash flow: -$1999.45, balance: $10000.55)
2025-10-30 08:24:18,104 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5731/9953
2025-10-30 08:24:18,107 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107641.00
2025-10-30 08:24:18,107 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107641.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,108 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:24:18,110 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,113 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 08:24:18,114 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.13, Commission=$0.00, Net=$-0.13 (cash flow: -$2000.13, balance: $9999.87)
2025-10-30 08:24:18,115 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6895/9953
2025-10-30 08:24:18,117 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109197.29
2025-10-30 08:24:18,117 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109197.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,117 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:18,119 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:24:18,119 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.59, Commission=$0.00, Net=$0.59 (cash flow: -$1999.41, balance: $10000.59)
2025-10-30 08:24:18,120 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6942/9953
2025-10-30 08:24:18,123 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108899.96
2025-10-30 08:24:18,124 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108899.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,124 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:18,126 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:24:18,126 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.13, Commission=$0.00, Net=$-0.13 (cash flow: +$1999.87, -$0.00, balance: $9999.87)
2025-10-30 08:24:18,127 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8746/9953
2025-10-30 08:24:18,133 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112100.00
2025-10-30 08:24:18,133 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112100.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:18,133 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:18,135 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:18,136 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:24:18,136 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.28, Commission=$0.00, Net=$-2.28 (cash flow: +$1997.72, -$0.00, balance: $9997.72)
2025-10-30 08:24:18,137 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8282/9953
2025-10-30 08:24:18,138 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111233.55
2025-10-30 08:24:18,138 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111233.55 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:18,138 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:18,142 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180

Eval num_timesteps=3500, episode_reward=-0.00 +/- 0.00
Episode length: 586.20 +/- 783.67
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 586       |
|    mean_reward        | -7.04e-05 |
| time/                 |           |
|    total_timesteps    | 3500      |
| train/                |           |
|    entropy_loss       | -1.08     |
|    explained_variance | -7.73     |
|    learning_rate      | 0.0007    |
|    n_updates          | 699       |
|    policy_loss        | -0.0169   |
|    value_loss         | 0.000491  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.49     |
|    ep_rew_mean     | 6.1e-06  |
| time/              |          |
|    fps             | 29       |
|    iterations      | 700      |
|    time_elapsed    | 119      |
|    total_timesteps | 3500     |
---------------------------------

2025-10-30 08:24:20,729 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:24:20,729 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.30, Commission=$0.00, Net=$0.30 (cash flow: -$1999.70, balance: $10000.30)
2025-10-30 08:24:20,730 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4793/9953
2025-10-30 08:24:20,733 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108200.00
2025-10-30 08:24:20,734 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108200.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,734 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:20,737 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,739 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:20,740 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.59, Commission=$0.00, Net=$1.59 (cash flow: -$1998.41, balance: $10001.59)
2025-10-30 08:24:20,740 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9481/9953
2025-10-30 08:24:20,742 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110861.99
2025-10-30 08:24:20,743 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110861.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,743 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:20,746 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:20,746 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.36, Commission=$0.00, Net=$-0.36 (cash flow: +$1999.64, -$0.00, balance: $9999.64)
2025-10-30 08:24:20,747 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2158/9953
2025-10-30 08:24:20,749 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112140.43
2025-10-30 08:24:20,749 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112140.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,749 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:20,751 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,755 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:24:20,755 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.04, Commission=$0.00, Net=$0.04 (cash flow: -$1999.96, balance: $10000.04)
2025-10-30 08:24:20,756 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4046/9953
2025-10-30 08:24:20,758 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108000.00
2025-10-30 08:24:20,758 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,758 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:20,760 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,761 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:20,761 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.48, Commission=$0.00, Net=$0.48 (cash flow: -$1999.52, balance: $10000.48)
2025-10-30 08:24:20,762 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9832/9953
2025-10-30 08:24:20,764 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111435.02
2025-10-30 08:24:20,764 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111435.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,765 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:24:20,768 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,770 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:24:20,771 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: +$1999.79, -$0.00, balance: $9999.79)
2025-10-30 08:24:20,771 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 486/9953
2025-10-30 08:24:20,773 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109913.17
2025-10-30 08:24:20,773 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109913.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,773 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:20,775 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,778 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:24:20,778 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.48, Commission=$0.00, Net=$0.48 (cash flow: +$2000.48, -$0.00, balance: $10000.48)
2025-10-30 08:24:20,779 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1182/9953
2025-10-30 08:24:20,780 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113241.01
2025-10-30 08:24:20,780 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113241.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,781 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:24:20,783 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,784 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0177, signal=-1.0
2025-10-30 08:24:20,785 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.14, Commission=$0.00, Net=$-0.14 (cash flow: +$1999.86, -$0.00, balance: $9999.86)
2025-10-30 08:24:20,785 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3782/9953
2025-10-30 08:24:20,788 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108292.42
2025-10-30 08:24:20,789 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108292.42 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,789 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:20,791 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,792 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:20,792 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.14, Commission=$0.00, Net=$-2.14 (cash flow: +$1997.86, -$0.00, balance: $9997.86)
2025-10-30 08:24:20,793 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9538/9953
2025-10-30 08:24:20,798 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110697.96
2025-10-30 08:24:20,799 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110697.96 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,799 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:24:20,800 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,802 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 08:24:20,802 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: +$2000.16, -$0.00, balance: $10000.16)
2025-10-30 08:24:20,802 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8878/9953
2025-10-30 08:24:20,804 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111302.77
2025-10-30 08:24:20,804 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111302.77 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,804 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:20,806 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:20,806 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.28, Commission=$0.00, Net=$0.28 (cash flow: +$2000.28, -$0.00, balance: $10000.28)
2025-10-30 08:24:20,807 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9336/9953
2025-10-30 08:24:20,810 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110352.67
2025-10-30 08:24:20,810 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110352.67 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,811 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:24:20,812 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0181
2025-10-30 08:24:20,812 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.62, Commission=$0.00, Net=$0.62 (cash flow: +$2000.62, -$0.00, balance: $10000.62)
2025-10-30 08:24:20,813 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3267/9953
2025-10-30 08:24:20,815 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108268.00
2025-10-30 08:24:20,816 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108268.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,816 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:20,818 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,823 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:20,824 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.37, Commission=$0.00, Net=$-0.37 (cash flow: +$1999.63, -$0.00, balance: $9999.63)
2025-10-30 08:24:20,825 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 380/9953
2025-10-30 08:24:20,831 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109918.85
2025-10-30 08:24:20,831 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109918.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,832 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:20,833 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,835 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:24:20,835 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.42, Commission=$0.00, Net=$-1.42 (cash flow: -$2001.42, balance: $9998.58)
2025-10-30 08:24:20,836 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9134/9953
2025-10-30 08:24:20,837 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110021.60
2025-10-30 08:24:20,837 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110021.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,838 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:20,841 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,843 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:20,843 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.35, Commission=$0.00, Net=$-1.35 (cash flow: -$2001.35, balance: $9998.65)
2025-10-30 08:24:20,843 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1396/9953
2025-10-30 08:24:20,850 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113127.69
2025-10-30 08:24:20,851 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $113127.69 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,851 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:24:20,854 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,856 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0177
2025-10-30 08:24:20,856 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.77, Commission=$0.00, Net=$1.77 (cash flow: +$2001.77, -$0.00, balance: $10001.77)
2025-10-30 08:24:20,857 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4536/9953
2025-10-30 08:24:20,859 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108108.59
2025-10-30 08:24:20,859 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108108.59 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,859 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:20,861 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,864 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:24:20,864 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: +$2000.85, -$0.00, balance: $10000.85)
2025-10-30 08:24:20,865 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5750/9953
2025-10-30 08:24:20,867 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107652.00
2025-10-30 08:24:20,867 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107652.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,867 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:24:20,868 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,870 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:24:20,870 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.02, Commission=$0.00, Net=$1.02 (cash flow: +$2001.02, -$0.00, balance: $10001.02)
2025-10-30 08:24:20,871 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9888/9953
2025-10-30 08:24:20,874 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111669.29
2025-10-30 08:24:20,875 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111669.29 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,875 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:24:20,877 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 08:24:20,877 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 08:24:20,878 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8029/9953
2025-10-30 08:24:20,880 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110577.84
2025-10-30 08:24:20,880 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110577.84 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,880 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:20,881 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,884 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:24:20,885 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.14, Commission=$0.00, Net=$0.14 (cash flow: -$1999.86, balance: $10000.14)
2025-10-30 08:24:20,886 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9164/9953
2025-10-30 08:24:20,887 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109993.61
2025-10-30 08:24:20,887 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109993.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,887 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:20,889 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,894 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:24:20,894 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.32, Commission=$0.00, Net=$-1.32 (cash flow: +$1998.68, -$0.00, balance: $9998.68)
2025-10-30 08:24:20,895 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4925/9953
2025-10-30 08:24:20,896 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107983.19
2025-10-30 08:24:20,896 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107983.19 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:20,897 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:20,898 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,900 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:20,901 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.63, Commission=$0.00, Net=$0.63 (cash flow: -$1999.37, balance: $10000.63)
2025-10-30 08:24:20,901 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7084/9953
2025-10-30 08:24:20,906 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109242.25
2025-10-30 08:24:20,907 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109242.25 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:20,907 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:24:20,909 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:20,910 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:24:20,910 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.24, Commission=$0.00, Net=$0.24 (cash flow: +$2000.24, -$0.00, balance: $10000.24)

Eval num_timesteps=4000, episode_reward=-0.00 +/- 0.00
Episode length: 3.00 +/- 0.89
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 3         |
|    mean_reward        | -8e-07    |
| time/                 |           |
|    total_timesteps    | 4000      |
| train/                |           |
|    entropy_loss       | -1.08     |
|    explained_variance | -6.38e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 799       |
|    policy_loss        | 0.0916    |
|    value_loss         | 0.00607   |
-------------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 3.54      |
|    ep_rew_mean     | -9.04e-06 |
| time/              |           |
|    fps             | 33        |
|    iterations      | 800       |
|    time_elapsed    | 120       |
|    total_timesteps | 4000      |
----------------------------------

2025-10-30 08:24:21,679 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110784.27
2025-10-30 08:24:21,680 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110784.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,680 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:21,681 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,682 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:24:21,683 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.14, Commission=$0.00, Net=$-0.14 (cash flow: -$2000.14, balance: $9999.86)
2025-10-30 08:24:21,683 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9080/9953
2025-10-30 08:24:21,686 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109841.13
2025-10-30 08:24:21,687 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109841.13 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,687 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:21,689 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,690 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:21,691 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.42, Commission=$0.00, Net=$-1.42 (cash flow: -$2001.42, balance: $9998.58)
2025-10-30 08:24:21,691 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3370/9953
2025-10-30 08:24:21,693 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108458.21
2025-10-30 08:24:21,693 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108458.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,693 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:21,697 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,698 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:21,699 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.02, Commission=$0.00, Net=$1.02 (cash flow: -$1998.98, balance: $10001.02)
2025-10-30 08:24:21,700 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3279/9953
2025-10-30 08:24:21,701 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108201.99
2025-10-30 08:24:21,701 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108201.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,702 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:21,705 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,706 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:21,706 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: -$1999.80, balance: $10000.20)
2025-10-30 08:24:21,707 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5009/9953
2025-10-30 08:24:21,712 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108680.25
2025-10-30 08:24:21,712 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108680.25 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,713 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:21,715 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,723 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:21,724 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.86, Commission=$0.00, Net=$-2.86 (cash flow: -$2002.86, balance: $9997.14)
2025-10-30 08:24:21,725 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6610/9953
2025-10-30 08:24:21,728 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109918.68
2025-10-30 08:24:21,729 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109918.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,729 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:21,731 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:21,732 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.44, Commission=$0.00, Net=$0.44 (cash flow: -$1999.56, balance: $10000.44)
2025-10-30 08:24:21,732 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9733/9953
2025-10-30 08:24:21,737 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111353.48
2025-10-30 08:24:21,737 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111353.48 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,738 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:21,740 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,743 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:24:21,743 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.03, Commission=$0.00, Net=$-0.03 (cash flow: -$2000.03, balance: $9999.97)
2025-10-30 08:24:21,744 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8422/9953
2025-10-30 08:24:21,746 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110848.50
2025-10-30 08:24:21,746 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110848.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,746 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:21,751 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,754 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:24:21,754 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.53, Commission=$0.00, Net=$-1.53 (cash flow: -$2001.53, balance: $9998.47)
2025-10-30 08:24:21,755 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4966/9953
2025-10-30 08:24:21,766 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108628.22
2025-10-30 08:24:21,766 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108628.22 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,766 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:21,768 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:21,768 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: -$2000.73, balance: $9999.27)
2025-10-30 08:24:21,769 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6356/9953
2025-10-30 08:24:21,772 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108802.38
2025-10-30 08:24:21,772 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108802.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:21,772 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:21,775 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,778 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:24:21,778 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.74, Commission=$0.00, Net=$-0.74 (cash flow: +$1999.26, -$0.00, balance: $9999.26)
2025-10-30 08:24:21,779 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4294/9953
2025-10-30 08:24:21,781 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107988.16
2025-10-30 08:24:21,781 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107988.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,782 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:21,783 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,786 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:21,786 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.69, Commission=$0.00, Net=$2.69 (cash flow: -$1997.31, balance: $10002.69)
2025-10-30 08:24:21,787 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1789/9953
2025-10-30 08:24:21,790 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112430.43
2025-10-30 08:24:21,791 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112430.43 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,791 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:21,793 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,794 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:21,795 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.38, Commission=$0.00, Net=$-0.38 (cash flow: -$2000.38, balance: $9999.62)
2025-10-30 08:24:21,795 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5131/9953
2025-10-30 08:24:21,801 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107978.78
2025-10-30 08:24:21,801 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107978.78 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,801 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:21,803 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:21,803 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.34, Commission=$0.00, Net=$0.34 (cash flow: -$1999.66, balance: $10000.34)
2025-10-30 08:24:21,804 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6258/9953
2025-10-30 08:24:21,806 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108388.01
2025-10-30 08:24:21,806 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108388.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,806 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:21,810 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,812 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:21,812 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.33, Commission=$0.00, Net=$-0.33 (cash flow: -$2000.33, balance: $9999.67)
2025-10-30 08:24:21,813 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2091/9953
2025-10-30 08:24:21,814 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112115.46
2025-10-30 08:24:21,814 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112115.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,814 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:21,817 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,819 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:24:21,819 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.03, Commission=$0.00, Net=$0.03 (cash flow: -$1999.97, balance: $10000.03)
2025-10-30 08:24:21,820 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3850/9953
2025-10-30 08:24:21,826 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107627.56
2025-10-30 08:24:21,827 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107627.56 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,827 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:24:21,829 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:24:21,830 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.17, Commission=$0.00, Net=$-0.17 (cash flow: -$2000.17, balance: $9999.83)
2025-10-30 08:24:21,831 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1490/9953
2025-10-30 08:24:21,834 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112897.97
2025-10-30 08:24:21,835 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112897.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,835 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:24:21,839 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,844 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 08:24:21,845 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.04, Commission=$0.00, Net=$-1.04 (cash flow: -$2001.04, balance: $9998.96)
2025-10-30 08:24:21,846 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8706/9953
2025-10-30 08:24:21,847 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111717.78
2025-10-30 08:24:21,848 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111717.78 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:21,848 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:24:21,850 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,851 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:24:21,851 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.58, Commission=$0.00, Net=$0.58 (cash flow: +$2000.58, -$0.00, balance: $10000.58)
2025-10-30 08:24:21,852 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2284/9953
2025-10-30 08:24:21,856 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112081.73
2025-10-30 08:24:21,856 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112081.73 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:21,856 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:21,859 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:24:21,859 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.67, Commission=$0.00, Net=$-1.67 (cash flow: +$1998.33, -$0.00, balance: $9998.33)
2025-10-30 08:24:21,860 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5603/9953
2025-10-30 08:24:21,861 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108024.00
2025-10-30 08:24:21,861 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108024.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:21,862 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:21,864 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,866 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:21,867 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.07, Commission=$0.00, Net=$3.07 (cash flow: +$2003.07, -$0.00, balance: $10003.07)
2025-10-30 08:24:21,867 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5003/9953
2025-10-30 08:24:21,872 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108939.37
2025-10-30 08:24:21,872 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108939.37 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:21,873 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:21,875 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:24:21,875 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.64, Commission=$0.00, Net=$0.64 (cash flow: +$2000.64, -$0.00, balance: $10000.64)
2025-10-30 08:24:21,876 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7015/9953
2025-10-30 08:24:21,877 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109071.66
2025-10-30 08:24:21,877 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109071.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,878 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:21,879 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:21,888 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:24:21,888 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.06, Commission=$0.00, Net=$-0.06 (cash flow: -$2000.06, balance: $9999.94)
2025-10-30 08:24:21,890 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5883/9953
2025-10-30 08:24:21,893 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=106807.29
2025-10-30 08:24:21,893 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $106807.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:21,894 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:24:21,895 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187

Eval num_timesteps=4500, episode_reward=0.00 +/- 0.00
Episode length: 9.20 +/- 5.91
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 9.2      |
|    mean_reward        | 7.42e-05 |
| time/                 |          |
|    total_timesteps    | 4500     |
| train/                |          |
|    entropy_loss       | -1.08    |
|    explained_variance | 0.685    |
|    learning_rate      | 0.0007   |
|    n_updates          | 899      |
|    policy_loss        | -0.0197  |
|    value_loss         | 0.000321 |
------------------------------------
New best mean reward!
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.71     |
|    ep_rew_mean     | 1.24e-05 |
| time/              |          |
|    fps             | 37       |
|    iterations      | 900      |
|    time_elapsed    | 121      |
|    total_timesteps | 4500     |
---------------------------------

2025-10-30 08:24:22,827 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110292.94
2025-10-30 08:24:22,827 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110292.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,827 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:22,829 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,830 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:24:22,830 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-4.59, Commission=$0.00, Net=$-4.59 (cash flow: -$2004.59, balance: $9995.41)
2025-10-30 08:24:22,831 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2996/9953
2025-10-30 08:24:22,834 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108417.64
2025-10-30 08:24:22,834 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108417.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,835 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:22,836 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,837 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:22,837 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.49, Commission=$0.00, Net=$0.49 (cash flow: -$1999.51, balance: $10000.49)
2025-10-30 08:24:22,838 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8690/9953
2025-10-30 08:24:22,843 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110974.25
2025-10-30 08:24:22,843 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110974.25 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,844 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:22,845 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:22,845 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.46, Commission=$0.00, Net=$-0.46 (cash flow: -$2000.46, balance: $9999.54)
2025-10-30 08:24:22,846 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9396/9953
2025-10-30 08:24:22,847 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110612.82
2025-10-30 08:24:22,847 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110612.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,848 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:22,849 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,851 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:24:22,851 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.12, Commission=$0.00, Net=$-0.12 (cash flow: -$2000.12, balance: $9999.88)
2025-10-30 08:24:22,852 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9634/9953
2025-10-30 08:24:22,855 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110906.14
2025-10-30 08:24:22,856 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110906.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,856 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:22,858 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:22,858 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.86, Commission=$0.00, Net=$1.86 (cash flow: -$1998.14, balance: $10001.86)
2025-10-30 08:24:22,859 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4061/9953
2025-10-30 08:24:22,860 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107920.37
2025-10-30 08:24:22,861 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107920.37 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,861 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:22,862 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,864 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:24:22,864 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: +$2000.93, -$0.00, balance: $10000.93)
2025-10-30 08:24:22,865 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8393/9953
2025-10-30 08:24:22,869 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111180.14
2025-10-30 08:24:22,870 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111180.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,870 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:22,873 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:22,874 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.34, Commission=$0.00, Net=$0.34 (cash flow: -$1999.66, balance: $10000.34)
2025-10-30 08:24:22,875 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1730/9953
2025-10-30 08:24:22,880 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112227.02
2025-10-30 08:24:22,880 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112227.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,880 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:22,882 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,884 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:24:22,884 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.16, Commission=$0.00, Net=$-0.16 (cash flow: +$1999.84, -$0.00, balance: $9999.84)
2025-10-30 08:24:22,884 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2102/9953
2025-10-30 08:24:22,886 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111912.79
2025-10-30 08:24:22,886 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111912.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,886 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:22,889 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,891 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:24:22,891 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.29, Commission=$0.00, Net=$-2.29 (cash flow: -$2002.29, balance: $9997.71)
2025-10-30 08:24:22,892 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5927/9953
2025-10-30 08:24:22,895 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107432.01
2025-10-30 08:24:22,895 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107432.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,896 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:24:22,899 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,900 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:24:22,900 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.45, Commission=$0.00, Net=$-2.45 (cash flow: +$1997.55, -$0.00, balance: $9997.55)
2025-10-30 08:24:22,901 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1551/9953
2025-10-30 08:24:22,902 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112210.00
2025-10-30 08:24:22,902 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112210.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,903 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:22,904 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,905 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:22,905 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: -$1999.84, balance: $10000.16)
2025-10-30 08:24:22,906 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5060/9953
2025-10-30 08:24:22,909 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108990.70
2025-10-30 08:24:22,910 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108990.70 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,910 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:22,912 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,914 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:22,914 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.59, Commission=$0.00, Net=$1.59 (cash flow: -$1998.41, balance: $10001.59)
2025-10-30 08:24:22,915 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1798/9953
2025-10-30 08:24:22,916 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112543.11
2025-10-30 08:24:22,916 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112543.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,916 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:22,919 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:24:22,919 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: +$1999.89, -$0.00, balance: $9999.89)
2025-10-30 08:24:22,920 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 15/9953
2025-10-30 08:24:22,921 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108421.46
2025-10-30 08:24:22,921 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108421.46 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,921 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:22,923 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:22,924 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: -$2000.35, balance: $9999.65)
2025-10-30 08:24:22,924 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2173/9953
2025-10-30 08:24:22,925 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112125.15
2025-10-30 08:24:22,926 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112125.15 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,926 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:22,927 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,930 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:22,930 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.41, Commission=$0.00, Net=$3.41 (cash flow: -$1996.59, balance: $10003.41)
2025-10-30 08:24:22,931 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2324/9953
2025-10-30 08:24:22,933 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111836.00
2025-10-30 08:24:22,933 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111836.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,933 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:24:22,934 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,937 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0179
2025-10-30 08:24:22,938 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.83, Commission=$0.00, Net=$1.83 (cash flow: +$2001.83, -$0.00, balance: $10001.83)
2025-10-30 08:24:22,938 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1087/9953
2025-10-30 08:24:22,940 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113459.17
2025-10-30 08:24:22,941 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113459.17 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,941 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 08:24:22,942 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,943 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0176
2025-10-30 08:24:22,943 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.18, Commission=$0.00, Net=$-0.18 (cash flow: +$1999.82, -$0.00, balance: $9999.82)
2025-10-30 08:24:22,944 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2282/9953
2025-10-30 08:24:22,945 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112106.07
2025-10-30 08:24:22,945 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112106.07 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,946 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:22,949 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0178
2025-10-30 08:24:22,949 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.77, Commission=$0.00, Net=$-0.77 (cash flow: +$1999.23, -$0.00, balance: $9999.23)
2025-10-30 08:24:22,950 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4657/9953
2025-10-30 08:24:22,951 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108731.98
2025-10-30 08:24:22,951 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108731.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,951 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:22,953 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:22,953 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.75, Commission=$0.00, Net=$0.75 (cash flow: -$1999.25, balance: $10000.75)
2025-10-30 08:24:22,953 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4878/9953
2025-10-30 08:24:22,954 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107949.44
2025-10-30 08:24:22,955 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107949.44 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,955 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:22,957 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:22,957 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.83, Commission=$0.00, Net=$0.83 (cash flow: -$1999.17, balance: $10000.83)
2025-10-30 08:24:22,958 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6377/9953
2025-10-30 08:24:22,960 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108802.71
2025-10-30 08:24:22,960 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108802.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,961 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:22,962 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,963 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 08:24:22,963 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.58, Commission=$0.00, Net=$0.58 (cash flow: +$2000.58, -$0.00, balance: $10000.58)
2025-10-30 08:24:22,963 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7954/9953
2025-10-30 08:24:22,966 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109980.55
2025-10-30 08:24:22,966 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109980.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:22,966 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:22,969 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:22,970 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:24:22,970 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.63, Commission=$0.00, Net=$1.63 (cash flow: +$2001.63, -$0.00, balance: $10001.63)
2025-10-30 08:24:22,971 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2955/9953
2025-10-30 08:24:22,973 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108242.92
2025-10-30 08:24:22,974 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108242.92 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:22,974 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:22,975 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:22,976 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.70, Commission=$0.00, Net=$0.70 (cash flow: -$1999.30, balance: $10000.70)

Eval num_timesteps=5000, episode_reward=-0.00 +/- 0.00
Episode length: 7.20 +/- 6.94
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 7.2       |
|    mean_reward        | -3.12e-05 |
| time/                 |           |
|    total_timesteps    | 5000      |
| train/                |           |
|    entropy_loss       | -1.07     |
|    explained_variance | -3.16e+04 |
|    learning_rate      | 0.0007    |
|    n_updates          | 999       |
|    policy_loss        | -0.015    |
|    value_loss         | 0.000308  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.55     |
|    ep_rew_mean     | -4.9e-06 |
| time/              |          |
|    fps             | 40       |
|    iterations      | 1000     |
|    time_elapsed    | 122      |
|    total_timesteps | 5000     |
---------------------------------

2025-10-30 08:24:23,992 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110953.15
2025-10-30 08:24:23,993 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110953.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:23,993 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:23,995 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:23,996 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.06, Commission=$0.00, Net=$1.06 (cash flow: +$2001.06, -$0.00, balance: $10001.06)
2025-10-30 08:24:23,996 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7004/9953
2025-10-30 08:24:23,998 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109070.69
2025-10-30 08:24:23,998 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109070.69 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:23,998 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:24:24,000 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:24:24,000 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.99, Commission=$0.00, Net=$0.99 (cash flow: +$2000.99, -$0.00, balance: $10000.99)
2025-10-30 08:24:24,001 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8195/9953
2025-10-30 08:24:24,004 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111277.33
2025-10-30 08:24:24,005 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111277.33 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,005 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:24,007 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,009 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:24,009 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.77, Commission=$0.00, Net=$-0.77 (cash flow: +$1999.23, -$0.00, balance: $9999.23)
2025-10-30 08:24:24,010 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3662/9953
2025-10-30 08:24:24,012 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108086.72
2025-10-30 08:24:24,013 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108086.72 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,013 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:24,017 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:24,017 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.17, Commission=$0.00, Net=$0.17 (cash flow: -$1999.83, balance: $10000.17)
2025-10-30 08:24:24,018 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4930/9953
2025-10-30 08:24:24,020 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108049.41
2025-10-30 08:24:24,021 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108049.41 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,021 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:24,023 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:24,023 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.51, Commission=$0.00, Net=$-0.51 (cash flow: -$2000.51, balance: $9999.49)
2025-10-30 08:24:24,024 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5202/9953
2025-10-30 08:24:24,026 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108326.19
2025-10-30 08:24:24,026 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108326.19 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,026 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:24,030 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:24,030 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.87, Commission=$0.00, Net=$1.87 (cash flow: +$2001.87, -$0.00, balance: $10001.87)
2025-10-30 08:24:24,031 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9244/9953
2025-10-30 08:24:24,034 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110129.69
2025-10-30 08:24:24,035 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110129.69 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,035 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:24,037 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,039 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:24,039 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.58, Commission=$0.00, Net=$0.58 (cash flow: -$1999.42, balance: $10000.58)
2025-10-30 08:24:24,040 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4303/9953
2025-10-30 08:24:24,044 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107836.48
2025-10-30 08:24:24,045 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107836.48 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,045 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:24,047 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,049 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:24,049 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.12, Commission=$0.00, Net=$-0.12 (cash flow: -$2000.12, balance: $9999.88)
2025-10-30 08:24:24,050 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8514/9953
2025-10-30 08:24:24,051 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111008.06
2025-10-30 08:24:24,051 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111008.06 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,052 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:24,053 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,056 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:24,057 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.58, Commission=$0.00, Net=$-1.58 (cash flow: -$2001.58, balance: $9998.42)
2025-10-30 08:24:24,057 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 193/9953
2025-10-30 08:24:24,060 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108630.85
2025-10-30 08:24:24,060 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108630.85 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,060 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:24,062 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,067 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:24,067 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.17, Commission=$0.00, Net=$2.17 (cash flow: -$1997.83, balance: $10002.17)
2025-10-30 08:24:24,068 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5944/9953
2025-10-30 08:24:24,073 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107352.95
2025-10-30 08:24:24,073 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107352.95 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,073 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:24:24,075 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,077 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:24:24,077 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.62, Commission=$0.00, Net=$-1.62 (cash flow: -$2001.62, balance: $9998.38)
2025-10-30 08:24:24,078 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6203/9953
2025-10-30 08:24:24,079 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108222.48
2025-10-30 08:24:24,080 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108222.48 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,080 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:24,082 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,085 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:24:24,085 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.94, Commission=$0.00, Net=$-0.94 (cash flow: +$1999.06, -$0.00, balance: $9999.06)
2025-10-30 08:24:24,086 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9581/9953
2025-10-30 08:24:24,089 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110994.40
2025-10-30 08:24:24,089 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $110994.40 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,089 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:24,092 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,094 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:24:24,094 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.49, Commission=$0.00, Net=$1.49 (cash flow: +$2001.49, -$0.00, balance: $10001.49)
2025-10-30 08:24:24,095 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7817/9953
2025-10-30 08:24:24,097 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109988.75
2025-10-30 08:24:24,097 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109988.75 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,097 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:24,099 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:24:24,100 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.79, Commission=$0.00, Net=$-0.79 (cash flow: +$1999.21, -$0.00, balance: $9999.21)
2025-10-30 08:24:24,100 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3484/9953
2025-10-30 08:24:24,102 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108205.52
2025-10-30 08:24:24,102 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108205.52 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,102 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:24,106 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,107 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:24,107 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.85, Commission=$0.00, Net=$-0.85 (cash flow: +$1999.15, -$0.00, balance: $9999.15)
2025-10-30 08:24:24,108 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2358/9953
2025-10-30 08:24:24,110 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111311.52
2025-10-30 08:24:24,110 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111311.52 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,111 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:24,112 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,117 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:24,117 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.45, Commission=$0.00, Net=$0.45 (cash flow: -$1999.55, balance: $10000.45)
2025-10-30 08:24:24,118 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2976/9953
2025-10-30 08:24:24,120 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108500.00
2025-10-30 08:24:24,120 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108500.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,120 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:24,122 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,126 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:24,127 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.00, Commission=$0.00, Net=$-0.00 (cash flow: -$2000.00, balance: $10000.00)
2025-10-30 08:24:24,127 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6226/9953
2025-10-30 08:24:24,131 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108200.00
2025-10-30 08:24:24,131 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108200.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,132 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:24,135 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,137 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:24,138 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.13, Commission=$0.00, Net=$-2.13 (cash flow: -$2002.13, balance: $9997.87)
2025-10-30 08:24:24,138 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2052/9953
2025-10-30 08:24:24,140 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111971.15
2025-10-30 08:24:24,140 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111971.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:24,141 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:24:24,142 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,145 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:24:24,146 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.16, Commission=$0.00, Net=$0.16 (cash flow: +$2000.16, -$0.00, balance: $10000.16)
2025-10-30 08:24:24,146 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6134/9953
2025-10-30 08:24:24,149 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108326.79
2025-10-30 08:24:24,149 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108326.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,149 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:24,151 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,155 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:24,155 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.19, Commission=$0.00, Net=$2.19 (cash flow: -$1997.81, balance: $10002.19)
2025-10-30 08:24:24,156 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1475/9953
2025-10-30 08:24:24,158 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112404.21
2025-10-30 08:24:24,159 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112404.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,159 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:24,161 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:24:24,161 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.07, Commission=$0.00, Net=$0.07 (cash flow: -$1999.93, balance: $10000.07)
2025-10-30 08:24:24,162 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 616/9953
2025-10-30 08:24:24,165 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111849.79
2025-10-30 08:24:24,165 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111849.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,165 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:24,169 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:24,172 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:24:24,173 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.27, Commission=$0.00, Net=$0.27 (cash flow: -$1999.73, balance: $10000.27)
2025-10-30 08:24:24,174 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1275/9953
2025-10-30 08:24:24,175 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113810.00
2025-10-30 08:24:24,175 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113810.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:24,176 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 08:24:24,179 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0176

Eval num_timesteps=5500, episode_reward=-0.00 +/- 0.00
Episode length: 1877.40 +/- 2411.98
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 1.88e+03 |
|    mean_reward        | -0.002   |
| time/                 |          |
|    total_timesteps    | 5500     |
| train/                |          |
|    entropy_loss       | -0.999   |
|    explained_variance | 0.158    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1099     |
|    policy_loss        | -0.00288 |
|    value_loss         | 9.31e-06 |
------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.62     |
|    ep_rew_mean     | 1.65e-05 |
| time/              |          |
|    fps             | 42       |
|    iterations      | 1100     |
|    time_elapsed    | 129      |
|    total_timesteps | 5500     |
---------------------------------

2025-10-30 08:24:30,518 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:24:30,518 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.68, Commission=$0.00, Net=$1.68 (cash flow: -$1998.32, balance: $10001.68)
2025-10-30 08:24:30,519 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3767/9953
2025-10-30 08:24:30,521 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108090.07
2025-10-30 08:24:30,521 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108090.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,521 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:30,523 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,524 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:30,524 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.64, Commission=$0.00, Net=$-0.64 (cash flow: -$2000.64, balance: $9999.36)
2025-10-30 08:24:30,525 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9057/9953
2025-10-30 08:24:30,527 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110036.86
2025-10-30 08:24:30,527 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110036.86 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:30,528 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:30,529 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,530 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:24:30,530 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.07, Commission=$0.00, Net=$1.07 (cash flow: +$2001.07, -$0.00, balance: $10001.07)
2025-10-30 08:24:30,531 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5902/9953
2025-10-30 08:24:30,532 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=106942.72
2025-10-30 08:24:30,532 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $106942.72 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,533 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:24:30,534 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,537 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:24:30,537 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.08, Commission=$0.00, Net=$-1.08 (cash flow: -$2001.08, balance: $9998.92)
2025-10-30 08:24:30,538 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1175/9953
2025-10-30 08:24:30,539 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113366.00
2025-10-30 08:24:30,539 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113366.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:30,539 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 08:24:30,541 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,545 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0176, signal=-1.0
2025-10-30 08:24:30,545 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.03, Commission=$0.00, Net=$-2.03 (cash flow: +$1997.97, -$0.00, balance: $9997.97)
2025-10-30 08:24:30,545 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8670/9953
2025-10-30 08:24:30,547 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111278.46
2025-10-30 08:24:30,547 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111278.46 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:30,547 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:30,548 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,549 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:30,550 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.30, Commission=$0.00, Net=$-2.30 (cash flow: +$1997.70, -$0.00, balance: $9997.70)
2025-10-30 08:24:30,550 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9040/9953
2025-10-30 08:24:30,551 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110099.99
2025-10-30 08:24:30,552 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110099.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,552 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:30,555 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,556 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:30,556 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.91, Commission=$0.00, Net=$0.91 (cash flow: -$1999.09, balance: $10000.91)
2025-10-30 08:24:30,557 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2528/9953
2025-10-30 08:24:30,559 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110367.13
2025-10-30 08:24:30,559 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110367.13 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,559 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:30,561 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,573 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:24:30,574 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.34, Commission=$0.00, Net=$-1.34 (cash flow: -$2001.34, balance: $9998.66)
2025-10-30 08:24:30,574 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9290/9953
2025-10-30 08:24:30,576 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109919.48
2025-10-30 08:24:30,576 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109919.48 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,576 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:30,579 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,581 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:30,582 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-5.01, Commission=$0.00, Net=$-5.01 (cash flow: -$2005.01, balance: $9994.99)
2025-10-30 08:24:30,582 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 584/9953
2025-10-30 08:24:30,583 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111227.36
2025-10-30 08:24:30,583 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111227.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,584 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:30,587 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:30,587 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.49, Commission=$0.00, Net=$0.49 (cash flow: -$1999.51, balance: $10000.49)
2025-10-30 08:24:30,587 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2717/9953
2025-10-30 08:24:30,589 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108723.98
2025-10-30 08:24:30,589 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108723.98 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:30,590 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:30,591 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:24:30,591 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.63, Commission=$0.00, Net=$0.63 (cash flow: +$2000.63, -$0.00, balance: $10000.63)
2025-10-30 08:24:30,592 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1266/9953
2025-10-30 08:24:30,594 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113778.36
2025-10-30 08:24:30,594 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113778.36 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,594 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 08:24:30,597 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,599 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0176, signal=1.0
2025-10-30 08:24:30,599 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.46, Commission=$0.00, Net=$1.46 (cash flow: -$1998.54, balance: $10001.46)
2025-10-30 08:24:30,599 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2568/9953
2025-10-30 08:24:30,601 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110906.93
2025-10-30 08:24:30,601 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110906.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,601 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:30,604 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,609 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:30,610 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.61, Commission=$0.00, Net=$0.61 (cash flow: -$1999.39, balance: $10000.61)
2025-10-30 08:24:30,610 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8680/9953
2025-10-30 08:24:30,611 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111030.00
2025-10-30 08:24:30,611 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111030.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:30,612 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:30,613 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,614 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:30,614 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.45, Commission=$0.00, Net=$-2.45 (cash flow: +$1997.55, -$0.00, balance: $9997.55)
2025-10-30 08:24:30,615 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5920/9953
2025-10-30 08:24:30,618 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107188.80
2025-10-30 08:24:30,618 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107188.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,618 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:24:30,620 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,624 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0187, signal=1.0
2025-10-30 08:24:30,625 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-5.36, Commission=$0.00, Net=$-5.36 (cash flow: -$2005.36, balance: $9994.64)
2025-10-30 08:24:30,625 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3476/9953
2025-10-30 08:24:30,626 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107969.06
2025-10-30 08:24:30,627 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107969.06 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,627 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:30,628 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,630 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:30,630 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.08, Commission=$0.00, Net=$-2.08 (cash flow: -$2002.08, balance: $9997.92)
2025-10-30 08:24:30,631 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7713/9953
2025-10-30 08:24:30,634 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110431.47
2025-10-30 08:24:30,634 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110431.47 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,635 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:30,636 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,640 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:24:30,641 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.60, Commission=$0.00, Net=$-1.60 (cash flow: -$2001.60, balance: $9998.40)
2025-10-30 08:24:30,641 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7045/9953
2025-10-30 08:24:30,643 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108809.03
2025-10-30 08:24:30,643 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108809.03 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:30,643 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:30,644 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,645 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0184, signal=-1.0
2025-10-30 08:24:30,645 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.26, Commission=$0.00, Net=$0.26 (cash flow: +$2000.26, -$0.00, balance: $10000.26)
2025-10-30 08:24:30,646 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 850/9953
2025-10-30 08:24:30,647 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112326.72
2025-10-30 08:24:30,647 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112326.72 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,647 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:30,651 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,652 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:30,652 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.46, Commission=$0.00, Net=$-0.46 (cash flow: -$2000.46, balance: $9999.54)
2025-10-30 08:24:30,653 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3257/9953
2025-10-30 08:24:30,655 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108252.82
2025-10-30 08:24:30,655 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108252.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,656 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:30,657 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,660 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:30,660 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.17, Commission=$0.00, Net=$-0.17 (cash flow: -$2000.17, balance: $9999.83)
2025-10-30 08:24:30,660 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2093/9953
2025-10-30 08:24:30,662 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112038.14
2025-10-30 08:24:30,662 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112038.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,663 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:30,664 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,665 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:24:30,666 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.24, Commission=$0.00, Net=$1.24 (cash flow: -$1998.76, balance: $10001.24)
2025-10-30 08:24:30,666 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2354/9953
2025-10-30 08:24:30,670 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111451.16
2025-10-30 08:24:30,670 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111451.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,670 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:30,672 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:30,674 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:24:30,674 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.51, Commission=$0.00, Net=$2.51 (cash flow: -$1997.49, balance: $10002.51)
2025-10-30 08:24:30,675 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2821/9953
2025-10-30 08:24:30,677 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109254.90
2025-10-30 08:24:30,677 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109254.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:30,678 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:30,679 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

Eval num_timesteps=6000, episode_reward=-0.00 +/- 0.00
Episode length: 5132.20 +/- 2205.14
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 5.13e+03  |
|    mean_reward        | -0.00494  |
| time/                 |           |
|    total_timesteps    | 6000      |
| train/                |           |
|    entropy_loss       | -0.882    |
|    explained_variance | -1.19e+04 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1199      |
|    policy_loss        | -0.0168   |
|    value_loss         | 0.000315  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 4.04     |
|    ep_rew_mean     | 2.1e-05  |
| time/              |          |
|    fps             | 40       |
|    iterations      | 1200     |
|    time_elapsed    | 146      |
|    total_timesteps | 6000     |
---------------------------------

2025-10-30 08:24:48,206 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,208 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:24:48,208 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.44, Commission=$0.00, Net=$1.44 (cash flow: +$2001.44, -$0.00, balance: $10001.44)
2025-10-30 08:24:48,209 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 992/9953
2025-10-30 08:24:48,210 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113225.15
2025-10-30 08:24:48,211 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113225.15 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,211 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:24:48,213 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,218 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 08:24:48,218 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.15, Commission=$0.00, Net=$0.15 (cash flow: -$1999.85, balance: $10000.15)
2025-10-30 08:24:48,219 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6335/9953
2025-10-30 08:24:48,221 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108553.80
2025-10-30 08:24:48,222 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108553.80 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,222 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:48,226 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,227 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:48,228 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.14, Commission=$0.00, Net=$-0.14 (cash flow: -$2000.14, balance: $9999.86)
2025-10-30 08:24:48,228 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3813/9953
2025-10-30 08:24:48,230 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107973.49
2025-10-30 08:24:48,230 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107973.49 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,231 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:48,233 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:48,233 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.23, Commission=$0.00, Net=$-0.23 (cash flow: -$2000.23, balance: $9999.77)
2025-10-30 08:24:48,234 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5951/9953
2025-10-30 08:24:48,238 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107220.96
2025-10-30 08:24:48,239 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107220.96 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,239 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:24:48,241 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,244 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:24:48,245 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$4.77, Commission=$0.00, Net=$4.77 (cash flow: -$1995.23, balance: $10004.77)
2025-10-30 08:24:48,246 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5986/9953
2025-10-30 08:24:48,247 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107254.64
2025-10-30 08:24:48,247 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107254.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,248 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:24:48,252 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,253 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 08:24:48,254 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.13, Commission=$0.00, Net=$2.13 (cash flow: -$1997.87, balance: $10002.13)
2025-10-30 08:24:48,255 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8913/9953
2025-10-30 08:24:48,257 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110985.99
2025-10-30 08:24:48,257 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110985.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,257 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:48,259 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,261 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:24:48,261 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.94, Commission=$0.00, Net=$-0.94 (cash flow: -$2000.94, balance: $9999.06)
2025-10-30 08:24:48,262 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6534/9953
2025-10-30 08:24:48,266 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109898.97
2025-10-30 08:24:48,266 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109898.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,266 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:48,268 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,269 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:24:48,270 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.13, Commission=$0.00, Net=$-1.13 (cash flow: -$2001.13, balance: $9998.87)
2025-10-30 08:24:48,270 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1589/9953
2025-10-30 08:24:48,274 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112079.99
2025-10-30 08:24:48,275 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112079.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:48,275 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:24:48,277 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,279 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:24:48,279 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.00, Commission=$0.00, Net=$-2.00 (cash flow: +$1998.00, -$0.00, balance: $9998.00)
2025-10-30 08:24:48,280 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2076/9953
2025-10-30 08:24:48,281 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112024.03
2025-10-30 08:24:48,282 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112024.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,282 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:48,284 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,289 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:24:48,289 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.52, Commission=$0.00, Net=$-0.52 (cash flow: -$2000.52, balance: $9999.48)
2025-10-30 08:24:48,290 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3655/9953
2025-10-30 08:24:48,292 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108109.93
2025-10-30 08:24:48,292 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108109.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,293 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:48,294 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,299 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:48,299 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.03, Commission=$0.00, Net=$2.03 (cash flow: -$1997.97, balance: $10002.03)
2025-10-30 08:24:48,300 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1635/9953
2025-10-30 08:24:48,302 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112352.79
2025-10-30 08:24:48,302 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112352.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,303 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:48,305 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,311 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:48,311 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.52, Commission=$0.00, Net=$1.52 (cash flow: -$1998.48, balance: $10001.52)
2025-10-30 08:24:48,312 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7935/9953
2025-10-30 08:24:48,314 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110083.50
2025-10-30 08:24:48,315 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110083.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,315 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:48,319 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,322 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:48,322 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.64, Commission=$0.00, Net=$1.64 (cash flow: -$1998.36, balance: $10001.64)
2025-10-30 08:24:48,323 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8547/9953
2025-10-30 08:24:48,325 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111369.90
2025-10-30 08:24:48,325 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111369.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,326 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:48,330 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:48,330 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.03, Commission=$0.00, Net=$1.03 (cash flow: -$1998.97, balance: $10001.03)
2025-10-30 08:24:48,331 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8150/9953
2025-10-30 08:24:48,333 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110445.03
2025-10-30 08:24:48,333 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110445.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,334 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:48,336 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,338 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:24:48,338 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.17, Commission=$0.00, Net=$0.17 (cash flow: -$1999.83, balance: $10000.17)
2025-10-30 08:24:48,339 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8727/9953
2025-10-30 08:24:48,341 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111655.00
2025-10-30 08:24:48,341 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111655.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,342 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:48,346 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,348 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0179, signal=1.0
2025-10-30 08:24:48,348 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.76, Commission=$0.00, Net=$-2.76 (cash flow: -$2002.76, balance: $9997.24)
2025-10-30 08:24:48,349 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9116/9953
2025-10-30 08:24:48,351 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109957.15
2025-10-30 08:24:48,352 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109957.15 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,352 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:48,354 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,358 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:24:48,358 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.16, Commission=$0.00, Net=$1.16 (cash flow: -$1998.84, balance: $10001.16)
2025-10-30 08:24:48,359 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5457/9953
2025-10-30 08:24:48,361 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107749.02
2025-10-30 08:24:48,361 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107749.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:48,362 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:24:48,364 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,365 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:24:48,366 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.15, Commission=$0.00, Net=$1.15 (cash flow: +$2001.15, -$0.00, balance: $10001.15)
2025-10-30 08:24:48,366 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5630/9953
2025-10-30 08:24:48,368 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107950.00
2025-10-30 08:24:48,369 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107950.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,369 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:48,373 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,377 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:48,377 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.98, Commission=$0.00, Net=$1.98 (cash flow: -$1998.02, balance: $10001.98)
2025-10-30 08:24:48,378 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 310/9953
2025-10-30 08:24:48,380 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108364.55
2025-10-30 08:24:48,380 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108364.55 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,381 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:48,385 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,386 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:48,386 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.12, Commission=$0.00, Net=$1.12 (cash flow: -$1998.88, balance: $10001.12)
2025-10-30 08:24:48,387 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1672/9953
2025-10-30 08:24:48,389 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112369.18
2025-10-30 08:24:48,389 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112369.18 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,389 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:48,391 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:24:48,391 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.07, Commission=$0.00, Net=$0.07 (cash flow: -$1999.93, balance: $10000.07)
2025-10-30 08:24:48,392 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 555/9953
2025-10-30 08:24:48,394 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110949.99
2025-10-30 08:24:48,395 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110949.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,395 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:48,399 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:48,401 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:24:48,401 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.04, Commission=$0.00, Net=$-0.04 (cash flow: -$2000.04, balance: $9999.96)
2025-10-30 08:24:48,402 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3941/9953
2025-10-30 08:24:48,404 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108216.42
2025-10-30 08:24:48,405 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108216.42 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:48,405 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:48,407 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

Eval num_timesteps=6500, episode_reward=0.00 +/- 0.00
Episode length: 2599.60 +/- 1436.23
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 2.6e+03   |
|    mean_reward        | 0.00173   |
| time/                 |           |
|    total_timesteps    | 6500      |
| train/                |           |
|    entropy_loss       | -0.975    |
|    explained_variance | -5.29e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1299      |
|    policy_loss        | 0.011     |
|    value_loss         | 0.000109  |
-------------------------------------
New best mean reward!
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.71     |
|    ep_rew_mean     | -1.6e-05 |
| time/              |          |
|    fps             | 41       |
|    iterations      | 1300     |
|    time_elapsed    | 155      |
|    total_timesteps | 6500     |
---------------------------------

2025-10-30 08:24:56,450 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:24:56,451 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.86, Commission=$0.00, Net=$0.86 (cash flow: -$1999.14, balance: $10000.86)
2025-10-30 08:24:56,452 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8626/9953
2025-10-30 08:24:56,453 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110883.73
2025-10-30 08:24:56,454 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110883.73 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,454 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:56,456 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,461 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:56,461 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.69, Commission=$0.00, Net=$2.69 (cash flow: -$1997.31, balance: $10002.69)
2025-10-30 08:24:56,462 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9383/9953
2025-10-30 08:24:56,464 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110593.99
2025-10-30 08:24:56,465 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110593.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,465 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:56,467 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,472 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:24:56,472 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.55, Commission=$0.00, Net=$1.55 (cash flow: -$1998.45, balance: $10001.55)
2025-10-30 08:24:56,473 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 905/9953
2025-10-30 08:24:56,474 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112900.00
2025-10-30 08:24:56,475 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0177 @ $112900.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,475 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0177
2025-10-30 08:24:56,477 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,478 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0177, signal=-1.0
2025-10-30 08:24:56,479 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.20, Commission=$0.00, Net=$0.20 (cash flow: +$2000.20, -$0.00, balance: $10000.20)
2025-10-30 08:24:56,479 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4281/9953
2025-10-30 08:24:56,482 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108000.00
2025-10-30 08:24:56,482 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108000.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,482 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:56,486 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,488 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:56,488 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.30, Commission=$0.00, Net=$-0.30 (cash flow: +$1999.70, -$0.00, balance: $9999.70)
2025-10-30 08:24:56,489 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5184/9953
2025-10-30 08:24:56,492 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108311.00
2025-10-30 08:24:56,492 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108311.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,492 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:56,494 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,498 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:56,498 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.05, Commission=$0.00, Net=$-3.05 (cash flow: -$2003.05, balance: $9996.95)
2025-10-30 08:24:56,499 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3694/9953
2025-10-30 08:24:56,501 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107912.14
2025-10-30 08:24:56,501 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107912.14 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,501 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:56,503 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,505 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:56,506 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.22, Commission=$0.00, Net=$0.22 (cash flow: -$1999.78, balance: $10000.22)
2025-10-30 08:24:56,507 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 149/9953
2025-10-30 08:24:56,512 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109324.86
2025-10-30 08:24:56,512 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109324.86 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,512 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:56,515 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:24:56,515 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.45, Commission=$0.00, Net=$-0.45 (cash flow: -$2000.45, balance: $9999.55)
2025-10-30 08:24:56,516 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6279/9953
2025-10-30 08:24:56,518 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108552.64
2025-10-30 08:24:56,519 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108552.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,519 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:56,521 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:56,521 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.52, Commission=$0.00, Net=$0.52 (cash flow: -$1999.48, balance: $10000.52)
2025-10-30 08:24:56,522 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2366/9953
2025-10-30 08:24:56,523 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111237.71
2025-10-30 08:24:56,524 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111237.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,524 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:56,528 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,530 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:56,532 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.76, Commission=$0.00, Net=$0.76 (cash flow: +$2000.76, -$0.00, balance: $10000.76)
2025-10-30 08:24:56,533 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3477/9953
2025-10-30 08:24:56,535 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107978.00
2025-10-30 08:24:56,535 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107978.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,536 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:56,538 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,542 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:56,542 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.91, Commission=$0.00, Net=$-1.91 (cash flow: -$2001.91, balance: $9998.09)
2025-10-30 08:24:56,543 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3215/9953
2025-10-30 08:24:56,546 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108322.99
2025-10-30 08:24:56,547 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108322.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,547 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:56,549 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,553 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:56,554 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.65, Commission=$0.00, Net=$-0.65 (cash flow: -$2000.65, balance: $9999.35)
2025-10-30 08:24:56,554 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6406/9953
2025-10-30 08:24:56,557 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108820.40
2025-10-30 08:24:56,557 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108820.40 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,557 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:56,559 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,561 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:56,562 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.64, Commission=$0.00, Net=$-0.64 (cash flow: -$2000.64, balance: $9999.36)
2025-10-30 08:24:56,562 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8021/9953
2025-10-30 08:24:56,564 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110438.38
2025-10-30 08:24:56,565 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110438.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,565 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:24:56,569 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,578 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:24:56,578 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.20, Commission=$0.00, Net=$-3.20 (cash flow: -$2003.20, balance: $9996.80)
2025-10-30 08:24:56,579 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7977/9953
2025-10-30 08:24:56,580 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110055.04
2025-10-30 08:24:56,580 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $110055.04 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,581 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:56,585 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,587 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:24:56,588 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.11, Commission=$0.00, Net=$1.11 (cash flow: +$2001.11, -$0.00, balance: $10001.11)
2025-10-30 08:24:56,588 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 572/9953
2025-10-30 08:24:56,590 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111203.91
2025-10-30 08:24:56,590 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111203.91 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,591 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:24:56,592 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,594 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:24:56,594 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.01, Commission=$0.00, Net=$1.01 (cash flow: +$2001.01, -$0.00, balance: $10001.01)
2025-10-30 08:24:56,595 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5870/9953
2025-10-30 08:24:56,601 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=106857.03
2025-10-30 08:24:56,601 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $106857.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,601 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:24:56,603 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,605 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:24:56,605 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.80, Commission=$0.00, Net=$-0.80 (cash flow: -$2000.80, balance: $9999.20)
2025-10-30 08:24:56,606 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2661/9953
2025-10-30 08:24:56,610 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109622.94
2025-10-30 08:24:56,610 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109622.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,610 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:56,612 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,615 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:24:56,615 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.79, Commission=$0.00, Net=$-2.79 (cash flow: -$2002.79, balance: $9997.21)
2025-10-30 08:24:56,616 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7148/9953
2025-10-30 08:24:56,618 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109514.84
2025-10-30 08:24:56,618 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109514.84 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,618 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:56,623 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,625 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:24:56,625 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.11, Commission=$0.00, Net=$0.11 (cash flow: -$1999.89, balance: $10000.11)
2025-10-30 08:24:56,626 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6710/9953
2025-10-30 08:24:56,628 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109676.61
2025-10-30 08:24:56,628 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109676.61 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,629 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:24:56,631 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,632 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:24:56,633 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.03, Commission=$0.00, Net=$-1.03 (cash flow: +$1998.97, -$0.00, balance: $9998.97)
2025-10-30 08:24:56,633 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1034/9953
2025-10-30 08:24:56,637 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112766.07
2025-10-30 08:24:56,638 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112766.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,638 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:24:56,640 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,642 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 08:24:56,642 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.53, Commission=$0.00, Net=$-0.53 (cash flow: -$2000.53, balance: $9999.47)
2025-10-30 08:24:56,643 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8693/9953
2025-10-30 08:24:56,646 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110912.26
2025-10-30 08:24:56,646 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110912.26 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:56,646 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:56,651 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:56,653 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:24:56,653 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.07, Commission=$0.00, Net=$-3.07 (cash flow: -$2003.07, balance: $9996.93)
2025-10-30 08:24:56,654 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8124/9953
2025-10-30 08:24:56,656 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110423.99
2025-10-30 08:24:56,656 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110423.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:56,656 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:24:56,658 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum

Eval num_timesteps=7000, episode_reward=-0.00 +/- 0.00
Episode length: 12.20 +/- 14.13
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 12.2      |
|    mean_reward        | -0.000163 |
| time/                 |           |
|    total_timesteps    | 7000      |
| train/                |           |
|    entropy_loss       | -1.07     |
|    explained_variance | -25.6     |
|    learning_rate      | 0.0007    |
|    n_updates          | 1399      |
|    policy_loss        | 0.00347   |
|    value_loss         | 1.27e-05  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.72     |
|    ep_rew_mean     | 8.08e-06 |
| time/              |          |
|    fps             | 44       |
|    iterations      | 1400     |
|    time_elapsed    | 156      |
|    total_timesteps | 7000     |
---------------------------------

2025-10-30 08:24:57,822 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,825 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:57,825 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.81, Commission=$0.00, Net=$0.81 (cash flow: -$1999.19, balance: $10000.81)
2025-10-30 08:24:57,826 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 681/9953
2025-10-30 08:24:57,829 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112169.21
2025-10-30 08:24:57,829 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112169.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,830 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:57,833 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,836 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:24:57,836 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.40, Commission=$0.00, Net=$-1.40 (cash flow: -$2001.40, balance: $9998.60)
2025-10-30 08:24:57,837 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7094/9953
2025-10-30 08:24:57,839 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109390.38
2025-10-30 08:24:57,840 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109390.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,840 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:24:57,842 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:24:57,842 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: -$2000.73, balance: $9999.27)
2025-10-30 08:24:57,843 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4189/9953
2025-10-30 08:24:57,848 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107306.97
2025-10-30 08:24:57,848 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107306.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,849 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:24:57,851 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,853 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:24:57,854 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.43, Commission=$0.00, Net=$-0.43 (cash flow: -$2000.43, balance: $9999.57)
2025-10-30 08:24:57,855 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4573/9953
2025-10-30 08:24:57,857 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108147.99
2025-10-30 08:24:57,858 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108147.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:57,858 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:57,862 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:57,863 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.43, Commission=$0.00, Net=$-1.43 (cash flow: +$1998.57, -$0.00, balance: $9998.57)
2025-10-30 08:24:57,864 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3497/9953
2025-10-30 08:24:57,867 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107986.00
2025-10-30 08:24:57,868 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107986.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,868 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:57,871 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,875 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:57,876 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.00, Commission=$0.00, Net=$-1.00 (cash flow: -$2001.00, balance: $9999.00)
2025-10-30 08:24:57,877 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3343/9953
2025-10-30 08:24:57,879 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108413.08
2025-10-30 08:24:57,879 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108413.08 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:57,879 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:24:57,881 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:24:57,882 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.78, Commission=$0.00, Net=$0.78 (cash flow: +$2000.78, -$0.00, balance: $10000.78)
2025-10-30 08:24:57,883 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4051/9953
2025-10-30 08:24:57,885 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107945.49
2025-10-30 08:24:57,885 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107945.49 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,886 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:57,890 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:24:57,890 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.12, Commission=$0.00, Net=$-1.12 (cash flow: -$2001.12, balance: $9998.88)
2025-10-30 08:24:57,891 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6675/9953
2025-10-30 08:24:57,893 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109360.01
2025-10-30 08:24:57,894 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109360.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:57,894 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:24:57,896 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,898 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 08:24:57,898 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.81, Commission=$0.00, Net=$-0.81 (cash flow: +$1999.19, -$0.00, balance: $9999.19)
2025-10-30 08:24:57,899 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2706/9953
2025-10-30 08:24:57,901 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108494.90
2025-10-30 08:24:57,902 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108494.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,902 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:57,906 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,908 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:57,908 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.06, Commission=$0.00, Net=$-2.06 (cash flow: -$2002.06, balance: $9997.94)
2025-10-30 08:24:57,909 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1023/9953
2025-10-30 08:24:57,911 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113069.62
2025-10-30 08:24:57,911 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113069.62 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,912 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:24:57,915 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,916 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 08:24:57,917 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.19, Commission=$0.00, Net=$2.19 (cash flow: -$1997.81, balance: $10002.19)
2025-10-30 08:24:57,917 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8488/9953
2025-10-30 08:24:57,922 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110908.99
2025-10-30 08:24:57,923 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110908.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,923 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:57,926 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:57,926 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.36, Commission=$0.00, Net=$-1.36 (cash flow: -$2001.36, balance: $9998.64)
2025-10-30 08:24:57,927 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3133/9953
2025-10-30 08:24:57,930 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107989.24
2025-10-30 08:24:57,930 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107989.24 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,930 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:24:57,932 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,936 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:24:57,937 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: -$2000.21, balance: $9999.79)
2025-10-30 08:24:57,938 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7610/9953
2025-10-30 08:24:57,940 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111114.90
2025-10-30 08:24:57,940 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111114.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,941 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:57,943 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:57,943 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.62, Commission=$0.00, Net=$-0.62 (cash flow: -$2000.62, balance: $9999.38)
2025-10-30 08:24:57,944 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 731/9953
2025-10-30 08:24:57,947 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111765.02
2025-10-30 08:24:57,947 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111765.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,948 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:24:57,950 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,956 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:24:57,956 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.78, Commission=$0.00, Net=$-2.78 (cash flow: -$2002.78, balance: $9997.22)
2025-10-30 08:24:57,957 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7357/9953
2025-10-30 08:24:57,960 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110073.27
2025-10-30 08:24:57,960 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $110073.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,960 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:24:57,963 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,968 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:24:57,968 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.29, Commission=$0.00, Net=$0.29 (cash flow: -$1999.71, balance: $10000.29)
2025-10-30 08:24:57,970 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3611/9953
2025-10-30 08:24:57,973 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108583.66
2025-10-30 08:24:57,973 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108583.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,973 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:57,976 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,978 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:24:57,978 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.24, Commission=$0.00, Net=$-0.24 (cash flow: -$2000.24, balance: $9999.76)
2025-10-30 08:24:57,979 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4478/9953
2025-10-30 08:24:57,984 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108338.65
2025-10-30 08:24:57,984 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108338.65 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:24:57,985 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:24:57,988 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:57,990 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:24:57,990 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.22, Commission=$0.00, Net=$0.22 (cash flow: +$2000.22, -$0.00, balance: $10000.22)
2025-10-30 08:24:57,991 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6391/9953
2025-10-30 08:24:57,994 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108760.28
2025-10-30 08:24:57,994 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108760.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:57,995 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:57,998 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:58,004 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:58,005 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.15, Commission=$0.00, Net=$1.15 (cash flow: -$1998.85, balance: $10001.15)
2025-10-30 08:24:58,005 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 829/9953
2025-10-30 08:24:58,007 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112639.99
2025-10-30 08:24:58,007 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112639.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:58,008 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:58,009 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:58,017 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:58,018 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.71, Commission=$0.00, Net=$-0.71 (cash flow: -$2000.71, balance: $9999.29)
2025-10-30 08:24:58,019 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1926/9953
2025-10-30 08:24:58,024 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112291.21
2025-10-30 08:24:58,025 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112291.21 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:58,025 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:24:58,028 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:58,030 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:24:58,030 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: -$2000.21, balance: $9999.79)
2025-10-30 08:24:58,031 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6269/9953
2025-10-30 08:24:58,033 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108532.29
2025-10-30 08:24:58,033 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108532.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:58,033 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:24:58,036 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:24:58,041 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:24:58,042 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.18, Commission=$0.00, Net=$-0.18 (cash flow: -$2000.18, balance: $9999.82)
2025-10-30 08:24:58,043 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8261/9953
2025-10-30 08:24:58,045 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111208.88
2025-10-30 08:24:58,045 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111208.88 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:24:58,046 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:24:58,048 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:24:58,048 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.14, Commission=$0.00, Net=$0.14 (cash flow: -$1999.86, balance: $10000.14)
2025-10-30 08:24:58,050 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6846/9953

Eval num_timesteps=7500, episode_reward=0.00 +/- 0.00
Episode length: 514.00 +/- 818.43
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 514      |
|    mean_reward        | 0.00189  |
| time/                 |          |
|    total_timesteps    | 7500     |
| train/                |          |
|    entropy_loss       | -0.998   |
|    explained_variance | -0.544   |
|    learning_rate      | 0.0007   |
|    n_updates          | 1499     |
|    policy_loss        | -0.00225 |
|    value_loss         | 1.4e-05  |
------------------------------------
New best mean reward!
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.93     |
|    ep_rew_mean     | 4.62e-06 |
| time/              |          |
|    fps             | 47       |
|    iterations      | 1500     |
|    time_elapsed    | 159      |
|    total_timesteps | 7500     |
---------------------------------

2025-10-30 08:25:00,816 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:25:00,816 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.31, Commission=$0.00, Net=$1.31 (cash flow: +$2001.31, -$0.00, balance: $10001.31)
2025-10-30 08:25:00,818 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3857/9953
2025-10-30 08:25:00,820 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107704.38
2025-10-30 08:25:00,820 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107704.38 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:00,820 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:25:00,822 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:25:00,822 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.41, Commission=$0.00, Net=$-0.41 (cash flow: -$2000.41, balance: $9999.59)
2025-10-30 08:25:00,822 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6256/9953
2025-10-30 08:25:00,824 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108375.71
2025-10-30 08:25:00,824 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108375.71 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:00,824 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:00,827 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:00,830 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:25:00,831 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.64, Commission=$0.00, Net=$-0.64 (cash flow: -$2000.64, balance: $9999.36)
2025-10-30 08:25:00,837 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9424/9953
2025-10-30 08:25:00,845 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110724.79
2025-10-30 08:25:00,850 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110724.79 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:00,851 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:00,873 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:00,910 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:00,929 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.51, Commission=$0.00, Net=$-0.51 (cash flow: -$2000.51, balance: $9999.49)
2025-10-30 08:25:00,988 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2250/9953
2025-10-30 08:25:00,994 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111566.70
2025-10-30 08:25:00,995 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111566.70 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:00,996 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:25:01,001 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,010 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:25:01,012 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.47, Commission=$0.00, Net=$2.47 (cash flow: +$2002.47, -$0.00, balance: $10002.47)
2025-10-30 08:25:01,017 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 362/9953
2025-10-30 08:25:01,032 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109656.70
2025-10-30 08:25:01,033 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109656.70 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,035 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:25:01,041 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,046 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:25:01,049 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.40, Commission=$0.00, Net=$-0.40 (cash flow: +$1999.60, -$0.00, balance: $9999.60)
2025-10-30 08:25:01,052 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2174/9953
2025-10-30 08:25:01,057 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112100.71
2025-10-30 08:25:01,057 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112100.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,058 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:01,061 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,064 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:01,065 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.37, Commission=$0.00, Net=$-3.37 (cash flow: +$1996.63, -$0.00, balance: $9996.63)
2025-10-30 08:25:01,066 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3261/9953
2025-10-30 08:25:01,068 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108274.32
2025-10-30 08:25:01,068 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108274.32 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,068 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:25:01,071 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,072 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:25:01,072 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.43, Commission=$0.00, Net=$-0.43 (cash flow: +$1999.57, -$0.00, balance: $9999.57)
2025-10-30 08:25:01,073 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6681/9953
2025-10-30 08:25:01,075 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109323.16
2025-10-30 08:25:01,075 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109323.16 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,075 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:25:01,080 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,081 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:25:01,082 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.16, Commission=$0.00, Net=$1.16 (cash flow: -$1998.84, balance: $10001.16)
2025-10-30 08:25:01,082 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6774/9953
2025-10-30 08:25:01,086 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109257.97
2025-10-30 08:25:01,086 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109257.97 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,086 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:25:01,089 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,090 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:25:01,091 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.43, Commission=$0.00, Net=$0.43 (cash flow: -$1999.57, balance: $10000.43)
2025-10-30 08:25:01,092 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9881/9953
2025-10-30 08:25:01,097 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111550.86
2025-10-30 08:25:01,097 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111550.86 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,097 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:25:01,099 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:25:01,100 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.31, Commission=$0.00, Net=$-0.31 (cash flow: -$2000.31, balance: $9999.69)
2025-10-30 08:25:01,101 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9433/9953
2025-10-30 08:25:01,103 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110574.00
2025-10-30 08:25:01,103 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110574.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,104 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:01,106 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,110 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:01,111 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.37, Commission=$0.00, Net=$0.37 (cash flow: -$1999.63, balance: $10000.37)
2025-10-30 08:25:01,112 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6297/9953
2025-10-30 08:25:01,115 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108705.75
2025-10-30 08:25:01,115 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108705.75 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,116 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:01,118 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,120 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:25:01,121 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.09, Commission=$0.00, Net=$1.09 (cash flow: -$1998.91, balance: $10001.09)
2025-10-30 08:25:01,122 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 356/9953
2025-10-30 08:25:01,126 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109694.58
2025-10-30 08:25:01,127 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109694.58 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,127 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:25:01,130 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,135 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:25:01,135 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.37, Commission=$0.00, Net=$-1.37 (cash flow: -$2001.37, balance: $9998.63)
2025-10-30 08:25:01,136 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4343/9953
2025-10-30 08:25:01,138 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107482.28
2025-10-30 08:25:01,139 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107482.28 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,139 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:25:01,141 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,142 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:25:01,143 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.09, Commission=$0.00, Net=$1.09 (cash flow: -$1998.91, balance: $10001.09)
2025-10-30 08:25:01,143 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9000/9953
2025-10-30 08:25:01,145 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110434.38
2025-10-30 08:25:01,146 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110434.38 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,146 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:25:01,150 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,152 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:25:01,152 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.33, Commission=$0.00, Net=$-0.33 (cash flow: +$1999.67, -$0.00, balance: $9999.67)
2025-10-30 08:25:01,153 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5795/9953
2025-10-30 08:25:01,157 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107352.89
2025-10-30 08:25:01,157 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107352.89 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,157 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:25:01,160 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,165 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:25:01,165 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.46, Commission=$0.00, Net=$-0.46 (cash flow: +$1999.54, -$0.00, balance: $9999.54)
2025-10-30 08:25:01,166 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7417/9953
2025-10-30 08:25:01,168 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109955.00
2025-10-30 08:25:01,168 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109955.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,169 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:25:01,172 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,178 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:25:01,178 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.94, Commission=$0.00, Net=$0.94 (cash flow: -$1999.06, balance: $10000.94)
2025-10-30 08:25:01,179 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7200/9953
2025-10-30 08:25:01,181 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108881.07
2025-10-30 08:25:01,182 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0184 @ $108881.07 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,182 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0184
2025-10-30 08:25:01,184 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0184
2025-10-30 08:25:01,185 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.23, Commission=$0.00, Net=$0.23 (cash flow: +$2000.23, -$0.00, balance: $10000.23)
2025-10-30 08:25:01,186 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1478/9953
2025-10-30 08:25:01,188 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112447.00
2025-10-30 08:25:01,188 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112447.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,189 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:01,193 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,195 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:01,196 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.28, Commission=$0.00, Net=$-0.28 (cash flow: +$1999.72, -$0.00, balance: $9999.72)
2025-10-30 08:25:01,196 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8049/9953
2025-10-30 08:25:01,199 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110443.81
2025-10-30 08:25:01,200 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110443.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,200 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:01,203 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:01,204 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.02, Commission=$0.00, Net=$-0.02 (cash flow: -$2000.02, balance: $9999.98)
2025-10-30 08:25:01,204 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6009/9953
2025-10-30 08:25:01,207 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107568.44
2025-10-30 08:25:01,207 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107568.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:01,207 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:25:01,211 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,213 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:25:01,214 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.36, Commission=$0.00, Net=$-2.36 (cash flow: +$1997.64, -$0.00, balance: $9997.64)
2025-10-30 08:25:01,215 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5392/9953
2025-10-30 08:25:01,216 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108100.02
2025-10-30 08:25:01,217 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108100.02 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:01,217 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:01,219 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:01,225 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0

Eval num_timesteps=8000, episode_reward=0.00 +/- 0.00
Episode length: 203.80 +/- 313.80
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 204       |
|    mean_reward        | 0.00157   |
| time/                 |           |
|    total_timesteps    | 8000      |
| train/                |           |
|    entropy_loss       | -0.751    |
|    explained_variance | -36.6     |
|    learning_rate      | 0.0007    |
|    n_updates          | 1599      |
|    policy_loss        | -0.000154 |
|    value_loss         | 6.74e-07  |
-------------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 3.9       |
|    ep_rew_mean     | -2.44e-05 |
| time/              |           |
|    fps             | 49        |
|    iterations      | 1600      |
|    time_elapsed    | 161       |
|    total_timesteps | 8000      |
----------------------------------

2025-10-30 08:25:02,796 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:25:02,796 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.12, Commission=$0.00, Net=$1.12 (cash flow: -$1998.88, balance: $10001.12)
2025-10-30 08:25:02,797 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 852/9953
2025-10-30 08:25:02,798 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112352.83
2025-10-30 08:25:02,799 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112352.83 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,799 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:02,800 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,802 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:02,802 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.79, Commission=$0.00, Net=$0.79 (cash flow: +$2000.79, -$0.00, balance: $10000.79)
2025-10-30 08:25:02,803 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1034/9953
2025-10-30 08:25:02,806 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112766.07
2025-10-30 08:25:02,806 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112766.07 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,807 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:25:02,809 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,811 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0177
2025-10-30 08:25:02,811 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.66, Commission=$0.00, Net=$-1.66 (cash flow: -$2001.66, balance: $9998.34)
2025-10-30 08:25:02,812 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6009/9953
2025-10-30 08:25:02,815 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107568.44
2025-10-30 08:25:02,815 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107568.44 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,816 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:25:02,818 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,819 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:25:02,819 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.36, Commission=$0.00, Net=$-2.36 (cash flow: +$1997.64, -$0.00, balance: $9997.64)
2025-10-30 08:25:02,820 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 363/9953
2025-10-30 08:25:02,822 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109656.70
2025-10-30 08:25:02,822 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109656.70 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,823 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:25:02,824 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,828 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:25:02,828 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.59, Commission=$0.00, Net=$-0.59 (cash flow: -$2000.59, balance: $9999.41)
2025-10-30 08:25:02,829 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 244/9953
2025-10-30 08:25:02,830 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108523.72
2025-10-30 08:25:02,831 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108523.72 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,831 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:02,833 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,838 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:25:02,838 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.33, Commission=$0.00, Net=$-1.33 (cash flow: -$2001.33, balance: $9998.67)
2025-10-30 08:25:02,839 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9712/9953
2025-10-30 08:25:02,841 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111063.22
2025-10-30 08:25:02,841 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111063.22 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,842 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:25:02,844 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,849 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:25:02,849 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.07, Commission=$0.00, Net=$-0.07 (cash flow: -$2000.07, balance: $9999.93)
2025-10-30 08:25:02,850 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6155/9953
2025-10-30 08:25:02,851 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108475.99
2025-10-30 08:25:02,851 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108475.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,852 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:02,855 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,858 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:25:02,858 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.18, Commission=$0.00, Net=$2.18 (cash flow: -$1997.82, balance: $10002.18)
2025-10-30 08:25:02,859 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8609/9953
2025-10-30 08:25:02,861 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111227.33
2025-10-30 08:25:02,861 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111227.33 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,861 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:25:02,863 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,868 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:25:02,868 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.09, Commission=$0.00, Net=$2.09 (cash flow: -$1997.91, balance: $10002.09)
2025-10-30 08:25:02,869 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8176/9953
2025-10-30 08:25:02,871 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110970.62
2025-10-30 08:25:02,871 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110970.62 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,872 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:25:02,873 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,877 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0180, signal=1.0
2025-10-30 08:25:02,877 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.49, Commission=$0.00, Net=$-1.49 (cash flow: -$2001.49, balance: $9998.51)
2025-10-30 08:25:02,878 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5662/9953
2025-10-30 08:25:02,881 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107684.42
2025-10-30 08:25:02,881 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107684.42 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,881 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:25:02,883 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,888 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0186, signal=-1.0
2025-10-30 08:25:02,888 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.13, Commission=$0.00, Net=$0.13 (cash flow: +$2000.13, -$0.00, balance: $10000.13)
2025-10-30 08:25:02,889 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6989/9953
2025-10-30 08:25:02,891 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108897.68
2025-10-30 08:25:02,891 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108897.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,891 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:02,893 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,899 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:25:02,899 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.58, Commission=$0.00, Net=$0.58 (cash flow: -$1999.42, balance: $10000.58)
2025-10-30 08:25:02,900 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1630/9953
2025-10-30 08:25:02,902 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112315.34
2025-10-30 08:25:02,902 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112315.34 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,903 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:02,905 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,908 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:02,909 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.07, Commission=$0.00, Net=$-0.07 (cash flow: +$1999.93, -$0.00, balance: $9999.93)
2025-10-30 08:25:02,909 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9590/9953
2025-10-30 08:25:02,911 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111099.99
2025-10-30 08:25:02,911 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111099.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,911 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:25:02,913 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,915 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:25:02,915 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.89, Commission=$0.00, Net=$-0.89 (cash flow: +$1999.11, -$0.00, balance: $9999.11)
2025-10-30 08:25:02,916 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7436/9953
2025-10-30 08:25:02,921 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109766.27
2025-10-30 08:25:02,922 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109766.27 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,922 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:25:02,924 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,926 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0182, signal=-1.0
2025-10-30 08:25:02,926 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: +$1999.89, -$0.00, balance: $9999.89)
2025-10-30 08:25:02,927 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2778/9953
2025-10-30 08:25:02,929 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108993.24
2025-10-30 08:25:02,929 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $108993.24 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,930 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:02,933 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,936 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 08:25:02,936 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-3.64, Commission=$0.00, Net=$-3.64 (cash flow: +$1996.36, -$0.00, balance: $9996.36)
2025-10-30 08:25:02,937 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5720/9953
2025-10-30 08:25:02,938 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107618.94
2025-10-30 08:25:02,938 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107618.94 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,939 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:25:02,940 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:25:02,940 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: +$1999.27, -$0.00, balance: $9999.27)
2025-10-30 08:25:02,941 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3656/9953
2025-10-30 08:25:02,945 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108077.30
2025-10-30 08:25:02,945 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108077.30 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,946 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:02,947 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,949 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:25:02,949 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.84, Commission=$0.00, Net=$1.84 (cash flow: -$1998.16, balance: $10001.84)
2025-10-30 08:25:02,950 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8007/9953
2025-10-30 08:25:02,951 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110246.64
2025-10-30 08:25:02,952 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110246.64 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,952 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:02,956 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,957 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:25:02,958 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.48, Commission=$0.00, Net=$-0.48 (cash flow: -$2000.48, balance: $9999.52)
2025-10-30 08:25:02,958 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7480/9953
2025-10-30 08:25:02,960 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110265.33
2025-10-30 08:25:02,961 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110265.33 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,961 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:25:02,963 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,965 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:25:02,965 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: +$1999.65, -$0.00, balance: $9999.65)
2025-10-30 08:25:02,966 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4344/9953
2025-10-30 08:25:02,969 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107448.00
2025-10-30 08:25:02,970 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107448.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,970 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:25:02,971 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,973 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 08:25:02,973 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.03, Commission=$0.00, Net=$1.03 (cash flow: -$1998.97, balance: $10001.03)
2025-10-30 08:25:02,974 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 662/9953
2025-10-30 08:25:02,975 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111980.10
2025-10-30 08:25:02,975 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0179 @ $111980.10 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:02,975 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0179
2025-10-30 08:25:02,977 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:02,981 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0179, signal=-1.0
2025-10-30 08:25:02,982 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.92, Commission=$0.00, Net=$1.92 (cash flow: +$2001.92, -$0.00, balance: $10001.92)
2025-10-30 08:25:02,982 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7421/9953
2025-10-30 08:25:02,984 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109903.18
2025-10-30 08:25:02,984 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109903.18 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:02,985 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182

Eval num_timesteps=8500, episode_reward=0.00 +/- 0.00
Episode length: 138.80 +/- 267.10
------------------------------------
| eval/                 |          |
|    mean_ep_length     | 139      |
|    mean_reward        | 0.00116  |
| time/                 |          |
|    total_timesteps    | 8500     |
| train/                |          |
|    entropy_loss       | -0.885   |
|    explained_variance | -8.3     |
|    learning_rate      | 0.0007   |
|    n_updates          | 1699     |
|    policy_loss        | 0.00334  |
|    value_loss         | 1.98e-05 |
------------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 4.67      |
|    ep_rew_mean     | -4.32e-06 |
| time/              |           |
|    fps             | 52        |
|    iterations      | 1700      |
|    time_elapsed    | 163       |
|    total_timesteps | 8500      |
----------------------------------

2025-10-30 08:25:04,467 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107576.01
2025-10-30 08:25:04,468 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107576.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,468 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:25:04,471 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,473 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0186, signal=1.0
2025-10-30 08:25:04,473 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.60, Commission=$0.00, Net=$1.60 (cash flow: -$1998.40, balance: $10001.60)
2025-10-30 08:25:04,474 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2499/9953
2025-10-30 08:25:04,476 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110572.86
2025-10-30 08:25:04,476 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110572.86 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,476 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:04,479 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,520 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:04,521 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.95, Commission=$0.00, Net=$3.95 (cash flow: -$1996.05, balance: $10003.95)
2025-10-30 08:25:04,522 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4035/9953
2025-10-30 08:25:04,526 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107864.62
2025-10-30 08:25:04,527 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107864.62 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:04,527 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:25:04,529 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,531 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:25:04,531 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.50, Commission=$0.00, Net=$-0.50 (cash flow: +$1999.50, -$0.00, balance: $9999.50)
2025-10-30 08:25:04,532 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7534/9953
2025-10-30 08:25:04,533 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110228.93
2025-10-30 08:25:04,534 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110228.93 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,534 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:04,537 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,541 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:04,542 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.06, Commission=$0.00, Net=$1.06 (cash flow: -$1998.94, balance: $10001.06)
2025-10-30 08:25:04,543 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2174/9953
2025-10-30 08:25:04,545 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112100.71
2025-10-30 08:25:04,545 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112100.71 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,545 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:04,547 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,549 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:25:04,549 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$3.37, Commission=$0.00, Net=$3.37 (cash flow: -$1996.63, balance: $10003.37)
2025-10-30 08:25:04,550 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8134/9953
2025-10-30 08:25:04,554 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110455.98
2025-10-30 08:25:04,554 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110455.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,555 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:04,556 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,559 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:04,559 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.67, Commission=$0.00, Net=$1.67 (cash flow: -$1998.33, balance: $10001.67)
2025-10-30 08:25:04,560 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2119/9953
2025-10-30 08:25:04,565 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112143.90
2025-10-30 08:25:04,565 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112143.90 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,565 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:04,567 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,570 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:25:04,570 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: -$2000.21, balance: $9999.79)
2025-10-30 08:25:04,571 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3756/9953
2025-10-30 08:25:04,575 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108075.00
2025-10-30 08:25:04,575 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108075.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:04,575 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:25:04,577 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:25:04,577 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 08:25:04,578 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1132/9953
2025-10-30 08:25:04,580 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=113331.87
2025-10-30 08:25:04,580 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0176 @ $113331.87 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:04,580 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0176
2025-10-30 08:25:04,582 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,584 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0176, signal=-1.0
2025-10-30 08:25:04,584 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.21, Commission=$0.00, Net=$-0.21 (cash flow: +$1999.79, -$0.00, balance: $9999.79)
2025-10-30 08:25:04,585 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4937/9953
2025-10-30 08:25:04,589 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108155.99
2025-10-30 08:25:04,589 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108155.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,590 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:04,592 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,595 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:25:04,595 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.86, Commission=$0.00, Net=$-2.86 (cash flow: -$2002.86, balance: $9997.14)
2025-10-30 08:25:04,596 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7138/9953
2025-10-30 08:25:04,600 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109396.55
2025-10-30 08:25:04,601 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109396.55 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:04,601 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:04,604 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,605 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:25:04,606 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.80, Commission=$0.00, Net=$0.80 (cash flow: +$2000.80, -$0.00, balance: $10000.80)
2025-10-30 08:25:04,606 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4180/9953
2025-10-30 08:25:04,608 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107090.76
2025-10-30 08:25:04,608 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0187 @ $107090.76 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,609 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0187
2025-10-30 08:25:04,613 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,615 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0187
2025-10-30 08:25:04,615 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.40, Commission=$0.00, Net=$-1.40 (cash flow: -$2001.40, balance: $9998.60)
2025-10-30 08:25:04,616 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5329/9953
2025-10-30 08:25:04,618 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108432.17
2025-10-30 08:25:04,619 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108432.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,619 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:04,620 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,626 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0184, signal=1.0
2025-10-30 08:25:04,628 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.33, Commission=$0.00, Net=$0.33 (cash flow: -$1999.67, balance: $10000.33)
2025-10-30 08:25:04,629 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1502/9953
2025-10-30 08:25:04,632 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112890.81
2025-10-30 08:25:04,632 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $112890.81 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,632 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:25:04,634 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,641 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0177, signal=1.0
2025-10-30 08:25:04,641 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.35, Commission=$0.00, Net=$-0.35 (cash flow: -$2000.35, balance: $9999.65)
2025-10-30 08:25:04,642 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7131/9953
2025-10-30 08:25:04,644 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109236.37
2025-10-30 08:25:04,644 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109236.37 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,645 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:25:04,648 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,649 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:25:04,650 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.16, Commission=$0.00, Net=$-0.16 (cash flow: -$2000.16, balance: $9999.84)
2025-10-30 08:25:04,650 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4914/9953
2025-10-30 08:25:04,653 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107937.22
2025-10-30 08:25:04,654 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107937.22 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,654 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:04,656 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,659 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:25:04,660 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.88, Commission=$0.00, Net=$-0.88 (cash flow: -$2000.88, balance: $9999.12)
2025-10-30 08:25:04,660 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7245/9953
2025-10-30 08:25:04,662 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109449.11
2025-10-30 08:25:04,662 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109449.11 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:04,663 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:04,665 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,666 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 08:25:04,666 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.76, Commission=$0.00, Net=$2.76 (cash flow: +$2002.76, -$0.00, balance: $10002.76)
2025-10-30 08:25:04,667 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5030/9953
2025-10-30 08:25:04,669 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108997.71
2025-10-30 08:25:04,670 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $108997.71 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:04,670 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:04,674 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:25:04,674 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.27, Commission=$0.00, Net=$-0.27 (cash flow: +$1999.73, -$0.00, balance: $9999.73)
2025-10-30 08:25:04,675 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2680/9953
2025-10-30 08:25:04,678 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109059.62
2025-10-30 08:25:04,678 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $109059.62 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,679 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:25:04,680 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,684 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0183
2025-10-30 08:25:04,685 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.18, Commission=$0.00, Net=$0.18 (cash flow: -$1999.82, balance: $10000.18)
2025-10-30 08:25:04,686 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1901/9953
2025-10-30 08:25:04,688 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112315.51
2025-10-30 08:25:04,688 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112315.51 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,688 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:04,691 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,700 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:25:04,700 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.15, Commission=$0.00, Net=$-0.15 (cash flow: -$2000.15, balance: $9999.85)
2025-10-30 08:25:04,702 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3242/9953
2025-10-30 08:25:04,704 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108044.01
2025-10-30 08:25:04,704 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108044.01 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,705 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:04,707 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:04,713 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:25:04,713 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.39, Commission=$0.00, Net=$-1.39 (cash flow: -$2001.39, balance: $9998.61)
2025-10-30 08:25:04,714 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7543/9953
2025-10-30 08:25:04,716 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110499.99
2025-10-30 08:25:04,717 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110499.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:04,717 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:04,719 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:04,720 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: -$2000.11, balance: $9999.89)
2025-10-30 08:25:04,721 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2498/9953
2025-10-30 08:25:04,722 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110575.40

Eval num_timesteps=9000, episode_reward=0.00 +/- 0.00
Episode length: 32.20 +/- 53.03
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 32.2      |
|    mean_reward        | 7.28e-05  |
| time/                 |           |
|    total_timesteps    | 9000      |
| train/                |           |
|    entropy_loss       | -0.972    |
|    explained_variance | -1.58e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1799      |
|    policy_loss        | -0.0076   |
|    value_loss         | 4.52e-05  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.83     |
|    ep_rew_mean     | 1.52e-05 |
| time/              |          |
|    fps             | 54       |
|    iterations      | 1800     |
|    time_elapsed    | 164      |
|    total_timesteps | 9000     |
---------------------------------

2025-10-30 08:25:05,990 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:05,993 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:25:05,993 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.77, Commission=$0.00, Net=$0.77 (cash flow: -$1999.23, balance: $10000.77)
2025-10-30 08:25:05,994 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4574/9953
2025-10-30 08:25:05,996 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108147.99
2025-10-30 08:25:05,996 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108147.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:05,996 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:25:06,000 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,002 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:25:06,003 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.62, Commission=$0.00, Net=$-0.62 (cash flow: +$1999.38, -$0.00, balance: $9999.38)
2025-10-30 08:25:06,003 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 470/9953
2025-10-30 08:25:06,006 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109847.90
2025-10-30 08:25:06,006 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109847.90 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,006 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:25:06,008 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:25:06,009 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.37, Commission=$0.00, Net=$0.37 (cash flow: +$2000.37, -$0.00, balance: $10000.37)
2025-10-30 08:25:06,010 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7663/9953
2025-10-30 08:25:06,012 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111213.24
2025-10-30 08:25:06,013 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111213.24 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,013 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:25:06,016 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,018 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:25:06,018 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.72, Commission=$0.00, Net=$-0.72 (cash flow: +$1999.28, -$0.00, balance: $9999.28)
2025-10-30 08:25:06,019 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4839/9953
2025-10-30 08:25:06,021 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107719.98
2025-10-30 08:25:06,022 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0186 @ $107719.98 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,022 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0186
2025-10-30 08:25:06,024 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0186
2025-10-30 08:25:06,024 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.00, Commission=$0.00, Net=$0.00 (cash flow: +$2000.00, -$0.00, balance: $10000.00)
2025-10-30 08:25:06,025 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1965/9953
2025-10-30 08:25:06,027 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112190.12
2025-10-30 08:25:06,028 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112190.12 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,028 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:06,032 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,034 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:25:06,034 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.04, Commission=$0.00, Net=$0.04 (cash flow: -$1999.96, balance: $10000.04)
2025-10-30 08:25:06,035 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9727/9953
2025-10-30 08:25:06,039 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111186.15
2025-10-30 08:25:06,039 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111186.15 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,039 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:25:06,043 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,045 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0180, signal=-1.0
2025-10-30 08:25:06,045 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.64, Commission=$0.00, Net=$1.64 (cash flow: +$2001.64, -$0.00, balance: $10001.64)
2025-10-30 08:25:06,046 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2910/9953
2025-10-30 08:25:06,048 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108994.99
2025-10-30 08:25:06,048 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $108994.99 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,048 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:25:06,050 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,052 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:25:06,052 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.93, Commission=$0.00, Net=$0.93 (cash flow: -$1999.07, balance: $10000.93)
2025-10-30 08:25:06,053 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6949/9953
2025-10-30 08:25:06,057 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108890.27
2025-10-30 08:25:06,058 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108890.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,058 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:06,061 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:25:06,061 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.17, Commission=$0.00, Net=$-0.17 (cash flow: -$2000.17, balance: $9999.83)
2025-10-30 08:25:06,062 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9165/9953
2025-10-30 08:25:06,065 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109977.99
2025-10-30 08:25:06,065 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0182 @ $109977.99 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,065 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0182
2025-10-30 08:25:06,067 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0182
2025-10-30 08:25:06,067 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.73, Commission=$0.00, Net=$-0.73 (cash flow: +$1999.27, -$0.00, balance: $9999.27)
2025-10-30 08:25:06,068 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1261/9953
2025-10-30 08:25:06,072 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113857.45
2025-10-30 08:25:06,072 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113857.45 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,073 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 08:25:06,075 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,080 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0176, signal=1.0
2025-10-30 08:25:06,081 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.22, Commission=$0.00, Net=$1.22 (cash flow: -$1998.78, balance: $10001.22)
2025-10-30 08:25:06,082 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5474/9953
2025-10-30 08:25:06,084 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107588.45
2025-10-30 08:25:06,085 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0186 @ $107588.45 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,085 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0186
2025-10-30 08:25:06,087 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0186
2025-10-30 08:25:06,087 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.85, Commission=$0.00, Net=$-0.85 (cash flow: -$2000.85, balance: $9999.15)
2025-10-30 08:25:06,088 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9516/9953
2025-10-30 08:25:06,090 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110960.82
2025-10-30 08:25:06,091 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $110960.82 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,091 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:25:06,095 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,098 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0180
2025-10-30 08:25:06,098 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.39, Commission=$0.00, Net=$0.39 (cash flow: -$1999.61, balance: $10000.39)
2025-10-30 08:25:06,099 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 225/9953
2025-10-30 08:25:06,101 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108368.34
2025-10-30 08:25:06,101 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108368.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,101 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:06,104 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,109 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0185, signal=1.0
2025-10-30 08:25:06,110 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.69, Commission=$0.00, Net=$-1.69 (cash flow: -$2001.69, balance: $9998.31)
2025-10-30 08:25:06,111 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1628/9953
2025-10-30 08:25:06,115 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112413.84
2025-10-30 08:25:06,115 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112413.84 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,115 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:06,118 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,122 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:25:06,122 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$2.12, Commission=$0.00, Net=$2.12 (cash flow: -$1997.88, balance: $10002.12)
2025-10-30 08:25:06,123 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9030/9953
2025-10-30 08:25:06,128 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110343.31
2025-10-30 08:25:06,128 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110343.31 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,129 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:25:06,130 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,133 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:25:06,133 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.79, Commission=$0.00, Net=$-2.79 (cash flow: +$1997.21, -$0.00, balance: $9997.21)
2025-10-30 08:25:06,134 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2534/9953
2025-10-30 08:25:06,136 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110439.94
2025-10-30 08:25:06,136 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110439.94 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,136 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:06,140 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,142 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0181, signal=1.0
2025-10-30 08:25:06,142 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.43, Commission=$0.00, Net=$0.43 (cash flow: -$1999.57, balance: $10000.43)
2025-10-30 08:25:06,143 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1219/9953
2025-10-30 08:25:06,146 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113643.03
2025-10-30 08:25:06,146 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0176 @ $113643.03 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,147 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0176
2025-10-30 08:25:06,149 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,155 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0176, signal=1.0
2025-10-30 08:25:06,155 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.76, Commission=$0.00, Net=$0.76 (cash flow: -$1999.24, balance: $10000.76)
2025-10-30 08:25:06,157 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7455/9953
2025-10-30 08:25:06,159 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110443.17
2025-10-30 08:25:06,160 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110443.17 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,160 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:06,164 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:06,165 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.27, Commission=$0.00, Net=$0.27 (cash flow: -$1999.73, balance: $10000.27)
2025-10-30 08:25:06,165 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1529/9953
2025-10-30 08:25:06,167 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112545.06
2025-10-30 08:25:06,167 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112545.06 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,167 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:06,169 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,171 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:06,171 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.89, Commission=$0.00, Net=$-0.89 (cash flow: +$1999.11, -$0.00, balance: $9999.11)
2025-10-30 08:25:06,172 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6409/9953
2025-10-30 08:25:06,174 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108892.71
2025-10-30 08:25:06,174 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108892.71 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:06,174 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:06,178 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,180 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:25:06,180 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.47, Commission=$0.00, Net=$-0.47 (cash flow: -$2000.47, balance: $9999.53)
2025-10-30 08:25:06,181 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6793/9953
2025-10-30 08:25:06,182 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109340.00
2025-10-30 08:25:06,183 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109340.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,183 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:06,185 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,186 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 08:25:06,186 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.61, Commission=$0.00, Net=$1.61 (cash flow: +$2001.61, -$0.00, balance: $10001.61)
2025-10-30 08:25:06,187 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6837/9953
2025-10-30 08:25:06,191 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109534.01
2025-10-30 08:25:06,191 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109534.01 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:06,192 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:06,194 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:06,195 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0183, signal=-1.0
2025-10-30 08:25:06,196 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: +$1999.89, -$0.00, balance: $9999.89)

Eval num_timesteps=9500, episode_reward=0.00 +/- 0.00
Episode length: 9.80 +/- 11.29
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 9.8       |
|    mean_reward        | 1.38e-05  |
| time/                 |           |
|    total_timesteps    | 9500      |
| train/                |           |
|    entropy_loss       | -1.06     |
|    explained_variance | -1.66e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1899      |
|    policy_loss        | 0.00171   |
|    value_loss         | 3.96e-06  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.7      |
|    ep_rew_mean     | 2.09e-06 |
| time/              |          |
|    fps             | 57       |
|    iterations      | 1900     |
|    time_elapsed    | 166      |
|    total_timesteps | 9500     |
---------------------------------

2025-10-30 08:25:07,372 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112242.10
2025-10-30 08:25:07,373 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112242.10 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,373 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:07,375 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,378 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:07,378 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.69, Commission=$0.00, Net=$0.69 (cash flow: +$2000.69, -$0.00, balance: $10000.69)
2025-10-30 08:25:07,379 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 758/9953
2025-10-30 08:25:07,382 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112240.00
2025-10-30 08:25:07,382 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112240.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,382 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:07,387 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,389 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0178, signal=1.0
2025-10-30 08:25:07,390 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.28, Commission=$0.00, Net=$-0.28 (cash flow: -$2000.28, balance: $9999.72)
2025-10-30 08:25:07,391 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 7099/9953
2025-10-30 08:25:07,393 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109389.72
2025-10-30 08:25:07,393 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109389.72 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,394 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:07,396 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,398 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:25:07,398 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.99, Commission=$0.00, Net=$0.99 (cash flow: +$2000.99, -$0.00, balance: $10000.99)
2025-10-30 08:25:07,399 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 488/9953
2025-10-30 08:25:07,403 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109939.50
2025-10-30 08:25:07,403 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109939.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,404 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:25:07,406 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,408 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0182
2025-10-30 08:25:07,409 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.99, Commission=$0.00, Net=$1.99 (cash flow: -$1998.01, balance: $10001.99)
2025-10-30 08:25:07,410 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5100/9953
2025-10-30 08:25:07,417 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108174.66
2025-10-30 08:25:07,418 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108174.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,418 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:07,420 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,424 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:25:07,425 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.01, Commission=$0.00, Net=$-1.01 (cash flow: -$2001.01, balance: $9998.99)
2025-10-30 08:25:07,426 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3311/9953
2025-10-30 08:25:07,428 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108255.00
2025-10-30 08:25:07,428 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108255.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,429 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:25:07,430 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,432 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0185
2025-10-30 08:25:07,432 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.11, Commission=$0.00, Net=$-0.11 (cash flow: -$2000.11, balance: $9999.89)
2025-10-30 08:25:07,433 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 168/9953
2025-10-30 08:25:07,435 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108992.66
2025-10-30 08:25:07,435 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0183 @ $108992.66 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,435 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0183
2025-10-30 08:25:07,439 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,442 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0183, signal=1.0
2025-10-30 08:25:07,442 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.97, Commission=$0.00, Net=$-0.97 (cash flow: -$2000.97, balance: $9999.03)
2025-10-30 08:25:07,443 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 3872/9953
2025-10-30 08:25:07,448 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=107898.74
2025-10-30 08:25:07,449 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $107898.74 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,449 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:25:07,451 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,453 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0185, signal=-1.0
2025-10-30 08:25:07,454 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.26, Commission=$0.00, Net=$1.26 (cash flow: +$2001.26, -$0.00, balance: $10001.26)
2025-10-30 08:25:07,455 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8541/9953
2025-10-30 08:25:07,457 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111433.63
2025-10-30 08:25:07,457 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111433.63 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,457 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:25:07,461 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0179
2025-10-30 08:25:07,461 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.24, Commission=$0.00, Net=$0.24 (cash flow: -$1999.76, balance: $10000.24)
2025-10-30 08:25:07,462 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2583/9953
2025-10-30 08:25:07,465 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=110569.29
2025-10-30 08:25:07,466 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0181 @ $110569.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,466 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0181
2025-10-30 08:25:07,468 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,472 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0181
2025-10-30 08:25:07,472 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.18, Commission=$0.00, Net=$0.18 (cash flow: -$1999.82, balance: $10000.18)
2025-10-30 08:25:07,473 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6890/9953
2025-10-30 08:25:07,476 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109343.53
2025-10-30 08:25:07,476 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109343.53 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,477 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:07,479 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:25:07,480 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.56, Commission=$0.00, Net=$-1.56 (cash flow: +$1998.44, -$0.00, balance: $9998.44)
2025-10-30 08:25:07,481 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1475/9953
2025-10-30 08:25:07,487 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112447.00
2025-10-30 08:25:07,488 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0178 @ $112447.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,488 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0178
2025-10-30 08:25:07,490 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0178
2025-10-30 08:25:07,491 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.10, Commission=$0.00, Net=$1.10 (cash flow: -$1998.90, balance: $10001.10)
2025-10-30 08:25:07,491 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8394/9953
2025-10-30 08:25:07,493 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111161.00
2025-10-30 08:25:07,494 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111161.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,494 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:25:07,496 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,500 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:25:07,500 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-0.36, Commission=$0.00, Net=$-0.36 (cash flow: +$1999.64, -$0.00, balance: $9999.64)
2025-10-30 08:25:07,501 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2394/9953
2025-10-30 08:25:07,503 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110610.02
2025-10-30 08:25:07,503 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110610.02 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,504 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:25:07,505 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,507 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:25:07,507 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.13, Commission=$0.00, Net=$0.13 (cash flow: +$2000.13, -$0.00, balance: $10000.13)
2025-10-30 08:25:07,508 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6649/9953
2025-10-30 08:25:07,512 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=109545.36
2025-10-30 08:25:07,513 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0183 @ $109545.36 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,513 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0183
2025-10-30 08:25:07,515 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0183
2025-10-30 08:25:07,515 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-1.44, Commission=$0.00, Net=$-1.44 (cash flow: +$1998.56, -$0.00, balance: $9998.56)
2025-10-30 08:25:07,516 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 5184/9953
2025-10-30 08:25:07,519 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=108311.00
2025-10-30 08:25:07,519 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0185 @ $108311.00 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,519 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0185
2025-10-30 08:25:07,521 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0185
2025-10-30 08:25:07,521 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$1.13, Commission=$0.00, Net=$1.13 (cash flow: +$2001.13, -$0.00, balance: $10001.13)
2025-10-30 08:25:07,522 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 295/9953
2025-10-30 08:25:07,527 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108459.27
2025-10-30 08:25:07,527 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108459.27 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,528 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:07,530 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,531 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:25:07,531 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.85, Commission=$0.00, Net=$0.85 (cash flow: -$1999.15, balance: $10000.85)
2025-10-30 08:25:07,532 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9255/9953
2025-10-30 08:25:07,534 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109944.98
2025-10-30 08:25:07,534 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109944.98 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,534 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:25:07,538 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,540 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=-0.0182, signal=1.0
2025-10-30 08:25:07,540 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.88, Commission=$0.00, Net=$0.88 (cash flow: -$1999.12, balance: $10000.88)
2025-10-30 08:25:07,541 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9450/9953
2025-10-30 08:25:07,543 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=110674.51
2025-10-30 08:25:07,543 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0181 @ $110674.51 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,543 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0181
2025-10-30 08:25:07,545 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,547 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0181, signal=-1.0
2025-10-30 08:25:07,547 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.23, Commission=$0.00, Net=$0.23 (cash flow: +$2000.23, -$0.00, balance: $10000.23)
2025-10-30 08:25:07,548 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6956/9953
2025-10-30 08:25:07,552 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108865.31
2025-10-30 08:25:07,552 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108865.31 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,552 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:25:07,554 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,556 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=-0.0184
2025-10-30 08:25:07,557 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.94, Commission=$0.00, Net=$-2.94 (cash flow: -$2002.94, balance: $9997.06)
2025-10-30 08:25:07,558 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1556/9953
2025-10-30 08:25:07,559 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=112141.21
2025-10-30 08:25:07,560 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0178 @ $112141.21 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,560 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0178
2025-10-30 08:25:07,564 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,567 - rl_trading_lab.environment.portfolio - DEBUG - Closing position: current=0.0178, signal=-1.0
2025-10-30 08:25:07,568 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$-2.52, Commission=$0.00, Net=$-2.52 (cash flow: +$1997.48, -$0.00, balance: $9997.48)
2025-10-30 08:25:07,568 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8237/9953
2025-10-30 08:25:07,572 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=1.0, price=111127.97
2025-10-30 08:25:07,572 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: LONG 0.0180 @ $111127.97 (cash flow: -$2000.00, remaining: $8000.00)
2025-10-30 08:25:07,573 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=0.0180
2025-10-30 08:25:07,575 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:25:07,577 - rl_trading_lab.environment.trading_env - DEBUG - Hold action closing position: size=0.0180
2025-10-30 08:25:07,577 - rl_trading_lab.environment.portfolio - DEBUG - Position closed: P&L=$0.69, Commission=$0.00, Net=$0.69 (cash flow: +$2000.69, -$0.00, balance: $10000.69)
2025-10-30 08:25:07,581 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9697/9953
2025-10-30 08:25:07,584 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111023.18
2025-10-30 08:25:07,584 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111023.18 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:25:07,584 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180

Eval num_timesteps=10000, episode_reward=-0.00 +/- 0.00
Episode length: 6.80 +/- 5.27
-------------------------------------
| eval/                 |           |
|    mean_ep_length     | 6.8       |
|    mean_reward        | -8.8e-06  |
| time/                 |           |
|    total_timesteps    | 10000     |
| train/                |           |
|    entropy_loss       | -1.03     |
|    explained_variance | -1.68e+03 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1999      |
|    policy_loss        | -0.00456  |
|    value_loss         | 2.08e-05  |
-------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 3.83     |
|    ep_rew_mean     | 2.41e-05 |
| time/              |          |
|    fps             | 59       |
|    iterations      | 2000     |
|    time_elapsed    | 167      |
|    total_timesteps | 10000    |
---------------------------------

In [32]:
mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=10)

2025-10-30 08:12:39,801 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9906/9953
2025-10-30 08:12:39,803 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111639.68
2025-10-30 08:12:39,803 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111639.68 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:39,803 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:12:39,806 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:39,835 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4673/9953
2025-10-30 08:12:39,836 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108686.34
2025-10-30 08:12:39,836 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0184 @ $108686.34 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:39,837 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0184
2025-10-30 08:12:39,839 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:42,730 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6719/9953
2025-10-30 08:12:42,732 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=109705.84
2025-10-30 08:12:42,732 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0182 @ $109705.84 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:42,732 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0182
2025-10-30 08:12:42,734 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:44,328 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4443/9953
2025-10-30 08:12:44,329 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=108000.00
2025-10-30 08:12:44,329 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $108000.00 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:44,329 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:12:44,331 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:47,355 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9920/9953
2025-10-30 08:12:47,356 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111716.29
2025-10-30 08:12:47,356 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $111716.29 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:47,357 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:12:47,358 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:47,373 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 2083/9953
2025-10-30 08:12:47,375 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=112030.50
2025-10-30 08:12:47,375 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0179 @ $112030.50 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:47,375 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0179
2025-10-30 08:12:47,377 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:52,256 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 6116/9953
2025-10-30 08:12:52,258 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=107913.60
2025-10-30 08:12:52,258 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0185 @ $107913.60 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:52,258 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0185
2025-10-30 08:12:52,260 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:54,160 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 9706/9953
2025-10-30 08:12:54,161 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111089.05
2025-10-30 08:12:54,161 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111089.05 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:54,161 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:12:54,163 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:12:54,281 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 1062/9953
2025-10-30 08:12:54,282 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=113261.87
2025-10-30 08:12:54,282 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0177 @ $113261.87 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:12:54,283 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0177
2025-10-30 08:12:54,284 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:13:00,148 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 8391/9953
2025-10-30 08:13:00,149 - rl_trading_lab.environment.portfolio - DEBUG - Opening position: signal=-1.0, price=111168.57
2025-10-30 08:13:00,150 - rl_trading_lab.environment.portfolio - DEBUG - Trade #1: SHORT 0.0180 @ $111168.57 (cash flow: +$2000.00, -$0.00, remaining: $12000.00)
2025-10-30 08:13:00,150 - rl_trading_lab.environment.portfolio - DEBUG - Position opened: size=-0.0180
2025-10-30 08:13:00,151 - rl_trading_lab.environment.portfolio - DEBUG - Position held for 1 bars, need 2 bars minimum
2025-10-30 08:13:00,821 - rl_trading_lab.environment.trading_env - DEBUG - Episode reset: randomized start at step 4676/9953

In [33]:
mean_reward, std_reward

(np.float64(-0.0021728999999999993), np.float64(0.003209531880196861))